ChibiOS/RT: Statistics
Statistics
RT Kernel » Debug
Detailed Description
Statistics services.
Data Structures
struct kernel_stats_t
Type of a kernel statistics structure.
Functions
void _stats_init (void)
Initializes the statistics module.
void _stats_increase_irq (void)
Increases the IRQ counter.
void _stats_ctxswc (thread_t *ntp, thread_t *otp)
Updates context switch related statistics.
void _stats_start_measure_crit_thd (void)
Starts the measurement of a thread critical zone.
void _stats_stop_measure_crit_thd (void)
Stops the measurement of a thread critical zone.
void _stats_start_measure_crit_isr (void)
Starts the measurement of an ISR critical zone.
void _stats_stop_measure_crit_isr (void)
Stops the measurement of an ISR critical zone.
Function Documentation
_stats_init()
void _stats_init (void)
Initializes the statistics module.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 62 of file chstats.c.
References ch, chTMObjectInit(), ch_system::kernel_stats, kernel_stats_t::m_crit_isr, kernel_stats_t::m_crit_thd, kernel_stats_t::n_ctxswc, and kernel_stats_t::n_irq.
Referenced by chSysInit().
_stats_increase_irq()
void _stats_increase_irq (void)
Increases the IRQ counter.
Definition at line 73 of file chstats.c.
References ch, ch_system::kernel_stats, and kernel_stats_t::n_irq.
_stats_ctxswc()
void _stats_ctxswc (thread_t * ntp, thread_t * otp)
Updates context switch related statistics.
Parameters
[in] ntp the thread to be switched in
[in] otp the thread to be switched out
Definition at line 86 of file chstats.c.
References ch, chTMChainMeasurementToX(), ch_system::kernel_stats, kernel_stats_t::n_ctxswc, and ch_thread::stats.
_stats_start_measure_crit_thd()
void _stats_start_measure_crit_thd (void)
Starts the measurement of a thread critical zone.
Definition at line 95 of file chstats.c.
References ch, chTMStartMeasurementX(), ch_system::kernel_stats, and kernel_stats_t::m_crit_thd.
Referenced by chSysLock().
_stats_stop_measure_crit_thd()
void _stats_stop_measure_crit_thd (void)
Stops the measurement of a thread critical zone.
Definition at line 103 of file chstats.c.
References ch, chTMStopMeasurementX(), ch_system::kernel_stats, and kernel_stats_t::m_crit_thd.
Referenced by chSysUnlock().
_stats_start_measure_crit_isr()
void _stats_start_measure_crit_isr (void)
Starts the measurement of an ISR critical zone.
Definition at line 111 of file chstats.c.
References ch, chTMStartMeasurementX(), ch_system::kernel_stats, and kernel_stats_t::m_crit_isr.
Referenced by chSysLockFromISR().
_stats_stop_measure_crit_isr()
void _stats_stop_measure_crit_isr (void)
Stops the measurement of an ISR critical zone.
Definition at line 119 of file chstats.c.
References ch, chTMStopMeasurementX(), ch_system::kernel_stats, and kernel_stats_t::m_crit_isr.
Referenced by chSysUnlockFromISR().