ChibiOS/RT: Debug
Debug
RT Kernel
Detailed Description
Debug APIs and services:
Runtime system state and call protocol check. The following panic messages can be generated:
SV#1, misplaced chSysDisable().
Called from an ISR.
Called from a critical zone.
SV#2, misplaced chSysSuspend()
Called from an ISR.
Called from a critical zone.
SV#3, misplaced chSysEnable().
Called from an ISR.
Called from a critical zone.
SV#4, misplaced chSysLock().
Called from an ISR.
Called from a critical zone.
SV#5, misplaced chSysUnlock().
Called from an ISR.
Not called from a critical zone.
SV#6, misplaced chSysLockFromISR().
Not called from an ISR.
Called from a critical zone.
SV#7, misplaced chSysUnlockFromISR().
Not called from an ISR.
Not called from a critical zone.
SV#8, misplaced CH_IRQ_PROLOGUE().
Not called at ISR begin.
Called from a critical zone.
SV#9, misplaced CH_IRQ_EPILOGUE().
CH_IRQ_PROLOGUE() missing.
Not called at ISR end.
Called from a critical zone.
SV#10, misplaced I-class function.
I-class function not called from within a critical zone.
SV#11, misplaced S-class function.
S-class function not called from within a critical zone.
Called from an ISR.
Trace buffer.
Parameters check.
Kernel assertions.
Kernel panics.
Note
Stack checks are not implemented in this module but in the port layer in an architecture-dependent way.
Modules
Checks and Assertions
Tracing
Statistics
Debug related settings
#define CH_DBG_STACK_FILL_VALUE 0x55
Fill value for thread stack area in debug mode.
Macro Functions
#define chDbgCheck(c)
Function parameters check.
#define chDbgAssert(c, r)
Condition assertion.
Functions
void _dbg_check_disable (void)
Guard code for chSysDisable().
void _dbg_check_suspend (void)
Guard code for chSysSuspend().
void _dbg_check_enable (void)
Guard code for chSysEnable().
void _dbg_check_lock (void)
Guard code for chSysLock().
void _dbg_check_unlock (void)
Guard code for chSysUnlock().
void _dbg_check_lock_from_isr (void)
Guard code for chSysLockFromIsr().
void _dbg_check_unlock_from_isr (void)
Guard code for chSysUnlockFromIsr().
void _dbg_check_enter_isr (void)
Guard code for CH_IRQ_PROLOGUE().
void _dbg_check_leave_isr (void)
Guard code for CH_IRQ_EPILOGUE().
void chDbgCheckClassI (void)
I-class functions context check.
void chDbgCheckClassS (void)
S-class functions context check.
Macro Definition Documentation
CH_DBG_STACK_FILL_VALUE
#define CH_DBG_STACK_FILL_VALUE 0x55
Fill value for thread stack area in debug mode.
Definition at line 47 of file chdebug.h.
Referenced by chThdCreate(), chThdCreateFromHeap(), chThdCreateFromMemoryPool(), chThdCreateStatic(), and chThdCreateSuspended().
chDbgCheck
#define chDbgCheck (c)
Value:
do {                                                  \
  /*lint -save -e506 -e774 [2.1, 14.3] Can be a constant by design.*/       \
  if (CH_DBG_ENABLE_CHECKS != FALSE) {                                      \
    if (!(c)) {                                                             \
  /*lint -restore*/                                                         \
      chSysHalt(__func__);                                                  \
    }                                                                       \
  }                                                                         \
} while (false)
Function parameters check.
If the condition check fails then the kernel panics and halts.
Note
The condition is tested only if the CH_DBG_ENABLE_CHECKS switch is specified in chconf.h else the macro does nothing.
Parameters
[in] c the condition to be verified to be true
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 101 of file chdebug.h.
Referenced by chCondBroadcastI(), chCondObjectInit(), chCondSignal(), chCondSignalI(), chCondWaitS(), chCondWaitTimeoutS(), chCoreAllocAlignedWithOffsetI(), chEvtBroadcastFlagsI(), chEvtDispatch(), chEvtRegisterMaskWithFlags(), chEvtSignal(), chEvtSignalI(), chEvtUnregister(), chGuardedPoolLoadArray(), chHeapAllocAligned(), chHeapFree(), chHeapObjectInit(), chMBFetchI(), chMBFetchTimeoutS(), chMBObjectInit(), chMBPostAheadI(), chMBPostAheadTimeoutS(), chMBPostI(), chMBPostTimeoutS(), chMBResetI(), chMsgSend(), chMtxLockS(), chMtxObjectInit(), chMtxTryLockS(), chMtxUnlock(), chMtxUnlockS(), chPoolAllocI(), chPoolFreeI(), chPoolLoadArray(), chPoolObjectInitAligned(), chSchReadyAheadI(), chSchReadyI(), chSemAddCounterI(), chSemObjectInit(), chSemResetI(), chSemSignal(), chSemSignalI(), chSemSignalWait(), chSemWaitS(), chSemWaitTimeoutS(), chThdCreateFromMemoryPool(), chThdCreateStatic(), chThdCreateSuspendedI(), chThdSetPriority(), chThdSleepS(), chThdWait(), chTimeAddX(), chVTDoResetI(), and chVTDoSetI().
chDbgAssert
#define chDbgAssert (c, r)
Value:
do {                                              \
  /*lint -save -e506 -e774 [2.1, 14.3] Can be a constant by design.*/       \
  if (CH_DBG_ENABLE_ASSERTS != FALSE) {                                     \
    if (!(c)) {                                                             \
  /*lint -restore*/                                                         \
      chSysHalt(__func__);                                                  \
    }                                                                       \
  }                                                                         \
} while (false)
Condition assertion.
If the condition check fails then the kernel panics with a message and halts.
Note
The condition is tested only if the CH_DBG_ENABLE_ASSERTS switch is specified in chconf.h else the macro does nothing.
The remark string is not currently used except for putting a comment in the code about the assertion.
Parameters
[in] c the condition to be verified to be true
[in] r a remark string
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 127 of file chdebug.h.
Referenced by chCondWaitS(), chCondWaitTimeoutS(), chEvtDispatch(), chFifoSendObject(), chFifoSendObjectAhead(), chFifoSendObjectAheadI(), chFifoSendObjectAheadS(), chFifoSendObjectI(), chFifoSendObjectS(), chGuardedPoolAllocI(), chMsgGet(), chMsgRelease(), chMtxLockS(), chMtxTryLockS(), chMtxUnlock(), chMtxUnlockS(), chPoolFreeI(), chRegNextThread(), chSchReadyAheadI(), chSchReadyI(), chSchWakeupS(), chSemAddCounterI(), chSemResetI(), chSemSignal(), chSemSignalI(), chSemSignalWait(), chSemWaitS(), chSemWaitTimeoutS(), chSysUnlock(), chThdAddRef(), chThdCreate(), chThdCreateStatic(), chThdCreateSuspended(), chThdDoDequeueNextI(), chThdExitS(), chThdRelease(), chThdResumeI(), chThdResumeS(), chThdStart(), chThdStartI(), chThdSuspendS(), chThdSuspendTimeoutS(), chThdWait(), chTimeI2MS(), chTimeI2S(), chTimeI2US(), chTimeMS2I(), chTimeS2I(), chTimeUS2I(), chVTDoResetI(), chVTDoSetI(), and chVTDoTickI().
Function Documentation
_dbg_check_disable()
void _dbg_check_disable (void)
Guard code for chSysDisable().
Function Class:
Not an API, this function is for internal use only.
Definition at line 114 of file chdebug.c.
References ch, chSysHalt(), ch_system::dbg, ch_system_debug::isr_cnt, and ch_system_debug::lock_cnt.
Referenced by chSysDisable().
_dbg_check_suspend()
void _dbg_check_suspend (void)
Guard code for chSysSuspend().
Function Class:
Not an API, this function is for internal use only.
Definition at line 126 of file chdebug.c.
References ch, chSysHalt(), ch_system::dbg, ch_system_debug::isr_cnt, and ch_system_debug::lock_cnt.
Referenced by chSysSuspend().
_dbg_check_enable()
void _dbg_check_enable (void)
Guard code for chSysEnable().
Function Class:
Not an API, this function is for internal use only.
Definition at line 138 of file chdebug.c.
References ch, chSysHalt(), ch_system::dbg, ch_system_debug::isr_cnt, and ch_system_debug::lock_cnt.
Referenced by chSysEnable().
_dbg_check_lock()
void _dbg_check_lock (void)
Guard code for chSysLock().
Function Class:
Not an API, this function is for internal use only.
Definition at line 150 of file chdebug.c.
References ch, chSysHalt(), ch_system::dbg, ch_system_debug::isr_cnt, and ch_system_debug::lock_cnt.
Referenced by chSysLock().
_dbg_check_unlock()
void _dbg_check_unlock (void)
Guard code for chSysUnlock().
Function Class:
Not an API, this function is for internal use only.
Definition at line 163 of file chdebug.c.
References ch, chSysHalt(), ch_system::dbg, ch_system_debug::isr_cnt, and ch_system_debug::lock_cnt.
Referenced by chSysUnlock().
_dbg_check_lock_from_isr()
void _dbg_check_lock_from_isr (void)
Guard code for chSysLockFromIsr().
Function Class:
Not an API, this function is for internal use only.
Definition at line 176 of file chdebug.c.
References ch, chSysHalt(), ch_system::dbg, ch_system_debug::isr_cnt, and ch_system_debug::lock_cnt.
Referenced by chSysLockFromISR().
_dbg_check_unlock_from_isr()
void _dbg_check_unlock_from_isr (void)
Guard code for chSysUnlockFromIsr().
Function Class:
Not an API, this function is for internal use only.
Definition at line 189 of file chdebug.c.
References ch, chSysHalt(), ch_system::dbg, ch_system_debug::isr_cnt, and ch_system_debug::lock_cnt.
Referenced by chSysUnlockFromISR().
_dbg_check_enter_isr()
void _dbg_check_enter_isr (void)
Guard code for CH_IRQ_PROLOGUE().
Function Class:
Not an API, this function is for internal use only.
Definition at line 202 of file chdebug.c.
References ch, chSysHalt(), ch_system::dbg, ch_system_debug::isr_cnt, and ch_system_debug::lock_cnt.
_dbg_check_leave_isr()
void _dbg_check_leave_isr (void)
Guard code for CH_IRQ_EPILOGUE().
Function Class:
Not an API, this function is for internal use only.
Definition at line 217 of file chdebug.c.
References ch, chSysHalt(), ch_system::dbg, ch_system_debug::isr_cnt, and ch_system_debug::lock_cnt.
chDbgCheckClassI()
void chDbgCheckClassI (void)
I-class functions context check.
Verifies that the system is in an appropriate state for invoking an I-class API function. A panic is generated if the state is not compatible.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 235 of file chdebug.c.
References ch, chSysHalt(), ch_system::dbg, ch_system_debug::isr_cnt, and ch_system_debug::lock_cnt.
Referenced by chBSemGetStateI(), chBSemResetI(), chBSemSignalI(), chCondBroadcastI(), chCondSignalI(), chCoreAllocAlignedWithOffsetI(), chDbgResumeTraceI(), chDbgSuspendTraceI(), chDbgWriteTraceI(), chEvtBroadcastFlagsI(), chEvtSignalI(), chMBFetchI(), chMBGetFreeCountI(), chMBGetUsedCountI(), chMBPeekI(), chMBPostAheadI(), chMBPostI(), chMBResetI(), chMsgIsPendingI(), chPoolAllocI(), chPoolFreeI(), chSchReadyAheadI(), chSchReadyI(), chSemAddCounterI(), chSemFastSignalI(), chSemFastWaitI(), chSemGetCounterI(), chSemResetI(), chSemSignalI(), chSysIntegrityCheckI(), chSysTimerHandlerI(), chThdCreateSuspendedI(), chThdQueueIsEmptyI(), chVTDoResetI(), chVTDoSetI(), chVTDoTickI(), chVTGetTimersStateI(), chVTIsArmedI(), and queue_notempty().
chDbgCheckClassS()
void chDbgCheckClassS (void)
S-class functions context check.
Verifies that the system is in an appropriate state for invoking an S-class API function. A panic is generated if the state is not compatible.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 250 of file chdebug.c.
References ch, chSysHalt(), ch_system::dbg, ch_system_debug::isr_cnt, and ch_system_debug::lock_cnt.
Referenced by chBSemWaitS(), chBSemWaitTimeoutS(), chCondWaitS(), chCondWaitTimeoutS(), chMBFetchTimeoutS(), chMBPostAheadTimeoutS(), chMBPostTimeoutS(), chMsgReleaseS(), chMtxLockS(), chMtxQueueNotEmptyS(), chMtxTryLockS(), chMtxUnlockS(), chSchCanYieldS(), chSchGoSleepS(), chSchGoSleepTimeoutS(), chSchIsRescRequiredI(), chSchRescheduleS(), chSchWakeupS(), chSemWaitS(), and chSemWaitTimeoutS().