ChibiOS/RT: Version Numbers and Identification
Version Numbers and Identification
RT Kernel
Detailed Description
Kernel related info.
Macros
#define _CHIBIOS_RT_
ChibiOS/RT identification macro.
#define CH_KERNEL_STABLE 1
Stable release flag.
ChibiOS/RT version identification
#define CH_KERNEL_VERSION "5.1.0"
Kernel version string.
#define CH_KERNEL_MAJOR 5
Kernel version major number.
#define CH_KERNEL_MINOR 1
Kernel version minor number.
#define CH_KERNEL_PATCH 0
Kernel version patch number.
Constants for configuration options
#define FALSE 0
Generic 'false' preprocessor boolean constant.
#define TRUE 1
Generic 'true' preprocessor boolean constant.
Functions
void chSysHalt (const char *reason)
Halts the system.
Macro Definition Documentation
_CHIBIOS_RT_
#define _CHIBIOS_RT_
ChibiOS/RT identification macro.
Definition at line 37 of file ch.h.
CH_KERNEL_STABLE
#define CH_KERNEL_STABLE 1
Stable release flag.
Definition at line 42 of file ch.h.
CH_KERNEL_VERSION
#define CH_KERNEL_VERSION "5.1.0"
Kernel version string.
Definition at line 51 of file ch.h.
CH_KERNEL_MAJOR
#define CH_KERNEL_MAJOR 5
Kernel version major number.
Definition at line 56 of file ch.h.
CH_KERNEL_MINOR
#define CH_KERNEL_MINOR 1
Kernel version minor number.
Definition at line 61 of file ch.h.
CH_KERNEL_PATCH
#define CH_KERNEL_PATCH 0
Kernel version patch number.
Definition at line 66 of file ch.h.
FALSE
#define FALSE 0
Generic 'false' preprocessor boolean constant.
Note
It is meant to be used in configuration files as switch.
Definition at line 77 of file ch.h.
TRUE
#define TRUE 1
Generic 'true' preprocessor boolean constant.
Note
It is meant to be used in configuration files as switch.
Definition at line 85 of file ch.h.
Function Documentation
chSysHalt()
void chSysHalt (const char * reason)
Halts the system.
This function is invoked by the operating system when an unrecoverable error is detected, for example because a programming error in the application code that triggers an assertion while in debug mode.
Note
Can be invoked from any system state.
Parameters
[in] reason pointer to an error string
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 198 of file chsys.c.
References _trace_halt(), ch, CH_CFG_SYSTEM_HALT_HOOK, ch_system::dbg, and ch_system_debug::panic_msg.
Referenced by _dbg_check_disable(), _dbg_check_enable(), _dbg_check_enter_isr(), _dbg_check_leave_isr(), _dbg_check_lock(), _dbg_check_lock_from_isr(), _dbg_check_suspend(), _dbg_check_unlock(), _dbg_check_unlock_from_isr(), chDbgCheckClassI(), and chDbgCheckClassS().