ChibiOS/NIL: API
API
NIL Kernel
Detailed Description
Macros
#define _CHIBIOS_NIL_
ChibiOS/NIL identification macro.
#define CH_KERNEL_STABLE 1
Stable release flag.
#define CH_CFG_USE_FACTORY TRUE
Objects Factory APIs.
#define CH_CFG_FACTORY_MAX_NAMES_LENGTH 8
Maximum length for object names.
#define CH_CFG_FACTORY_OBJECTS_REGISTRY TRUE
Enables the registry of generic objects.
#define CH_CFG_FACTORY_GENERIC_BUFFERS TRUE
Enables factory for generic buffers.
#define CH_CFG_FACTORY_SEMAPHORES TRUE
Enables factory for semaphores.
#define CH_CFG_FACTORY_MAILBOXES TRUE
Enables factory for mailboxes.
#define CH_CFG_FACTORY_OBJ_FIFOS TRUE
Enables factory for objects FIFOs.
#define THD_IDLE_BASE (&__main_thread_stack_base__)
#define __CH_STRINGIFY(a) #a
Utility to make the parameter a quoted string.
ChibiOS/NIL version identification
#define CH_KERNEL_VERSION "3.1.0"
Kernel version string.
#define CH_KERNEL_MAJOR 3
Kernel version major number.
#define CH_KERNEL_MINOR 1
Kernel version minor number.
#define CH_KERNEL_PATCH 0
Kernel version patch number.
Wakeup messages
#define MSG_OK (msg_t)0
OK wakeup message.
#define MSG_TIMEOUT (msg_t)-1
Wake-up caused by a timeout condition.
#define MSG_RESET (msg_t)-2
Wake-up caused by a reset condition.
Special time constants
#define TIME_IMMEDIATE ((sysinterval_t)-1)
Zero time specification for some functions with a timeout specification.
#define TIME_INFINITE ((sysinterval_t)0)
Infinite time specification for all functions with a timeout specification.
#define TIME_MAX_INTERVAL ((sysinterval_t)-2)
Maximum interval constant usable as timeout.
#define TIME_MAX_SYSTIME ((systime_t)-1)
Maximum system of system time before it wraps.
Thread state related macros
#define NIL_STATE_READY (tstate_t)0
Thread ready or executing.
#define NIL_STATE_SLEEPING (tstate_t)1
Thread sleeping.
#define NIL_STATE_SUSP (tstate_t)2
Thread suspended.
#define NIL_STATE_WTQUEUE (tstate_t)3
On queue or semaph.
#define NIL_STATE_WTOREVT (tstate_t)4
Waiting for events.
#define NIL_THD_IS_READY(tr) ((tr)->state == NIL_STATE_READY)
#define NIL_THD_IS_SLEEPING(tr) ((tr)->state == NIL_STATE_SLEEPING)
#define NIL_THD_IS_SUSP(tr) ((tr)->state == NIL_STATE_SUSP)
#define NIL_THD_IS_WTQUEUE(tr) ((tr)->state == NIL_STATE_WTQUEUE)
#define NIL_THD_IS_WTOREVT(tr) ((tr)->state == NIL_STATE_WTOREVT)
Events related macros
#define ALL_EVENTS ((eventmask_t)-1)
All events allowed mask.
#define EVENT_MASK(eid) ((eventmask_t)(1 << (eid)))
Returns an event mask from an event identifier.
Threads tables definition macros
#define THD_TABLE_BEGIN const thread_config_t nil_thd_configs[CH_CFG_NUM_THREADS + 1] = {
Start of user threads table.
#define THD_TABLE_ENTRY(wap, name, funcp, arg)
Entry of user threads table.
#define THD_TABLE_END
End of user threads table.
Memory alignment support macros
#define MEM_ALIGN_MASK(a) ((size_t)(a) - 1U)
Alignment mask constant.
#define MEM_ALIGN_PREV(p, a) ((size_t)(p) & ~MEM_ALIGN_MASK(a))
Aligns to the previous aligned memory address.
#define MEM_ALIGN_NEXT(p, a)
Aligns to the new aligned memory address.
#define MEM_IS_ALIGNED(p, a) (((size_t)(p) & MEM_ALIGN_MASK(a)) == 0U)
Returns whatever a pointer or memory size is aligned.
#define MEM_IS_VALID_ALIGNMENT(a) (((size_t)(a) != 0U) && (((size_t)(a) & ((size_t)(a) - 1U)) == 0U))
Returns whatever a constant is a valid alignment.
Working Areas
#define THD_WORKING_AREA_SIZE(n)
Calculates the total Working Area size.
#define THD_WORKING_AREA(s, n) PORT_WORKING_AREA(s, n)
Static working area allocation.
Threads abstraction macros
#define THD_FUNCTION(tname, arg) PORT_THD_FUNCTION(tname, arg)
Thread declaration macro.
ISRs abstraction macros
#define CH_IRQ_IS_VALID_PRIORITY(prio) PORT_IRQ_IS_VALID_PRIORITY(prio)
Priority level validation macro.
#define CH_IRQ_IS_VALID_KERNEL_PRIORITY(prio) PORT_IRQ_IS_VALID_KERNEL_PRIORITY(prio)
Priority level validation macro.
#define CH_IRQ_PROLOGUE()
IRQ handler enter code.
#define CH_IRQ_EPILOGUE()
IRQ handler exit code.
#define CH_IRQ_HANDLER(id) PORT_IRQ_HANDLER(id)
Standard normal IRQ handler declaration.
Fast ISRs abstraction macros
#define CH_FAST_IRQ_HANDLER(id) PORT_FAST_IRQ_HANDLER(id)
Standard fast IRQ handler declaration.
Time conversion utilities
#define TIME_S2I(secs) ((sysinterval_t)((time_conv_t)(secs) * (time_conv_t)CH_CFG_ST_FREQUENCY))
Seconds to time interval.
#define TIME_MS2I(msecs)
Milliseconds to time interval.
#define TIME_US2I(usecs)
Microseconds to time interval.
#define TIME_I2S(interval)
Time interval to seconds.
#define TIME_I2MS(interval)
Time interval to milliseconds.
#define TIME_I2US(interval)
Time interval to microseconds.
Threads queues
#define _THREADS_QUEUE_DATA(name) {(cnt_t)0}
Data part of a static threads queue object initializer.
#define _THREADS_QUEUE_DECL(name) threads_queue_t name = _THREADS_QUEUE_DATA(name)
Static threads queue object initializer.
Semaphores macros
#define _SEMAPHORE_DATA(name, n) {n}
Data part of a static semaphore initializer.
#define SEMAPHORE_DECL(name, n) semaphore_t name = _SEMAPHORE_DATA(name, n)
Static semaphore initializer.
Macro Functions
#define chSysGetRealtimeCounterX() (rtcnt_t)port_rt_get_counter_value()
Returns the current value of the system real time counter.
#define chSysDisable()
Raises the system interrupt priority mask to the maximum level.
#define chSysSuspend()
Raises the system interrupt priority mask to system level.
#define chSysEnable()
Lowers the system interrupt priority mask to user level.
#define chSysLock()
Enters the kernel lock state.
#define chSysUnlock()
Leaves the kernel lock state.
#define chSysLockFromISR()
Enters the kernel lock state from within an interrupt handler.
#define chSysUnlockFromISR()
Leaves the kernel lock state from within an interrupt handler.
#define chSchIsRescRequiredI() ((bool)(nil.current != nil.next))
Evaluates if a reschedule is required.
#define chThdGetSelfX() nil.current
Returns a pointer to the current thread_t.
#define chThdSleepSeconds(secs) chThdSleep(TIME_S2I(secs))
Delays the invoking thread for the specified number of seconds.
#define chThdSleepMilliseconds(msecs) chThdSleep(TIME_MS2I(msecs))
Delays the invoking thread for the specified number of milliseconds.
#define chThdSleepMicroseconds(usecs) chThdSleep(TIME_US2I(usecs))
Delays the invoking thread for the specified number of microseconds.
#define chThdSleepS(timeout) (void) chSchGoSleepTimeoutS(NIL_STATE_SLEEPING, timeout)
Suspends the invoking thread for the specified time.
#define chThdSleepUntilS(abstime)
Suspends the invoking thread until the system time arrives to the specified value.
#define chThdQueueObjectInit(tqp) ((tqp)->cnt = (cnt_t)0)
Initializes a threads queue object.
#define chThdQueueIsEmptyI(tqp) ((bool)(tqp->cnt >= (cnt_t)0))
Evaluates to true if the specified queue is empty.
#define chSemObjectInit(sp, n) ((sp)->cnt = n)
Initializes a semaphore with the specified counter value.
#define chSemWait(sp) chSemWaitTimeout(sp, TIME_INFINITE)
Performs a wait operation on a semaphore.
#define chSemWaitS(sp) chSemWaitTimeoutS(sp, TIME_INFINITE)
Performs a wait operation on a semaphore.
#define chSemFastWaitI(sp) ((sp)->cnt--)
Decreases the semaphore counter.
#define chSemFastSignalI(sp) ((sp)->cnt++)
Increases the semaphore counter.
#define chSemGetCounterI(sp) ((sp)->cnt)
Returns the semaphore counter current value.
#define chVTGetSystemTimeX() (nil.systime)
Current system time.
#define chVTTimeElapsedSinceX(start) chTimeDiffX((start), chVTGetSystemTimeX())
Returns the elapsed time since the specified start time.
#define chTimeAddX(systime, interval) ((systime_t)(systime) + (systime_t)(interval))
Adds an interval to a system time returning a system time.
#define chTimeDiffX(start, end) ((sysinterval_t)((systime_t)((systime_t)(end) - (systime_t)(start))))
Subtracts two system times returning an interval.
#define chTimeIsInRangeX(time, start, end)
Checks if the specified time is within the specified time range.
#define chDbgCheck(c)
Function parameters check.
#define chDbgAssert(c, r)
Condition assertion.
Typedefs
typedef uint32_t systime_t
Type of system time.
typedef uint32_t sysinterval_t
Type of time interval.
typedef uint64_t time_conv_t
Type of time conversion variable.
typedef struct nil_thread thread_t
Type of a structure representing a thread.
typedef struct nil_threads_queue threads_queue_t
Type of a queue of threads.
typedef threads_queue_t semaphore_t
Type of a structure representing a semaphore.
typedef void(* tfunc_t) (void *p)
Thread function.
typedef struct nil_thread_cfg thread_config_t
Type of a structure representing a thread static configuration.
typedef thread_t * thread_reference_t
Type of a thread reference.
typedef struct nil_system nil_system_t
Type of a structure representing the system.
Data Structures
struct nil_threads_queue
Structure representing a queue of threads.
struct nil_thread_cfg
Structure representing a thread static configuration.
struct nil_thread
Structure representing a thread.
struct nil_system
System data structure.
Functions
static thread_t * nil_find_thread (tstate_t state, void *p)
Retrieves the highest priority thread in the specified state and associated to the specified object.
static cnt_t nil_ready_all (void *p, cnt_t cnt, msg_t msg)
Puts in ready state all thread matching the specified status and associated object.
void _dbg_check_disable (void)
Guard code for chSysDisable().
void _dbg_check_suspend (void)
Guard code for chSysSuspend().
void _dbg_check_enable (void)
Guard code for chSysEnable().
void _dbg_check_lock (void)
Guard code for chSysLock().
void _dbg_check_unlock (void)
Guard code for chSysUnlock().
void _dbg_check_lock_from_isr (void)
Guard code for chSysLockFromIsr().
void _dbg_check_unlock_from_isr (void)
Guard code for chSysUnlockFromIsr().
void _dbg_check_enter_isr (void)
Guard code for CH_IRQ_PROLOGUE().
void _dbg_check_leave_isr (void)
Guard code for CH_IRQ_EPILOGUE().
void chDbgCheckClassI (void)
I-class functions context check.
void chDbgCheckClassS (void)
S-class functions context check.
void chSysInit (void)
Initializes the kernel.
void chSysHalt (const char *reason)
Halts the system.
void chSysTimerHandlerI (void)
Time management handler.
void chSysUnconditionalLock (void)
Unconditionally enters the kernel lock state.
void chSysUnconditionalUnlock (void)
Unconditionally leaves the kernel lock state.
syssts_t chSysGetStatusAndLockX (void)
Returns the execution status and enters a critical zone.
void chSysRestoreStatusX (syssts_t sts)
Restores the specified execution status and leaves a critical zone.
bool chSysIsCounterWithinX (rtcnt_t cnt, rtcnt_t start, rtcnt_t end)
Realtime window test.
void chSysPolledDelayX (rtcnt_t cycles)
Polled delay.
thread_t * chSchReadyI (thread_t *tp, msg_t msg)
Makes the specified thread ready for execution.
bool chSchIsPreemptionRequired (void)
Evaluates if preemption is required.
void chSchDoReschedule (void)
Switches to the first thread on the runnable queue.
void chSchRescheduleS (void)
Reschedules if needed.
msg_t chSchGoSleepTimeoutS (tstate_t newstate, sysinterval_t timeout)
Puts the current thread to sleep into the specified state with timeout specification.
msg_t chThdSuspendTimeoutS (thread_reference_t *trp, sysinterval_t timeout)
Sends the current thread sleeping and sets a reference variable.
void chThdResumeI (thread_reference_t *trp, msg_t msg)
Wakes up a thread waiting on a thread reference object.
void chThdResume (thread_reference_t *trp, msg_t msg)
Wakes up a thread waiting on a thread reference object.
void chThdSleep (sysinterval_t timeout)
Suspends the invoking thread for the specified time.
void chThdSleepUntil (systime_t abstime)
Suspends the invoking thread until the system time arrives to the specified value.
msg_t chThdEnqueueTimeoutS (threads_queue_t *tqp, sysinterval_t timeout)
Enqueues the caller thread on a threads queue object.
void chThdDoDequeueNextI (threads_queue_t *tqp, msg_t msg)
Dequeues and wakes up one thread from the threads queue object.
void chThdDequeueNextI (threads_queue_t *tqp, msg_t msg)
Dequeues and wakes up one thread from the threads queue object, if any.
void chThdDequeueAllI (threads_queue_t *tqp, msg_t msg)
Dequeues and wakes up all threads from the threads queue object.
msg_t chSemWaitTimeout (semaphore_t *sp, sysinterval_t timeout)
Performs a wait operation on a semaphore with timeout specification.
msg_t chSemWaitTimeoutS (semaphore_t *sp, sysinterval_t timeout)
Performs a wait operation on a semaphore with timeout specification.
void chSemSignal (semaphore_t *sp)
Performs a signal operation on a semaphore.
void chSemSignalI (semaphore_t *sp)
Performs a signal operation on a semaphore.
void chSemReset (semaphore_t *sp, cnt_t n)
Performs a reset operation on the semaphore.
void chSemResetI (semaphore_t *sp, cnt_t n)
Performs a reset operation on the semaphore.
void chEvtSignal (thread_t *tp, eventmask_t mask)
Adds a set of event flags directly to the specified thread_t.
void chEvtSignalI (thread_t *tp, eventmask_t mask)
Adds a set of event flags directly to the specified thread_t.
eventmask_t chEvtWaitAnyTimeout (eventmask_t mask, sysinterval_t timeout)
Waits for any of the specified events.
Variables
nil_system_t nil
System data structures.
Macro Definition Documentation
_CHIBIOS_NIL_
#define _CHIBIOS_NIL_
ChibiOS/NIL identification macro.
Definition at line 44 of file ch.h.
CH_KERNEL_STABLE
#define CH_KERNEL_STABLE 1
Stable release flag.
Definition at line 49 of file ch.h.
CH_KERNEL_VERSION
#define CH_KERNEL_VERSION "3.1.0"
Kernel version string.
Definition at line 58 of file ch.h.
CH_KERNEL_MAJOR
#define CH_KERNEL_MAJOR 3
Kernel version major number.
Definition at line 63 of file ch.h.
CH_KERNEL_MINOR
#define CH_KERNEL_MINOR 1
Kernel version minor number.
Definition at line 68 of file ch.h.
CH_KERNEL_PATCH
#define CH_KERNEL_PATCH 0
Kernel version patch number.
Definition at line 73 of file ch.h.
MSG_OK
#define MSG_OK (msg_t)0
OK wakeup message.
Definition at line 80 of file ch.h.
Referenced by chEvtWaitAnyTimeout(), chFifoSendObject(), chFifoSendObjectAhead(), chFifoSendObjectAheadI(), chFifoSendObjectAheadS(), chFifoSendObjectI(), chFifoSendObjectS(), chGuardedPoolAllocTimeoutS(), chMBFetchI(), chMBFetchTimeoutS(), chMBPostAheadI(), chMBPostAheadTimeoutS(), chMBPostI(), chMBPostTimeoutS(), chSemSignalI(), and chSemWaitTimeoutS().
MSG_TIMEOUT
#define MSG_TIMEOUT (msg_t)-1
Wake-up caused by a timeout condition.
Definition at line 81 of file ch.h.
Referenced by chMBFetchI(), chMBPostAheadI(), chMBPostI(), chSemWaitTimeoutS(), chThdEnqueueTimeoutS(), and chThdSuspendTimeoutS().
MSG_RESET
#define MSG_RESET (msg_t)-2
Wake-up caused by a reset condition.
Definition at line 84 of file ch.h.
Referenced by chMBFetchI(), chMBFetchTimeoutS(), chMBPostAheadI(), chMBPostAheadTimeoutS(), chMBPostI(), chMBPostTimeoutS(), chMBResetI(), and chSemResetI().
TIME_IMMEDIATE
#define TIME_IMMEDIATE ((sysinterval_t)-1)
Zero time specification for some functions with a timeout specification.
Note
Not all functions accept TIME_IMMEDIATE as timeout parameter, see the specific function documentation.
Definition at line 99 of file ch.h.
Referenced by chEvtWaitAnyTimeout(), chFifoSendObject(), chFifoSendObjectAhead(), chFifoSendObjectAheadS(), chFifoSendObjectS(), chSemWaitTimeoutS(), chThdEnqueueTimeoutS(), and chThdSuspendTimeoutS().
TIME_INFINITE
#define TIME_INFINITE ((sysinterval_t)0)
Infinite time specification for all functions with a timeout specification.
Definition at line 105 of file ch.h.
Referenced by chSchGoSleepTimeoutS().
TIME_MAX_INTERVAL
#define TIME_MAX_INTERVAL ((sysinterval_t)-2)
Maximum interval constant usable as timeout.
Definition at line 110 of file ch.h.
TIME_MAX_SYSTIME
#define TIME_MAX_SYSTIME ((systime_t)-1)
Maximum system of system time before it wraps.
Definition at line 115 of file ch.h.
NIL_STATE_READY
#define NIL_STATE_READY (tstate_t)0
Thread ready or executing.
Definition at line 122 of file ch.h.
NIL_STATE_SLEEPING
#define NIL_STATE_SLEEPING (tstate_t)1
Thread sleeping.
Definition at line 125 of file ch.h.
NIL_STATE_SUSP
#define NIL_STATE_SUSP (tstate_t)2
Thread suspended.
Definition at line 126 of file ch.h.
Referenced by chThdSuspendTimeoutS().
NIL_STATE_WTQUEUE
#define NIL_STATE_WTQUEUE (tstate_t)3
On queue or semaph.
Definition at line 127 of file ch.h.
Referenced by chSemSignalI(), chSemWaitTimeoutS(), chThdDoDequeueNextI(), chThdEnqueueTimeoutS(), and nil_ready_all().
NIL_STATE_WTOREVT
#define NIL_STATE_WTOREVT (tstate_t)4
Waiting for events.
Definition at line 128 of file ch.h.
Referenced by chEvtWaitAnyTimeout().
ALL_EVENTS
#define ALL_EVENTS ((eventmask_t)-1)
All events allowed mask.
Definition at line 143 of file ch.h.
EVENT_MASK
#define EVENT_MASK (eid) ((eventmask_t)(1 << (eid)))
Returns an event mask from an event identifier.
Definition at line 148 of file ch.h.
CH_CFG_USE_FACTORY
#define CH_CFG_USE_FACTORY TRUE
Objects Factory APIs.
If enabled then the objects factory APIs are included in the kernel.
Note
The default is FALSE.
Definition at line 277 of file ch.h.
CH_CFG_FACTORY_MAX_NAMES_LENGTH
#define CH_CFG_FACTORY_MAX_NAMES_LENGTH 8
Maximum length for object names.
If the specified length is zero then the name is stored by pointer but this could have unintended side effects.
Definition at line 286 of file ch.h.
CH_CFG_FACTORY_OBJECTS_REGISTRY
#define CH_CFG_FACTORY_OBJECTS_REGISTRY TRUE
Enables the registry of generic objects.
Definition at line 293 of file ch.h.
CH_CFG_FACTORY_GENERIC_BUFFERS
#define CH_CFG_FACTORY_GENERIC_BUFFERS TRUE
Enables factory for generic buffers.
Definition at line 300 of file ch.h.
CH_CFG_FACTORY_SEMAPHORES
#define CH_CFG_FACTORY_SEMAPHORES TRUE
Enables factory for semaphores.
Definition at line 307 of file ch.h.
CH_CFG_FACTORY_MAILBOXES
#define CH_CFG_FACTORY_MAILBOXES TRUE
Enables factory for mailboxes.
Definition at line 314 of file ch.h.
CH_CFG_FACTORY_OBJ_FIFOS
#define CH_CFG_FACTORY_OBJ_FIFOS TRUE
Enables factory for objects FIFOs.
Definition at line 321 of file ch.h.
THD_IDLE_BASE
#define THD_IDLE_BASE (&__main_thread_stack_base__)
Boundaries of the idle thread boundaries, only required if stack checking is enabled.
Definition at line 520 of file ch.h.
Referenced by chSysInit().
__CH_STRINGIFY
#define __CH_STRINGIFY (a) #a
Utility to make the parameter a quoted string.
Definition at line 719 of file ch.h.
THD_TABLE_BEGIN
#define THD_TABLE_BEGIN const thread_config_t nil_thd_configs[CH_CFG_NUM_THREADS + 1] = {
Start of user threads table.
Definition at line 728 of file ch.h.
THD_TABLE_ENTRY
#define THD_TABLE_ENTRY (wap, name, funcp, arg)
Value:
{wap, ((stkalign_t *)(wap)) + (sizeof (wap) / sizeof(stkalign_t)),        \
   name, funcp, arg},
Entry of user threads table.
Definition at line 734 of file ch.h.
THD_TABLE_END
#define THD_TABLE_END
Value:
{THD_IDLE_BASE, THD_IDLE_END, "idle", NULL, NULL}                         \
};
End of user threads table.
Definition at line 741 of file ch.h.
MEM_ALIGN_MASK
#define MEM_ALIGN_MASK (a) ((size_t)(a) - 1U)
Alignment mask constant.
Parameters
[in] a alignment, must be a power of two
Definition at line 754 of file ch.h.
Referenced by chPoolFreeI().
MEM_ALIGN_PREV
#define MEM_ALIGN_PREV (p, a) ((size_t)(p) & ~MEM_ALIGN_MASK(a))
Aligns to the previous aligned memory address.
Parameters
[in] p variable to be aligned
[in] a alignment, must be a power of two
Definition at line 762 of file ch.h.
MEM_ALIGN_NEXT
#define MEM_ALIGN_NEXT (p, a)
Value:
MEM_ALIGN_PREV((size_t)(p) +                \
                                               MEM_ALIGN_MASK(a), (a))
Aligns to the new aligned memory address.
Parameters
[in] p variable to be aligned
[in] a alignment, must be a power of two
Definition at line 770 of file ch.h.
Referenced by chCoreAllocAlignedWithOffsetI(), chHeapAllocAligned(), and chHeapObjectInit().
MEM_IS_ALIGNED
#define MEM_IS_ALIGNED (p, a) (((size_t)(p) & MEM_ALIGN_MASK(a)) == 0U)
Returns whatever a pointer or memory size is aligned.
Parameters
[in] p variable to be aligned
[in] a alignment, must be a power of two
Definition at line 779 of file ch.h.
Referenced by chHeapFree().
MEM_IS_VALID_ALIGNMENT
#define MEM_IS_VALID_ALIGNMENT (a) (((size_t)(a) != 0U) && (((size_t)(a) & ((size_t)(a) - 1U)) == 0U))
Returns whatever a constant is a valid alignment.
Valid alignments are powers of two.
Parameters
[in] a alignment to be checked, must be a constant
Definition at line 787 of file ch.h.
Referenced by chCoreAllocAlignedWithOffsetI(), and chHeapAllocAligned().
THD_WORKING_AREA_SIZE
#define THD_WORKING_AREA_SIZE (n)
Value:
MEM_ALIGN_NEXT(PORT_WA_SIZE(n),            \
                                                PORT_STACK_ALIGN)
Calculates the total Working Area size.
Parameters
[in] n the stack size to be assigned to the thread
Returns
The total used memory in bytes.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 802 of file ch.h.
THD_WORKING_AREA
#define THD_WORKING_AREA (s, n) PORT_WORKING_AREA(s, n)
Static working area allocation.
This macro is used to allocate a static thread working area aligned as both position and size.
Parameters
[in] s the name to be assigned to the stack array
[in] n the stack size to be assigned to the thread
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 815 of file ch.h.
THD_FUNCTION
#define THD_FUNCTION (tname, arg) PORT_THD_FUNCTION(tname, arg)
Thread declaration macro.
Note
Thread declarations should be performed using this macro because the port layer could define optimizations for thread functions.
Definition at line 826 of file ch.h.
CH_IRQ_IS_VALID_PRIORITY
#define CH_IRQ_IS_VALID_PRIORITY (prio) PORT_IRQ_IS_VALID_PRIORITY(prio)
Priority level validation macro.
This macro determines if the passed value is a valid priority level for the underlying architecture.
Parameters
[in] prio the priority level
Returns
Priority range result.
Return values
false if the priority is invalid or if the architecture does not support priorities.
true if the priority is valid.
Definition at line 844 of file ch.h.
CH_IRQ_IS_VALID_KERNEL_PRIORITY
#define CH_IRQ_IS_VALID_KERNEL_PRIORITY (prio) PORT_IRQ_IS_VALID_KERNEL_PRIORITY(prio)
Priority level validation macro.
This macro determines if the passed value is a valid priority level that cannot preempt the kernel critical zone.
Parameters
[in] prio the priority level
Returns
Priority range result.
Return values
false if the priority is invalid or if the architecture does not support priorities.
true if the priority is valid.
Definition at line 862 of file ch.h.
CH_IRQ_PROLOGUE
#define CH_IRQ_PROLOGUE ()
Value:
PORT_IRQ_PROLOGUE();                                                      \
  _dbg_check_enter_isr()
IRQ handler enter code.
Note
Usually IRQ handlers functions are also declared naked.
On some architectures this macro can be empty.
Function Class:Special function, this function has special requirements see the notes.
Definition at line 875 of file ch.h.
CH_IRQ_EPILOGUE
#define CH_IRQ_EPILOGUE ()
Value:
_dbg_check_leave_isr();                                                   \
  PORT_IRQ_EPILOGUE()
IRQ handler exit code.
Note
Usually IRQ handlers function are also declared naked.
Function Class:Special function, this function has special requirements see the notes.
Definition at line 885 of file ch.h.
CH_IRQ_HANDLER
#define CH_IRQ_HANDLER (id) PORT_IRQ_HANDLER(id)
Standard normal IRQ handler declaration.
Note
id can be a function name or a vector number depending on the port implementation.
Function Class:Special function, this function has special requirements see the notes.
Definition at line 896 of file ch.h.
CH_FAST_IRQ_HANDLER
#define CH_FAST_IRQ_HANDLER (id) PORT_FAST_IRQ_HANDLER(id)
Standard fast IRQ handler declaration.
Note
id can be a function name or a vector number depending on the port implementation.
Not all architectures support fast interrupts.
Function Class:Special function, this function has special requirements see the notes.
Definition at line 910 of file ch.h.
TIME_S2I
#define TIME_S2I (secs) ((sysinterval_t)((time_conv_t)(secs) * (time_conv_t)CH_CFG_ST_FREQUENCY))
Seconds to time interval.
Converts from seconds to system ticks number.
Note
The result is rounded upward to the next tick boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] secs number of seconds
Returns
The number of ticks.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 930 of file ch.h.
TIME_MS2I
#define TIME_MS2I (msecs)
Value:
((sysinterval_t)((((time_conv_t)(msecs) *                                 \
                     (time_conv_t)CH_CFG_ST_FREQUENCY) +                    \
                    (time_conv_t)999) / (time_conv_t)1000))
Milliseconds to time interval.
Converts from milliseconds to system ticks number.
Note
The result is rounded upward to the next tick boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] msecs number of milliseconds
Returns
The number of ticks.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 946 of file ch.h.
TIME_US2I
#define TIME_US2I (usecs)
Value:
((sysinterval_t)((((time_conv_t)(usecs) *                                 \
                     (time_conv_t)CH_CFG_ST_FREQUENCY) +                    \
                    (time_conv_t)999999) / (time_conv_t)1000000))
Microseconds to time interval.
Converts from microseconds to system ticks number.
Note
The result is rounded upward to the next tick boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] usecs number of microseconds
Returns
The number of ticks.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 964 of file ch.h.
TIME_I2S
#define TIME_I2S (interval)
Value:
(time_secs_t)(((time_conv_t)(interval) +                                  \
                 (time_conv_t)CH_CFG_ST_FREQUENCY -                         \
                 (time_conv_t)1) / (time_conv_t)CH_CFG_ST_FREQUENCY)
Time interval to seconds.
Converts from system ticks number to seconds.
Note
The result is rounded up to the next second boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] interval interval in ticks
Returns
The number of seconds.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 982 of file ch.h.
TIME_I2MS
#define TIME_I2MS (interval)
Value:
(time_msecs_t)((((time_conv_t)(interval) * (time_conv_t)1000) +           \
                  (time_conv_t)CH_CFG_ST_FREQUENCY - (time_conv_t)1) /      \
                 (time_conv_t)CH_CFG_ST_FREQUENCY)
Time interval to milliseconds.
Converts from system ticks number to milliseconds.
Note
The result is rounded up to the next millisecond boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] interval interval in ticks
Returns
The number of milliseconds.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1000 of file ch.h.
TIME_I2US
#define TIME_I2US (interval)
Value:
(time_msecs_t)((((time_conv_t)(interval) * (time_conv_t)1000000) +      \
                    (time_conv_t)CH_CFG_ST_FREQUENCY - (time_conv_t)1) /    \
                   (time_conv_t)CH_CFG_ST_FREQUENCY)
Time interval to microseconds.
Converts from system ticks number to microseconds.
Note
The result is rounded up to the next microsecond boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] interval interval in ticks
Returns
The number of microseconds.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1018 of file ch.h.
_THREADS_QUEUE_DATA
#define _THREADS_QUEUE_DATA (name) {(cnt_t)0}
Data part of a static threads queue object initializer.
This macro should be used when statically initializing a threads queue that is part of a bigger structure.
Parameters
[in] name the name of the threads queue variable
Definition at line 1034 of file ch.h.
_THREADS_QUEUE_DECL
#define _THREADS_QUEUE_DECL (name) threads_queue_t name = _THREADS_QUEUE_DATA(name)
Static threads queue object initializer.
Statically initialized threads queues require no explicit initialization using queue_init().
Parameters
[in] name the name of the threads queue variable
Definition at line 1043 of file ch.h.
_SEMAPHORE_DATA
#define _SEMAPHORE_DATA (name, n) {n}
Data part of a static semaphore initializer.
This macro should be used when statically initializing a semaphore that is part of a bigger structure.
Parameters
[in] name the name of the semaphore variable
[in] n the counter initial value, this value must be non-negative
Definition at line 1060 of file ch.h.
SEMAPHORE_DECL
#define SEMAPHORE_DECL (name, n) semaphore_t name = _SEMAPHORE_DATA(name, n)
Static semaphore initializer.
Statically initialized semaphores require no explicit initialization using chSemInit().
Parameters
[in] name the name of the semaphore variable
[in] n the counter initial value, this value must be non-negative
Definition at line 1071 of file ch.h.
chSysGetRealtimeCounterX
#define chSysGetRealtimeCounterX () (rtcnt_t)port_rt_get_counter_value()
Returns the current value of the system real time counter.
Note
This function is only available if the port layer supports the option PORT_SUPPORTS_RT.
Returns
The value of the system realtime counter of type rtcnt_t.
Function Class:This is an X-Class API, this function can be invoked from any context.
Definition at line 1089 of file ch.h.
Referenced by chSysPolledDelayX().
chSysDisable
#define chSysDisable ()
Value:
{                                                    \
  port_disable();                                                           \
  _dbg_check_disable();                                                     \
}
Raises the system interrupt priority mask to the maximum level.
All the maskable interrupt sources are disabled regardless their hardware priority.
Note
Do not invoke this API from within a kernel lock.
Function Class:Special function, this function has special requirements see the notes.
Definition at line 1100 of file ch.h.
chSysSuspend
#define chSysSuspend ()
Value:
{                                                    \
  port_suspend();                                                           \
  _dbg_check_suspend();                                                     \
}
Raises the system interrupt priority mask to system level.
The interrupt sources that should not be able to preempt the kernel are disabled, interrupt sources with higher priority are still enabled.
Note
Do not invoke this API from within a kernel lock.
This API is no replacement for chSysLock(), the chSysLock() could do more than just disable the interrupts.
Function Class:Special function, this function has special requirements see the notes.
Definition at line 1116 of file ch.h.
Referenced by chSysInit().
chSysEnable
#define chSysEnable ()
Value:
{                                                     \
  _dbg_check_enable();                                                      \
  port_enable();                                                            \
}
Lowers the system interrupt priority mask to user level.
All the interrupt sources are enabled.
Note
Do not invoke this API from within a kernel lock.
This API is no replacement for chSysUnlock(), the chSysUnlock() could do more than just enable the interrupts.
Function Class:Special function, this function has special requirements see the notes.
Definition at line 1130 of file ch.h.
chSysLock
#define chSysLock ()
Value:
{                                                       \
  port_lock();                                                              \
  _dbg_check_lock();                                                        \
}
Enters the kernel lock state.
Function Class:Special function, this function has special requirements see the notes.
Definition at line 1140 of file ch.h.
Referenced by chBSemSignal(), chCoreAllocAligned(), chCoreAllocAlignedWithOffset(), chEvtSignal(), chEvtWaitAnyTimeout(), chGuardedPoolAllocTimeout(), chGuardedPoolFree(), chMBFetchTimeout(), chMBPostAheadTimeout(), chMBPostTimeout(), chMBReset(), chPoolAlloc(), chPoolFree(), chSemReset(), chSemSignal(), chSemWaitTimeout(), chSysGetStatusAndLockX(), chSysUnconditionalLock(), chThdResume(), chThdSleep(), and chThdSleepUntil().
chSysUnlock
#define chSysUnlock ()
Value:
{                                                     \
  _dbg_check_unlock();                                                      \
  port_unlock();                                                            \
}
Leaves the kernel lock state.
Function Class:Special function, this function has special requirements see the notes.
Definition at line 1150 of file ch.h.
Referenced by chBSemSignal(), chCoreAllocAligned(), chCoreAllocAlignedWithOffset(), chEvtSignal(), chEvtWaitAnyTimeout(), chGuardedPoolAllocTimeout(), chGuardedPoolFree(), chMBFetchTimeout(), chMBPostAheadTimeout(), chMBPostTimeout(), chMBReset(), chPoolAlloc(), chPoolFree(), chSemReset(), chSemSignal(), chSemWaitTimeout(), chSysInit(), chSysRestoreStatusX(), chSysUnconditionalUnlock(), chThdResume(), chThdSleep(), and chThdSleepUntil().
chSysLockFromISR
#define chSysLockFromISR ()
Value:
{                                                \
  port_lock_from_isr();                                                     \
  _dbg_check_lock_from_isr();                                               \
}
Enters the kernel lock state from within an interrupt handler.
Note
This API may do nothing on some architectures, it is required because on ports that support preemptable interrupt handlers it is required to raise the interrupt mask to the same level of the system mutual exclusion zone.
It is good practice to invoke this API before invoking any I-class syscall from an interrupt handler.
This API must be invoked exclusively from interrupt handlers.
Function Class:Special function, this function has special requirements see the notes.
Definition at line 1167 of file ch.h.
Referenced by chSysGetStatusAndLockX().
chSysUnlockFromISR
#define chSysUnlockFromISR ()
Value:
{                                              \
  _dbg_check_unlock_from_isr();                                             \
  port_unlock_from_isr();                                                   \
}
Leaves the kernel lock state from within an interrupt handler.
Note
This API may do nothing on some architectures, it is required because on ports that support preemptable interrupt handlers it is required to raise the interrupt mask to the same level of the system mutual exclusion zone.
It is good practice to invoke this API after invoking any I-class syscall from an interrupt handler.
This API must be invoked exclusively from interrupt handlers.
Function Class:Special function, this function has special requirements see the notes.
Definition at line 1185 of file ch.h.
Referenced by chSysRestoreStatusX().
chSchIsRescRequiredI
#define chSchIsRescRequiredI () ((bool)(nil.current != nil.next))
Evaluates if a reschedule is required.
Return values
true if there is a thread that must go in running state immediately.
false if preemption is not required.
Function Class:This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 1199 of file ch.h.
Referenced by chSchIsPreemptionRequired(), and chSchRescheduleS().
chThdGetSelfX
#define chThdGetSelfX () nil.current
Returns a pointer to the current thread_t.
Function Class:This is an X-Class API, this function can be invoked from any context.
Definition at line 1206 of file ch.h.
chThdSleepSeconds
#define chThdSleepSeconds (secs) chThdSleep(TIME_S2I(secs))
Delays the invoking thread for the specified number of seconds.
Note
The specified time is rounded up to a value allowed by the real system clock.
The maximum specified value is implementation dependent.
Parameters
[in] secs time in seconds, must be different from zero
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1218 of file ch.h.
chThdSleepMilliseconds
#define chThdSleepMilliseconds (msecs) chThdSleep(TIME_MS2I(msecs))
Delays the invoking thread for the specified number of milliseconds.
Note
The specified time is rounded up to a value allowed by the real system clock.
The maximum specified value is implementation dependent.
Parameters
[in] msecs time in milliseconds, must be different from zero
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1231 of file ch.h.
chThdSleepMicroseconds
#define chThdSleepMicroseconds (usecs) chThdSleep(TIME_US2I(usecs))
Delays the invoking thread for the specified number of microseconds.
Note
The specified time is rounded up to a value allowed by the real system clock.
The maximum specified value is implementation dependent.
Parameters
[in] usecs time in microseconds, must be different from zero
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1244 of file ch.h.
chThdSleepS
#define chThdSleepS (timeout) (void) chSchGoSleepTimeoutS(NIL_STATE_SLEEPING, timeout)
Suspends the invoking thread for the specified time.
Parameters
[in] timeout the delay in system ticks
Function Class:This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 1253 of file ch.h.
Referenced by chThdSleep().
chThdSleepUntilS
#define chThdSleepUntilS (abstime)
Value:
(void) chSchGoSleepTimeoutS(NIL_STATE_SLEEPING,                           \
                              chTimeDiffX(chVTGetSystemTimeX(), (abstime)))
Suspends the invoking thread until the system time arrives to the specified value.
Parameters
[in] abstime absolute system time
Function Class:This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 1264 of file ch.h.
Referenced by chThdSleepUntil().
chThdQueueObjectInit
#define chThdQueueObjectInit (tqp) ((tqp)->cnt = (cnt_t)0)
Initializes a threads queue object.
Parameters
[out] tqp pointer to the threads queue object
Function Class:Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 1275 of file ch.h.
Referenced by chMBObjectInit().
chThdQueueIsEmptyI
#define chThdQueueIsEmptyI (tqp) ((bool)(tqp->cnt >= (cnt_t)0))
Evaluates to true if the specified queue is empty.
Parameters
[out] tqp pointer to the threads queue object
Returns
The queue status.
Return values
false if the queue is not empty.
true if the queue is empty.
Function Class:This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 1287 of file ch.h.
chSemObjectInit
#define chSemObjectInit (sp, n) ((sp)->cnt = n)
Initializes a semaphore with the specified counter value.
Parameters
[out] sp pointer to a semaphore_t structure
[in] n initial value of the semaphore counter. Must be non-negative.
Function Class:Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 1299 of file ch.h.
Referenced by _factory_init(), chBSemObjectInit(), and chGuardedPoolObjectInitAligned().
chSemWait
#define chSemWait (sp) chSemWaitTimeout(sp, TIME_INFINITE)
Performs a wait operation on a semaphore.
Parameters
[in] sp pointer to a semaphore_t structure
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
CH_MSG_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
CH_MSG_RST if the semaphore has been reset using chSemReset().
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1313 of file ch.h.
Referenced by chBSemWait().
chSemWaitS
#define chSemWaitS (sp) chSemWaitTimeoutS(sp, TIME_INFINITE)
Performs a wait operation on a semaphore.
Parameters
[in] sp pointer to a semaphore_t structure
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
CH_MSG_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
CH_MSG_RST if the semaphore has been reset using chSemReset().
Function Class:This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 1327 of file ch.h.
Referenced by chBSemWaitS().
chSemFastWaitI
#define chSemFastWaitI (sp) ((sp)->cnt--)
Decreases the semaphore counter.
This macro can be used when the counter is known to be positive.
Parameters
[in] sp pointer to a semaphore_t structure
Function Class:This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 1337 of file ch.h.
Referenced by chGuardedPoolAllocI().
chSemFastSignalI
#define chSemFastSignalI (sp) ((sp)->cnt++)
Increases the semaphore counter.
This macro can be used when the counter is known to be not negative.
Parameters
[in] sp pointer to a semaphore_t structure
Function Class:This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 1348 of file ch.h.
chSemGetCounterI
#define chSemGetCounterI (sp) ((sp)->cnt)
Returns the semaphore counter current value.
Function Class:This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 1355 of file ch.h.
Referenced by chGuardedPoolAllocI().
chVTGetSystemTimeX
#define chVTGetSystemTimeX () (nil.systime)
Current system time.
Returns the number of system ticks since the chSysInit() invocation.
Note
The counter can reach its maximum and then restart from zero.
This function can be called from any context but its atomicity is not guaranteed on architectures whose word size is less than systime_t size.
Returns
The system time in ticks.
Function Class:This is an X-Class API, this function can be invoked from any context.
Definition at line 1372 of file ch.h.
Referenced by chSchGoSleepTimeoutS().
chVTTimeElapsedSinceX
#define chVTTimeElapsedSinceX (start) chTimeDiffX((start), chVTGetSystemTimeX())
Returns the elapsed time since the specified start time.
Parameters
[in] start start time
Returns
The elapsed time.
Function Class:This is an X-Class API, this function can be invoked from any context.
Definition at line 1385 of file ch.h.
chTimeAddX
#define chTimeAddX (systime, interval) ((systime_t)(systime) + (systime_t)(interval))
Adds an interval to a system time returning a system time.
Parameters
[in] systime base system time
[in] interval interval to be added
Returns
The new system time.
Function Class:This is an X-Class API, this function can be invoked from any context.
Definition at line 1397 of file ch.h.
Referenced by chSchGoSleepTimeoutS().
chTimeDiffX
#define chTimeDiffX (start, end) ((sysinterval_t)((systime_t)((systime_t)(end) - (systime_t)(start))))
Subtracts two system times returning an interval.
Parameters
[in] start first system time
[in] end second system time
Returns
The interval representing the time difference.
Function Class:This is an X-Class API, this function can be invoked from any context.
Definition at line 1409 of file ch.h.
chTimeIsInRangeX
#define chTimeIsInRangeX (time, start, end)
Value:
((bool)((systime_t)((systime_t)(time) - (systime_t)(start)) <             \
          (systime_t)((systime_t)(end) - (systime_t)(start))))
Checks if the specified time is within the specified time range.
Note
When start==end then the function returns always true because the whole time range is specified.
Parameters
[in] time the time to be verified
[in] start the start of the time window (inclusive)
[in] end the end of the time window (non inclusive)
Return values
true current time within the specified time window.
false current time not within the specified time window.
Function Class:This is an X-Class API, this function can be invoked from any context.
Definition at line 1425 of file ch.h.
Referenced by chSchGoSleepTimeoutS().
chDbgCheck
#define chDbgCheck (c)
Value:
do {                                                  \
  /*lint -save -e506 -e774 [2.1, 14.3] Can be a constant by design.*/       \
  if (CH_DBG_ENABLE_CHECKS != FALSE) {                                      \
    if (!(c)) {                                                             \
  /*lint -restore*/                                                         \
      chSysHalt(__func__);                                                  \
    }                                                                       \
  }                                                                         \
} while (false)
Function parameters check.
If the condition check fails then the kernel panics and halts.
Note
The condition is tested only if the CH_DBG_ENABLE_CHECKS switch is specified in chconf.h else the macro does nothing.
Parameters
[in] c the condition to be verified to be true
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1440 of file ch.h.
Referenced by chCoreAllocAlignedWithOffsetI(), chEvtSignalI(), chGuardedPoolLoadArray(), chHeapAllocAligned(), chHeapFree(), chHeapObjectInit(), chMBFetchI(), chMBFetchTimeoutS(), chMBObjectInit(), chMBPostAheadI(), chMBPostAheadTimeoutS(), chMBPostI(), chMBPostTimeoutS(), chMBResetI(), chPoolAllocI(), chPoolFreeI(), chPoolLoadArray(), chPoolObjectInitAligned(), chSchReadyI(), chSemResetI(), chSemSignalI(), chSemWaitTimeoutS(), chThdDequeueAllI(), chThdDequeueNextI(), and chThdEnqueueTimeoutS().
chDbgAssert
#define chDbgAssert (c, r)
Value:
do {                                              \
  /*lint -save -e506 -e774 [2.1, 14.3] Can be a constant by design.*/       \
  if (CH_DBG_ENABLE_ASSERTS != FALSE) {                                     \
    if (!(c)) {                                                             \
  /*lint -restore*/                                                         \
      chSysHalt(__func__);                                                  \
    }                                                                       \
  }                                                                         \
} while (false)
Condition assertion.
If the condition check fails then the kernel panics with a message and halts.
Note
The condition is tested only if the CH_DBG_ENABLE_ASSERTS switch is specified in chconf.h else the macro does nothing.
The remark string is not currently used except for putting a comment in the code about the assertion.
Parameters
[in] c the condition to be verified to be true
[in] r a remark string
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1466 of file ch.h.
Referenced by chFifoSendObject(), chFifoSendObjectAhead(), chFifoSendObjectAheadI(), chFifoSendObjectAheadS(), chFifoSendObjectI(), chFifoSendObjectS(), chGuardedPoolAllocI(), chPoolFreeI(), chSchGoSleepTimeoutS(), chSchReadyI(), chSysTimerHandlerI(), chThdDoDequeueNextI(), chThdEnqueueTimeoutS(), chThdResumeI(), chThdSuspendTimeoutS(), nil_find_thread(), and nil_ready_all().
Typedef Documentation
systime_t
typedef uint32_t systime_t
Type of system time.
Note
It is selectable in configuration between 16 or 32 bits.
Definition at line 536 of file ch.h.
sysinterval_t
typedef uint32_t sysinterval_t
Type of time interval.
Note
It is selectable in configuration between 16 or 32 bits.
Definition at line 542 of file ch.h.
time_conv_t
typedef uint64_t time_conv_t
Type of time conversion variable.
Note
This type must have double width than other time types, it is only used internally for conversions.
Definition at line 549 of file ch.h.
thread_t
typedef struct nil_thread thread_t
Type of a structure representing a thread.
Note
It is required as an early definition.
Definition at line 561 of file ch.h.
threads_queue_t
typedef struct nil_threads_queue threads_queue_t
Type of a queue of threads.
Definition at line 575 of file ch.h.
semaphore_t
typedef threads_queue_t semaphore_t
Type of a structure representing a semaphore.
Note
Semaphores are implemented on thread queues, the object is the same, the behavior is slightly different.
Definition at line 583 of file ch.h.
tfunc_t
typedef void(* tfunc_t) (void *p)
Thread function.
Definition at line 589 of file ch.h.
thread_config_t
typedef struct nil_thread_cfg thread_config_t
Type of a structure representing a thread static configuration.
Definition at line 594 of file ch.h.
thread_reference_t
typedef thread_t* thread_reference_t
Type of a thread reference.
Definition at line 610 of file ch.h.
nil_system_t
typedef struct nil_system nil_system_t
Type of a structure representing the system.
Definition at line 647 of file ch.h.
Function Documentation
nil_find_thread()
static thread_t* nil_find_thread (tstate_t state, void * p) static
Retrieves the highest priority thread in the specified state and associated to the specified object.
Note
The search is unbounded, the thread is assumed to exist.
Parameters
[in] state thread state
[in] p object pointer
Returns
Pointer to the thread.
Definition at line 61 of file ch.c.
References CH_CFG_NUM_THREADS, chDbgAssert, nil_thread::p, nil_thread::state, and nil_system::threads.
Referenced by chSemSignalI(), and chThdDoDequeueNextI().
nil_ready_all()
static cnt_t nil_ready_all (void * p, cnt_t cnt, msg_t msg) static
Puts in ready state all thread matching the specified status and associated object.
Parameters
[in] p object pointer
[in] cnt number of threads to be readied as a negative number, non negative numbers are ignored
[in] msg the wakeup message
Returns
Always zero.
Function Class:This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 88 of file ch.c.
References CH_CFG_NUM_THREADS, chDbgAssert, chSchReadyI(), NIL_STATE_WTQUEUE, nil_thread::p, nil_thread::state, and nil_system::threads.
Referenced by chSemResetI(), and chThdDequeueAllI().
_dbg_check_disable()
void _dbg_check_disable (void)
Guard code for chSysDisable().
Function Class:Not an API, this function is for internal use only.
Definition at line 121 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
_dbg_check_suspend()
void _dbg_check_suspend (void)
Guard code for chSysSuspend().
Function Class:Not an API, this function is for internal use only.
Definition at line 133 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
_dbg_check_enable()
void _dbg_check_enable (void)
Guard code for chSysEnable().
Function Class:Not an API, this function is for internal use only.
Definition at line 145 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
_dbg_check_lock()
void _dbg_check_lock (void)
Guard code for chSysLock().
Function Class:Not an API, this function is for internal use only.
Definition at line 157 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
_dbg_check_unlock()
void _dbg_check_unlock (void)
Guard code for chSysUnlock().
Function Class:Not an API, this function is for internal use only.
Definition at line 170 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
_dbg_check_lock_from_isr()
void _dbg_check_lock_from_isr (void)
Guard code for chSysLockFromIsr().
Function Class:Not an API, this function is for internal use only.
Definition at line 183 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
_dbg_check_unlock_from_isr()
void _dbg_check_unlock_from_isr (void)
Guard code for chSysUnlockFromIsr().
Function Class:Not an API, this function is for internal use only.
Definition at line 196 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
_dbg_check_enter_isr()
void _dbg_check_enter_isr (void)
Guard code for CH_IRQ_PROLOGUE().
Function Class:Not an API, this function is for internal use only.
Definition at line 209 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
_dbg_check_leave_isr()
void _dbg_check_leave_isr (void)
Guard code for CH_IRQ_EPILOGUE().
Function Class:Not an API, this function is for internal use only.
Definition at line 224 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
chDbgCheckClassI()
void chDbgCheckClassI (void)
I-class functions context check.
Verifies that the system is in an appropriate state for invoking an I-class API function. A panic is generated if the state is not compatible.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 242 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
Referenced by chBSemGetStateI(), chBSemResetI(), chBSemSignalI(), chCoreAllocAlignedWithOffsetI(), chEvtSignalI(), chMBFetchI(), chMBGetFreeCountI(), chMBGetUsedCountI(), chMBPeekI(), chMBPostAheadI(), chMBPostI(), chMBResetI(), chPoolAllocI(), chPoolFreeI(), chSchReadyI(), chSemResetI(), chSemSignalI(), chSysTimerHandlerI(), chThdDequeueAllI(), and chThdDequeueNextI().
chDbgCheckClassS()
void chDbgCheckClassS (void)
S-class functions context check.
Verifies that the system is in an appropriate state for invoking an S-class API function. A panic is generated if the state is not compatible.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 257 of file ch.c.
References chSysHalt(), nil_system::isr_cnt, and nil_system::lock_cnt.
Referenced by chBSemWaitS(), chBSemWaitTimeoutS(), chMBFetchTimeoutS(), chMBPostAheadTimeoutS(), chMBPostTimeoutS(), chSchGoSleepTimeoutS(), chSchRescheduleS(), chSemWaitTimeoutS(), and chThdEnqueueTimeoutS().
chSysInit()
void chSysInit (void)
Initializes the kernel.
Initializes the kernel structures, the current instructions flow becomes the idle thread upon return. The idle thread must not invoke any kernel primitive able to change state to not runnable.
Note
This function assumes that the nil global variable has been zeroed by the runtime environment. If this is not the case then make sure to clear it before calling this function.
Function Class:Special function, this function has special requirements see the notes.
Definition at line 276 of file ch.c.
References _core_init(), _factory_init(), _heap_init(), nil_thread_cfg::arg, CH_CFG_NUM_THREADS, CH_CFG_SYSTEM_INIT_HOOK, CH_CFG_THREAD_EXT_INIT_HOOK, chSysSuspend, chSysUnlock, nil_system::current, nil_thread_cfg::funcp, nil_system::isr_cnt, nil_system::lock_cnt, nil_system::next, THD_IDLE_BASE, nil_system::threads, nil_thread::wabase, nil_thread_cfg::wbase, and nil_thread_cfg::wend.
chSysHalt()
void chSysHalt (const char * reason)
Halts the system.
This function is invoked by the operating system when an unrecoverable error is detected, for example because a programming error in the application code that triggers an assertion while in debug mode.
Note
Can be invoked from any system state.
Parameters
[in] reason pointer to an error string
Function Class:Special function, this function has special requirements see the notes.
Definition at line 357 of file ch.c.
References CH_CFG_SYSTEM_HALT_HOOK, and nil_system::dbg_panic_msg.
Referenced by _dbg_check_disable(), _dbg_check_enable(), _dbg_check_enter_isr(), _dbg_check_leave_isr(), _dbg_check_lock(), _dbg_check_lock_from_isr(), _dbg_check_suspend(), _dbg_check_unlock(), _dbg_check_unlock_from_isr(), chDbgCheckClassI(), and chDbgCheckClassS().
chSysTimerHandlerI()
void chSysTimerHandlerI (void)
Time management handler.
Note
This handler has to be invoked by a periodic ISR in order to reschedule the waiting threads.
Function Class:This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 382 of file ch.c.
References chDbgAssert, chDbgCheckClassI(), nil_system::systime, nil_system::threads, and nil_thread::timeout.
chSysUnconditionalLock()
void chSysUnconditionalLock (void)
Unconditionally enters the kernel lock state.
Note
Can be called without previous knowledge of the current lock state. The final state is "s-locked".
Function Class:Special function, this function has special requirements see the notes.
Definition at line 482 of file ch.c.
References chSysLock.
chSysUnconditionalUnlock()
void chSysUnconditionalUnlock (void)
Unconditionally leaves the kernel lock state.
Note
Can be called without previous knowledge of the current lock state. The final state is "normal".
Function Class:Special function, this function has special requirements see the notes.
Definition at line 496 of file ch.c.
References chSysUnlock.
chSysGetStatusAndLockX()
syssts_t chSysGetStatusAndLockX (void)
Returns the execution status and enters a critical zone.
This functions enters into a critical zone and can be called from any context. Because its flexibility it is less efficient than chSysLock() which is preferable when the calling context is known.
Postcondition
The system is in a critical zone.
Returns
The previous system status, the encoding of this status word is architecture-dependent and opaque.
Function Class:This is an X-Class API, this function can be invoked from any context.
Definition at line 516 of file ch.c.
References chSysLock, and chSysLockFromISR.
chSysRestoreStatusX()
void chSysRestoreStatusX (syssts_t sts)
Restores the specified execution status and leaves a critical zone.
Note
A call to chSchRescheduleS() is automatically performed if exiting the critical zone and if not in ISR context.
Parameters
[in] sts the system status to be restored.
Function Class:This is an X-Class API, this function can be invoked from any context.
Definition at line 539 of file ch.c.
References chSchRescheduleS(), chSysUnlock, and chSysUnlockFromISR.
chSysIsCounterWithinX()
bool chSysIsCounterWithinX (rtcnt_t cnt, rtcnt_t start, rtcnt_t end)
Realtime window test.
This function verifies if the current realtime counter value lies within the specified range or not. The test takes care of the realtime counter wrapping to zero on overflow.
Note
When start==end then the function returns always true because the whole time range is specified.
This function is only available if the port layer supports the option PORT_SUPPORTS_RT.
Parameters
[in] cnt the counter value to be tested
[in] start the start of the time window (inclusive)
[in] end the end of the time window (non inclusive)
Return values
true current time within the specified time window.
false current time not within the specified time window.
Function Class:This is an X-Class API, this function can be invoked from any context.
Definition at line 571 of file ch.c.
Referenced by chSysPolledDelayX().
chSysPolledDelayX()
void chSysPolledDelayX (rtcnt_t cycles)
Polled delay.
Note
The real delay is always few cycles in excess of the specified value.
This function is only available if the port layer supports the option PORT_SUPPORTS_RT.
Parameters
[in] cycles number of cycles
Function Class:This is an X-Class API, this function can be invoked from any context.
Definition at line 587 of file ch.c.
References chSysGetRealtimeCounterX, and chSysIsCounterWithinX().
chSchReadyI()
thread_t * chSchReadyI (thread_t * tp, msg_t msg)
Makes the specified thread ready for execution.
Parameters
[in] tp pointer to the thread_t object
[in] msg the wakeup message
Returns
The same reference passed as parameter.
Definition at line 604 of file ch.c.
References CH_CFG_NUM_THREADS, chDbgAssert, chDbgCheck, chDbgCheckClassI(), and nil_system::threads.
Referenced by chSemSignalI(), chThdDoDequeueNextI(), and nil_ready_all().
chSchIsPreemptionRequired()
bool chSchIsPreemptionRequired (void)
Evaluates if preemption is required.
The decision is taken by comparing the relative priorities and depending on the state of the round robin timeout counter.
Note
Not a user function, it is meant to be invoked by the scheduler itself or from within the port layer.
Return values
true if there is a thread that must go in running state immediately.
false if preemption is not required.
Function Class:Special function, this function has special requirements see the notes.
Definition at line 633 of file ch.c.
References chSchIsRescRequiredI.
chSchDoReschedule()
void chSchDoReschedule (void)
Switches to the first thread on the runnable queue.
Note
Not a user function, it is meant to be invoked by the scheduler itself or from within the port layer.
Function Class:Special function, this function has special requirements see the notes.
Definition at line 645 of file ch.c.
References CH_CFG_IDLE_LEAVE_HOOK, CH_CFG_NUM_THREADS, nil_system::current, nil_system::next, and nil_system::threads.
Referenced by chSchRescheduleS().
chSchRescheduleS()
void chSchRescheduleS (void)
Reschedules if needed.
Function Class:This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 660 of file ch.c.
References chDbgCheckClassS(), chSchDoReschedule(), and chSchIsRescRequiredI.
Referenced by chBSemSignal(), chEvtSignal(), chGuardedPoolFree(), chGuardedPoolFreeS(), chMBFetchTimeoutS(), chMBPostAheadTimeoutS(), chMBPostTimeoutS(), chMBReset(), chSemReset(), chSemSignal(), chSysRestoreStatusX(), and chThdResume().
chSchGoSleepTimeoutS()
msg_t chSchGoSleepTimeoutS (tstate_t newstate, sysinterval_t timeout)
Puts the current thread to sleep into the specified state with timeout specification.
The thread goes into a sleeping state, if it is not awakened explicitly within the specified system time then it is forcibly awakened with a NIL_MSG_TMO low level message.
Parameters
[in] newstate the new thread state or a semaphore pointer
[in] timeout the number of ticks before the operation timeouts. the following special values are allowed:
TIME_INFINITE no timeout.
Returns
The wakeup message.
Return values
NIL_MSG_TMO if a timeout occurred.
Function Class:This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 686 of file ch.c.
References CH_CFG_NUM_THREADS, CH_CFG_ST_TIMEDELTA, chDbgAssert, chDbgCheckClassS(), chTimeAddX, chTimeIsInRangeX, chVTGetSystemTimeX, nil_system::current, nil_system::lasttime, nil_system::nexttime, nil_thread::state, nil_system::threads, TIME_INFINITE, and nil_thread::timeout.
Referenced by chEvtWaitAnyTimeout(), chSemWaitTimeoutS(), chThdEnqueueTimeoutS(), and chThdSuspendTimeoutS().
chThdSuspendTimeoutS()
msg_t chThdSuspendTimeoutS (thread_reference_t * trp, sysinterval_t timeout)
Sends the current thread sleeping and sets a reference variable.
Note
This function must reschedule, it can only be called from thread context.
Parameters
[in] trp a pointer to a thread reference object
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
TIME_IMMEDIATE the thread is not enqueued and the function returns MSG_TIMEOUT as if a timeout occurred.
Returns
The wake up message.
Function Class:This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 770 of file ch.c.
References chDbgAssert, chSchGoSleepTimeoutS(), nil_system::current, MSG_TIMEOUT, NIL_STATE_SUSP, TIME_IMMEDIATE, and nil_thread::trp.
chThdResumeI()
void chThdResumeI (thread_reference_t * trp, msg_t msg)
Wakes up a thread waiting on a thread reference object.
Note
This function must not reschedule because it can be called from ISR context.
Parameters
[in] trp a pointer to a thread reference object
[in] msg the message code
Function Class:This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 793 of file ch.c.
References chDbgAssert.
Referenced by chThdResume().
chThdResume()
void chThdResume (thread_reference_t * trp, msg_t msg)
Wakes up a thread waiting on a thread reference object.
Note
This function must reschedule, it can only be called from thread context.
Parameters
[in] trp a pointer to a thread reference object
[in] msg the message code
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 815 of file ch.c.
References chSchRescheduleS(), chSysLock, chSysUnlock, and chThdResumeI().
chThdSleep()
void chThdSleep (sysinterval_t timeout)
Suspends the invoking thread for the specified time.
Parameters
[in] timeout the delay in system ticks
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 830 of file ch.c.
References chSysLock, chSysUnlock, and chThdSleepS.
chThdSleepUntil()
void chThdSleepUntil (systime_t abstime)
Suspends the invoking thread until the system time arrives to the specified value.
Parameters
[in] abstime absolute system time
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 845 of file ch.c.
References chSysLock, chSysUnlock, and chThdSleepUntilS.
chThdEnqueueTimeoutS()
msg_t chThdEnqueueTimeoutS (threads_queue_t * tqp, sysinterval_t timeout)
Enqueues the caller thread on a threads queue object.
The caller thread is enqueued and put to sleep until it is dequeued or the specified timeouts expires.
Parameters
[in] tqp pointer to the threads queue object
[in] timeout the timeout in system ticks, the special values are handled as follow:
TIME_INFINITE the thread enters an infinite sleep state.
TIME_IMMEDIATE the thread is not enqueued and the function returns MSG_TIMEOUT as if a timeout occurred.
Returns
The message from osalQueueWakeupOneI() or osalQueueWakeupAllI() functions.
Return values
MSG_TIMEOUT if the thread has not been dequeued within the specified timeout or if the function has been invoked with TIME_IMMEDIATE as timeout specification.
Function Class:This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 875 of file ch.c.
References chDbgAssert, chDbgCheck, chDbgCheckClassS(), chSchGoSleepTimeoutS(), nil_threads_queue::cnt, nil_system::current, MSG_TIMEOUT, NIL_STATE_WTQUEUE, TIME_IMMEDIATE, and nil_thread::tqp.
Referenced by chMBFetchTimeoutS(), chMBPostAheadTimeoutS(), and chMBPostTimeoutS().
chThdDoDequeueNextI()
void chThdDoDequeueNextI (threads_queue_t * tqp, msg_t msg)
Dequeues and wakes up one thread from the threads queue object.
Dequeues one thread from the queue without checking if the queue is empty.
Precondition
The queue must contain at least an object.
Parameters
[in] tqp pointer to the threads queue object
[in] msg the message code
Function Class:This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 902 of file ch.c.
References chDbgAssert, chSchReadyI(), nil_threads_queue::cnt, nil_find_thread(), and NIL_STATE_WTQUEUE.
Referenced by chThdDequeueNextI().
chThdDequeueNextI()
void chThdDequeueNextI (threads_queue_t * tqp, msg_t msg)
Dequeues and wakes up one thread from the threads queue object, if any.
Parameters
[in] tqp pointer to the threads queue object
[in] msg the message code
Function Class:This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 921 of file ch.c.
References chDbgCheck, chDbgCheckClassI(), chThdDoDequeueNextI(), and nil_threads_queue::cnt.
Referenced by chMBFetchI(), chMBFetchTimeoutS(), chMBPostAheadI(), chMBPostAheadTimeoutS(), chMBPostI(), and chMBPostTimeoutS().
chThdDequeueAllI()
void chThdDequeueAllI (threads_queue_t * tqp, msg_t msg)
Dequeues and wakes up all threads from the threads queue object.
Parameters
[in] tqp pointer to the threads queue object
[in] msg the message code
Function Class:This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 939 of file ch.c.
References chDbgCheck, chDbgCheckClassI(), nil_threads_queue::cnt, and nil_ready_all().
Referenced by chMBResetI().
chSemWaitTimeout()
msg_t chSemWaitTimeout (semaphore_t * sp, sysinterval_t timeout)
Performs a wait operation on a semaphore with timeout specification.
Parameters
[in] sp pointer to a semaphore_t structure
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
NIL_MSG_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
NIL_MSG_RST if the semaphore has been reset using chSemReset().
NIL_MSG_TMO if the semaphore has not been signaled or reset within the specified timeout.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 967 of file ch.c.
References chSemWaitTimeoutS(), chSysLock, and chSysUnlock.
Referenced by chBSemWaitTimeout().
chSemWaitTimeoutS()
msg_t chSemWaitTimeoutS (semaphore_t * sp, sysinterval_t timeout)
Performs a wait operation on a semaphore with timeout specification.
Parameters
[in] sp pointer to a semaphore_t structure
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
NIL_MSG_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
NIL_MSG_RST if the semaphore has been reset using chSemReset().
NIL_MSG_TMO if the semaphore has not been signaled or reset within the specified timeout.
Function Class:This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 996 of file ch.c.
References chDbgCheck, chDbgCheckClassS(), chSchGoSleepTimeoutS(), nil_threads_queue::cnt, nil_system::current, MSG_OK, MSG_TIMEOUT, NIL_STATE_WTQUEUE, nil_thread::semp, and TIME_IMMEDIATE.
Referenced by chBSemWaitTimeoutS(), chGuardedPoolAllocTimeoutS(), and chSemWaitTimeout().
chSemSignal()
void chSemSignal (semaphore_t * sp)
Performs a signal operation on a semaphore.
Parameters
[in] sp pointer to a semaphore_t structure
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1026 of file ch.c.
References chSchRescheduleS(), chSemSignalI(), chSysLock, and chSysUnlock.
chSemSignalI()
void chSemSignalI (semaphore_t * sp)
Performs a signal operation on a semaphore.
Postcondition
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters
[in] sp pointer to a semaphore_t structure
Function Class:This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 1045 of file ch.c.
References chDbgCheck, chDbgCheckClassI(), chSchReadyI(), nil_threads_queue::cnt, MSG_OK, nil_find_thread(), and NIL_STATE_WTQUEUE.
Referenced by chBSemSignalI(), chGuardedPoolFreeI(), and chSemSignal().
chSemReset()
void chSemReset (semaphore_t * sp, cnt_t n)
Performs a reset operation on the semaphore.
Postcondition
After invoking this function all the threads waiting on the semaphore, if any, are released and the semaphore counter is set to the specified, non negative, value.
Parameters
[in] sp pointer to a semaphore_t structure
[in] n the new value of the semaphore counter. The value must be non-negative.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1068 of file ch.c.
References chSchRescheduleS(), chSemResetI(), chSysLock, and chSysUnlock.
Referenced by chBSemReset().
chSemResetI()
void chSemResetI (semaphore_t * sp, cnt_t n)
Performs a reset operation on the semaphore.
Postcondition
After invoking this function all the threads waiting on the semaphore, if any, are released and the semaphore counter is set to the specified, non negative, value.
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters
[in] sp pointer to a semaphore_t structure
[in] n the new value of the semaphore counter. The value must be non-negative.
Function Class:This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 1092 of file ch.c.
References chDbgCheck, chDbgCheckClassI(), nil_threads_queue::cnt, MSG_RESET, and nil_ready_all().
Referenced by chBSemResetI(), and chSemReset().
chEvtSignal()
void chEvtSignal (thread_t * tp, eventmask_t mask)
Adds a set of event flags directly to the specified thread_t.
Parameters
[in] tp the thread to be signaled
[in] mask the event flags set to be ORed
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1115 of file ch.c.
References chEvtSignalI(), chSchRescheduleS(), chSysLock, and chSysUnlock.
chEvtSignalI()
void chEvtSignalI (thread_t * tp, eventmask_t mask)
Adds a set of event flags directly to the specified thread_t.
Postcondition
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters
[in] tp the thread to be signaled
[in] mask the event flags set to be ORed
Function Class:This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 1135 of file ch.c.
References chDbgCheck, chDbgCheckClassI(), and nil_thread::epmask.
Referenced by chEvtSignal().
chEvtWaitAnyTimeout()
eventmask_t chEvtWaitAnyTimeout (eventmask_t mask, sysinterval_t timeout)
Waits for any of the specified events.
The function waits for any event among those specified in mask to become pending then the events are cleared and returned.
Parameters
[in] mask mask of the event flags that the function should wait for, ALL_EVENTS enables all the events
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The mask of the served and cleared events.
Return values
0 if the operation has timed out.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1165 of file ch.c.
References chSchGoSleepTimeoutS(), chSysLock, chSysUnlock, nil_system::current, nil_thread::epmask, nil_thread::ewmask, MSG_OK, NIL_STATE_WTOREVT, and TIME_IMMEDIATE.
Variable Documentation
nil
nil_system_t nil
System data structures.
Definition at line 41 of file ch.c.