ChibiOS/HAL: Managed Flash Storage Driver
Managed Flash Storage Driver
HAL » Complex Drivers
Managed Flash Storage Driver.
Detailed Description
Managed Flash Storage Driver.
This module implements a managed flash storage able to store a finite number of variable-size records. Records are retrieved by their index number.
The driver is automatically performs:
Wear leveling.
Auto repair after power loss.
Garbage collection in order to remove erased data.
Macros
#define RET_ON_ERROR(err)
Error check helper.
Configuration options
#define MFS_CFG_MAX_RECORDS 32
Maximum number of indexed records in the managed storage.
#define MFS_CFG_MAX_REPAIR_ATTEMPTS 3
Maximum number of repair attempts on partition mount.
#define MFS_CFG_WRITE_VERIFY TRUE
Verify written data.
#define MFS_CFG_STRONG_CHECKING TRUE
Enables a stronger and slower check procedure on mount.
#define MFS_CFG_BUFFER_SIZE 32
Size of the buffer used for data copying.
Error codes handling macros
#define MFS_IS_ERROR(err) ((err) < MFS_NO_ERROR)
#define MFS_IS_WARNING(err) ((err) > MFS_NO_ERROR)
Typedefs
typedef uint32_t mfs_id_t
Type of a record identifier.
Data Structures
union mfs_bank_header_t
Type of a bank header.
union mfs_data_header_t
Type of a data block header.
struct MFSConfig
Type of a MFS configuration structure.
struct MFSDriver
Type of an MFS instance.
Functions
static mfs_error_t mfs_flash_read (MFSDriver *mfsp, flash_offset_t offset, size_t n, uint8_t *rp)
Flash read.
static mfs_error_t mfs_flash_write (MFSDriver *mfsp, flash_offset_t offset, size_t n, const uint8_t *wp)
Flash write.
static mfs_error_t mfs_flash_copy (MFSDriver *mfsp, flash_offset_t doffset, flash_offset_t soffset, uint32_t n)
Flash copy.
static mfs_error_t mfs_record_check (MFSDriver *mfsp, mfs_data_header_t *dhdrp, flash_offset_t offset, flash_offset_t limit, mfs_record_state_t *sts)
Verifies integrity of a record.
static mfs_error_t mfs_bank_erase (MFSDriver *mfsp, mfs_bank_t bank)
Erases and verifies all sectors belonging to a bank.
static mfs_error_t mfs_bank_verify_erase (MFSDriver *mfsp, mfs_bank_t bank)
Erases and verifies all sectors belonging to a bank.
static mfs_error_t mfs_bank_write_header (MFSDriver *mfsp, mfs_bank_t bank, uint32_t cnt)
Writes the validation header in a bank.
static mfs_error_t mfs_bank_scan_records (MFSDriver *mfsp, mfs_bank_t bank, mfs_bank_state_t *statep)
Scans blocks searching for records.
static mfs_error_t mfs_bank_get_state (MFSDriver *mfsp, mfs_bank_t bank, mfs_bank_state_t *statep, uint32_t *cntp)
Determines the state of a bank.
static mfs_error_t mfs_bank_mount (MFSDriver *mfsp, mfs_bank_t bank, mfs_bank_state_t *statep)
Selects a bank as current.
static mfs_error_t mfs_garbage_collect (MFSDriver *mfsp)
Enforces a garbage collection.
static mfs_error_t mfs_try_mount (MFSDriver *mfsp)
Performs a flash partition mount attempt.
mfs_error_t mfs_mount (MFSDriver *mfsp)
Configures and activates a MFS driver.
void mfsObjectInit (MFSDriver *mfsp)
Initializes an instance.
mfs_error_t mfsStart (MFSDriver *mfsp, const MFSConfig *config)
Configures and activates a MFS driver.
void mfsStop (MFSDriver *mfsp)
Deactivates a MFS driver.
mfs_error_t mfsErase (MFSDriver *mfsp)
Destroys the state of the managed storage by erasing the flash.
mfs_error_t mfsReadRecord (MFSDriver *mfsp, mfs_id_t id, size_t *np, uint8_t *buffer)
Retrieves and reads a data record.
mfs_error_t mfsWriteRecord (MFSDriver *mfsp, mfs_id_t id, size_t n, const uint8_t *buffer)
Creates or updates a data record.
mfs_error_t mfsEraseRecord (MFSDriver *mfsp, mfs_id_t id)
Erases a data record.
mfs_error_t mfsPerformGarbageCollection (MFSDriver *mfsp)
Enforces a garbage collection operation.
Enumerations
enum mfs_bank_t
Type of a flash bank.
enum mfs_state_t
Type of driver state machine states.
enum mfs_error_t
Type of an MFS error code.
enum mfs_bank_state_t
Type of a bank state assessment.
enum mfs_record_state_t
Type of a record state assessment.
Macro Definition Documentation
RET_ON_ERROR
#define RET_ON_ERROR (err)
Value:
do {                                              \
  mfs_error_t e = (err);                                                    \
  if (e != MFS_NO_ERROR) {                                                  \
    return e;                                                               \
  }                                                                         \
} while (false)
Error check helper.
Definition at line 52 of file mfs.c.
Referenced by mfs_flash_copy(), and mfs_try_mount().
MFS_CFG_MAX_RECORDS
#define MFS_CFG_MAX_RECORDS 32
Maximum number of indexed records in the managed storage.
Note
Record indexes go from 0 to MFS_CFG_MAX_RECORDS - 1.
Definition at line 54 of file mfs.h.
Referenced by mfsEraseRecord(), mfsReadRecord(), and mfsWriteRecord().
MFS_CFG_MAX_REPAIR_ATTEMPTS
#define MFS_CFG_MAX_REPAIR_ATTEMPTS 3
Maximum number of repair attempts on partition mount.
Definition at line 61 of file mfs.h.
MFS_CFG_WRITE_VERIFY
#define MFS_CFG_WRITE_VERIFY TRUE
Verify written data.
Definition at line 68 of file mfs.h.
MFS_CFG_STRONG_CHECKING
#define MFS_CFG_STRONG_CHECKING TRUE
Enables a stronger and slower check procedure on mount.
Strong checking requires reading of the whole written data and this can be slow, normal checking only checks integrity of metadata, data errors would be detected on read.
Definition at line 78 of file mfs.h.
MFS_CFG_BUFFER_SIZE
#define MFS_CFG_BUFFER_SIZE 32
Size of the buffer used for data copying.
Note
The buffer size must be a power of two and not smaller than 16 bytes.
Larger buffers improve performance, buffers with size multiple of the flash program page size work better.
Definition at line 89 of file mfs.h.
Referenced by mfs_flash_copy().
Typedef Documentation
mfs_id_t
typedef uint32_t mfs_id_t
Type of a record identifier.
Definition at line 176 of file mfs.h.
Enumeration Type Documentation
mfs_bank_t
enum mfs_bank_t
Type of a flash bank.
Definition at line 120 of file mfs.h.
mfs_state_t
enum mfs_state_t
Type of driver state machine states.
Definition at line 128 of file mfs.h.
mfs_error_t
enum mfs_error_t
Type of an MFS error code.
Note
Errors are negative integers, informative warnings are positive integers.
Definition at line 140 of file mfs.h.
mfs_bank_state_t
enum mfs_bank_state_t
Type of a bank state assessment.
Definition at line 156 of file mfs.h.
mfs_record_state_t
enum mfs_record_state_t
Type of a record state assessment.
Definition at line 166 of file mfs.h.
Function Documentation
mfs_flash_read()
static mfs_error_t mfs_flash_read (MFSDriver * mfsp, flash_offset_t offset, size_t n, uint8_t * rp) static
Flash read.
Parameters
[in] mfsp pointer to the MFSDriver object
[in] offset flash offset
[in] n number of bytes to be read
[out] rp pointer to the data buffer
Returns
The operation status.
Function Class:Not an API, this function is for internal use only.
Definition at line 151 of file mfs.c.
References MFSDriver::config, MFSConfig::flashp, and flashRead.
Referenced by mfs_flash_copy().
mfs_flash_write()
static mfs_error_t mfs_flash_write (MFSDriver * mfsp, flash_offset_t offset, size_t n, const uint8_t * wp) static
Flash write.
Note
If the option MFS_CFG_WRITE_VERIFY is enabled then the flash is also read back for verification.
Parameters
[in] mfsp pointer to the MFSDriver object
[in] offset flash offset
[in] n number of bytes to be written
[in] wp pointer to the data buffer
Returns
The operation status.
Function Class:Not an API, this function is for internal use only.
Definition at line 177 of file mfs.c.
References MFSDriver::config, MFSConfig::flashp, and flashProgram.
Referenced by mfs_flash_copy().
mfs_flash_copy()
static mfs_error_t mfs_flash_copy (MFSDriver * mfsp, flash_offset_t doffset, flash_offset_t soffset, uint32_t n) static
Flash copy.
Note
If the option MFS_CFG_WRITE_VERIFY is enabled then the flash is also read back for verification.
Parameters
[in] mfsp pointer to the MFSDriver object
[in] doffset destination flash offset
[in] soffset source flash offset
[in] n number of bytes to be copied
Returns
The operation status.
Function Class:Not an API, this function is for internal use only.
Definition at line 220 of file mfs.c.
References MFSDriver::buffer, MFS_CFG_BUFFER_SIZE, mfs_flash_read(), mfs_flash_write(), and RET_ON_ERROR.
mfs_record_check()
static mfs_error_t mfs_record_check (MFSDriver * mfsp, mfs_data_header_t * dhdrp, flash_offset_t offset, flash_offset_t limit, mfs_record_state_t * sts) static
Verifies integrity of a record.
Parameters
[in] mfsp pointer to the MFSDriver object
[in] dhdrp pointer to the header to be checked
[in] offset flash offset of the header to be checked
[in] limit flash limit offset
[out] sts assessed record state
Returns
The operation status.
Function Class:Not an API, this function is for internal use only.
Definition at line 259 of file mfs.c.
References MFSDriver::config, MFSConfig::erased, and mfs_data_header_t::magic.
mfs_bank_erase()
static mfs_error_t mfs_bank_erase (MFSDriver * mfsp, mfs_bank_t bank) static
Erases and verifies all sectors belonging to a bank.
Parameters
[in] mfsp pointer to the MFSDriver object
[in] bank bank to be erased
Returns
The operation status.
Function Class:Not an API, this function is for internal use only.
Definition at line 302 of file mfs.c.
mfs_bank_verify_erase()
static mfs_error_t mfs_bank_verify_erase (MFSDriver * mfsp, mfs_bank_t bank) static
Erases and verifies all sectors belonging to a bank.
Parameters
[in] mfsp pointer to the MFSDriver object
[in] bank bank to be verified
Returns
The operation status.
Function Class:Not an API, this function is for internal use only.
Definition at line 348 of file mfs.c.
mfs_bank_write_header()
static mfs_error_t mfs_bank_write_header (MFSDriver * mfsp, mfs_bank_t bank, uint32_t cnt) static
Writes the validation header in a bank.
Parameters
[in] mfsp pointer to the MFSDriver object
[in] bank bank to be validated
[in] cnt value for the flash usage counter
Returns
The operation status.
Return values
MFS_NO_ERROR if the operation has been successfully completed.
Function Class:Not an API, this function is for internal use only.
Definition at line 389 of file mfs.c.
mfs_bank_scan_records()
static mfs_error_t mfs_bank_scan_records (MFSDriver * mfsp, mfs_bank_t bank, mfs_bank_state_t * statep) static
Scans blocks searching for records.
Note
The block integrity is strongly checked.
Parameters
[in] mfsp pointer to the MFSDriver object
[in] bank the bank identifier
[out] statep bank state, it can be:
MFS_BANK_PARTIAL
MFS_BANK_OK
Returns
The operation status.
Function Class:Not an API, this function is for internal use only.
Definition at line 430 of file mfs.c.
mfs_bank_get_state()
static mfs_error_t mfs_bank_get_state (MFSDriver * mfsp, mfs_bank_t bank, mfs_bank_state_t * statep, uint32_t * cntp) static
Determines the state of a bank.
Note
This function does not test the bank integrity by scanning the data area, it just checks the header.
Parameters
[in] mfsp pointer to the MFSDriver object
[in] bank bank to be checked
[out] statep bank state, it can be:
MFS_BANK_ERASED
MFS_BANK_GARBAGE
MFS_BANK_OK
[out] cntp bank counter
Returns
The operation status.
Function Class:Not an API, this function is for internal use only.
Definition at line 521 of file mfs.c.
Referenced by mfs_try_mount().
mfs_bank_mount()
static mfs_error_t mfs_bank_mount (MFSDriver * mfsp, mfs_bank_t bank, mfs_bank_state_t * statep) static
Selects a bank as current.
Note
The bank header is assumed to be valid.
Parameters
[in] mfsp pointer to the MFSDriver object
[in] bank bank to be scanned
[out] statep bank state, it can be:
MFS_BANK_ERASED
MFS_BANK_GARBAGE
MFS_BANK_PARTIAL
MFS_BANK_OK
Returns
The operation status.
Function Class:Not an API, this function is for internal use only.
Definition at line 589 of file mfs.c.
mfs_garbage_collect()
static mfs_error_t mfs_garbage_collect (MFSDriver * mfsp) static
Enforces a garbage collection.
Storage data is compacted into a single bank.
Parameters
[out] mfsp pointer to the MFSDriver object
Returns
The operation status.
Function Class:Not an API, this function is for internal use only.
Definition at line 622 of file mfs.c.
References MFSDriver::current_bank.
mfs_try_mount()
static mfs_error_t mfs_try_mount (MFSDriver * mfsp) static
Performs a flash partition mount attempt.
Parameters
[in] mfsp pointer to the MFSDriver object
Returns
The operation status.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 673 of file mfs.c.
References mfs_bank_get_state(), and RET_ON_ERROR.
mfs_mount()
mfs_error_t mfs_mount (MFSDriver * mfsp)
Configures and activates a MFS driver.
Parameters
[in] mfsp pointer to the MFSDriver object
Returns
The operation status.
Return values
MFS_NO_ERROR if the operation has been successfully completed.
MFS_WARN_GC if the operation triggered a garbage collection.
MFS_ERR_FLASH_FAILURE if the flash memory is unusable because HW failures. Makes the driver enter the MFS_ERROR state.
MFS_ERR_INTERNAL if an internal logic failure is detected.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 793 of file mfs.c.
mfsObjectInit()
void mfsObjectInit (MFSDriver * mfsp)
Initializes an instance.
Parameters
[out] mfsp pointer to the MFSDriver object
Function Class:Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 832 of file mfs.c.
References osalDbgCheck, and MFSDriver::state.
mfsStart()
mfs_error_t mfsStart (MFSDriver * mfsp, const MFSConfig * config)
Configures and activates a MFS driver.
Parameters
[in] mfsp pointer to the MFSDriver object
[in] config pointer to the configuration
Returns
The operation status.
Return values
MFS_NO_ERROR if the operation has been successfully completed.
MFS_WARN_GC if the operation triggered a garbage collection.
MFS_ERR_FLASH_FAILURE if the flash memory is unusable because HW failures. Makes the driver enter the MFS_ERROR state.
MFS_ERR_INTERNAL if an internal logic failure is detected.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 854 of file mfs.c.
References osalDbgAssert, osalDbgCheck, and MFSDriver::state.
mfsStop()
void mfsStop (MFSDriver * mfsp)
Deactivates a MFS driver.
Parameters
[in] mfsp pointer to the MFSDriver object
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 873 of file mfs.c.
References osalDbgAssert, osalDbgCheck, and MFSDriver::state.
mfsErase()
mfs_error_t mfsErase (MFSDriver * mfsp)
Destroys the state of the managed storage by erasing the flash.
Parameters
[in] mfsp pointer to the MFSDriver object
Returns
The operation status.
Return values
MFS_ERR_INV_STATE if the driver is in not in MSG_READY state.
MFS_NO_ERROR if the operation has been successfully completed.
MFS_ERR_FLASH_FAILURE if the flash memory is unusable because HW failures. Makes the driver enter the MFS_ERROR state.
MFS_ERR_INTERNAL if an internal logic failure is detected.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 896 of file mfs.c.
References osalDbgCheck, and MFSDriver::state.
mfsReadRecord()
mfs_error_t mfsReadRecord (MFSDriver * mfsp, mfs_id_t id, size_t * np, uint8_t * buffer)
Retrieves and reads a data record.
Parameters
[in] mfsp pointer to the MFSDriver object
[in] id record numeric identifier, the valid range is between 1 and MFS_CFG_MAX_RECORDS
[in,out] np on input is the maximum buffer size, on return it is the size of the data copied into the buffer
[out] buffer pointer to a buffer for record data
Returns
The operation status.
Return values
MFS_NO_ERROR if the operation has been successfully completed.
MFS_ERR_INV_STATE if the driver is in not in MSG_READY state.
MFS_ERR_INV_SIZE if the passed buffer is not large enough to contain the record data.
MFS_ERR_NOT_FOUND if the specified id does not exists.
MFS_ERR_FLASH_FAILURE if the flash memory is unusable because HW failures. Makes the driver enter the MFS_ERROR state.
MFS_ERR_INTERNAL if an internal logic failure is detected.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 931 of file mfs.c.
References MFS_CFG_MAX_RECORDS, osalDbgCheck, and MFSDriver::state.
mfsWriteRecord()
mfs_error_t mfsWriteRecord (MFSDriver * mfsp, mfs_id_t id, size_t n, const uint8_t * buffer)
Creates or updates a data record.
Parameters
[in] mfsp pointer to the MFSDriver object
[in] id record numeric identifier, the valid range is between 1 and MFS_CFG_MAX_RECORDS
[in] n size of data to be written, it cannot be zero
[in] buffer pointer to a buffer for record data
Returns
The operation status.
Return values
MFS_NO_ERROR if the operation has been successfully completed.
MFS_WARN_GC if the operation triggered a garbage collection.
MFS_ERR_INV_STATE if the driver is in not in MSG_READY state.
MFS_ERR_OUT_OF_MEM if there is not enough flash space for the operation.
MFS_ERR_FLASH_FAILURE if the flash memory is unusable because HW failures. Makes the driver enter the MFS_ERROR state.
MFS_ERR_INTERNAL if an internal logic failure is detected.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 996 of file mfs.c.
References MFS_CFG_MAX_RECORDS, osalDbgCheck, and MFSDriver::state.
mfsEraseRecord()
mfs_error_t mfsEraseRecord (MFSDriver * mfsp, mfs_id_t id)
Erases a data record.
Parameters
[in] mfsp pointer to the MFSDriver object
[in] id record numeric identifier, the valid range is between 1 and MFS_CFG_MAX_RECORDS
Returns
The operation status.
Return values
MFS_NO_ERROR if the operation has been successfully completed.
MFS_WARN_GC if the operation triggered a garbage collection.
MFS_ERR_INV_STATE if the driver is in not in MSG_READY state.
MFS_ERR_FLASH_FAILURE if the flash memory is unusable because HW failures. Makes the driver enter the MFS_ERROR state.
MFS_ERR_INTERNAL if an internal logic failure is detected.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1084 of file mfs.c.
References MFS_CFG_MAX_RECORDS, osalDbgCheck, and MFSDriver::state.
mfsPerformGarbageCollection()
mfs_error_t mfsPerformGarbageCollection (MFSDriver * mfsp)
Enforces a garbage collection operation.
Garbage collection involves: integrity check, optionally repairs, obsolete data removal, data compaction and a flash bank swap.
Parameters
[in] mfsp pointer to the MFSDriver object
Returns
The operation status.
Return values
MFS_NO_ERROR if the operation has been successfully completed.
MFS_ERR_INV_STATE if the driver is in not in MSG_READY state.
MFS_ERR_FLASH_FAILURE if the flash memory is unusable because HW failures. Makes the driver enter the MFS_ERROR state.
MFS_ERR_INTERNAL if an internal logic failure is detected.
Function Class:Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1153 of file mfs.c.
References osalDbgCheck, and MFSDriver::state.