ChibiOS/HAL for STM32F3xx: ADC Driver
ADC Driver
HAL » Normal Drivers
Generic ADC Driver.
Detailed Description
Generic ADC Driver.
This module implements a generic ADC (Analog to Digital Converter) driver supporting a variety of buffer and conversion modes.
Precondition
In order to use the ADC driver the HAL_USE_ADC option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
ADC Operations
The ADC driver is quite complex, an explanation of the terminology and of the operational details follows.
ADC Conversion Groups
The ADCConversionGroup is the objects that specifies a physical conversion operation. This structure contains some standard fields and several implementation-dependent fields.
The standard fields define the CG mode, the number of channels belonging to the CG and the optional callbacks.
The implementation-dependent fields specify the physical ADC operation mode, the analog channels belonging to the group and any other implementation-specific setting. Usually the extra fields just mirror the physical ADC registers, please refer to the vendor's MCU Reference Manual for details about the available settings. Details are also available into the documentation of the ADC low level drivers and in the various sample applications.
ADC Conversion Modes
The driver supports several conversion modes:
One Shot, the driver performs a single group conversion then stops.
Linear Buffer, the driver performs a series of group conversions then stops. This mode is like a one shot conversion repeated N times, the buffer pointer increases after each conversion. The buffer is organized as an S(CG)*N samples matrix, when S(CG) is the conversion group size (number of channels) and N is the buffer depth (number of repeated conversions).
Circular Buffer, much like the linear mode but the operation does not stop when the buffer is filled, it is automatically restarted with the buffer pointer wrapping back to the buffer base.
ADC Callbacks
The driver is able to invoke callbacks during the conversion process. A callback is invoked when the operation has been completed or, in circular mode, when the buffer has been filled and the operation is restarted. In circular mode a callback is also invoked when the buffer is half filled.
The "half filled" and "filled" callbacks in circular mode allow to implement "streaming processing" of the sampled data, while the driver is busy filling one half of the buffer the application can process the other half, this allows for continuous interleaved operations.
The driver is not thread safe for performance reasons, if you need to access the ADC bus from multiple threads then use the adcAcquireBus() and adcReleaseBus() APIs in order to gain exclusive access.
ADC configuration options
#define ADC_USE_WAIT TRUE
Enables synchronous APIs.
#define ADC_USE_MUTUAL_EXCLUSION TRUE
Enables the adcAcquireBus() and adcReleaseBus() APIs.
Low level driver helper macros
#define _adc_reset_i(adcp) osalThreadResumeI(&(adcp)->thread, MSG_RESET)
Resumes a thread waiting for a conversion completion.
#define _adc_reset_s(adcp) osalThreadResumeS(&(adcp)->thread, MSG_RESET)
Resumes a thread waiting for a conversion completion.
#define _adc_wakeup_isr(adcp)
Wakes up the waiting thread.
#define _adc_timeout_isr(adcp)
Wakes up the waiting thread with a timeout message.
#define _adc_isr_half_code(adcp)
Common ISR code, half buffer event.
#define _adc_isr_full_code(adcp)
Common ISR code, full buffer event.
#define _adc_isr_error_code(adcp, err)
Common ISR code, error event.
Available analog channels
#define ADC_CHANNEL_IN0 0
External analog input 0.
#define ADC_CHANNEL_IN1 1
External analog input 1.
#define ADC_CHANNEL_IN2 2
External analog input 2.
#define ADC_CHANNEL_IN3 3
External analog input 3.
#define ADC_CHANNEL_IN4 4
External analog input 4.
#define ADC_CHANNEL_IN5 5
External analog input 5.
#define ADC_CHANNEL_IN6 6
External analog input 6.
#define ADC_CHANNEL_IN7 7
External analog input 7.
#define ADC_CHANNEL_IN8 8
External analog input 8.
#define ADC_CHANNEL_IN9 9
External analog input 9.
#define ADC_CHANNEL_IN10 10
External analog input 10.
#define ADC_CHANNEL_IN11 11
External analog input 11.
#define ADC_CHANNEL_IN12 12
External analog input 12.
#define ADC_CHANNEL_IN13 13
External analog input 13.
#define ADC_CHANNEL_IN14 14
External analog input 14.
#define ADC_CHANNEL_IN15 15
External analog input 15.
#define ADC_CHANNEL_IN16 16
External analog input 16.
#define ADC_CHANNEL_IN17 17
External analog input 17.
#define ADC_CHANNEL_IN18 18
External analog input 18.
Resolution
#define ADC_CFGR1_RES_12BIT (0 << 3)
#define ADC_CFGR1_RES_10BIT (1 << 3)
#define ADC_CFGR1_RES_8BIT (2 << 3)
#define ADC_CFGR1_RES_6BIT (3 << 3)
CFGR register configuration helpers
#define ADC_CFGR_DMACFG_MASK (1 << 1)
#define ADC_CFGR_DMACFG_ONESHOT (0 << 1)
#define ADC_CFGR_DMACFG_CIRCULAR (1 << 1)
#define ADC_CFGR_RES_MASK (3 << 3)
#define ADC_CFGR_RES_12BITS (0 << 3)
#define ADC_CFGR_RES_10BITS (1 << 3)
#define ADC_CFGR_RES_8BITS (2 << 3)
#define ADC_CFGR_RES_6BITS (3 << 3)
#define ADC_CFGR_ALIGN_MASK (1 << 5)
#define ADC_CFGR_ALIGN_RIGHT (0 << 5)
#define ADC_CFGR_ALIGN_LEFT (1 << 5)
#define ADC_CFGR_EXTSEL_MASK (15 << 6)
#define ADC_CFGR_EXTSEL_SRC(n) ((n) << 6)
#define ADC_CFGR_EXTEN_MASK (3 << 10)
#define ADC_CFGR_EXTEN_DISABLED (0 << 10)
#define ADC_CFGR_EXTEN_RISING (1 << 10)
#define ADC_CFGR_EXTEN_FALLING (2 << 10)
#define ADC_CFGR_EXTEN_BOTH (3 << 10)
#define ADC_CFGR_DISCEN_MASK (1 << 16)
#define ADC_CFGR_DISCEN_DISABLED (0 << 16)
#define ADC_CFGR_DISCEN_ENABLED (1 << 16)
#define ADC_CFGR_DISCNUM_MASK (7 << 17)
#define ADC_CFGR_DISCNUM_VAL(n) ((n) << 17)
#define ADC_CFGR_AWD1_DISABLED 0
#define ADC_CFGR_AWD1_ALL (1 << 23)
#define ADC_CFGR_AWD1_SINGLE(n) (((n) << 26) | (1 << 23) | (1 << 22))
CCR register configuration helpers
#define ADC_CCR_DUAL_MASK (31 << 0)
#define ADC_CCR_DUAL_FIELD(n) ((n) << 0)
#define ADC_CCR_DELAY_MASK (15 << 8)
#define ADC_CCR_DELAY_FIELD(n) ((n) << 8)
#define ADC_CCR_DMACFG_MASK (1 << 13)
#define ADC_CCR_DMACFG_ONESHOT (0 << 13)
#define ADC_CCR_DMACFG_CIRCULAR (1 << 13)
#define ADC_CCR_MDMA_MASK (3 << 14)
#define ADC_CCR_MDMA_DISABLED (0 << 14)
#define ADC_CCR_MDMA_WORD (2 << 14)
#define ADC_CCR_MDMA_HWORD (3 << 14)
#define ADC_CCR_CKMODE_MASK (3 << 16)
#define ADC_CCR_CKMODE_ADCCK (0 << 16)
#define ADC_CCR_CKMODE_AHB_DIV1 (1 << 16)
#define ADC_CCR_CKMODE_AHB_DIV2 (2 << 16)
#define ADC_CCR_CKMODE_AHB_DIV4 (3 << 16)
#define ADC_CCR_VREFEN (1 << 22)
#define ADC_CCR_TSEN (1 << 23)
#define ADC_CCR_VBATEN (1 << 24)
Configuration options
#define STM32_ADC_DUAL_MODE FALSE
Enables the ADC master/slave mode.
#define STM32_ADC_COMPACT_SAMPLES FALSE
Makes the ADC samples type an 8bits one.
#define STM32_ADC_USE_ADC1 FALSE
ADC1 driver enable switch.
#define STM32_ADC_USE_ADC2 FALSE
ADC2 driver enable switch.
#define STM32_ADC_USE_ADC3 FALSE
ADC3 driver enable switch.
#define STM32_ADC_USE_ADC4 FALSE
ADC4 driver enable switch.
#define STM32_ADC_ADC1_DMA_PRIORITY 2
ADC1 DMA priority (0..3|lowest..highest).
#define STM32_ADC_ADC2_DMA_PRIORITY 2
ADC2 DMA priority (0..3|lowest..highest).
#define STM32_ADC_ADC3_DMA_PRIORITY 2
ADC3 DMA priority (0..3|lowest..highest).
#define STM32_ADC_ADC4_DMA_PRIORITY 2
ADC4 DMA priority (0..3|lowest..highest).
#define STM32_ADC_ADC12_IRQ_PRIORITY 5
ADC1/ADC2 interrupt priority level setting.
#define STM32_ADC_ADC3_IRQ_PRIORITY 5
ADC3 interrupt priority level setting.
#define STM32_ADC_ADC4_IRQ_PRIORITY 5
ADC4 interrupt priority level setting.
#define STM32_ADC_ADC1_DMA_IRQ_PRIORITY 5
ADC1 DMA interrupt priority level setting.
#define STM32_ADC_ADC2_DMA_IRQ_PRIORITY 5
ADC2 DMA interrupt priority level setting.
#define STM32_ADC_ADC3_DMA_IRQ_PRIORITY 5
ADC3 DMA interrupt priority level setting.
#define STM32_ADC_ADC4_DMA_IRQ_PRIORITY 5
ADC4 DMA interrupt priority level setting.
#define STM32_ADC_ADC12_CLOCK_MODE ADC_CCR_CKMODE_AHB_DIV1
ADC1/ADC2 clock source and mode.
#define STM32_ADC_ADC34_CLOCK_MODE ADC_CCR_CKMODE_AHB_DIV1
ADC3/ADC4 clock source and mode.
#define STM32_ADC_ADC123_CLOCK_MODE ADC_CCR_CKMODE_AHB_DIV1
ADC1/ADC2/ADC3 clock source and mode.
Threashold register initializer
#define ADC_TR(low, high) (((uint32_t)(high) << 16) | (uint32_t)(low))
Sequences building helper macros
#define ADC_SQR1_NUM_CH(n) (((n) - 1) << 0)
Number of channels in a conversion sequence.
#define ADC_SQR1_SQ1_N(n) ((n) << 6)
1st channel in seq.
#define ADC_SQR1_SQ2_N(n) ((n) << 12)
2nd channel in seq.
#define ADC_SQR1_SQ3_N(n) ((n) << 18)
3rd channel in seq.
#define ADC_SQR1_SQ4_N(n) ((n) << 24)
4th channel in seq.
#define ADC_SQR2_SQ5_N(n) ((n) << 0)
5th channel in seq.
#define ADC_SQR2_SQ6_N(n) ((n) << 6)
6th channel in seq.
#define ADC_SQR2_SQ7_N(n) ((n) << 12)
7th channel in seq.
#define ADC_SQR2_SQ8_N(n) ((n) << 18)
8th channel in seq.
#define ADC_SQR2_SQ9_N(n) ((n) << 24)
9th channel in seq.
#define ADC_SQR3_SQ10_N(n) ((n) << 0)
10th channel in seq.
#define ADC_SQR3_SQ11_N(n) ((n) << 6)
11th channel in seq.
#define ADC_SQR3_SQ12_N(n) ((n) << 12)
12th channel in seq.
#define ADC_SQR3_SQ13_N(n) ((n) << 18)
13th channel in seq.
#define ADC_SQR3_SQ14_N(n) ((n) << 24)
14th channel in seq.
#define ADC_SQR4_SQ15_N(n) ((n) << 0)
15th channel in seq.
#define ADC_SQR4_SQ16_N(n) ((n) << 6)
16th channel in seq.
Sampling rate settings helper macros
#define ADC_SMPR1_SMP_AN0(n) ((n) << 0)
AN0 sampling time.
#define ADC_SMPR1_SMP_AN1(n) ((n) << 3)
AN1 sampling time.
#define ADC_SMPR1_SMP_AN2(n) ((n) << 6)
AN2 sampling time.
#define ADC_SMPR1_SMP_AN3(n) ((n) << 9)
AN3 sampling time.
#define ADC_SMPR1_SMP_AN4(n) ((n) << 12)
AN4 sampling time.
#define ADC_SMPR1_SMP_AN5(n) ((n) << 15)
AN5 sampling time.
#define ADC_SMPR1_SMP_AN6(n) ((n) << 18)
AN6 sampling time.
#define ADC_SMPR1_SMP_AN7(n) ((n) << 21)
AN7 sampling time.
#define ADC_SMPR1_SMP_AN8(n) ((n) << 24)
AN8 sampling time.
#define ADC_SMPR1_SMP_AN9(n) ((n) << 27)
AN9 sampling time.
#define ADC_SMPR2_SMP_AN10(n) ((n) << 0)
AN10 sampling time.
#define ADC_SMPR2_SMP_AN11(n) ((n) << 3)
AN11 sampling time.
#define ADC_SMPR2_SMP_AN12(n) ((n) << 6)
AN12 sampling time.
#define ADC_SMPR2_SMP_AN13(n) ((n) << 9)
AN13 sampling time.
#define ADC_SMPR2_SMP_AN14(n) ((n) << 12)
AN14 sampling time.
#define ADC_SMPR2_SMP_AN15(n) ((n) << 15)
AN15 sampling time.
#define ADC_SMPR2_SMP_AN16(n) ((n) << 18)
AN16 sampling time.
#define ADC_SMPR2_SMP_AN17(n) ((n) << 21)
AN17 sampling time.
#define ADC_SMPR2_SMP_AN18(n) ((n) << 24)
AN18 sampling time.
Typedefs
typedef uint16_t adcsample_t
ADC sample data type.
typedef uint16_t adc_channels_num_t
Channels number in a conversion group.
typedef struct ADCDriver ADCDriver
Type of a structure representing an ADC driver.
typedef void(* adccallback_t) (ADCDriver *adcp, adcsample_t *buffer, size_t n)
ADC notification callback type.
typedef void(* adcerrorcallback_t) (ADCDriver *adcp, adcerror_t err)
ADC error callback type.
Data Structures
struct ADCConversionGroup
Conversion group configuration structure.
struct ADCConfig
Driver configuration structure.
struct ADCDriver
Structure representing an ADC driver.
Functions
void adcInit (void)
ADC Driver initialization.
void adcObjectInit (ADCDriver *adcp)
Initializes the standard part of a ADCDriver structure.
void adcStart (ADCDriver *adcp, const ADCConfig *config)
Configures and activates the ADC peripheral.
void adcStop (ADCDriver *adcp)
Deactivates the ADC peripheral.
void adcStartConversion (ADCDriver *adcp, const ADCConversionGroup *grpp, adcsample_t *samples, size_t depth)
Starts an ADC conversion.
void adcStartConversionI (ADCDriver *adcp, const ADCConversionGroup *grpp, adcsample_t *samples, size_t depth)
Starts an ADC conversion.
void adcStopConversion (ADCDriver *adcp)
Stops an ongoing conversion.
void adcStopConversionI (ADCDriver *adcp)
Stops an ongoing conversion.
msg_t adcConvert (ADCDriver *adcp, const ADCConversionGroup *grpp, adcsample_t *samples, size_t depth)
Performs an ADC conversion.
void adcAcquireBus (ADCDriver *adcp)
Gains exclusive access to the ADC peripheral.
void adcReleaseBus (ADCDriver *adcp)
Releases exclusive access to the ADC peripheral.
static void adc_lld_vreg_on (ADCDriver *adcp)
Enables the ADC voltage regulator.
static void adc_lld_vreg_off (ADCDriver *adcp)
Disables the ADC voltage regulator.
static void adc_lld_analog_on (ADCDriver *adcp)
Enables the ADC analog circuit.
static void adc_lld_analog_off (ADCDriver *adcp)
Disables the ADC analog circuit.
static void adc_lld_calibrate (ADCDriver *adcp)
Calibrates and ADC unit.
static void adc_lld_stop_adc (ADCDriver *adcp)
Stops an ongoing conversion, if any.
static void adc_lld_serve_dma_interrupt (ADCDriver *adcp, uint32_t flags)
ADC DMA ISR service routine.
static void adc_lld_serve_interrupt (ADCDriver *adcp, uint32_t isr)
ADC ISR service routine.
OSAL_IRQ_HANDLER (STM32_ADC1_HANDLER)
ADC1/ADC2 interrupt handler.
OSAL_IRQ_HANDLER (STM32_ADC3_HANDLER)
ADC3 interrupt handler.
OSAL_IRQ_HANDLER (STM32_ADC4_HANDLER)
ADC4 interrupt handler.
void adc_lld_init (void)
Low level ADC driver initialization.
void adc_lld_start (ADCDriver *adcp)
Configures and activates the ADC peripheral.
void adc_lld_stop (ADCDriver *adcp)
Deactivates the ADC peripheral.
void adc_lld_start_conversion (ADCDriver *adcp)
Starts an ADC conversion.
void adc_lld_stop_conversion (ADCDriver *adcp)
Stops an ongoing conversion.
void adcSTM32EnableVREF (ADCDriver *adcp)
Enables the VREFEN bit.
void adcSTM32DisableVREF (ADCDriver *adcp)
Disables the VREFEN bit.
void adcSTM32EnableTS (ADCDriver *adcp)
Enables the TSEN bit.
void adcSTM32DisableTS (ADCDriver *adcp)
Disables the TSEN bit.
void adcSTM32EnableVBAT (ADCDriver *adcp)
Enables the VBATEN bit.
void adcSTM32DisableVBAT (ADCDriver *adcp)
Disables the VBATEN bit.
Enumerations
enum adcstate_t {
ADC_UNINIT = 0, ADC_STOP = 1, ADC_READY = 2, ADC_ACTIVE = 3,
ADC_COMPLETE = 4, ADC_ERROR = 5
}
Driver state machine possible states.
enum adcerror_t {
ADC_ERR_DMAFAILURE = 0, ADC_ERR_OVERFLOW = 1, ADC_ERR_AWD1 = 2, ADC_ERR_AWD2 = 3,
ADC_ERR_AWD3 = 4
}
Possible ADC failure causes.
Variables
ADCDriver ADCD1
ADC1 driver identifier.
ADCDriver ADCD2
ADC2 driver identifier.
ADCDriver ADCD3
ADC3 driver identifier.
ADCDriver ADCD4
ADC4 driver identifier.
Macro Definition Documentation
ADC_USE_WAIT
#define ADC_USE_WAIT TRUE
Enables synchronous APIs.
Note
Disabling this option saves both code and data space.
Definition at line 47 of file hal_adc.h.
ADC_USE_MUTUAL_EXCLUSION
#define ADC_USE_MUTUAL_EXCLUSION TRUE
Enables the adcAcquireBus() and adcReleaseBus() APIs.
Note
Disabling this option saves both code and data space.
Definition at line 55 of file hal_adc.h.
_adc_reset_i
#define _adc_reset_i (adcp) osalThreadResumeI(&(adcp)->thread, MSG_RESET)
Resumes a thread waiting for a conversion completion.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 97 of file hal_adc.h.
Referenced by adcStopConversionI().
_adc_reset_s
#define _adc_reset_s (adcp) osalThreadResumeS(&(adcp)->thread, MSG_RESET)
Resumes a thread waiting for a conversion completion.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 107 of file hal_adc.h.
Referenced by adcStopConversion().
_adc_wakeup_isr
#define _adc_wakeup_isr (adcp)
Value:
{                                             \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(adcp)->thread, MSG_OK);                               \
  osalSysUnlockFromISR();                                                   \
}
Wakes up the waiting thread.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 117 of file hal_adc.h.
_adc_timeout_isr
#define _adc_timeout_isr (adcp)
Value:
{                                            \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(adcp)->thread, MSG_TIMEOUT);                          \
  osalSysUnlockFromISR();                                                   \
}
Wakes up the waiting thread with a timeout message.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 130 of file hal_adc.h.
_adc_isr_half_code
#define _adc_isr_half_code (adcp)
Value:
{                                          \
  if ((adcp)->grpp->end_cb != NULL) {                                       \
    (adcp)->grpp->end_cb(adcp, (adcp)->samples, (adcp)->depth / 2);         \
  }                                                                         \
}
Common ISR code, half buffer event.
This code handles the portable part of the ISR code:
Callback invocation.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 155 of file hal_adc.h.
_adc_isr_full_code
#define _adc_isr_full_code (adcp)
Common ISR code, full buffer event.
This code handles the portable part of the ISR code:
Callback invocation.
Waiting thread wakeup, if any.
Driver state transitions.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 175 of file hal_adc.h.
_adc_isr_error_code
#define _adc_isr_error_code (adcp, err)
Value:
{                                    \
  adc_lld_stop_conversion(adcp);                                            \
  if ((adcp)->grpp->error_cb != NULL) {                                     \
    (adcp)->state = ADC_ERROR;                                              \
    (adcp)->grpp->error_cb(adcp, err);                                      \
    if ((adcp)->state == ADC_ERROR)                                         \
      (adcp)->state = ADC_READY;                                            \
      (adcp)->grpp = NULL;                                                  \
  }                                                                         \
  else {                                                                    \
    (adcp)->state = ADC_READY;                                              \
    (adcp)->grpp = NULL;                                                    \
  }                                                                         \
  _adc_timeout_isr(adcp);                                                   \
}
Common ISR code, error event.
This code handles the portable part of the ISR code:
Callback invocation.
Waiting thread timeout signaling, if any.
Driver state transitions.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] adcp pointer to the ADCDriver object
[in] err platform dependent error code
Function Class:
Not an API, this function is for internal use only.
Definition at line 226 of file hal_adc.h.
Referenced by adc_lld_serve_interrupt().
ADC_CHANNEL_IN0
#define ADC_CHANNEL_IN0 0
External analog input 0.
Definition at line 38 of file hal_adc_lld.h.
ADC_CHANNEL_IN1
#define ADC_CHANNEL_IN1 1
External analog input 1.
Definition at line 39 of file hal_adc_lld.h.
ADC_CHANNEL_IN2
#define ADC_CHANNEL_IN2 2
External analog input 2.
Definition at line 40 of file hal_adc_lld.h.
ADC_CHANNEL_IN3
#define ADC_CHANNEL_IN3 3
External analog input 3.
Definition at line 41 of file hal_adc_lld.h.
ADC_CHANNEL_IN4
#define ADC_CHANNEL_IN4 4
External analog input 4.
Definition at line 42 of file hal_adc_lld.h.
ADC_CHANNEL_IN5
#define ADC_CHANNEL_IN5 5
External analog input 5.
Definition at line 43 of file hal_adc_lld.h.
ADC_CHANNEL_IN6
#define ADC_CHANNEL_IN6 6
External analog input 6.
Definition at line 44 of file hal_adc_lld.h.
ADC_CHANNEL_IN7
#define ADC_CHANNEL_IN7 7
External analog input 7.
Definition at line 45 of file hal_adc_lld.h.
ADC_CHANNEL_IN8
#define ADC_CHANNEL_IN8 8
External analog input 8.
Definition at line 46 of file hal_adc_lld.h.
ADC_CHANNEL_IN9
#define ADC_CHANNEL_IN9 9
External analog input 9.
Definition at line 47 of file hal_adc_lld.h.
ADC_CHANNEL_IN10
#define ADC_CHANNEL_IN10 10
External analog input 10.
Definition at line 48 of file hal_adc_lld.h.
ADC_CHANNEL_IN11
#define ADC_CHANNEL_IN11 11
External analog input 11.
Definition at line 49 of file hal_adc_lld.h.
ADC_CHANNEL_IN12
#define ADC_CHANNEL_IN12 12
External analog input 12.
Definition at line 50 of file hal_adc_lld.h.
ADC_CHANNEL_IN13
#define ADC_CHANNEL_IN13 13
External analog input 13.
Definition at line 51 of file hal_adc_lld.h.
ADC_CHANNEL_IN14
#define ADC_CHANNEL_IN14 14
External analog input 14.
Definition at line 52 of file hal_adc_lld.h.
ADC_CHANNEL_IN15
#define ADC_CHANNEL_IN15 15
External analog input 15.
Definition at line 53 of file hal_adc_lld.h.
ADC_CHANNEL_IN16
#define ADC_CHANNEL_IN16 16
External analog input 16.
Definition at line 54 of file hal_adc_lld.h.
ADC_CHANNEL_IN17
#define ADC_CHANNEL_IN17 17
External analog input 17.
Definition at line 55 of file hal_adc_lld.h.
ADC_CHANNEL_IN18
#define ADC_CHANNEL_IN18 18
External analog input 18.
Definition at line 56 of file hal_adc_lld.h.
STM32_ADC_DUAL_MODE
#define STM32_ADC_DUAL_MODE FALSE
Enables the ADC master/slave mode.
Note
In dual mode only ADCD1 and ADCD3 are available.
Definition at line 182 of file hal_adc_lld.h.
STM32_ADC_COMPACT_SAMPLES
#define STM32_ADC_COMPACT_SAMPLES FALSE
Makes the ADC samples type an 8bits one.
Note
10 and 12 bits sampling mode must not be used when this option is enabled.
Definition at line 191 of file hal_adc_lld.h.
STM32_ADC_USE_ADC1
#define STM32_ADC_USE_ADC1 FALSE
ADC1 driver enable switch.
If set to TRUE the support for ADC1 is included.
Note
The default is FALSE.
Definition at line 200 of file hal_adc_lld.h.
STM32_ADC_USE_ADC2
#define STM32_ADC_USE_ADC2 FALSE
ADC2 driver enable switch.
If set to TRUE the support for ADC2 is included.
Note
The default is FALSE.
Definition at line 209 of file hal_adc_lld.h.
STM32_ADC_USE_ADC3
#define STM32_ADC_USE_ADC3 FALSE
ADC3 driver enable switch.
If set to TRUE the support for ADC3 is included.
Note
The default is FALSE.
Definition at line 218 of file hal_adc_lld.h.
STM32_ADC_USE_ADC4
#define STM32_ADC_USE_ADC4 FALSE
ADC4 driver enable switch.
If set to TRUE the support for ADC4 is included.
Note
The default is FALSE.
Definition at line 226 of file hal_adc_lld.h.
STM32_ADC_ADC1_DMA_PRIORITY
#define STM32_ADC_ADC1_DMA_PRIORITY 2
ADC1 DMA priority (0..3|lowest..highest).
Definition at line 233 of file hal_adc_lld.h.
STM32_ADC_ADC2_DMA_PRIORITY
#define STM32_ADC_ADC2_DMA_PRIORITY 2
ADC2 DMA priority (0..3|lowest..highest).
Definition at line 240 of file hal_adc_lld.h.
STM32_ADC_ADC3_DMA_PRIORITY
#define STM32_ADC_ADC3_DMA_PRIORITY 2
ADC3 DMA priority (0..3|lowest..highest).
Definition at line 247 of file hal_adc_lld.h.
STM32_ADC_ADC4_DMA_PRIORITY
#define STM32_ADC_ADC4_DMA_PRIORITY 2
ADC4 DMA priority (0..3|lowest..highest).
Definition at line 254 of file hal_adc_lld.h.
STM32_ADC_ADC12_IRQ_PRIORITY
#define STM32_ADC_ADC12_IRQ_PRIORITY 5
ADC1/ADC2 interrupt priority level setting.
Definition at line 261 of file hal_adc_lld.h.
STM32_ADC_ADC3_IRQ_PRIORITY
#define STM32_ADC_ADC3_IRQ_PRIORITY 5
ADC3 interrupt priority level setting.
Definition at line 268 of file hal_adc_lld.h.
STM32_ADC_ADC4_IRQ_PRIORITY
#define STM32_ADC_ADC4_IRQ_PRIORITY 5
ADC4 interrupt priority level setting.
Definition at line 275 of file hal_adc_lld.h.
STM32_ADC_ADC1_DMA_IRQ_PRIORITY
#define STM32_ADC_ADC1_DMA_IRQ_PRIORITY 5
ADC1 DMA interrupt priority level setting.
Definition at line 282 of file hal_adc_lld.h.
Referenced by adc_lld_start().
STM32_ADC_ADC2_DMA_IRQ_PRIORITY
#define STM32_ADC_ADC2_DMA_IRQ_PRIORITY 5
ADC2 DMA interrupt priority level setting.
Definition at line 289 of file hal_adc_lld.h.
STM32_ADC_ADC3_DMA_IRQ_PRIORITY
#define STM32_ADC_ADC3_DMA_IRQ_PRIORITY 5
ADC3 DMA interrupt priority level setting.
Definition at line 296 of file hal_adc_lld.h.
STM32_ADC_ADC4_DMA_IRQ_PRIORITY
#define STM32_ADC_ADC4_DMA_IRQ_PRIORITY 5
ADC4 DMA interrupt priority level setting.
Definition at line 303 of file hal_adc_lld.h.
STM32_ADC_ADC12_CLOCK_MODE
#define STM32_ADC_ADC12_CLOCK_MODE ADC_CCR_CKMODE_AHB_DIV1
ADC1/ADC2 clock source and mode.
Definition at line 311 of file hal_adc_lld.h.
STM32_ADC_ADC34_CLOCK_MODE
#define STM32_ADC_ADC34_CLOCK_MODE ADC_CCR_CKMODE_AHB_DIV1
ADC3/ADC4 clock source and mode.
Definition at line 318 of file hal_adc_lld.h.
STM32_ADC_ADC123_CLOCK_MODE
#define STM32_ADC_ADC123_CLOCK_MODE ADC_CCR_CKMODE_AHB_DIV1
ADC1/ADC2/ADC3 clock source and mode.
Definition at line 327 of file hal_adc_lld.h.
Referenced by adc_lld_stop().
ADC_SQR1_NUM_CH
#define ADC_SQR1_NUM_CH (n) (((n) - 1) << 0)
Number of channels in a conversion sequence.
Definition at line 813 of file hal_adc_lld.h.
ADC_SQR1_SQ1_N
#define ADC_SQR1_SQ1_N (n) ((n) << 6)
1st channel in seq.
Definition at line 815 of file hal_adc_lld.h.
ADC_SQR1_SQ2_N
#define ADC_SQR1_SQ2_N (n) ((n) << 12)
2nd channel in seq.
Definition at line 816 of file hal_adc_lld.h.
ADC_SQR1_SQ3_N
#define ADC_SQR1_SQ3_N (n) ((n) << 18)
3rd channel in seq.
Definition at line 817 of file hal_adc_lld.h.
ADC_SQR1_SQ4_N
#define ADC_SQR1_SQ4_N (n) ((n) << 24)
4th channel in seq.
Definition at line 818 of file hal_adc_lld.h.
ADC_SQR2_SQ5_N
#define ADC_SQR2_SQ5_N (n) ((n) << 0)
5th channel in seq.
Definition at line 820 of file hal_adc_lld.h.
ADC_SQR2_SQ6_N
#define ADC_SQR2_SQ6_N (n) ((n) << 6)
6th channel in seq.
Definition at line 821 of file hal_adc_lld.h.
ADC_SQR2_SQ7_N
#define ADC_SQR2_SQ7_N (n) ((n) << 12)
7th channel in seq.
Definition at line 822 of file hal_adc_lld.h.
ADC_SQR2_SQ8_N
#define ADC_SQR2_SQ8_N (n) ((n) << 18)
8th channel in seq.
Definition at line 823 of file hal_adc_lld.h.
ADC_SQR2_SQ9_N
#define ADC_SQR2_SQ9_N (n) ((n) << 24)
9th channel in seq.
Definition at line 824 of file hal_adc_lld.h.
ADC_SQR3_SQ10_N
#define ADC_SQR3_SQ10_N (n) ((n) << 0)
10th channel in seq.
Definition at line 826 of file hal_adc_lld.h.
ADC_SQR3_SQ11_N
#define ADC_SQR3_SQ11_N (n) ((n) << 6)
11th channel in seq.
Definition at line 827 of file hal_adc_lld.h.
ADC_SQR3_SQ12_N
#define ADC_SQR3_SQ12_N (n) ((n) << 12)
12th channel in seq.
Definition at line 828 of file hal_adc_lld.h.
ADC_SQR3_SQ13_N
#define ADC_SQR3_SQ13_N (n) ((n) << 18)
13th channel in seq.
Definition at line 829 of file hal_adc_lld.h.
ADC_SQR3_SQ14_N
#define ADC_SQR3_SQ14_N (n) ((n) << 24)
14th channel in seq.
Definition at line 830 of file hal_adc_lld.h.
ADC_SQR4_SQ15_N
#define ADC_SQR4_SQ15_N (n) ((n) << 0)
15th channel in seq.
Definition at line 832 of file hal_adc_lld.h.
ADC_SQR4_SQ16_N
#define ADC_SQR4_SQ16_N (n) ((n) << 6)
16th channel in seq.
Definition at line 833 of file hal_adc_lld.h.
ADC_SMPR1_SMP_AN0
#define ADC_SMPR1_SMP_AN0 (n) ((n) << 0)
AN0 sampling time.
Definition at line 840 of file hal_adc_lld.h.
ADC_SMPR1_SMP_AN1
#define ADC_SMPR1_SMP_AN1 (n) ((n) << 3)
AN1 sampling time.
Definition at line 841 of file hal_adc_lld.h.
ADC_SMPR1_SMP_AN2
#define ADC_SMPR1_SMP_AN2 (n) ((n) << 6)
AN2 sampling time.
Definition at line 842 of file hal_adc_lld.h.
ADC_SMPR1_SMP_AN3
#define ADC_SMPR1_SMP_AN3 (n) ((n) << 9)
AN3 sampling time.
Definition at line 843 of file hal_adc_lld.h.
ADC_SMPR1_SMP_AN4
#define ADC_SMPR1_SMP_AN4 (n) ((n) << 12)
AN4 sampling time.
Definition at line 844 of file hal_adc_lld.h.
ADC_SMPR1_SMP_AN5
#define ADC_SMPR1_SMP_AN5 (n) ((n) << 15)
AN5 sampling time.
Definition at line 845 of file hal_adc_lld.h.
ADC_SMPR1_SMP_AN6
#define ADC_SMPR1_SMP_AN6 (n) ((n) << 18)
AN6 sampling time.
Definition at line 846 of file hal_adc_lld.h.
ADC_SMPR1_SMP_AN7
#define ADC_SMPR1_SMP_AN7 (n) ((n) << 21)
AN7 sampling time.
Definition at line 847 of file hal_adc_lld.h.
ADC_SMPR1_SMP_AN8
#define ADC_SMPR1_SMP_AN8 (n) ((n) << 24)
AN8 sampling time.
Definition at line 848 of file hal_adc_lld.h.
ADC_SMPR1_SMP_AN9
#define ADC_SMPR1_SMP_AN9 (n) ((n) << 27)
AN9 sampling time.
Definition at line 849 of file hal_adc_lld.h.
ADC_SMPR2_SMP_AN10
#define ADC_SMPR2_SMP_AN10 (n) ((n) << 0)
AN10 sampling time.
Definition at line 851 of file hal_adc_lld.h.
ADC_SMPR2_SMP_AN11
#define ADC_SMPR2_SMP_AN11 (n) ((n) << 3)
AN11 sampling time.
Definition at line 852 of file hal_adc_lld.h.
ADC_SMPR2_SMP_AN12
#define ADC_SMPR2_SMP_AN12 (n) ((n) << 6)
AN12 sampling time.
Definition at line 853 of file hal_adc_lld.h.
ADC_SMPR2_SMP_AN13
#define ADC_SMPR2_SMP_AN13 (n) ((n) << 9)
AN13 sampling time.
Definition at line 854 of file hal_adc_lld.h.
ADC_SMPR2_SMP_AN14
#define ADC_SMPR2_SMP_AN14 (n) ((n) << 12)
AN14 sampling time.
Definition at line 855 of file hal_adc_lld.h.
ADC_SMPR2_SMP_AN15
#define ADC_SMPR2_SMP_AN15 (n) ((n) << 15)
AN15 sampling time.
Definition at line 856 of file hal_adc_lld.h.
ADC_SMPR2_SMP_AN16
#define ADC_SMPR2_SMP_AN16 (n) ((n) << 18)
AN16 sampling time.
Definition at line 857 of file hal_adc_lld.h.
ADC_SMPR2_SMP_AN17
#define ADC_SMPR2_SMP_AN17 (n) ((n) << 21)
AN17 sampling time.
Definition at line 858 of file hal_adc_lld.h.
ADC_SMPR2_SMP_AN18
#define ADC_SMPR2_SMP_AN18 (n) ((n) << 24)
AN18 sampling time.
Definition at line 859 of file hal_adc_lld.h.
Typedef Documentation
adcsample_t
typedef uint16_t adcsample_t
ADC sample data type.
Definition at line 595 of file hal_adc_lld.h.
adc_channels_num_t
typedef uint16_t adc_channels_num_t
Channels number in a conversion group.
Definition at line 603 of file hal_adc_lld.h.
ADCDriver
typedef struct ADCDriver ADCDriver
Type of a structure representing an ADC driver.
Definition at line 621 of file hal_adc_lld.h.
adccallback_t
typedef void(* adccallback_t) (ADCDriver *adcp, adcsample_t *buffer, size_t n)
ADC notification callback type.
Parameters
[in] adcp pointer to the ADCDriver object triggering the callback
[in] buffer pointer to the most recent samples data
[in] n number of buffer rows available starting from buffer
Definition at line 631 of file hal_adc_lld.h.
adcerrorcallback_t
typedef void(* adcerrorcallback_t) (ADCDriver *adcp, adcerror_t err)
ADC error callback type.
Parameters
[in] adcp pointer to the ADCDriver object triggering the callback
[in] err ADC error code
Definition at line 640 of file hal_adc_lld.h.
Enumeration Type Documentation
adcstate_t
enum adcstate_t
Driver state machine possible states.
Enumerator
ADC_UNINIT
Not initialized.
ADC_STOP
Stopped.
ADC_READY
Ready.
ADC_ACTIVE
Converting.
ADC_COMPLETE
Conversion complete.
ADC_ERROR
Conversion error.
Definition at line 70 of file hal_adc.h.
adcerror_t
enum adcerror_t
Possible ADC failure causes.
Note
Error codes are architecture dependent and should not relied upon.
Enumerator
ADC_ERR_DMAFAILURE
DMA operations failure.
ADC_ERR_OVERFLOW
ADC overflow condition.
ADC_ERR_AWD1
Watchdog 1 triggered.
ADC_ERR_AWD2
Watchdog 2 triggered.
ADC_ERR_AWD3
Watchdog 3 triggered.
Definition at line 610 of file hal_adc_lld.h.
Function Documentation
adcInit()
void adcInit (void)
ADC Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file hal_adc.c.
References adc_lld_init().
Referenced by halInit().
adcObjectInit()
void adcObjectInit (ADCDriver * adcp)
Initializes the standard part of a ADCDriver structure.
Parameters
[out] adcp pointer to the ADCDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 68 of file hal_adc.c.
References ADC_STOP, ADCDriver::config, ADCDriver::depth, ADCDriver::grpp, ADCDriver::mutex, osalMutexObjectInit(), ADCDriver::samples, ADCDriver::state, and ADCDriver::thread.
adcStart()
void adcStart (ADCDriver * adcp, const ADCConfig * config)
Configures and activates the ADC peripheral.
Parameters
[in] adcp pointer to the ADCDriver object
[in] config pointer to the ADCConfig object. Depending on the implementation the value can be NULL.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 95 of file hal_adc.c.
References adc_lld_start(), ADC_READY, ADC_STOP, ADCDriver::config, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and ADCDriver::state.
adcStop()
void adcStop (ADCDriver * adcp)
Deactivates the ADC peripheral.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 115 of file hal_adc.c.
References adc_lld_stop(), ADC_READY, ADC_STOP, ADCDriver::config, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and ADCDriver::state.
adcStartConversion()
void adcStartConversion (ADCDriver * adcp, const ADCConversionGroup * grpp, adcsample_t * samples, size_t depth)
Starts an ADC conversion.
Starts an asynchronous conversion operation.
Note
The buffer is organized as a matrix of M*N elements where M is the channels number configured into the conversion group and N is the buffer depth. The samples are sequentially written into the buffer with no gaps.
Parameters
[in] adcp pointer to the ADCDriver object
[in] grpp pointer to a ADCConversionGroup object
[out] samples pointer to the samples buffer
[in] depth buffer depth (matrix rows number). The buffer depth must be one or an even number.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 147 of file hal_adc.c.
References adcStartConversionI(), osalSysLock(), and osalSysUnlock().
adcStartConversionI()
void adcStartConversionI (ADCDriver * adcp, const ADCConversionGroup * grpp, adcsample_t * samples, size_t depth)
Starts an ADC conversion.
Starts an asynchronous conversion operation.
Postcondition
The callbacks associated to the conversion group will be invoked on buffer fill and error events.
Note
The buffer is organized as a matrix of M*N elements where M is the channels number configured into the conversion group and N is the buffer depth. The samples are sequentially written into the buffer with no gaps.
Parameters
[in] adcp pointer to the ADCDriver object
[in] grpp pointer to a ADCConversionGroup object
[out] samples pointer to the samples buffer
[in] depth buffer depth (matrix rows number). The buffer depth must be one or an even number.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 175 of file hal_adc.c.
References ADC_ACTIVE, ADC_COMPLETE, ADC_ERROR, adc_lld_start_conversion(), ADC_READY, ADCDriver::depth, ADCDriver::grpp, osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, ADCDriver::samples, and ADCDriver::state.
Referenced by adcConvert(), and adcStartConversion().
adcStopConversion()
void adcStopConversion (ADCDriver * adcp)
Stops an ongoing conversion.
This function stops the currently ongoing conversion and returns the driver in the ADC_READY state. If there was no conversion being processed then the function does nothing.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 205 of file hal_adc.c.
References _adc_reset_s, ADC_ACTIVE, adc_lld_stop_conversion(), ADC_READY, ADCDriver::grpp, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and ADCDriver::state.
adcStopConversionI()
void adcStopConversionI (ADCDriver * adcp)
Stops an ongoing conversion.
This function stops the currently ongoing conversion and returns the driver in the ADC_READY state. If there was no conversion being processed then the function does nothing.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 231 of file hal_adc.c.
References _adc_reset_i, ADC_ACTIVE, ADC_COMPLETE, adc_lld_stop_conversion(), ADC_READY, ADCDriver::grpp, osalDbgAssert, osalDbgCheck, osalDbgCheckClassI, and ADCDriver::state.
adcConvert()
msg_t adcConvert (ADCDriver * adcp, const ADCConversionGroup * grpp, adcsample_t * samples, size_t depth)
Performs an ADC conversion.
Performs a synchronous conversion operation.
Note
The buffer is organized as a matrix of M*N elements where M is the channels number configured into the conversion group and N is the buffer depth. The samples are sequentially written into the buffer with no gaps.
Parameters
[in] adcp pointer to the ADCDriver object
[in] grpp pointer to a ADCConversionGroup object
[out] samples pointer to the samples buffer
[in] depth buffer depth (matrix rows number). The buffer depth must be one or an even number.
Returns
The operation result.
Return values
MSG_OK Conversion finished.
MSG_RESET The conversion has been stopped using acdStopConversion() or acdStopConversionI(), the result buffer may contain incorrect data.
MSG_TIMEOUT The conversion has been stopped because an hardware error.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 272 of file hal_adc.c.
References adcStartConversionI(), osalDbgAssert, osalSysLock(), osalSysUnlock(), osalThreadSuspendS(), and ADCDriver::thread.
adcAcquireBus()
void adcAcquireBus (ADCDriver * adcp)
Gains exclusive access to the ADC peripheral.
This function tries to gain ownership to the ADC bus, if the bus is already being used then the invoking thread is queued.
Precondition
In order to use this function the option ADC_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 299 of file hal_adc.c.
References ADCDriver::mutex, osalDbgCheck, and osalMutexLock().
adcReleaseBus()
void adcReleaseBus (ADCDriver * adcp)
Releases exclusive access to the ADC peripheral.
Precondition
In order to use this function the option ADC_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 315 of file hal_adc.c.
References ADCDriver::mutex, osalDbgCheck, and osalMutexUnlock().
adc_lld_vreg_on()
static void adc_lld_vreg_on (ADCDriver * adcp) static
Enables the ADC voltage regulator.
Parameters
[in] adcp pointer to the ADCDriver object
Definition at line 113 of file hal_adc_lld.c.
References ADCDriver::adcm, ADCDriver::adcs, OSAL_US2RTC, osalSysPolledDelayX(), and STM32_HCLK.
adc_lld_vreg_off()
static void adc_lld_vreg_off (ADCDriver * adcp) static
Disables the ADC voltage regulator.
Parameters
[in] adcp pointer to the ADCDriver object
Definition at line 139 of file hal_adc_lld.c.
References ADCDriver::adcm, and ADCDriver::adcs.
Referenced by adc_lld_stop().
adc_lld_analog_on()
static void adc_lld_analog_on (ADCDriver * adcp) static
Enables the ADC analog circuit.
Parameters
[in] adcp pointer to the ADCDriver object
Definition at line 165 of file hal_adc_lld.c.
References ADCDriver::adcm, and ADCDriver::adcs.
adc_lld_analog_off()
static void adc_lld_analog_off (ADCDriver * adcp) static
Disables the ADC analog circuit.
Parameters
[in] adcp pointer to the ADCDriver object
Definition at line 195 of file hal_adc_lld.c.
References ADCDriver::adcm, and ADCDriver::adcs.
Referenced by adc_lld_stop().
adc_lld_calibrate()
static void adc_lld_calibrate (ADCDriver * adcp) static
Calibrates and ADC unit.
Parameters
[in] adcp pointer to the ADCDriver object
Definition at line 212 of file hal_adc_lld.c.
References ADCDriver::adcm, ADCDriver::adcs, and osalDbgAssert.
adc_lld_stop_adc()
static void adc_lld_stop_adc (ADCDriver * adcp) static
Stops an ongoing conversion, if any.
Parameters
[in] adcp pointer to the ADCDriver object
Definition at line 246 of file hal_adc_lld.c.
References ADCDriver::adcm.
Referenced by adc_lld_stop(), and adc_lld_stop_conversion().
adc_lld_serve_dma_interrupt()
static void adc_lld_serve_dma_interrupt (ADCDriver * adcp, uint32_t flags) static
ADC DMA ISR service routine.
Parameters
[in] adcp pointer to the ADCDriver object
[in] flags pre-shifted content of the ISR register
Definition at line 261 of file hal_adc_lld.c.
Referenced by adc_lld_start().
adc_lld_serve_interrupt()
static void adc_lld_serve_interrupt (ADCDriver * adcp, uint32_t isr) static
ADC ISR service routine.
Parameters
[in] adcp pointer to the ADCDriver object
[in] isr content of the ISR register
Definition at line 291 of file hal_adc_lld.c.
References _adc_isr_error_code, ADC_ERR_AWD1, ADC_ERR_AWD2, ADC_ERR_AWD3, ADC_ERR_OVERFLOW, ADCDriver::dmastp, dmaStreamGetTransactionSize, and ADCDriver::grpp.
OSAL_IRQ_HANDLER() [1/3]
OSAL_IRQ_HANDLER (STM32_ADC1_HANDLER)
ADC1/ADC2 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 329 of file hal_adc_lld.c.
OSAL_IRQ_HANDLER() [2/3]
OSAL_IRQ_HANDLER (STM32_ADC3_HANDLER)
ADC3 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 377 of file hal_adc_lld.c.
OSAL_IRQ_HANDLER() [3/3]
OSAL_IRQ_HANDLER (STM32_ADC4_HANDLER)
ADC4 interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 419 of file hal_adc_lld.c.
adc_lld_init()
void adc_lld_init (void)
Low level ADC driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 442 of file hal_adc_lld.c.
Referenced by adcInit().
adc_lld_start()
void adc_lld_start (ADCDriver * adcp)
Configures and activates the ADC peripheral.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 581 of file hal_adc_lld.c.
References adc_lld_serve_dma_interrupt(), ADC_STOP, ADCDriver::config, default_config, ADCDriver::dmastp, dmaStreamAllocate(), osalDbgAssert, ADCDriver::state, and STM32_ADC_ADC1_DMA_IRQ_PRIORITY.
Referenced by adcStart().
adc_lld_stop()
void adc_lld_stop (ADCDriver * adcp)
Deactivates the ADC peripheral.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 697 of file hal_adc_lld.c.
References adc_lld_analog_off(), adc_lld_stop_adc(), adc_lld_vreg_off(), ADC_READY, ADCDriver::adcc, ADCDriver::dmastp, dmaStreamRelease(), ADCDriver::state, and STM32_ADC_ADC123_CLOCK_MODE.
Referenced by adcStop().
adc_lld_start_conversion()
void adc_lld_start_conversion (ADCDriver * adcp)
Starts an ADC conversion.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 786 of file hal_adc_lld.c.
References ADCConversionGroup::ccr, and ADCDriver::grpp.
Referenced by adcStartConversionI().
adc_lld_stop_conversion()
void adc_lld_stop_conversion (ADCDriver * adcp)
Stops an ongoing conversion.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 877 of file hal_adc_lld.c.
References adc_lld_stop_adc(), ADCDriver::dmastp, and dmaStreamDisable.
Referenced by adcStopConversion(), and adcStopConversionI().
adcSTM32EnableVREF()
void adcSTM32EnableVREF (ADCDriver * adcp)
Enables the VREFEN bit.
The VREFEN bit is required in order to sample the VREF channel.
Note
This is an STM32-only functionality.
This function is meant to be called after adcStart().
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 893 of file hal_adc_lld.c.
References ADCDriver::adcc.
adcSTM32DisableVREF()
void adcSTM32DisableVREF (ADCDriver * adcp)
Disables the VREFEN bit.
The VREFEN bit is required in order to sample the VREF channel.
Note
This is an STM32-only functionality.
This function is meant to be called after adcStart().
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 908 of file hal_adc_lld.c.
References ADCDriver::adcc.
adcSTM32EnableTS()
void adcSTM32EnableTS (ADCDriver * adcp)
Enables the TSEN bit.
The TSEN bit is required in order to sample the internal temperature sensor and internal reference voltage.
Note
This is an STM32-only functionality.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 923 of file hal_adc_lld.c.
References ADCDriver::adcc.
adcSTM32DisableTS()
void adcSTM32DisableTS (ADCDriver * adcp)
Disables the TSEN bit.
The TSEN bit is required in order to sample the internal temperature sensor and internal reference voltage.
Note
This is an STM32-only functionality.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 938 of file hal_adc_lld.c.
References ADCDriver::adcc.
adcSTM32EnableVBAT()
void adcSTM32EnableVBAT (ADCDriver * adcp)
Enables the VBATEN bit.
The VBATEN bit is required in order to sample the VBAT channel.
Note
This is an STM32-only functionality.
This function is meant to be called after adcStart().
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 953 of file hal_adc_lld.c.
References ADCDriver::adcc.
adcSTM32DisableVBAT()
void adcSTM32DisableVBAT (ADCDriver * adcp)
Disables the VBATEN bit.
The VBATEN bit is required in order to sample the VBAT channel.
Note
This is an STM32-only functionality.
This function is meant to be called after adcStart().
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 968 of file hal_adc_lld.c.
References ADCDriver::adcc.
Variable Documentation
ADCD1
ADCDriver ADCD1
ADC1 driver identifier.
Definition at line 76 of file hal_adc_lld.c.
ADCD2
ADCDriver ADCD2
ADC2 driver identifier.
Definition at line 81 of file hal_adc_lld.c.
ADCD3
ADCDriver ADCD3
ADC3 driver identifier.
Definition at line 86 of file hal_adc_lld.c.
ADCD4
ADCDriver ADCD4
ADC4 driver identifier.
Definition at line 91 of file hal_adc_lld.c.