ChibiOS/HAL for STM32F3xx: I2C Driver
I2C Driver
HAL » Normal Drivers
Generic I2C Driver.
Detailed Description
Generic I2C Driver.
This module implements a generic I2C (Inter-Integrated Circuit) driver.
Precondition
In order to use the I2C driver the HAL_USE_I2C option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
The driver is not thread safe for performance reasons, if you need to access the I2C bus from multiple threads then use the i2cAcquireBus() and i2cReleaseBus() APIs in order to gain exclusive access.
Macros
#define I2C_USE_MUTUAL_EXCLUSION TRUE
Enables the mutual exclusion APIs on the I2C bus.
#define _i2c_wakeup_isr(i2cp)
Wakes up the waiting thread notifying no errors.
#define _i2c_wakeup_error_isr(i2cp)
Wakes up the waiting thread notifying errors.
#define i2cMasterTransmit(i2cp, addr, txbuf, txbytes, rxbuf, rxbytes)
Wrap i2cMasterTransmitTimeout function with TIME_INFINITE timeout.
#define i2cMasterReceive(i2cp, addr, rxbuf, rxbytes) (i2cMasterReceiveTimeout(i2cp, addr, rxbuf, rxbytes, TIME_INFINITE))
Wrap i2cMasterReceiveTimeout function with TIME_INFINITE timeout.
#define STM32_DMA_REQUIRED
error checks
#define i2c_lld_get_errors(i2cp) ((i2cp)->errors)
Get errors from I2C driver.
I2C bus error conditions
#define I2C_NO_ERROR 0x00
No error.
#define I2C_BUS_ERROR 0x01
Bus Error.
#define I2C_ARBITRATION_LOST 0x02
Arbitration Lost.
#define I2C_ACK_FAILURE 0x04
Acknowledge Failure.
#define I2C_OVERRUN 0x08
Overrun/Underrun.
#define I2C_PEC_ERROR 0x10
PEC Error in reception.
#define I2C_TIMEOUT 0x20
Hardware timeout.
#define I2C_SMB_ALERT 0x40
SMBus Alert.
TIMINGR register definitions
#define STM32_TIMINGR_PRESC_MASK (15U << 28)
#define STM32_TIMINGR_PRESC(n) ((n) << 28)
#define STM32_TIMINGR_SCLDEL_MASK (15U << 20)
#define STM32_TIMINGR_SCLDEL(n) ((n) << 20)
#define STM32_TIMINGR_SDADEL_MASK (15U << 16)
#define STM32_TIMINGR_SDADEL(n) ((n) << 16)
#define STM32_TIMINGR_SCLH_MASK (255U << 8)
#define STM32_TIMINGR_SCLH(n) ((n) << 8)
#define STM32_TIMINGR_SCLL_MASK (255U << 0)
#define STM32_TIMINGR_SCLL(n) ((n) << 0)
Configuration options
#define STM32_I2C_USE_I2C1 FALSE
I2C1 driver enable switch.
#define STM32_I2C_USE_I2C2 FALSE
I2C2 driver enable switch.
#define STM32_I2C_USE_I2C3 FALSE
I2C3 driver enable switch.
#define STM32_I2C_USE_I2C4 FALSE
I2C4 driver enable switch.
#define STM32_I2C_BUSY_TIMEOUT 50
I2C timeout on busy condition in milliseconds.
#define STM32_I2C_I2C1_IRQ_PRIORITY 10
I2C1 interrupt priority level setting.
#define STM32_I2C_I2C2_IRQ_PRIORITY 10
I2C2 interrupt priority level setting.
#define STM32_I2C_I2C3_IRQ_PRIORITY 10
I2C3 interrupt priority level setting.
#define STM32_I2C_I2C4_IRQ_PRIORITY 10
I2C4 interrupt priority level setting.
#define STM32_I2C_USE_DMA TRUE
DMA use switch.
#define STM32_I2C_I2C1_DMA_PRIORITY 1
I2C1 DMA priority (0..3|lowest..highest).
#define STM32_I2C_I2C2_DMA_PRIORITY 1
I2C2 DMA priority (0..3|lowest..highest).
#define STM32_I2C_I2C3_DMA_PRIORITY 1
I2C3 DMA priority (0..3|lowest..highest).
#define STM32_I2C_I2C4_DMA_PRIORITY 1
I2C4 DMA priority (0..3|lowest..highest).
#define STM32_I2C_DMA_ERROR_HOOK(i2cp) osalSysHalt("DMA failure")
I2C DMA error hook.
Typedefs
typedef uint16_t i2caddr_t
Type representing an I2C address.
typedef uint32_t i2cflags_t
Type of I2C driver condition flags.
typedef struct I2CDriver I2CDriver
Type of a structure representing an I2C driver.
Data Structures
struct I2CConfig
Type of I2C driver configuration structure.
struct I2CDriver
Structure representing an I2C driver.
Functions
void i2cInit (void)
I2C Driver initialization.
void i2cObjectInit (I2CDriver *i2cp)
Initializes the standard part of a I2CDriver structure.
void i2cStart (I2CDriver *i2cp, const I2CConfig *config)
Configures and activates the I2C peripheral.
void i2cStop (I2CDriver *i2cp)
Deactivates the I2C peripheral.
i2cflags_t i2cGetErrors (I2CDriver *i2cp)
Returns the errors mask associated to the previous operation.
msg_t i2cMasterTransmitTimeout (I2CDriver *i2cp, i2caddr_t addr, const uint8_t *txbuf, size_t txbytes, uint8_t *rxbuf, size_t rxbytes, sysinterval_t timeout)
Sends data via the I2C bus.
msg_t i2cMasterReceiveTimeout (I2CDriver *i2cp, i2caddr_t addr, uint8_t *rxbuf, size_t rxbytes, sysinterval_t timeout)
Receives data from the I2C bus.
void i2cAcquireBus (I2CDriver *i2cp)
Gains exclusive access to the I2C bus.
void i2cReleaseBus (I2CDriver *i2cp)
Releases exclusive access to the I2C bus.
static void i2c_lld_set_address (I2CDriver *i2cp, i2caddr_t addr)
Slave address setup.
static void i2c_lld_setup_rx_transfer (I2CDriver *i2cp)
I2C RX transfer setup.
static void i2c_lld_setup_tx_transfer (I2CDriver *i2cp)
I2C TX transfer setup.
static void i2c_lld_abort_operation (I2CDriver *i2cp)
Aborts an I2C transaction.
static void i2c_lld_serve_interrupt (I2CDriver *i2cp, uint32_t isr)
I2C shared ISR code.
static void i2c_lld_serve_error_interrupt (I2CDriver *i2cp, uint32_t isr)
I2C error handler.
OSAL_IRQ_HANDLER (STM32_I2C1_GLOBAL_HANDLER)
I2C1 event interrupt handler.
OSAL_IRQ_HANDLER (STM32_I2C2_GLOBAL_HANDLER)
I2C2 event interrupt handler.
OSAL_IRQ_HANDLER (STM32_I2C3_GLOBAL_HANDLER)
I2C3 event interrupt handler.
OSAL_IRQ_HANDLER (STM32_I2C4_GLOBAL_HANDLER)
I2C4 event interrupt handler.
void i2c_lld_init (void)
Low level I2C driver initialization.
void i2c_lld_start (I2CDriver *i2cp)
Configures and activates the I2C peripheral.
void i2c_lld_stop (I2CDriver *i2cp)
Deactivates the I2C peripheral.
msg_t i2c_lld_master_receive_timeout (I2CDriver *i2cp, i2caddr_t addr, uint8_t *rxbuf, size_t rxbytes, sysinterval_t timeout)
Receives data via the I2C bus as master.
msg_t i2c_lld_master_transmit_timeout (I2CDriver *i2cp, i2caddr_t addr, const uint8_t *txbuf, size_t txbytes, uint8_t *rxbuf, size_t rxbytes, sysinterval_t timeout)
Transmits data via the I2C bus as master.
Enumerations
enum i2cstate_t {
I2C_UNINIT = 0, I2C_STOP = 1, I2C_READY = 2, I2C_ACTIVE_TX = 3,
I2C_ACTIVE_RX = 4
}
Driver state machine possible states.
Variables
I2CDriver I2CD1
I2C1 driver identifier.
I2CDriver I2CD2
I2C2 driver identifier.
I2CDriver I2CD3
I2C3 driver identifier.
I2CDriver I2CD4
I2C4 driver identifier.
Macro Definition Documentation
I2C_NO_ERROR
#define I2C_NO_ERROR 0x00
No error.
Definition at line 43 of file hal_i2c.h.
Referenced by i2c_lld_master_receive_timeout(), i2c_lld_master_transmit_timeout(), and i2c_lld_serve_error_interrupt().
I2C_BUS_ERROR
#define I2C_BUS_ERROR 0x01
Bus Error.
Definition at line 44 of file hal_i2c.h.
Referenced by i2c_lld_serve_error_interrupt().
I2C_ARBITRATION_LOST
#define I2C_ARBITRATION_LOST 0x02
Arbitration Lost.
Definition at line 45 of file hal_i2c.h.
Referenced by i2c_lld_serve_error_interrupt().
I2C_ACK_FAILURE
#define I2C_ACK_FAILURE 0x04
Acknowledge Failure.
Definition at line 46 of file hal_i2c.h.
Referenced by i2c_lld_serve_interrupt().
I2C_OVERRUN
#define I2C_OVERRUN 0x08
Overrun/Underrun.
Definition at line 47 of file hal_i2c.h.
Referenced by i2c_lld_serve_error_interrupt().
I2C_PEC_ERROR
#define I2C_PEC_ERROR 0x10
PEC Error in reception.
Definition at line 48 of file hal_i2c.h.
I2C_TIMEOUT
#define I2C_TIMEOUT 0x20
Hardware timeout.
Definition at line 51 of file hal_i2c.h.
Referenced by i2c_lld_serve_error_interrupt().
I2C_SMB_ALERT
#define I2C_SMB_ALERT 0x40
SMBus Alert.
Definition at line 52 of file hal_i2c.h.
I2C_USE_MUTUAL_EXCLUSION
#define I2C_USE_MUTUAL_EXCLUSION TRUE
Enables the mutual exclusion APIs on the I2C bus.
Definition at line 63 of file hal_i2c.h.
_i2c_wakeup_isr
#define _i2c_wakeup_isr (i2cp)
Value:
do {                                          \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(i2cp)->thread, MSG_OK);                               \
  osalSysUnlockFromISR();                                                   \
} while(0)
Wakes up the waiting thread notifying no errors.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 99 of file hal_i2c.h.
_i2c_wakeup_error_isr
#define _i2c_wakeup_error_isr (i2cp)
Value:
do {                                    \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(i2cp)->thread, MSG_RESET);                            \
  osalSysUnlockFromISR();                                                   \
} while(0)
Wakes up the waiting thread notifying errors.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 112 of file hal_i2c.h.
Referenced by i2c_lld_serve_error_interrupt(), and i2c_lld_serve_interrupt().
i2cMasterTransmit
#define i2cMasterTransmit (i2cp, addr, txbuf, txbytes, rxbuf, rxbytes)
Value:
(i2cMasterTransmitTimeout(i2cp, addr, txbuf, txbytes, rxbuf, rxbytes,     \
                            TIME_INFINITE))
Wrap i2cMasterTransmitTimeout function with TIME_INFINITE timeout.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 122 of file hal_i2c.h.
i2cMasterReceive
#define i2cMasterReceive (i2cp, addr, rxbuf, rxbytes) (i2cMasterReceiveTimeout(i2cp, addr, rxbuf, rxbytes, TIME_INFINITE))
Wrap i2cMasterReceiveTimeout function with TIME_INFINITE timeout.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 130 of file hal_i2c.h.
STM32_I2C_USE_I2C1
#define STM32_I2C_USE_I2C1 FALSE
I2C1 driver enable switch.
If set to TRUE the support for I2C1 is included.
Note
The default is FALSE.
Definition at line 68 of file hal_i2c_lld.h.
STM32_I2C_USE_I2C2
#define STM32_I2C_USE_I2C2 FALSE
I2C2 driver enable switch.
If set to TRUE the support for I2C2 is included.
Note
The default is FALSE.
Definition at line 77 of file hal_i2c_lld.h.
STM32_I2C_USE_I2C3
#define STM32_I2C_USE_I2C3 FALSE
I2C3 driver enable switch.
If set to TRUE the support for I2C3 is included.
Note
The default is FALSE.
Definition at line 86 of file hal_i2c_lld.h.
STM32_I2C_USE_I2C4
#define STM32_I2C_USE_I2C4 FALSE
I2C4 driver enable switch.
If set to TRUE the support for I2C4 is included.
Note
The default is FALSE.
Definition at line 95 of file hal_i2c_lld.h.
STM32_I2C_BUSY_TIMEOUT
#define STM32_I2C_BUSY_TIMEOUT 50
I2C timeout on busy condition in milliseconds.
Definition at line 102 of file hal_i2c_lld.h.
Referenced by i2c_lld_master_receive_timeout(), and i2c_lld_master_transmit_timeout().
STM32_I2C_I2C1_IRQ_PRIORITY
#define STM32_I2C_I2C1_IRQ_PRIORITY 10
I2C1 interrupt priority level setting.
Definition at line 109 of file hal_i2c_lld.h.
STM32_I2C_I2C2_IRQ_PRIORITY
#define STM32_I2C_I2C2_IRQ_PRIORITY 10
I2C2 interrupt priority level setting.
Definition at line 116 of file hal_i2c_lld.h.
STM32_I2C_I2C3_IRQ_PRIORITY
#define STM32_I2C_I2C3_IRQ_PRIORITY 10
I2C3 interrupt priority level setting.
Definition at line 123 of file hal_i2c_lld.h.
STM32_I2C_I2C4_IRQ_PRIORITY
#define STM32_I2C_I2C4_IRQ_PRIORITY 10
I2C4 interrupt priority level setting.
Definition at line 130 of file hal_i2c_lld.h.
STM32_I2C_USE_DMA
#define STM32_I2C_USE_DMA TRUE
DMA use switch.
Definition at line 137 of file hal_i2c_lld.h.
STM32_I2C_I2C1_DMA_PRIORITY
#define STM32_I2C_I2C1_DMA_PRIORITY 1
I2C1 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA streams but because of the streams ordering the RX stream has always priority over the TX stream.
Definition at line 147 of file hal_i2c_lld.h.
STM32_I2C_I2C2_DMA_PRIORITY
#define STM32_I2C_I2C2_DMA_PRIORITY 1
I2C2 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA streams but because of the streams ordering the RX stream has always priority over the TX stream.
Definition at line 157 of file hal_i2c_lld.h.
STM32_I2C_I2C3_DMA_PRIORITY
#define STM32_I2C_I2C3_DMA_PRIORITY 1
I2C3 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA streams but because of the streams ordering the RX stream has always priority over the TX stream.
Definition at line 167 of file hal_i2c_lld.h.
STM32_I2C_I2C4_DMA_PRIORITY
#define STM32_I2C_I2C4_DMA_PRIORITY 1
I2C4 DMA priority (0..3|lowest..highest).
Note
The priority level is used for both the TX and RX DMA streams but because of the streams ordering the RX stream has always priority over the TX stream.
Definition at line 177 of file hal_i2c_lld.h.
STM32_I2C_DMA_ERROR_HOOK
#define STM32_I2C_DMA_ERROR_HOOK (i2cp) osalSysHalt("DMA failure")
I2C DMA error hook.
Note
The default action for DMA errors is a system halt because DMA error can only happen because programming errors.
Definition at line 186 of file hal_i2c_lld.h.
STM32_DMA_REQUIRED
#define STM32_DMA_REQUIRED
error checks
Definition at line 332 of file hal_i2c_lld.h.
i2c_lld_get_errors
#define i2c_lld_get_errors (i2cp) ((i2cp)->errors)
Get errors from I2C driver.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 456 of file hal_i2c_lld.h.
Referenced by i2cGetErrors().
Typedef Documentation
i2caddr_t
typedef uint16_t i2caddr_t
Type representing an I2C address.
Definition at line 343 of file hal_i2c_lld.h.
i2cflags_t
typedef uint32_t i2cflags_t
Type of I2C driver condition flags.
Definition at line 348 of file hal_i2c_lld.h.
I2CDriver
typedef struct I2CDriver I2CDriver
Type of a structure representing an I2C driver.
Definition at line 375 of file hal_i2c_lld.h.
Enumeration Type Documentation
i2cstate_t
enum i2cstate_t
Driver state machine possible states.
Enumerator
I2C_UNINIT
Not initialized.
I2C_STOP
Stopped.
I2C_READY
Ready.
I2C_ACTIVE_TX
Transmitting.
I2C_ACTIVE_RX
Receiving.
Definition at line 77 of file hal_i2c.h.
Function Documentation
i2cInit()
void i2cInit (void)
I2C Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 59 of file hal_i2c.c.
References i2c_lld_init().
Referenced by halInit().
i2cObjectInit()
void i2cObjectInit (I2CDriver * i2cp)
Initializes the standard part of a I2CDriver structure.
Parameters
[out] i2cp pointer to the I2CDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 71 of file hal_i2c.c.
References I2CDriver::config, I2C_STOP, osalMutexObjectInit(), and I2CDriver::state.
Referenced by i2c_lld_init().
i2cStart()
void i2cStart (I2CDriver * i2cp, const I2CConfig * config)
Configures and activates the I2C peripheral.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] config pointer to the I2CConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 93 of file hal_i2c.c.
References I2C_READY, I2C_STOP, osalDbgAssert, osalDbgCheck, and I2CDriver::state.
i2cStop()
void i2cStop (I2CDriver * i2cp)
Deactivates the I2C peripheral.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 113 of file hal_i2c.c.
References I2C_READY, I2C_STOP, osalDbgAssert, osalDbgCheck, osalSysLock(), and I2CDriver::state.
i2cGetErrors()
i2cflags_t i2cGetErrors (I2CDriver * i2cp)
Returns the errors mask associated to the previous operation.
Parameters
[in] i2cp pointer to the I2CDriver object
Returns
The errors mask.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 137 of file hal_i2c.c.
References i2c_lld_get_errors, and osalDbgCheck.
i2cMasterTransmitTimeout()
msg_t i2cMasterTransmitTimeout (I2CDriver * i2cp, i2caddr_t addr, const uint8_t * txbuf, size_t txbytes, uint8_t * rxbuf, size_t rxbytes, sysinterval_t timeout)
Sends data via the I2C bus.
Function designed to realize "read-through-write" transfer paradigm. If you want transmit data without any further read, than set rxbytes field to 0.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] addr slave device address (7 bits) without R/W bit
[in] txbuf pointer to transmit buffer
[in] txbytes number of bytes to be transmitted
[out] rxbuf pointer to receive buffer
[in] rxbytes number of bytes to be received, set it to 0 if you want transmit only
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 170 of file hal_i2c.c.
References osalDbgCheck.
i2cMasterReceiveTimeout()
msg_t i2cMasterReceiveTimeout (I2CDriver * i2cp, i2caddr_t addr, uint8_t * rxbuf, size_t rxbytes, sysinterval_t timeout)
Receives data from the I2C bus.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] addr slave device address (7 bits) without R/W bit
[out] rxbuf pointer to receive buffer
[in] rxbytes number of bytes to be received
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 221 of file hal_i2c.c.
References osalDbgCheck.
i2cAcquireBus()
void i2cAcquireBus (I2CDriver * i2cp)
Gains exclusive access to the I2C bus.
This function tries to gain ownership to the I2C bus, if the bus is already being used then the invoking thread is queued.
Precondition
In order to use this function the option I2C_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 261 of file hal_i2c.c.
References osalDbgCheck, and osalMutexLock().
i2cReleaseBus()
void i2cReleaseBus (I2CDriver * i2cp)
Releases exclusive access to the I2C bus.
Precondition
In order to use this function the option I2C_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 277 of file hal_i2c.c.
References osalDbgCheck, and osalMutexUnlock().
i2c_lld_set_address()
static void i2c_lld_set_address (I2CDriver * i2cp, i2caddr_t addr) static
Slave address setup.
Note
The RW bit is set to zero internally.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] addr slave device address
Function Class:
Not an API, this function is for internal use only.
Definition at line 133 of file hal_i2c_lld.c.
References I2CDriver::config, I2CConfig::cr2, and I2CDriver::i2c.
i2c_lld_setup_rx_transfer()
static void i2c_lld_setup_rx_transfer (I2CDriver * i2cp) static
I2C RX transfer setup.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 150 of file hal_i2c_lld.c.
References I2CDriver::i2c.
Referenced by i2c_lld_serve_interrupt().
i2c_lld_setup_tx_transfer()
static void i2c_lld_setup_tx_transfer (I2CDriver * i2cp) static
I2C TX transfer setup.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 178 of file hal_i2c_lld.c.
References I2CDriver::i2c.
Referenced by i2c_lld_serve_interrupt().
i2c_lld_abort_operation()
static void i2c_lld_abort_operation (I2CDriver * i2cp) static
Aborts an I2C transaction.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 206 of file hal_i2c_lld.c.
References I2CDriver::dmarx, dmaStreamDisable, I2CDriver::dmatx, and I2CDriver::i2c.
Referenced by i2c_lld_stop().
i2c_lld_serve_interrupt()
static void i2c_lld_serve_interrupt (I2CDriver * i2cp, uint32_t isr) static
I2C shared ISR code.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] isr content of the ISR register to be decoded
Function Class:
Not an API, this function is for internal use only.
Definition at line 234 of file hal_i2c_lld.c.
References _i2c_wakeup_error_isr, I2CDriver::dmarx, dmaStreamDisable, I2CDriver::dmatx, I2CDriver::errors, I2CDriver::i2c, I2C_ACK_FAILURE, I2C_ACTIVE_TX, i2c_lld_setup_rx_transfer(), i2c_lld_setup_tx_transfer(), and I2CDriver::state.
i2c_lld_serve_error_interrupt()
static void i2c_lld_serve_error_interrupt (I2CDriver * i2cp, uint32_t isr) static
I2C error handler.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] isr content of the ISR register to be decoded
Function Class:
Not an API, this function is for internal use only.
Definition at line 361 of file hal_i2c_lld.c.
References _i2c_wakeup_error_isr, I2CDriver::dmarx, dmaStreamDisable, I2CDriver::dmatx, I2CDriver::errors, I2CDriver::i2c, I2C_ARBITRATION_LOST, I2C_BUS_ERROR, I2C_NO_ERROR, I2C_OVERRUN, and I2C_TIMEOUT.
OSAL_IRQ_HANDLER() [1/4]
OSAL_IRQ_HANDLER (STM32_I2C1_GLOBAL_HANDLER)
I2C1 event interrupt handler.
Function Class:
Not an API, this function is for internal use only.
Definition at line 400 of file hal_i2c_lld.c.
References I2CDriver::i2c, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER() [2/4]
OSAL_IRQ_HANDLER (STM32_I2C2_GLOBAL_HANDLER)
I2C2 event interrupt handler.
Function Class:
Not an API, this function is for internal use only.
Definition at line 455 of file hal_i2c_lld.c.
References I2CDriver::i2c, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER() [3/4]
OSAL_IRQ_HANDLER (STM32_I2C3_GLOBAL_HANDLER)
I2C3 event interrupt handler.
Function Class:
Not an API, this function is for internal use only.
Definition at line 510 of file hal_i2c_lld.c.
References I2CDriver::i2c, and OSAL_IRQ_PROLOGUE.
OSAL_IRQ_HANDLER() [4/4]
OSAL_IRQ_HANDLER (STM32_I2C4_GLOBAL_HANDLER)
I2C4 event interrupt handler.
Function Class:
Not an API, this function is for internal use only.
Definition at line 565 of file hal_i2c_lld.c.
References I2CDriver::i2c, and OSAL_IRQ_PROLOGUE.
i2c_lld_init()
void i2c_lld_init (void)
Low level I2C driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 622 of file hal_i2c_lld.c.
References I2CDriver::dmarx, I2CDriver::i2c, i2cObjectInit(), STM32_DMA_STREAM, and I2CDriver::thread.
Referenced by i2cInit().
i2c_lld_start()
void i2c_lld_start (I2CDriver * i2cp)
Configures and activates the I2C peripheral.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 672 of file hal_i2c_lld.c.
References I2CDriver::i2c, I2C_STOP, I2CDriver::state, and I2CDriver::txdmamode.
i2c_lld_stop()
void i2c_lld_stop (I2CDriver * i2cp)
Deactivates the I2C peripheral.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 867 of file hal_i2c_lld.c.
References I2CDriver::dmarx, dmaStreamRelease(), I2CDriver::dmatx, i2c_lld_abort_operation(), I2C_STOP, and I2CDriver::state.
i2c_lld_master_receive_timeout()
msg_t i2c_lld_master_receive_timeout (I2CDriver * i2cp, i2caddr_t addr, uint8_t * rxbuf, size_t rxbytes, sysinterval_t timeout)
Receives data via the I2C bus as master.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] addr slave device address
[out] rxbuf pointer to the receive buffer
[in] rxbytes number of bytes to be received
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end. After a timeout the driver must be stopped and restarted because the bus is in an uncertain state.
Function Class:
Not an API, this function is for internal use only.
Definition at line 962 of file hal_i2c_lld.c.
References I2CDriver::dmarx, dmaStreamSetMemory0, dmaStreamSetMode, dmaStreamSetTransactionSize, I2CDriver::errors, I2CDriver::i2c, I2C_NO_ERROR, OSAL_MS2I, osalOsGetSystemTimeX(), osalSysLock(), osalSysUnlock(), osalTimeAddX(), osalTimeIsInRangeX(), I2CDriver::rxdmamode, and STM32_I2C_BUSY_TIMEOUT.
i2c_lld_master_transmit_timeout()
msg_t i2c_lld_master_transmit_timeout (I2CDriver * i2cp, i2caddr_t addr, const uint8_t * txbuf, size_t txbytes, uint8_t * rxbuf, size_t rxbytes, sysinterval_t timeout)
Transmits data via the I2C bus as master.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] addr slave device address
[in] txbuf pointer to the transmit buffer
[in] txbytes number of bytes to be transmitted
[out] rxbuf pointer to the receive buffer
[in] rxbytes number of bytes to be received
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end. After a timeout the driver must be stopped and restarted because the bus is in an uncertain state.
Function Class:
Not an API, this function is for internal use only.
Definition at line 1064 of file hal_i2c_lld.c.
References I2CDriver::dmarx, dmaStreamSetMemory0, dmaStreamSetMode, dmaStreamSetTransactionSize, I2CDriver::dmatx, I2CDriver::errors, I2CDriver::i2c, I2C_NO_ERROR, OSAL_MS2I, osalOsGetSystemTimeX(), osalSysLock(), osalSysUnlock(), osalTimeAddX(), osalTimeIsInRangeX(), I2CDriver::rxdmamode, STM32_I2C_BUSY_TIMEOUT, and I2CDriver::txdmamode.
Variable Documentation
I2CD1
I2CDriver I2CD1
I2C1 driver identifier.
Definition at line 98 of file hal_i2c_lld.c.
I2CD2
I2CDriver I2CD2
I2C2 driver identifier.
Definition at line 103 of file hal_i2c_lld.c.
I2CD3
I2CDriver I2CD3
I2C3 driver identifier.
Definition at line 108 of file hal_i2c_lld.c.
I2CD4
I2CDriver I2CD4
I2C4 driver identifier.
Definition at line 113 of file hal_i2c_lld.c.