ChibiOS/HAL for STM32F3xx: HAL Driver
HAL Driver
HAL » Normal Drivers
Hardware Abstraction Layer.
Detailed Description
Hardware Abstraction Layer.
The HAL (Hardware Abstraction Layer) driver performs the system initialization and includes the platform support code shared by the other drivers. This driver does contain any API function except for a general initialization function halInit() that must be invoked before any HAL service can be used, usually the HAL initialization should be performed immediately before the kernel initialization.
Some HAL driver implementations also offer a custom early clock setup function that can be invoked before the C runtime initialization in order to accelerate the startup time.
Macros
#define _CHIBIOS_HAL_
ChibiOS/HAL identification macro.
#define CH_HAL_STABLE 1
Stable release flag.
#define STM32_ACTIVATE_PLL TRUE
PLL activation flag.
#define STM32_PLLMUL ((STM32_PLLMUL_VALUE - 2) << 18)
PLLMUL field.
#define STM32_PLLCLKIN (STM32_HSECLK / STM32_PREDIV_VALUE)
PLL input clock frequency.
#define STM32_PLLCLKOUT (STM32_PLLCLKIN * STM32_PLLMUL_VALUE)
PLL output clock frequency.
#define STM32_SYSCLK STM32_PLLCLKOUT
System clock source.
#define STM32_HCLK (STM32_SYSCLK / 1)
AHB frequency.
#define STM32_PCLK1 (STM32_HCLK / 1)
APB1 frequency.
#define STM32_PCLK2 (STM32_HCLK / 1)
APB2 frequency.
#define STM32_RTCCLK STM32_LSECLK
RTC clock.
#define STM32_ADC12CLK 0
ADC12 frequency.
#define STM32_ADC34CLK 0
ADC34 frequency.
#define STM32_I2C1CLK STM32_SYSCLK
I2C1 frequency.
#define STM32_I2C2CLK STM32_SYSCLK
I2C2 frequency.
#define STM32_USART1CLK STM32_PCLK2
USART1 frequency.
#define STM32_USART2CLK STM32_PCLK1
USART2 frequency.
#define STM32_USART3CLK STM32_PCLK1
USART3 frequency.
#define STM32_UART4CLK STM32_PCLK1
UART4 frequency.
#define STM32_UART5CLK STM32_PCLK1
UART5 frequency.
#define STM32_TIM1CLK (STM32_PCLK2 * 2)
TIM1 frequency.
#define STM32_TIM8CLK (STM32_PCLK2 * 2)
TIM8 frequency.
#define STM32_HRTIM1CLK (STM32_PCLK2 * 2)
HRTIM1 frequency.
#define STM32_TIMCLK1 (STM32_PCLK1 * 1)
Timers 2, 3, 4, 6, 7 frequency.
#define STM32_TIMCLK2 (STM32_PCLK2 * 1)
Timers 1, 8, 15, 16, 17 frequency.
#define STM32_USBCLK ((STM32_PLLCLKOUT * 2) / 3)
USB frequency.
#define STM32_FLASHBITS 0x00000010
Flash settings.
#define STM32F3XX
Sub-family identifier.
ChibiOS/HAL version identification
#define HAL_VERSION "6.1.0"
HAL version string.
#define CH_HAL_MAJOR 6
HAL version major number.
#define CH_HAL_MINOR 1
HAL version minor number.
#define CH_HAL_PATCH 0
HAL version patch number.
Return codes
#define HAL_SUCCESS false
#define HAL_FAILED true
Platform identification macros
#define PLATFORM_NAME "STM32F301x8 Analog & DSP"
Absolute Maximum Ratings
#define STM32_SYSCLK_MAX 72000000
Maximum system clock frequency.
#define STM32_HSECLK_MAX 32000000
Maximum HSE clock frequency.
#define STM32_HSECLK_MIN 1000000
Minimum HSE clock frequency.
#define STM32_LSECLK_MAX 1000000
Maximum LSE clock frequency.
#define STM32_LSECLK_MIN 32768
Minimum LSE clock frequency.
#define STM32_PLLIN_MAX 24000000
Maximum PLLs input clock frequency.
#define STM32_PLLIN_MIN 1000000
Minimum PLLs input clock frequency.
#define STM32_PLLOUT_MAX 72000000
Maximum PLL output clock frequency.
#define STM32_PLLOUT_MIN 16000000
Minimum PLL output clock frequency.
#define STM32_PCLK1_MAX 36000000
Maximum APB1 clock frequency.
#define STM32_PCLK2_MAX 72000000
Maximum APB2 clock frequency.
#define STM32_ADCCLK_MAX 72000000
Maximum ADC clock frequency.
Internal clock sources
#define STM32_HSICLK 8000000
#define STM32_LSICLK 40000
PWR_CR register bits definitions
#define STM32_PLS_MASK (7 << 5)
#define STM32_PLS_LEV0 (0 << 5)
#define STM32_PLS_LEV1 (1 << 5)
#define STM32_PLS_LEV2 (2 << 5)
#define STM32_PLS_LEV3 (3 << 5)
#define STM32_PLS_LEV4 (4 << 5)
#define STM32_PLS_LEV5 (5 << 5)
#define STM32_PLS_LEV6 (6 << 5)
#define STM32_PLS_LEV7 (7 << 5)
RCC_CFGR register bits definitions
#define STM32_SW_HSI (0 << 0)
#define STM32_SW_HSE (1 << 0)
#define STM32_SW_PLL (2 << 0)
#define STM32_HPRE_DIV1 (0 << 4)
#define STM32_HPRE_DIV2 (8 << 4)
#define STM32_HPRE_DIV4 (9 << 4)
#define STM32_HPRE_DIV8 (10 << 4)
#define STM32_HPRE_DIV16 (11 << 4)
#define STM32_HPRE_DIV64 (12 << 4)
#define STM32_HPRE_DIV128 (13 << 4)
#define STM32_HPRE_DIV256 (14 << 4)
#define STM32_HPRE_DIV512 (15 << 4)
#define STM32_PPRE1_DIV1 (0 << 8)
#define STM32_PPRE1_DIV2 (4 << 8)
#define STM32_PPRE1_DIV4 (5 << 8)
#define STM32_PPRE1_DIV8 (6 << 8)
#define STM32_PPRE1_DIV16 (7 << 8)
#define STM32_PPRE2_DIV1 (0 << 11)
#define STM32_PPRE2_DIV2 (4 << 11)
#define STM32_PPRE2_DIV4 (5 << 11)
#define STM32_PPRE2_DIV8 (6 << 11)
#define STM32_PPRE2_DIV16 (7 << 11)
#define STM32_PLLSRC_HSI (0 << 16)
#define STM32_PLLSRC_HSE (1 << 16)
#define STM32_USBPRE_DIV1P5 (0 << 22)
#define STM32_USBPRE_DIV1 (1 << 22)
#define STM32_MCOSEL_NOCLOCK (0 << 24)
#define STM32_MCOSEL_LSI (2 << 24)
#define STM32_MCOSEL_LSE (3 << 24)
#define STM32_MCOSEL_SYSCLK (4 << 24)
#define STM32_MCOSEL_HSI (5 << 24)
#define STM32_MCOSEL_HSE (6 << 24)
#define STM32_MCOSEL_PLLDIV2 (7 << 24)
RCC_BDCR register bits definitions
#define STM32_RTCSEL_MASK (3 << 8)
#define STM32_RTCSEL_NOCLOCK (0 << 8)
#define STM32_RTCSEL_LSE (1 << 8)
#define STM32_RTCSEL_LSI (2 << 8)
#define STM32_RTCSEL_HSEDIV (3 << 8)
RCC_CFGR2 register bits definitions
#define STM32_PREDIV_MASK (15 << 0)
#define STM32_ADC12PRES_MASK (31 << 4)
#define STM32_ADC12PRES_NOCLOCK (0 << 4)
#define STM32_ADC12PRES_DIV1 (16 << 4)
#define STM32_ADC12PRES_DIV2 (17 << 4)
#define STM32_ADC12PRES_DIV4 (18 << 4)
#define STM32_ADC12PRES_DIV6 (19 << 4)
#define STM32_ADC12PRES_DIV8 (20 << 4)
#define STM32_ADC12PRES_DIV10 (21 << 4)
#define STM32_ADC12PRES_DIV12 (22 << 4)
#define STM32_ADC12PRES_DIV16 (23 << 4)
#define STM32_ADC12PRES_DIV32 (24 << 4)
#define STM32_ADC12PRES_DIV64 (25 << 4)
#define STM32_ADC12PRES_DIV128 (26 << 4)
#define STM32_ADC12PRES_DIV256 (27 << 4)
#define STM32_ADC34PRES_MASK (31 << 9)
#define STM32_ADC34PRES_NOCLOCK (0 << 9)
#define STM32_ADC34PRES_DIV1 (16 << 9)
#define STM32_ADC34PRES_DIV2 (17 << 9)
#define STM32_ADC34PRES_DIV4 (18 << 9)
#define STM32_ADC34PRES_DIV6 (19 << 9)
#define STM32_ADC34PRES_DIV8 (20 << 9)
#define STM32_ADC34PRES_DIV10 (21 << 9)
#define STM32_ADC34PRES_DIV12 (22 << 9)
#define STM32_ADC34PRES_DIV16 (23 << 9)
#define STM32_ADC34PRES_DIV32 (24 << 9)
#define STM32_ADC34PRES_DIV64 (25 << 9)
#define STM32_ADC34PRES_DIV128 (26 << 9)
#define STM32_ADC34PRES_DIV256 (27 << 9)
RCC_CFGR3 register bits definitions
#define STM32_USART1SW_MASK (3 << 0)
#define STM32_USART1SW_PCLK (0 << 0)
#define STM32_USART1SW_SYSCLK (1 << 0)
#define STM32_USART1SW_LSE (2 << 0)
#define STM32_USART1SW_HSI (3 << 0)
#define STM32_I2C1SW_MASK (1 << 4)
#define STM32_I2C1SW_HSI (0 << 4)
#define STM32_I2C1SW_SYSCLK (1 << 4)
#define STM32_I2C2SW_MASK (1 << 5)
#define STM32_I2C2SW_HSI (0 << 5)
#define STM32_I2C2SW_SYSCLK (1 << 5)
#define STM32_TIM1SW_MASK (1 << 8)
#define STM32_TIM1SW_PCLK2 (0 << 8)
#define STM32_TIM1SW_PLLX2 (1 << 8)
#define STM32_TIM8SW_MASK (1 << 9)
#define STM32_TIM8SW_PCLK2 (0 << 9)
#define STM32_TIM8SW_PLLX2 (1 << 9)
#define STM32_HRTIM1SW_MASK (1 << 12)
#define STM32_HRTIM1SW_PCLK2 (0 << 12)
#define STM32_HRTIM1SW_PLLX2 (1 << 12)
#define STM32_USART2SW_MASK (3 << 16)
#define STM32_USART2SW_PCLK (0 << 16)
#define STM32_USART2SW_SYSCLK (1 << 16)
#define STM32_USART2SW_LSE (2 << 16)
#define STM32_USART2SW_HSI (3 << 16)
#define STM32_USART3SW_MASK (3 << 18)
#define STM32_USART3SW_PCLK (0 << 18)
#define STM32_USART3SW_SYSCLK (1 << 18)
#define STM32_USART3SW_LSE (2 << 18)
#define STM32_USART3SW_HSI (3 << 18)
#define STM32_UART4SW_MASK (3 << 20)
#define STM32_UART4SW_PCLK (0 << 20)
#define STM32_UART4SW_SYSCLK (1 << 20)
#define STM32_UART4SW_LSE (2 << 20)
#define STM32_UART4SW_HSI (3 << 20)
#define STM32_UART5SW_MASK (3 << 22)
#define STM32_UART5SW_PCLK (0 << 22)
#define STM32_UART5SW_SYSCLK (1 << 22)
#define STM32_UART5SW_LSE (2 << 22)
#define STM32_UART5SW_HSI (3 << 22)
Configuration options
#define STM32_NO_INIT FALSE
Disables the PWR/RCC initialization in the HAL.
#define STM32_PVD_ENABLE FALSE
Enables or disables the programmable voltage detector.
#define STM32_PLS STM32_PLS_LEV0
Sets voltage level for programmable voltage detector.
#define STM32_HSI_ENABLED TRUE
Enables or disables the HSI clock source.
#define STM32_LSI_ENABLED TRUE
Enables or disables the LSI clock source.
#define STM32_HSE_ENABLED TRUE
Enables or disables the HSE clock source.
#define STM32_LSE_ENABLED FALSE
Enables or disables the LSE clock source.
#define STM32_SW STM32_SW_PLL
Main clock source selection.
#define STM32_PLLSRC STM32_PLLSRC_HSE
Clock source for the PLL.
#define STM32_PREDIV_VALUE 1
Crystal PLL pre-divider.
#define STM32_PLLMUL_VALUE 9
PLL multiplier value.
#define STM32_HPRE STM32_HPRE_DIV1
AHB prescaler value.
#define STM32_PPRE1 STM32_PPRE1_DIV2
APB1 prescaler value.
#define STM32_PPRE2 STM32_PPRE2_DIV2
APB2 prescaler value.
#define STM32_MCOSEL STM32_MCOSEL_NOCLOCK
MCO pin setting.
#define STM32_ADC12PRES STM32_ADC12PRES_DIV1
ADC12 prescaler value.
#define STM32_ADC34PRES STM32_ADC34PRES_DIV1
ADC34 prescaler value.
#define STM32_USART1SW STM32_USART1SW_PCLK
USART1 clock source.
#define STM32_USART2SW STM32_USART2SW_PCLK
USART2 clock source.
#define STM32_USART3SW STM32_USART3SW_PCLK
USART3 clock source.
#define STM32_UART4SW STM32_UART4SW_PCLK
UART4 clock source.
#define STM32_UART5SW STM32_UART5SW_PCLK
UART5 clock source.
#define STM32_I2C1SW STM32_I2C1SW_SYSCLK
I2C1 clock source.
#define STM32_I2C2SW STM32_I2C2SW_SYSCLK
I2C2 clock source.
#define STM32_TIM1SW STM32_TIM1SW_PCLK2
TIM1 clock source.
#define STM32_TIM8SW STM32_TIM8SW_PCLK2
TIM8 clock source.
#define STM32_HRTIM1SW STM32_HRTIM1SW_PCLK2
HRTIM1 clock source.
#define STM32_RTCSEL STM32_RTCSEL_LSI
RTC clock source.
#define STM32_USB_CLOCK_REQUIRED TRUE
USB clock setting.
#define STM32_USBPRE STM32_USBPRE_DIV1P5
USB prescaler initialization.
STM32F3xx capabilities
#define STM32_HAS_ADC1 TRUE
#define STM32_ADC1_HANDLER Vector88
#define STM32_ADC1_NUMBER 18
#define STM32_ADC1_DMA_MSK (STM32_DMA_STREAM_ID_MSK(1, 1))
#define STM32_ADC1_DMA_CHN 0x00000000
#define STM32_HAS_ADC2 TRUE
#define STM32_ADC2_HANDLER Vector88
#define STM32_ADC2_NUMBER 18
#define STM32_ADC2_DMA_MSK
#define STM32_ADC2_DMA_CHN 0x00000000
#define STM32_HAS_ADC3 TRUE
#define STM32_ADC3_HANDLER VectorFC
#define STM32_ADC3_NUMBER 47
#define STM32_ADC3_DMA_MSK (STM32_DMA_STREAM_ID_MSK(2, 5))
#define STM32_ADC3_DMA_CHN 0x00000000
#define STM32_HAS_ADC4 TRUE
#define STM32_ADC4_HANDLER Vector134
#define STM32_ADC4_NUMBER 61
#define STM32_ADC4_DMA_MSK
#define STM32_ADC4_DMA_CHN 0x00000000
#define STM32_HAS_SDADC1 FALSE
#define STM32_HAS_SDADC2 FALSE
#define STM32_HAS_SDADC3 FALSE
#define STM32_HAS_CAN1 TRUE
#define STM32_HAS_CAN2 FALSE
#define STM32_HAS_CAN3 FALSE
#define STM32_CAN_MAX_FILTERS 14
#define STM32_HAS_DAC1_CH1 TRUE
#define STM32_DAC_DAC1_CH1_DMA_STREAM STM32_DMA_STREAM_ID(2, 3)
#define STM32_HAS_DAC1_CH2 TRUE
#define STM32_DAC_DAC1_CH2_DMA_STREAM STM32_DMA_STREAM_ID(2, 4)
#define STM32_HAS_DAC2_CH1 FALSE
#define STM32_HAS_DAC2_CH2 FALSE
#define STM32_ADVANCED_DMA FALSE
#define STM32_DMA_SUPPORTS_CSELR FALSE
#define STM32_DMA1_NUM_CHANNELS 7
#define STM32_DMA1_CH1_HANDLER Vector6C
#define STM32_DMA1_CH2_HANDLER Vector70
#define STM32_DMA1_CH3_HANDLER Vector74
#define STM32_DMA1_CH4_HANDLER Vector78
#define STM32_DMA1_CH5_HANDLER Vector7C
#define STM32_DMA1_CH6_HANDLER Vector80
#define STM32_DMA1_CH7_HANDLER Vector84
#define STM32_DMA1_CH1_NUMBER 11
#define STM32_DMA1_CH2_NUMBER 12
#define STM32_DMA1_CH3_NUMBER 13
#define STM32_DMA1_CH4_NUMBER 14
#define STM32_DMA1_CH5_NUMBER 15
#define STM32_DMA1_CH6_NUMBER 16
#define STM32_DMA1_CH7_NUMBER 17
#define STM32_DMA2_NUM_CHANNELS 5
#define STM32_DMA2_CH1_HANDLER Vector120
#define STM32_DMA2_CH2_HANDLER Vector124
#define STM32_DMA2_CH3_HANDLER Vector128
#define STM32_DMA2_CH4_HANDLER Vector12C
#define STM32_DMA2_CH5_HANDLER Vector130
#define STM32_DMA2_CH1_NUMBER 56
#define STM32_DMA2_CH2_NUMBER 57
#define STM32_DMA2_CH3_NUMBER 58
#define STM32_DMA2_CH4_NUMBER 59
#define STM32_DMA2_CH5_NUMBER 60
#define STM32_HAS_ETH FALSE
#define STM32_EXTI_NUM_LINES 34
#define STM32_EXTI_IMR_MASK 0x1F800000U
#define STM32_EXTI_IMR2_MASK 0xFFFFFFFCU
#define STM32_HAS_GPIOA TRUE
#define STM32_HAS_GPIOB TRUE
#define STM32_HAS_GPIOC TRUE
#define STM32_HAS_GPIOD TRUE
#define STM32_HAS_GPIOE TRUE
#define STM32_HAS_GPIOF TRUE
#define STM32_HAS_GPIOG FALSE
#define STM32_HAS_GPIOH FALSE
#define STM32_HAS_GPIOI FALSE
#define STM32_HAS_GPIOJ FALSE
#define STM32_HAS_GPIOK FALSE
#define STM32_GPIO_EN_MASK
#define STM32_HAS_I2C1 TRUE
#define STM32_I2C_I2C1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 7)
#define STM32_I2C_I2C1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
#define STM32_HAS_I2C2 TRUE
#define STM32_I2C_I2C2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_I2C_I2C2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_HAS_I2C3 FALSE
#define STM32_HAS_I2C4 FALSE
#define STM32_HAS_QUADSPI1 FALSE
#define STM32_HAS_RTC TRUE
#define STM32_RTC_HAS_SUBSECONDS TRUE
#define STM32_RTC_HAS_PERIODIC_WAKEUPS TRUE
#define STM32_RTC_NUM_ALARMS 1
#define STM32_RTC_HAS_INTERRUPTS FALSE
#define STM32_HAS_SDIO FALSE
#define STM32_HAS_SPI1 TRUE
#define STM32_SPI1_SUPPORTS_I2S FALSE
#define STM32_SPI_SPI1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
#define STM32_SPI_SPI1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 3)
#define STM32_HAS_SPI2 TRUE
#define STM32_SPI2_SUPPORTS_I2S TRUE
#define STM32_SPI2_I2S_FULLDUPLEX TRUE
#define STM32_SPI_SPI2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_SPI_SPI2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_HAS_SPI3 TRUE
#define STM32_SPI3_SUPPORTS_I2S TRUE
#define STM32_SPI3_I2S_FULLDUPLEX TRUE
#define STM32_SPI_SPI3_RX_DMA_STREAM STM32_DMA_STREAM_ID(2, 1)
#define STM32_SPI_SPI3_TX_DMA_STREAM STM32_DMA_STREAM_ID(2, 2)
#define STM32_HAS_SPI4 FALSE
#define STM32_HAS_SPI5 FALSE
#define STM32_HAS_SPI6 FALSE
#define STM32_TIM_MAX_CHANNELS 6
#define STM32_HAS_TIM1 TRUE
#define STM32_TIM1_IS_32BITS FALSE
#define STM32_TIM1_CHANNELS 6
#define STM32_HAS_TIM2 TRUE
#define STM32_TIM2_IS_32BITS TRUE
#define STM32_TIM2_CHANNELS 4
#define STM32_HAS_TIM3 TRUE
#define STM32_TIM3_IS_32BITS FALSE
#define STM32_TIM3_CHANNELS 4
#define STM32_HAS_TIM4 TRUE
#define STM32_TIM4_IS_32BITS FALSE
#define STM32_TIM4_CHANNELS 4
#define STM32_HAS_TIM6 TRUE
#define STM32_TIM6_IS_32BITS FALSE
#define STM32_TIM6_CHANNELS 0
#define STM32_HAS_TIM7 TRUE
#define STM32_TIM7_IS_32BITS FALSE
#define STM32_TIM7_CHANNELS 0
#define STM32_HAS_TIM8 TRUE
#define STM32_TIM8_IS_32BITS FALSE
#define STM32_TIM8_CHANNELS 6
#define STM32_HAS_TIM15 TRUE
#define STM32_TIM15_IS_32BITS FALSE
#define STM32_TIM15_CHANNELS 2
#define STM32_HAS_TIM16 TRUE
#define STM32_TIM16_IS_32BITS FALSE
#define STM32_TIM16_CHANNELS 1
#define STM32_HAS_TIM17 TRUE
#define STM32_TIM17_IS_32BITS FALSE
#define STM32_TIM17_CHANNELS 1
#define STM32_HAS_TIM5 FALSE
#define STM32_HAS_TIM9 FALSE
#define STM32_HAS_TIM10 FALSE
#define STM32_HAS_TIM11 FALSE
#define STM32_HAS_TIM12 FALSE
#define STM32_HAS_TIM13 FALSE
#define STM32_HAS_TIM14 FALSE
#define STM32_HAS_TIM18 FALSE
#define STM32_HAS_TIM19 FALSE
#define STM32_HAS_TIM20 FALSE
#define STM32_HAS_TIM21 FALSE
#define STM32_HAS_TIM22 FALSE
#define STM32_HAS_USART1 TRUE
#define STM32_UART_USART1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_UART_USART1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4)
#define STM32_HAS_USART2 TRUE
#define STM32_UART_USART2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
#define STM32_UART_USART2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 7)
#define STM32_HAS_USART3 TRUE
#define STM32_UART_USART3_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 3)
#define STM32_UART_USART3_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
#define STM32_HAS_UART4 TRUE
#define STM32_UART_UART4_RX_DMA_STREAM STM32_DMA_STREAM_ID(2, 3)
#define STM32_UART_UART4_TX_DMA_STREAM STM32_DMA_STREAM_ID(2, 5)
#define STM32_HAS_UART5 TRUE
#define STM32_HAS_USART6 FALSE
#define STM32_HAS_UART7 FALSE
#define STM32_HAS_UART8 FALSE
#define STM32_HAS_LPUART1 FALSE
#define STM32_HAS_USB TRUE
#define STM32_USB_ACCESS_SCHEME_2x16 FALSE
#define STM32_USB_PMA_SIZE 512
#define STM32_USB_HAS_BCDR FALSE
#define STM32_HAS_OTG1 FALSE
#define STM32_HAS_OTG2 FALSE
#define STM32_HAS_IWDG TRUE
#define STM32_IWDG_IS_WINDOWED TRUE
#define STM32_HAS_LTDC FALSE
#define STM32_HAS_DMA2D FALSE
#define STM32_HAS_FSMC FALSE
#define STM32_HAS_CRC TRUE
#define STM32_CRC_PROGRAMMABLE TRUE
Functions
void halInit (void)
HAL initialization.
static void hal_lld_backup_domain_init (void)
Initializes the backup domain.
void hal_lld_init (void)
Low level HAL driver initialization.
void stm32_clock_init (void)
STM32 clocks and PLL initialization.
Variables
uint32_t SystemCoreClock = STM32_HCLK
CMSIS system core clock variable.
Macro Definition Documentation
_CHIBIOS_HAL_
#define _CHIBIOS_HAL_
ChibiOS/HAL identification macro.
Definition at line 176 of file hal.h.
CH_HAL_STABLE
#define CH_HAL_STABLE 1
Stable release flag.
Definition at line 181 of file hal.h.
HAL_VERSION
#define HAL_VERSION "6.1.0"
HAL version string.
Definition at line 190 of file hal.h.
CH_HAL_MAJOR
#define CH_HAL_MAJOR 6
HAL version major number.
Definition at line 195 of file hal.h.
CH_HAL_MINOR
#define CH_HAL_MINOR 1
HAL version minor number.
Definition at line 200 of file hal.h.
CH_HAL_PATCH
#define CH_HAL_PATCH 0
HAL version patch number.
Definition at line 205 of file hal.h.
STM32_SYSCLK_MAX
#define STM32_SYSCLK_MAX 72000000
Maximum system clock frequency.
Definition at line 108 of file hal_lld.h.
STM32_HSECLK_MAX
#define STM32_HSECLK_MAX 32000000
Maximum HSE clock frequency.
Definition at line 113 of file hal_lld.h.
STM32_HSECLK_MIN
#define STM32_HSECLK_MIN 1000000
Minimum HSE clock frequency.
Definition at line 118 of file hal_lld.h.
STM32_LSECLK_MAX
#define STM32_LSECLK_MAX 1000000
Maximum LSE clock frequency.
Definition at line 123 of file hal_lld.h.
STM32_LSECLK_MIN
#define STM32_LSECLK_MIN 32768
Minimum LSE clock frequency.
Definition at line 128 of file hal_lld.h.
STM32_PLLIN_MAX
#define STM32_PLLIN_MAX 24000000
Maximum PLLs input clock frequency.
Definition at line 133 of file hal_lld.h.
STM32_PLLIN_MIN
#define STM32_PLLIN_MIN 1000000
Minimum PLLs input clock frequency.
Definition at line 138 of file hal_lld.h.
STM32_PLLOUT_MAX
#define STM32_PLLOUT_MAX 72000000
Maximum PLL output clock frequency.
Definition at line 143 of file hal_lld.h.
STM32_PLLOUT_MIN
#define STM32_PLLOUT_MIN 16000000
Minimum PLL output clock frequency.
Definition at line 148 of file hal_lld.h.
STM32_PCLK1_MAX
#define STM32_PCLK1_MAX 36000000
Maximum APB1 clock frequency.
Definition at line 153 of file hal_lld.h.
STM32_PCLK2_MAX
#define STM32_PCLK2_MAX 72000000
Maximum APB2 clock frequency.
Definition at line 158 of file hal_lld.h.
STM32_ADCCLK_MAX
#define STM32_ADCCLK_MAX 72000000
Maximum ADC clock frequency.
Definition at line 163 of file hal_lld.h.
STM32_HSICLK
#define STM32_HSICLK 8000000
High speed internal clock.
Definition at line 170 of file hal_lld.h.
STM32_LSICLK
#define STM32_LSICLK 40000
Low speed internal clock.
Definition at line 171 of file hal_lld.h.
STM32_PLS_MASK
#define STM32_PLS_MASK (7 << 5)
PLS bits mask.
Definition at line 178 of file hal_lld.h.
STM32_PLS_LEV0
#define STM32_PLS_LEV0 (0 << 5)
PVD level 0.
Definition at line 179 of file hal_lld.h.
STM32_PLS_LEV1
#define STM32_PLS_LEV1 (1 << 5)
PVD level 1.
Definition at line 180 of file hal_lld.h.
STM32_PLS_LEV2
#define STM32_PLS_LEV2 (2 << 5)
PVD level 2.
Definition at line 181 of file hal_lld.h.
STM32_PLS_LEV3
#define STM32_PLS_LEV3 (3 << 5)
PVD level 3.
Definition at line 182 of file hal_lld.h.
STM32_PLS_LEV4
#define STM32_PLS_LEV4 (4 << 5)
PVD level 4.
Definition at line 183 of file hal_lld.h.
STM32_PLS_LEV5
#define STM32_PLS_LEV5 (5 << 5)
PVD level 5.
Definition at line 184 of file hal_lld.h.
STM32_PLS_LEV6
#define STM32_PLS_LEV6 (6 << 5)
PVD level 6.
Definition at line 185 of file hal_lld.h.
STM32_PLS_LEV7
#define STM32_PLS_LEV7 (7 << 5)
PVD level 7.
Definition at line 186 of file hal_lld.h.
STM32_SW_HSI
#define STM32_SW_HSI (0 << 0)
SYSCLK source is HSI.
Definition at line 193 of file hal_lld.h.
STM32_SW_HSE
#define STM32_SW_HSE (1 << 0)
SYSCLK source is HSE.
Definition at line 194 of file hal_lld.h.
STM32_SW_PLL
#define STM32_SW_PLL (2 << 0)
SYSCLK source is PLL.
Definition at line 195 of file hal_lld.h.
STM32_HPRE_DIV1
#define STM32_HPRE_DIV1 (0 << 4)
SYSCLK divided by 1.
Definition at line 197 of file hal_lld.h.
STM32_HPRE_DIV2
#define STM32_HPRE_DIV2 (8 << 4)
SYSCLK divided by 2.
Definition at line 198 of file hal_lld.h.
STM32_HPRE_DIV4
#define STM32_HPRE_DIV4 (9 << 4)
SYSCLK divided by 4.
Definition at line 199 of file hal_lld.h.
STM32_HPRE_DIV8
#define STM32_HPRE_DIV8 (10 << 4)
SYSCLK divided by 8.
Definition at line 200 of file hal_lld.h.
STM32_HPRE_DIV16
#define STM32_HPRE_DIV16 (11 << 4)
SYSCLK divided by 16.
Definition at line 201 of file hal_lld.h.
STM32_HPRE_DIV64
#define STM32_HPRE_DIV64 (12 << 4)
SYSCLK divided by 64.
Definition at line 202 of file hal_lld.h.
STM32_HPRE_DIV128
#define STM32_HPRE_DIV128 (13 << 4)
SYSCLK divided by 128.
Definition at line 203 of file hal_lld.h.
STM32_HPRE_DIV256
#define STM32_HPRE_DIV256 (14 << 4)
SYSCLK divided by 256.
Definition at line 204 of file hal_lld.h.
STM32_HPRE_DIV512
#define STM32_HPRE_DIV512 (15 << 4)
SYSCLK divided by 512.
Definition at line 205 of file hal_lld.h.
STM32_PPRE1_DIV1
#define STM32_PPRE1_DIV1 (0 << 8)
HCLK divided by 1.
Definition at line 207 of file hal_lld.h.
STM32_PPRE1_DIV2
#define STM32_PPRE1_DIV2 (4 << 8)
HCLK divided by 2.
Definition at line 208 of file hal_lld.h.
STM32_PPRE1_DIV4
#define STM32_PPRE1_DIV4 (5 << 8)
HCLK divided by 4.
Definition at line 209 of file hal_lld.h.
STM32_PPRE1_DIV8
#define STM32_PPRE1_DIV8 (6 << 8)
HCLK divided by 8.
Definition at line 210 of file hal_lld.h.
STM32_PPRE1_DIV16
#define STM32_PPRE1_DIV16 (7 << 8)
HCLK divided by 16.
Definition at line 211 of file hal_lld.h.
STM32_PPRE2_DIV1
#define STM32_PPRE2_DIV1 (0 << 11)
HCLK divided by 1.
Definition at line 213 of file hal_lld.h.
STM32_PPRE2_DIV2
#define STM32_PPRE2_DIV2 (4 << 11)
HCLK divided by 2.
Definition at line 214 of file hal_lld.h.
STM32_PPRE2_DIV4
#define STM32_PPRE2_DIV4 (5 << 11)
HCLK divided by 4.
Definition at line 215 of file hal_lld.h.
STM32_PPRE2_DIV8
#define STM32_PPRE2_DIV8 (6 << 11)
HCLK divided by 8.
Definition at line 216 of file hal_lld.h.
STM32_PPRE2_DIV16
#define STM32_PPRE2_DIV16 (7 << 11)
HCLK divided by 16.
Definition at line 217 of file hal_lld.h.
STM32_PLLSRC_HSI
#define STM32_PLLSRC_HSI (0 << 16)
PLL clock source is HSI/2.
Definition at line 219 of file hal_lld.h.
STM32_PLLSRC_HSE
#define STM32_PLLSRC_HSE (1 << 16)
PLL clock source is HSE/PREDIV.
Definition at line 220 of file hal_lld.h.
STM32_USBPRE_DIV1P5
#define STM32_USBPRE_DIV1P5 (0 << 22)
USB clock is PLLCLK/1.5.
Definition at line 224 of file hal_lld.h.
STM32_USBPRE_DIV1
#define STM32_USBPRE_DIV1 (1 << 22)
USB clock is PLLCLK/1.
Definition at line 225 of file hal_lld.h.
STM32_MCOSEL_NOCLOCK
#define STM32_MCOSEL_NOCLOCK (0 << 24)
No clock on MCO pin.
Definition at line 227 of file hal_lld.h.
STM32_MCOSEL_LSI
#define STM32_MCOSEL_LSI (2 << 24)
LSI clock on MCO pin.
Definition at line 228 of file hal_lld.h.
STM32_MCOSEL_LSE
#define STM32_MCOSEL_LSE (3 << 24)
LSE clock on MCO pin.
Definition at line 229 of file hal_lld.h.
STM32_MCOSEL_SYSCLK
#define STM32_MCOSEL_SYSCLK (4 << 24)
SYSCLK on MCO pin.
Definition at line 230 of file hal_lld.h.
STM32_MCOSEL_HSI
#define STM32_MCOSEL_HSI (5 << 24)
HSI clock on MCO pin.
Definition at line 231 of file hal_lld.h.
STM32_MCOSEL_HSE
#define STM32_MCOSEL_HSE (6 << 24)
HSE clock on MCO pin.
Definition at line 232 of file hal_lld.h.
STM32_MCOSEL_PLLDIV2
#define STM32_MCOSEL_PLLDIV2 (7 << 24)
PLL/2 clock on MCO pin.
Definition at line 233 of file hal_lld.h.
STM32_RTCSEL_MASK
#define STM32_RTCSEL_MASK (3 << 8)
RTC clock source mask.
Definition at line 240 of file hal_lld.h.
Referenced by hal_lld_backup_domain_init().
STM32_RTCSEL_NOCLOCK
#define STM32_RTCSEL_NOCLOCK (0 << 8)
No clock.
Definition at line 241 of file hal_lld.h.
STM32_RTCSEL_LSE
#define STM32_RTCSEL_LSE (1 << 8)
LSE used as RTC clock.
Definition at line 242 of file hal_lld.h.
STM32_RTCSEL_LSI
#define STM32_RTCSEL_LSI (2 << 8)
LSI used as RTC clock.
Definition at line 243 of file hal_lld.h.
STM32_RTCSEL_HSEDIV
#define STM32_RTCSEL_HSEDIV (3 << 8)
HSE divided by 32 used as RTC clock.
Definition at line 244 of file hal_lld.h.
STM32_PREDIV_MASK
#define STM32_PREDIV_MASK (15 << 0)
PREDIV divisor mask.
Definition at line 253 of file hal_lld.h.
STM32_ADC12PRES_MASK
#define STM32_ADC12PRES_MASK (31 << 4)
ADC12 clock source mask.
Definition at line 254 of file hal_lld.h.
STM32_ADC12PRES_NOCLOCK
#define STM32_ADC12PRES_NOCLOCK (0 << 4)
ADC12 clock is disabled.
Definition at line 255 of file hal_lld.h.
STM32_ADC12PRES_DIV1
#define STM32_ADC12PRES_DIV1 (16 << 4)
ADC12 clock is PLL/1.
Definition at line 256 of file hal_lld.h.
STM32_ADC12PRES_DIV2
#define STM32_ADC12PRES_DIV2 (17 << 4)
ADC12 clock is PLL/2.
Definition at line 257 of file hal_lld.h.
STM32_ADC12PRES_DIV4
#define STM32_ADC12PRES_DIV4 (18 << 4)
ADC12 clock is PLL/4.
Definition at line 258 of file hal_lld.h.
STM32_ADC12PRES_DIV6
#define STM32_ADC12PRES_DIV6 (19 << 4)
ADC12 clock is PLL/6.
Definition at line 259 of file hal_lld.h.
STM32_ADC12PRES_DIV8
#define STM32_ADC12PRES_DIV8 (20 << 4)
ADC12 clock is PLL/8.
Definition at line 260 of file hal_lld.h.
STM32_ADC12PRES_DIV10
#define STM32_ADC12PRES_DIV10 (21 << 4)
ADC12 clock is PLL/10.
Definition at line 261 of file hal_lld.h.
STM32_ADC12PRES_DIV12
#define STM32_ADC12PRES_DIV12 (22 << 4)
ADC12 clock is PLL/12.
Definition at line 262 of file hal_lld.h.
STM32_ADC12PRES_DIV16
#define STM32_ADC12PRES_DIV16 (23 << 4)
ADC12 clock is PLL/16.
Definition at line 263 of file hal_lld.h.
STM32_ADC12PRES_DIV32
#define STM32_ADC12PRES_DIV32 (24 << 4)
ADC12 clock is PLL/32.
Definition at line 264 of file hal_lld.h.
STM32_ADC12PRES_DIV64
#define STM32_ADC12PRES_DIV64 (25 << 4)
ADC12 clock is PLL/64.
Definition at line 265 of file hal_lld.h.
STM32_ADC12PRES_DIV128
#define STM32_ADC12PRES_DIV128 (26 << 4)
ADC12 clock is PLL/128.
Definition at line 266 of file hal_lld.h.
STM32_ADC12PRES_DIV256
#define STM32_ADC12PRES_DIV256 (27 << 4)
ADC12 clock is PLL/256.
Definition at line 267 of file hal_lld.h.
STM32_ADC34PRES_MASK
#define STM32_ADC34PRES_MASK (31 << 9)
ADC34 clock source mask.
Definition at line 268 of file hal_lld.h.
STM32_ADC34PRES_NOCLOCK
#define STM32_ADC34PRES_NOCLOCK (0 << 9)
ADC34 clock is disabled.
Definition at line 269 of file hal_lld.h.
STM32_ADC34PRES_DIV1
#define STM32_ADC34PRES_DIV1 (16 << 9)
ADC34 clock is PLL/1.
Definition at line 270 of file hal_lld.h.
STM32_ADC34PRES_DIV2
#define STM32_ADC34PRES_DIV2 (17 << 9)
ADC34 clock is PLL/2.
Definition at line 271 of file hal_lld.h.
STM32_ADC34PRES_DIV4
#define STM32_ADC34PRES_DIV4 (18 << 9)
ADC34 clock is PLL/4.
Definition at line 272 of file hal_lld.h.
STM32_ADC34PRES_DIV6
#define STM32_ADC34PRES_DIV6 (19 << 9)
ADC34 clock is PLL/6.
Definition at line 273 of file hal_lld.h.
STM32_ADC34PRES_DIV8
#define STM32_ADC34PRES_DIV8 (20 << 9)
ADC34 clock is PLL/8.
Definition at line 274 of file hal_lld.h.
STM32_ADC34PRES_DIV10
#define STM32_ADC34PRES_DIV10 (21 << 9)
ADC34 clock is PLL/10.
Definition at line 275 of file hal_lld.h.
STM32_ADC34PRES_DIV12
#define STM32_ADC34PRES_DIV12 (22 << 9)
ADC34 clock is PLL/12.
Definition at line 276 of file hal_lld.h.
STM32_ADC34PRES_DIV16
#define STM32_ADC34PRES_DIV16 (23 << 9)
ADC34 clock is PLL/16.
Definition at line 277 of file hal_lld.h.
STM32_ADC34PRES_DIV32
#define STM32_ADC34PRES_DIV32 (24 << 9)
ADC34 clock is PLL/32.
Definition at line 278 of file hal_lld.h.
STM32_ADC34PRES_DIV64
#define STM32_ADC34PRES_DIV64 (25 << 9)
ADC34 clock is PLL/64.
Definition at line 279 of file hal_lld.h.
STM32_ADC34PRES_DIV128
#define STM32_ADC34PRES_DIV128 (26 << 9)
ADC34 clock is PLL/128.
Definition at line 280 of file hal_lld.h.
STM32_ADC34PRES_DIV256
#define STM32_ADC34PRES_DIV256 (27 << 9)
ADC34 clock is PLL/256.
Definition at line 281 of file hal_lld.h.
STM32_USART1SW_MASK
#define STM32_USART1SW_MASK (3 << 0)
USART1 clock source mask.
Definition at line 288 of file hal_lld.h.
STM32_USART1SW_PCLK
#define STM32_USART1SW_PCLK (0 << 0)
USART1 clock is PCLK.
Definition at line 289 of file hal_lld.h.
STM32_USART1SW_SYSCLK
#define STM32_USART1SW_SYSCLK (1 << 0)
USART1 clock is SYSCLK.
Definition at line 290 of file hal_lld.h.
STM32_USART1SW_LSE
#define STM32_USART1SW_LSE (2 << 0)
USART1 clock is LSE.
Definition at line 291 of file hal_lld.h.
STM32_USART1SW_HSI
#define STM32_USART1SW_HSI (3 << 0)
USART1 clock is HSI.
Definition at line 292 of file hal_lld.h.
STM32_I2C1SW_MASK
#define STM32_I2C1SW_MASK (1 << 4)
I2C1 clock source mask.
Definition at line 293 of file hal_lld.h.
STM32_I2C1SW_HSI
#define STM32_I2C1SW_HSI (0 << 4)
I2C1 clock is HSI.
Definition at line 294 of file hal_lld.h.
STM32_I2C1SW_SYSCLK
#define STM32_I2C1SW_SYSCLK (1 << 4)
I2C1 clock is SYSCLK.
Definition at line 295 of file hal_lld.h.
STM32_I2C2SW_MASK
#define STM32_I2C2SW_MASK (1 << 5)
I2C2 clock source mask.
Definition at line 296 of file hal_lld.h.
STM32_I2C2SW_HSI
#define STM32_I2C2SW_HSI (0 << 5)
I2C2 clock is HSI.
Definition at line 297 of file hal_lld.h.
STM32_I2C2SW_SYSCLK
#define STM32_I2C2SW_SYSCLK (1 << 5)
I2C2 clock is SYSCLK.
Definition at line 298 of file hal_lld.h.
STM32_TIM1SW_MASK
#define STM32_TIM1SW_MASK (1 << 8)
TIM1 clock source mask.
Definition at line 299 of file hal_lld.h.
STM32_TIM1SW_PCLK2
#define STM32_TIM1SW_PCLK2 (0 << 8)
TIM1 clock is PCLK2.
Definition at line 300 of file hal_lld.h.
STM32_TIM1SW_PLLX2
#define STM32_TIM1SW_PLLX2 (1 << 8)
TIM1 clock is PLL*2.
Definition at line 301 of file hal_lld.h.
STM32_TIM8SW_MASK
#define STM32_TIM8SW_MASK (1 << 9)
TIM8 clock source mask.
Definition at line 302 of file hal_lld.h.
STM32_TIM8SW_PCLK2
#define STM32_TIM8SW_PCLK2 (0 << 9)
TIM8 clock is PCLK2.
Definition at line 303 of file hal_lld.h.
STM32_TIM8SW_PLLX2
#define STM32_TIM8SW_PLLX2 (1 << 9)
TIM8 clock is PLL*2.
Definition at line 304 of file hal_lld.h.
STM32_HRTIM1SW_MASK
#define STM32_HRTIM1SW_MASK (1 << 12)
HRTIM1 clock source mask.
Definition at line 305 of file hal_lld.h.
STM32_HRTIM1SW_PCLK2
#define STM32_HRTIM1SW_PCLK2 (0 << 12)
HRTIM1 clock is PCLK2.
Definition at line 306 of file hal_lld.h.
STM32_HRTIM1SW_PLLX2
#define STM32_HRTIM1SW_PLLX2 (1 << 12)
HRTIM1 clock is PLL*2.
Definition at line 307 of file hal_lld.h.
STM32_USART2SW_MASK
#define STM32_USART2SW_MASK (3 << 16)
USART2 clock source mask.
Definition at line 308 of file hal_lld.h.
STM32_USART2SW_PCLK
#define STM32_USART2SW_PCLK (0 << 16)
USART2 clock is PCLK.
Definition at line 309 of file hal_lld.h.
STM32_USART2SW_SYSCLK
#define STM32_USART2SW_SYSCLK (1 << 16)
USART2 clock is SYSCLK.
Definition at line 310 of file hal_lld.h.
STM32_USART2SW_LSE
#define STM32_USART2SW_LSE (2 << 16)
USART2 clock is LSE.
Definition at line 311 of file hal_lld.h.
STM32_USART2SW_HSI
#define STM32_USART2SW_HSI (3 << 16)
USART2 clock is HSI.
Definition at line 312 of file hal_lld.h.
STM32_USART3SW_MASK
#define STM32_USART3SW_MASK (3 << 18)
USART3 clock source mask.
Definition at line 313 of file hal_lld.h.
STM32_USART3SW_PCLK
#define STM32_USART3SW_PCLK (0 << 18)
USART3 clock is PCLK.
Definition at line 314 of file hal_lld.h.
STM32_USART3SW_SYSCLK
#define STM32_USART3SW_SYSCLK (1 << 18)
USART3 clock is SYSCLK.
Definition at line 315 of file hal_lld.h.
STM32_USART3SW_LSE
#define STM32_USART3SW_LSE (2 << 18)
USART3 clock is LSE.
Definition at line 316 of file hal_lld.h.
STM32_USART3SW_HSI
#define STM32_USART3SW_HSI (3 << 18)
USART3 clock is HSI.
Definition at line 317 of file hal_lld.h.
STM32_UART4SW_MASK
#define STM32_UART4SW_MASK (3 << 20)
USART4 clock source mask.
Definition at line 318 of file hal_lld.h.
STM32_UART4SW_PCLK
#define STM32_UART4SW_PCLK (0 << 20)
USART4 clock is PCLK.
Definition at line 319 of file hal_lld.h.
STM32_UART4SW_SYSCLK
#define STM32_UART4SW_SYSCLK (1 << 20)
USART4 clock is SYSCLK.
Definition at line 320 of file hal_lld.h.
STM32_UART4SW_LSE
#define STM32_UART4SW_LSE (2 << 20)
USART4 clock is LSE.
Definition at line 321 of file hal_lld.h.
STM32_UART4SW_HSI
#define STM32_UART4SW_HSI (3 << 20)
USART4 clock is HSI.
Definition at line 322 of file hal_lld.h.
STM32_UART5SW_MASK
#define STM32_UART5SW_MASK (3 << 22)
USART5 clock source mask.
Definition at line 323 of file hal_lld.h.
STM32_UART5SW_PCLK
#define STM32_UART5SW_PCLK (0 << 22)
USART5 clock is PCLK.
Definition at line 324 of file hal_lld.h.
STM32_UART5SW_SYSCLK
#define STM32_UART5SW_SYSCLK (1 << 22)
USART5 clock is SYSCLK.
Definition at line 325 of file hal_lld.h.
STM32_UART5SW_LSE
#define STM32_UART5SW_LSE (2 << 22)
USART5 clock is LSE.
Definition at line 326 of file hal_lld.h.
STM32_UART5SW_HSI
#define STM32_UART5SW_HSI (3 << 22)
USART5 clock is HSI.
Definition at line 327 of file hal_lld.h.
STM32_NO_INIT
#define STM32_NO_INIT FALSE
Disables the PWR/RCC initialization in the HAL.
Definition at line 342 of file hal_lld.h.
STM32_PVD_ENABLE
#define STM32_PVD_ENABLE FALSE
Enables or disables the programmable voltage detector.
Definition at line 349 of file hal_lld.h.
STM32_PLS
#define STM32_PLS STM32_PLS_LEV0
Sets voltage level for programmable voltage detector.
Definition at line 356 of file hal_lld.h.
STM32_HSI_ENABLED
#define STM32_HSI_ENABLED TRUE
Enables or disables the HSI clock source.
Definition at line 363 of file hal_lld.h.
STM32_LSI_ENABLED
#define STM32_LSI_ENABLED TRUE
Enables or disables the LSI clock source.
Definition at line 370 of file hal_lld.h.
STM32_HSE_ENABLED
#define STM32_HSE_ENABLED TRUE
Enables or disables the HSE clock source.
Definition at line 377 of file hal_lld.h.
STM32_LSE_ENABLED
#define STM32_LSE_ENABLED FALSE
Enables or disables the LSE clock source.
Definition at line 384 of file hal_lld.h.
STM32_SW
#define STM32_SW STM32_SW_PLL
Main clock source selection.
Note
If the selected clock source is not the PLL then the PLL is not initialized and started.
The default value is calculated for a 72MHz system clock from a 8MHz crystal using the PLL.
Definition at line 395 of file hal_lld.h.
STM32_PLLSRC
#define STM32_PLLSRC STM32_PLLSRC_HSE
Clock source for the PLL.
Note
This setting has only effect if the PLL is selected as the system clock source.
The default value is calculated for a 72MHz system clock from a 8MHz crystal using the PLL.
Definition at line 406 of file hal_lld.h.
Referenced by stm32_clock_init().
STM32_PREDIV_VALUE
#define STM32_PREDIV_VALUE 1
Crystal PLL pre-divider.
Note
This setting has only effect if the PLL is selected as the system clock source.
The default value is calculated for a 72MHz system clock from a 8MHz crystal using the PLL.
Definition at line 417 of file hal_lld.h.
STM32_PLLMUL_VALUE
#define STM32_PLLMUL_VALUE 9
PLL multiplier value.
Note
The allowed range is 2...16.
The default value is calculated for a 72MHz system clock from a 8MHz crystal using the PLL.
Definition at line 427 of file hal_lld.h.
STM32_HPRE
#define STM32_HPRE STM32_HPRE_DIV1
AHB prescaler value.
Note
The default value is calculated for a 72MHz system clock from a 8MHz crystal using the PLL.
Definition at line 436 of file hal_lld.h.
Referenced by stm32_clock_init().
STM32_PPRE1
#define STM32_PPRE1 STM32_PPRE1_DIV2
APB1 prescaler value.
Definition at line 443 of file hal_lld.h.
Referenced by stm32_clock_init().
STM32_PPRE2
#define STM32_PPRE2 STM32_PPRE2_DIV2
APB2 prescaler value.
Definition at line 450 of file hal_lld.h.
Referenced by stm32_clock_init().
STM32_MCOSEL
#define STM32_MCOSEL STM32_MCOSEL_NOCLOCK
MCO pin setting.
Definition at line 457 of file hal_lld.h.
Referenced by stm32_clock_init().
STM32_ADC12PRES
#define STM32_ADC12PRES STM32_ADC12PRES_DIV1
ADC12 prescaler value.
Definition at line 464 of file hal_lld.h.
Referenced by stm32_clock_init().
STM32_ADC34PRES
#define STM32_ADC34PRES STM32_ADC34PRES_DIV1
ADC34 prescaler value.
Definition at line 471 of file hal_lld.h.
Referenced by stm32_clock_init().
STM32_USART1SW
#define STM32_USART1SW STM32_USART1SW_PCLK
USART1 clock source.
Definition at line 478 of file hal_lld.h.
STM32_USART2SW
#define STM32_USART2SW STM32_USART2SW_PCLK
USART2 clock source.
Definition at line 485 of file hal_lld.h.
STM32_USART3SW
#define STM32_USART3SW STM32_USART3SW_PCLK
USART3 clock source.
Definition at line 492 of file hal_lld.h.
STM32_UART4SW
#define STM32_UART4SW STM32_UART4SW_PCLK
UART4 clock source.
Definition at line 499 of file hal_lld.h.
STM32_UART5SW
#define STM32_UART5SW STM32_UART5SW_PCLK
UART5 clock source.
Definition at line 506 of file hal_lld.h.
STM32_I2C1SW
#define STM32_I2C1SW STM32_I2C1SW_SYSCLK
I2C1 clock source.
Definition at line 513 of file hal_lld.h.
STM32_I2C2SW
#define STM32_I2C2SW STM32_I2C2SW_SYSCLK
I2C2 clock source.
Definition at line 520 of file hal_lld.h.
STM32_TIM1SW
#define STM32_TIM1SW STM32_TIM1SW_PCLK2
TIM1 clock source.
Definition at line 527 of file hal_lld.h.
STM32_TIM8SW
#define STM32_TIM8SW STM32_TIM8SW_PCLK2
TIM8 clock source.
Definition at line 534 of file hal_lld.h.
STM32_HRTIM1SW
#define STM32_HRTIM1SW STM32_HRTIM1SW_PCLK2
HRTIM1 clock source.
Definition at line 541 of file hal_lld.h.
STM32_RTCSEL
#define STM32_RTCSEL STM32_RTCSEL_LSI
RTC clock source.
Definition at line 548 of file hal_lld.h.
Referenced by hal_lld_backup_domain_init().
STM32_USB_CLOCK_REQUIRED
#define STM32_USB_CLOCK_REQUIRED TRUE
USB clock setting.
Definition at line 555 of file hal_lld.h.
STM32_USBPRE
#define STM32_USBPRE STM32_USBPRE_DIV1P5
USB prescaler initialization.
Definition at line 562 of file hal_lld.h.
Referenced by stm32_clock_init().
STM32_ACTIVATE_PLL
#define STM32_ACTIVATE_PLL TRUE
PLL activation flag.
Definition at line 733 of file hal_lld.h.
STM32_PLLMUL
#define STM32_PLLMUL ((STM32_PLLMUL_VALUE - 2) << 18)
PLLMUL field.
Definition at line 750 of file hal_lld.h.
Referenced by stm32_clock_init().
STM32_PLLCLKIN
#define STM32_PLLCLKIN (STM32_HSECLK / STM32_PREDIV_VALUE)
PLL input clock frequency.
Definition at line 759 of file hal_lld.h.
STM32_PLLCLKOUT
#define STM32_PLLCLKOUT (STM32_PLLCLKIN * STM32_PLLMUL_VALUE)
PLL output clock frequency.
Definition at line 774 of file hal_lld.h.
STM32_SYSCLK
#define STM32_SYSCLK STM32_PLLCLKOUT
System clock source.
Definition at line 785 of file hal_lld.h.
STM32_HCLK
#define STM32_HCLK (STM32_SYSCLK / 1)
AHB frequency.
Definition at line 803 of file hal_lld.h.
Referenced by adc_lld_vreg_on().
STM32_PCLK1
#define STM32_PCLK1 (STM32_HCLK / 1)
APB1 frequency.
Definition at line 833 of file hal_lld.h.
STM32_PCLK2
#define STM32_PCLK2 (STM32_HCLK / 1)
APB2 frequency.
Definition at line 855 of file hal_lld.h.
STM32_RTCCLK
#define STM32_RTCCLK STM32_LSECLK
RTC clock.
Definition at line 877 of file hal_lld.h.
STM32_ADC12CLK
#define STM32_ADC12CLK 0
ADC12 frequency.
Definition at line 892 of file hal_lld.h.
STM32_ADC34CLK
#define STM32_ADC34CLK 0
ADC34 frequency.
Definition at line 925 of file hal_lld.h.
STM32_I2C1CLK
#define STM32_I2C1CLK STM32_SYSCLK
I2C1 frequency.
Definition at line 970 of file hal_lld.h.
STM32_I2C2CLK
#define STM32_I2C2CLK STM32_SYSCLK
I2C2 frequency.
Definition at line 981 of file hal_lld.h.
STM32_USART1CLK
#define STM32_USART1CLK STM32_PCLK2
USART1 frequency.
Definition at line 990 of file hal_lld.h.
Referenced by uart_lld_init().
STM32_USART2CLK
#define STM32_USART2CLK STM32_PCLK1
USART2 frequency.
Definition at line 1005 of file hal_lld.h.
STM32_USART3CLK
#define STM32_USART3CLK STM32_PCLK1
USART3 frequency.
Definition at line 1020 of file hal_lld.h.
STM32_UART4CLK
#define STM32_UART4CLK STM32_PCLK1
UART4 frequency.
Definition at line 1035 of file hal_lld.h.
STM32_UART5CLK
#define STM32_UART5CLK STM32_PCLK1
UART5 frequency.
Definition at line 1050 of file hal_lld.h.
STM32_TIM1CLK
#define STM32_TIM1CLK (STM32_PCLK2 * 2)
TIM1 frequency.
Definition at line 1068 of file hal_lld.h.
STM32_TIM8CLK
#define STM32_TIM8CLK (STM32_PCLK2 * 2)
TIM8 frequency.
Definition at line 1090 of file hal_lld.h.
STM32_HRTIM1CLK
#define STM32_HRTIM1CLK (STM32_PCLK2 * 2)
HRTIM1 frequency.
Definition at line 1112 of file hal_lld.h.
STM32_TIMCLK1
#define STM32_TIMCLK1 (STM32_PCLK1 * 1)
Timers 2, 3, 4, 6, 7 frequency.
Definition at line 1131 of file hal_lld.h.
STM32_TIMCLK2
#define STM32_TIMCLK2 (STM32_PCLK2 * 1)
Timers 1, 8, 15, 16, 17 frequency.
Definition at line 1140 of file hal_lld.h.
STM32_USBCLK
#define STM32_USBCLK ((STM32_PLLCLKOUT * 2) / 3)
USB frequency.
Definition at line 1149 of file hal_lld.h.
STM32_FLASHBITS
#define STM32_FLASHBITS 0x00000010
Flash settings.
Definition at line 1160 of file hal_lld.h.
STM32F3XX
#define STM32F3XX
Sub-family identifier.
Definition at line 32 of file stm32_registry.h.
Function Documentation
halInit()
void halInit (void)
HAL initialization.
This function invokes the low level initialization code then initializes all the drivers enabled in the HAL. Finally the board-specific initialization is performed by invoking boardInit() (usually defined in board.c).
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file hal.c.
References adcInit(), canInit(), cryInit(), dacInit(), extInit(), gptInit(), hal_lld_init(), i2cInit(), i2sInit(), icuInit(), macInit(), mmcInit(), osalInit(), palInit, pwmInit(), qspiInit(), rtcInit(), sdcInit(), sdInit(), sduInit(), spiInit(), stInit(), uartInit(), usbInit(), and wdgInit().
hal_lld_backup_domain_init()
static void hal_lld_backup_domain_init (void) static
Initializes the backup domain.
Note
WARNING! Changing clock source impossible without resetting of the whole BKP domain.
Definition at line 54 of file hal_lld.c.
References STM32_RTCSEL, and STM32_RTCSEL_MASK.
hal_lld_init()
void hal_lld_init (void)
Low level HAL driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 105 of file hal_lld.c.
References rccResetAHB.
Referenced by halInit().
stm32_clock_init()
void stm32_clock_init (void)
STM32 clocks and PLL initialization.
Note
All the involved constants come from the file board.h.
This function should be invoked just after the system reset.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 150 of file hal_lld.c.
References STM32_ADC12PRES, STM32_ADC34PRES, STM32_HPRE, STM32_MCOSEL, STM32_PLLMUL, STM32_PLLSRC, STM32_PPRE1, STM32_PPRE2, and STM32_USBPRE.
Variable Documentation
SystemCoreClock
uint32_t SystemCoreClock = STM32_HCLK
CMSIS system core clock variable.
Note
It is declared in system_stm32f3xx.h.
Definition at line 39 of file hal_lld.c.