ChibiOS/EX: HTS221
HTS221
EX » Devices » STMicroelectronics Devices
Detailed Description
Macros
#define hts221HygrometerGetAxesNumber(devp) hygrometerGetAxesNumber(&((devp)->hygro_if))
Return the number of axes of the BaseHygrometer.
#define hts221HygrometerReadRaw(devp, axes) hygrometerReadRaw(&((devp)->hygro_if), axes)
Retrieves raw data from the BaseHygrometer.
#define hts221HygrometerReadCooked(devp, axes) hygrometerReadCooked(&((devp)->hygro_if), axes)
Retrieves cooked data from the BaseHygrometer.
#define hts221HygrometerSetBias(devp, bp) hygrometerSetBias(&((devp)->hygro_if), bp)
Set bias values for the BaseHygrometer.
#define hts221HygrometerResetBias(devp) hygrometerResetBias(&((devp)->hygro_if))
Reset bias values for the BaseHygrometer.
#define hts221HygrometerSetSensitivity(devp, sp) hygrometerSetSensitivity(&((devp)->hygro_if), sp)
Set sensitivity values for the BaseHygrometer.
#define hts221HygrometerResetSensitivity(devp) hygrometerResetSensitivity(&((devp)->hygro_if))
Reset sensitivity values for the BaseHygrometer.
#define hts221ThermometerGetAxesNumber(devp) thermometerGetAxesNumber(&((devp)->thermo_if))
Return the number of axes of the BaseThermometer.
#define hts221ThermometerReadRaw(devp, axes) thermometerReadRaw(&((devp)->thermo_if), axes)
Retrieves raw data from the BaseThermometer.
#define hts221ThermometerReadCooked(devp, axes) thermometerReadCooked(&((devp)->thermo_if), axes)
Retrieves cooked data from the BaseThermometer.
#define hts221ThermometerSetBias(devp, bp) thermometerSetBias(&((devp)->thermo_if), bp)
Set bias values for the BaseThermometer.
#define hts221ThermometerResetBias(devp) thermometerResetBias(&((devp)->thermo_if))
Reset bias values for the BaseThermometer.
#define hts221ThermometerSetSensitivity(devp, sp) thermometerSetSensitivity(&((devp)->thermo_if), sp)
Set sensitivity values for the BaseThermometer.
#define hts221ThermometerResetSensitivity(devp) thermometerResetSensitivity(&((devp)->thermo_if))
Reset sensitivity values for the BaseThermometer.
HTS221 data structures and types.
enum hts221_odr_t { HTS221_ODR_ONE_SHOT = 0x00 , HTS221_ODR_1HZ = 0x01 , HTS221_ODR_7HZ = 0x02 , HTS221_ODR_12P5HZ = 0x03 }
HTS221 output data rate and bandwidth.
enum hts221_avgh_t {
HTS221_AVGH_4 = 0x00 , HTS221_AVGH_8 = 0x01 , HTS221_AVGH_16 = 0x02 , HTS221_AVGH_32 = 0x03 ,
HTS221_AVGH_64 = 0x04 , HTS221_AVGH_128 = 0x05 , HTS221_AVGH_256 = 0x06 , HTS221_AVGH_512 = 0x07
}
HTS221 humidity resolution.
enum hts221_avgt_t {
HTS221_AVGT_2 = 0x00 , HTS221_AVGT_4 = 0x08 , HTS221_AVGT_8 = 0x10 , HTS221_AVGT_16 = 0x18 ,
HTS221_AVGT_32 = 0x20 , HTS221_AVGT_64 = 0x28 , HTS221_AVGT_128 = 0x30 , HTS221_AVGT_256 = 0x38
}
HTS221 temperature resolution.
enum hts221_bdu_t { HTS221_BDU_CONTINUOUS = 0x00 , HTS221_BDU_BLOCKED = 0x40 }
HTS221 block data update.
enum hts221_state_t { HTS221_UNINIT = 0 , HTS221_STOP = 1 , HTS221_READY = 2 }
Driver state machine possible states.
typedef struct HTS221Driver HTS221Driver
Structure representing a HTS221 driver.
#define _hts221_methods_alone
HTS221 specific methods.
#define _hts221_methods
HTS221 specific methods with inherited ones.
#define _hts221_data
HTS221Driver specific data.
Version identification
#define EX_HTS221_VERSION "1.1.2"
HTS221 driver version string.
#define EX_HTS221_MAJOR 1
HTS221 driver version major number.
#define EX_HTS221_MINOR 1
HTS221 driver version minor number.
#define EX_HTS221_PATCH 2
HTS221 driver version patch number.
#define HTS221_HYGRO_NUMBER_OF_AXES 1U
HTS221 hygrometer subsystem characteristics.
#define HTS221_THERMO_NUMBER_OF_AXES 1U
HTS221 thermometer subsystem characteristics.
HTS221 communication interfaces related bit masks
#define HTS221_DI_MASK 0xFF
#define HTS221_DI(n) (1 << n)
#define HTS221_AD_MASK 0x3F
#define HTS221_AD(n) (1 << n)
#define HTS221_MS (1 << 6)
#define HTS221_RW (1 << 7)
#define HTS221_SUB_MS (1 << 7)
#define HTS221_SAD 0x5F
HTS221 register addresses
#define HTS221_AD_WHO_AM_I 0x0F
#define HTS221_AD_AV_CONF 0x10
#define HTS221_AD_CTRL_REG1 0x20
#define HTS221_AD_CTRL_REG2 0x21
#define HTS221_AD_CTRL_REG3 0x22
#define HTS221_AD_STATUS_REG 0x27
#define HTS221_AD_HUMIDITY_OUT_L 0x28
#define HTS221_AD_HUMIDITY_OUT_H 0x29
#define HTS221_AD_TEMP_OUT_L 0x2A
#define HTS221_AD_TEMP_OUT_H 0x2B
#define HTS221_AD_CALIB_0 0x30
#define HTS221_AD_CALIB_1 0x31
#define HTS221_AD_CALIB_2 0x32
#define HTS221_AD_CALIB_3 0x33
#define HTS221_AD_CALIB_4 0x34
#define HTS221_AD_CALIB_5 0x35
#define HTS221_AD_CALIB_6 0x36
#define HTS221_AD_CALIB_7 0x37
#define HTS221_AD_CALIB_8 0x38
#define HTS221_AD_CALIB_9 0x39
#define HTS221_AD_CALIB_A 0x3A
#define HTS221_AD_CALIB_B 0x3B
#define HTS221_AD_CALIB_C 0x3C
#define HTS221_AD_CALIB_D 0x3D
#define HTS221_AD_CALIB_E 0x3E
#define HTS221_AD_CALIB_F 0x3F
HTS221_CTRL_REG1 register bits definitions
#define HTS221_CTRL_REG1_MASK 0x87
#define HTS221_CTRL_REG1_ODR0 (1 << 0)
#define HTS221_CTRL_REG1_ODR1 (1 << 1)
#define HTS221_CTRL_REG1_BDU (1 << 2)
#define HTS221_CTRL_REG1_PD (1 << 7)
HTS221_CTRL_REG2 register bits definitions
#define HTS221_CTRL_REG2_MASK 0x83
#define HTS221_CTRL_REG2_ONE_SHOT (1 << 0)
#define HTS221_CTRL_REG2_HEATER (1 << 1)
#define HTS221_CTRL_REG2_BOOT (1 << 7)
HTS221_CTRL_REG3 register bits definitions
#define HTS221_CTRL_REG3_MASK 0xC4
#define HTS221_CTRL_REG3_DRDY (1 << 2)
#define HTS221_CTRL_REG3_PP_OD (1 << 6)
#define HTS221_CTRL_REG3_INT_H_L (1 << 7)
Configuration options
#define HTS221_USE_SPI FALSE
HTS221 SPI interface switch.
#define HTS221_SHARED_SPI FALSE
HTS221 shared SPI switch.
#define HTS221_USE_I2C TRUE
HTS221 I2C interface switch.
#define HTS221_SHARED_I2C FALSE
HTS221 shared I2C switch.
#define HTS221_USE_ADVANCED FALSE
HTS221 advanced configurations switch.
Data Structures
struct HTS221Config
HTS221 configuration structure.
struct HTS221VMT
HTS221 virtual methods table.
struct HTS221Driver
HTS221 2-axis hygrometer/thermometer class.
Functions
static msg_t hts221I2CReadRegister (I2CDriver *i2cp, uint8_t reg, uint8_t *rxbuf, size_t n)
Reads registers value using I2C.
static msg_t hts221I2CWriteRegister (I2CDriver *i2cp, uint8_t *txbuf, size_t n)
Writes a value into a register using I2C.
static msg_t hts221Calibrate (HTS221Driver *devp)
Computes biases and sensitivities starting from data stored in calibration registers.
static size_t hygro_get_axes_number (void *ip)
Return the number of axes of the BaseHygrometer.
static msg_t hygro_read_raw (void *ip, int32_t axes[])
Retrieves raw data from the BaseHygrometer.
static msg_t hygro_read_cooked (void *ip, float axes[])
Retrieves cooked data from the BaseHygrometer.
static msg_t hygro_set_bias (void *ip, float *bp)
Set bias values for the BaseHygrometer.
static msg_t hygro_reset_bias (void *ip)
Reset bias values for the BaseHygrometer.
static msg_t hygro_set_sensitivity (void *ip, float *sp)
Set sensitivity values for the BaseHygrometer.
static msg_t hygro_reset_sensitivity (void *ip)
Reset sensitivity values for the BaseHygrometer.
static size_t thermo_get_axes_number (void *ip)
Return the number of axes of the BaseThermometer.
static msg_t thermo_read_raw (void *ip, int32_t axes[])
Retrieves raw data from the BaseThermometer.
static msg_t thermo_read_cooked (void *ip, float *axis)
Retrieves cooked data from the BaseThermometer.
static msg_t thermo_set_bias (void *ip, float *bp)
Set bias values for the BaseThermometer.
static msg_t thermo_reset_bias (void *ip)
Reset bias values for the BaseThermometer.
static msg_t thermo_set_sensitivity (void *ip, float *sp)
Set sensitivity values for the BaseThermometer.
static msg_t thermo_reset_sensitivity (void *ip)
Reset sensitivity values for the BaseThermometer.
void hts221ObjectInit (HTS221Driver *devp)
Initializes an instance.
void hts221Start (HTS221Driver *devp, const HTS221Config *config)
Configures and activates HTS221 Complex Driver peripheral.
void hts221Stop (HTS221Driver *devp)
Deactivates the HTS221 Complex Driver peripheral.
Macro Definition Documentation
EX_HTS221_VERSION
#define EX_HTS221_VERSION "1.1.2"
HTS221 driver version string.
Definition at line 47 of file hts221.h.
EX_HTS221_MAJOR
#define EX_HTS221_MAJOR 1
HTS221 driver version major number.
Definition at line 52 of file hts221.h.
EX_HTS221_MINOR
#define EX_HTS221_MINOR 1
HTS221 driver version minor number.
Definition at line 57 of file hts221.h.
EX_HTS221_PATCH
#define EX_HTS221_PATCH 2
HTS221 driver version patch number.
Definition at line 62 of file hts221.h.
HTS221_HYGRO_NUMBER_OF_AXES
#define HTS221_HYGRO_NUMBER_OF_AXES 1U
HTS221 hygrometer subsystem characteristics.
Note
Sensitivity is expressed as rH/LSB whereas rH stand for percentage of relative humidity.
Bias is expressed as rH.
Definition at line 72 of file hts221.h.
HTS221_THERMO_NUMBER_OF_AXES
#define HTS221_THERMO_NUMBER_OF_AXES 1U
HTS221 thermometer subsystem characteristics.
Note
Sensitivity is expressed as C/LSB.
Bias is expressed as C.
Definition at line 85 of file hts221.h.
HTS221_USE_SPI
#define HTS221_USE_SPI FALSE
HTS221 SPI interface switch.
If set to TRUE the support for SPI is included.
Note
The default is FALSE.
Definition at line 184 of file hts221.h.
HTS221_SHARED_SPI
#define HTS221_SHARED_SPI FALSE
HTS221 shared SPI switch.
If set to TRUE the device acquires SPI bus ownership on each transaction.
Note
The default is FALSE. Requires SPI_USE_MUTUAL_EXCLUSION
Definition at line 194 of file hts221.h.
HTS221_USE_I2C
#define HTS221_USE_I2C TRUE
HTS221 I2C interface switch.
If set to TRUE the support for I2C is included.
Note
The default is TRUE.
Definition at line 203 of file hts221.h.
HTS221_SHARED_I2C
#define HTS221_SHARED_I2C FALSE
HTS221 shared I2C switch.
If set to TRUE the device acquires I2C bus ownership on each transaction.
Note
The default is FALSE. Requires I2C_USE_MUTUAL_EXCLUSION
Definition at line 213 of file hts221.h.
HTS221_USE_ADVANCED
#define HTS221_USE_ADVANCED FALSE
HTS221 advanced configurations switch.
If set to TRUE more configurations are available.
Note
The default is FALSE.
Definition at line 222 of file hts221.h.
_hts221_methods_alone
#define _hts221_methods_alone
HTS221 specific methods.
Note
No methods so far, just a common ancestor interface.
Definition at line 390 of file hts221.h.
_hts221_methods
#define _hts221_methods
Value:
  _base_object_methods                                                      \
  _hts221_methods_alone
HTS221 specific methods with inherited ones.
Definition at line 395 of file hts221.h.
_hts221_data
#define _hts221_data
Value:
  /* Driver state.*/                                                        \
  hts221_state_t            state;                                          \
  /* Current configuration data.*/                                          \
  const HTS221Config        *config;                                        \
  /* Hygrometer subsystem axes number.*/                                    \
  size_t                    hygroaxes;                                      \
  /* Hygrometer subsystem current sensitivity.*/                            \
  float                     hygrosensitivity;                               \
  /* Hygrometer subsystem current bias .*/                                  \
  float                     hygrobias;                                      \
  /* Hygrometer subsystem factory sensitivity.*/                            \
  float                     hygrofactorysensitivity;                        \
  /* Hygrometer subsystem factory bias .*/                                  \
  float                     hygrofactorybias;                               \
  /* Thermometer subsystem axes number.*/                                   \
  size_t                    thermoaxes;                                     \
  /* Thermometer subsystem current sensitivity.*/                           \
  float                     thermosensitivity;                              \
  /* Thermometer subsystem current bias.*/                                  \
  float                     thermobias;                                     \
  /* Thermometer subsystem factory sensitivity.*/                           \
  float                     thermofactorysensitivity;                       \
  /* Thermometer subsystem factory bias.*/                                  \
  float                     thermofactorybias;
HTS221Driver specific data.
Definition at line 411 of file hts221.h.
hts221HygrometerGetAxesNumber
#define hts221HygrometerGetAxesNumber (devp) hygrometerGetAxesNumber(&((devp)->hygro_if))
Return the number of axes of the BaseHygrometer.
Parameters
[in] devp pointer to HTS221Driver.
Returns
the number of axes.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 464 of file hts221.h.
hts221HygrometerReadRaw
#define hts221HygrometerReadRaw (devp, axes) hygrometerReadRaw(&((devp)->hygro_if), axes)
Retrieves raw data from the BaseHygrometer.
Note
This data is retrieved from MEMS register without any algebraical manipulation.
The axes array must be at least the same size of the BaseHygrometer axes number.
Parameters
[in] devp pointer to HTS221Driver.
[out] axes a buffer which would be filled with raw data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 485 of file hts221.h.
hts221HygrometerReadCooked
#define hts221HygrometerReadCooked (devp, axes) hygrometerReadCooked(&((devp)->hygro_if), axes)
Retrieves cooked data from the BaseHygrometer.
Note
This data is manipulated according to the formula cooked = (raw * sensitivity) - bias.
Final data is expressed as rH.
The axes array must be at least the same size of the BaseHygrometer axes number.
Parameters
[in] devp pointer to HTS221Driver.
[out] axes a buffer which would be filled with cooked data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 507 of file hts221.h.
hts221HygrometerSetBias
#define hts221HygrometerSetBias (devp, bp) hygrometerSetBias(&((devp)->hygro_if), bp)
Set bias values for the BaseHygrometer.
Note
Bias must be expressed as rH.
The bias buffer must be at least the same size of the BaseHygrometer axes number.
Parameters
[in] devp pointer to HTS221Driver.
[in] bp a buffer which contains biases.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 524 of file hts221.h.
hts221HygrometerResetBias
#define hts221HygrometerResetBias (devp) hygrometerResetBias(&((devp)->hygro_if))
Reset bias values for the BaseHygrometer.
Note
Default biases value are obtained from device datasheet when available otherwise they are considered zero.
Parameters
[in] devp pointer to HTS221Driver.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 539 of file hts221.h.
hts221HygrometerSetSensitivity
#define hts221HygrometerSetSensitivity (devp, sp) hygrometerSetSensitivity(&((devp)->hygro_if), sp)
Set sensitivity values for the BaseHygrometer.
Note
Sensitivity must be expressed as rH/LSB.
The sensitivity buffer must be at least the same size of the BaseHygrometer axes number.
Parameters
[in] devp pointer to HTS221Driver.
[in] sp a buffer which contains sensitivities.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 556 of file hts221.h.
hts221HygrometerResetSensitivity
#define hts221HygrometerResetSensitivity (devp) hygrometerResetSensitivity(&((devp)->hygro_if))
Reset sensitivity values for the BaseHygrometer.
Note
Default sensitivities value are obtained from device datasheet.
Parameters
[in] devp pointer to HTS221Driver.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 570 of file hts221.h.
hts221ThermometerGetAxesNumber
#define hts221ThermometerGetAxesNumber (devp) thermometerGetAxesNumber(&((devp)->thermo_if))
Return the number of axes of the BaseThermometer.
Parameters
[in] devp pointer to HTS221Driver.
Returns
the number of axes.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 582 of file hts221.h.
hts221ThermometerReadRaw
#define hts221ThermometerReadRaw (devp, axes) thermometerReadRaw(&((devp)->thermo_if), axes)
Retrieves raw data from the BaseThermometer.
Note
This data is retrieved from MEMS register without any algebraical manipulation.
The axes array must be at least the same size of the BaseThermometer axes number.
Parameters
[in] devp pointer to HTS221Driver.
[out] axes a buffer which would be filled with raw data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 603 of file hts221.h.
hts221ThermometerReadCooked
#define hts221ThermometerReadCooked (devp, axes) thermometerReadCooked(&((devp)->thermo_if), axes)
Retrieves cooked data from the BaseThermometer.
Note
This data is manipulated according to the formula cooked = (raw * sensitivity) - bias.
Final data is expressed as C.
The axes array must be at least the same size of the BaseThermometer axes number.
Parameters
[in] devp pointer to HTS221Driver.
[out] axes a buffer which would be filled with cooked data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 625 of file hts221.h.
hts221ThermometerSetBias
#define hts221ThermometerSetBias (devp, bp) thermometerSetBias(&((devp)->thermo_if), bp)
Set bias values for the BaseThermometer.
Note
Bias must be expressed as C.
The bias buffer must be at least the same size of the BaseThermometer axes number.
Parameters
[in] devp pointer to HTS221Driver.
[in] bp a buffer which contains biases.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 642 of file hts221.h.
hts221ThermometerResetBias
#define hts221ThermometerResetBias (devp) thermometerResetBias(&((devp)->thermo_if))
Reset bias values for the BaseThermometer.
Note
Default biases value are obtained from device datasheet when available otherwise they are considered zero.
Parameters
[in] devp pointer to HTS221Driver.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 657 of file hts221.h.
hts221ThermometerSetSensitivity
#define hts221ThermometerSetSensitivity (devp, sp) thermometerSetSensitivity(&((devp)->thermo_if), sp)
Set sensitivity values for the BaseThermometer.
Note
Sensitivity must be expressed as C/LSB.
The sensitivity buffer must be at least the same size of the BaseThermometer axes number.
Parameters
[in] devp pointer to HTS221Driver.
[in] sp a buffer which contains sensitivities.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 674 of file hts221.h.
hts221ThermometerResetSensitivity
#define hts221ThermometerResetSensitivity (devp) thermometerResetSensitivity(&((devp)->thermo_if))
Reset sensitivity values for the BaseThermometer.
Note
Default sensitivities value are obtained from device datasheet.
Parameters
[in] devp pointer to HTS221Driver.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 688 of file hts221.h.
Typedef Documentation
HTS221Driver
typedef struct HTS221Driver HTS221Driver
Structure representing a HTS221 driver.
Definition at line 1 of file hts221.h.
Enumeration Type Documentation
hts221_odr_t
enum hts221_odr_t
HTS221 output data rate and bandwidth.
Enumerator
HTS221_ODR_ONE_SHOT
One shot.
HTS221_ODR_1HZ
Output data rate 1 Hz.
HTS221_ODR_7HZ
Output data rate 7 Hz.
HTS221_ODR_12P5HZ
Output data rate 12.5 Hz.
Definition at line 273 of file hts221.h.
hts221_avgh_t
enum hts221_avgh_t
HTS221 humidity resolution.
Enumerator
HTS221_AVGH_4
Number of internal average is 4.
HTS221_AVGH_8
Number of internal average is 8.
HTS221_AVGH_16
Number of internal average is 16.
HTS221_AVGH_32
Number of internal average is 32.
HTS221_AVGH_64
Number of internal average is 64.
HTS221_AVGH_128
Number of internal average is 128.
HTS221_AVGH_256
Number of internal average is 256.
HTS221_AVGH_512
Number of internal average is 512.
Definition at line 283 of file hts221.h.
hts221_avgt_t
enum hts221_avgt_t
HTS221 temperature resolution.
Enumerator
HTS221_AVGT_2
Number of internal average is 2.
HTS221_AVGT_4
Number of internal average is 4.
HTS221_AVGT_8
Number of internal average is 8.
HTS221_AVGT_16
Number of internal average is 16.
HTS221_AVGT_32
Number of internal average is 32.
HTS221_AVGT_64
Number of internal average is 64.
HTS221_AVGT_128
Number of internal average is 128.
HTS221_AVGT_256
Number of internal average is 256.
Definition at line 297 of file hts221.h.
hts221_bdu_t
enum hts221_bdu_t
HTS221 block data update.
Enumerator
HTS221_BDU_CONTINUOUS
Block data continuously updated.
HTS221_BDU_BLOCKED
Block data updated after reading.
Definition at line 311 of file hts221.h.
hts221_state_t
enum hts221_state_t
Driver state machine possible states.
Enumerator
HTS221_UNINIT
Not initialized.
HTS221_STOP
Stopped.
HTS221_READY
Ready.
Definition at line 319 of file hts221.h.
Function Documentation
hts221I2CReadRegister()
static msg_t hts221I2CReadRegister (I2CDriver * i2cp, uint8_t reg, uint8_t * rxbuf, size_t n) static
Reads registers value using I2C.
Precondition
The I2C interface must be initialized and the driver started.
Parameters
[in] i2cp pointer to the I2C interface
[in] reg first sub-register address
[out] rxbuf pointer to an output buffer
[in] n number of consecutive register to read
Returns
the operation status.
Function Class:
Not an API, this function is for internal use only.
Definition at line 69 of file hts221.c.
Referenced by hts221Calibrate(), hygro_read_raw(), and thermo_read_raw().
hts221I2CWriteRegister()
static msg_t hts221I2CWriteRegister (I2CDriver * i2cp, uint8_t * txbuf, size_t n) static
Writes a value into a register using I2C.
Precondition
The I2C interface must be initialized and the driver started.
Parameters
[in] i2cp pointer to the I2C interface
[in] txbuf buffer containing sub-address value in first position and values to write
[in] n size of txbuf less one (not considering the first element)
Returns
the operation status.
Function Class:
Not an API, this function is for internal use only.
Definition at line 92 of file hts221.c.
hts221Calibrate()
static msg_t hts221Calibrate (HTS221Driver * devp) static
Computes biases and sensitivities starting from data stored in calibration registers.
Note
Factory bias and sensitivity values are stored into the driver structure.
Parameters
[in] devp pointer to the HTS221 interface
Returns
the operation status.
Function Class:
Not an API, this function is for internal use only.
Definition at line 112 of file hts221.c.
References hts221I2CReadRegister().
Referenced by hts221Start().
hygro_get_axes_number()
static size_t hygro_get_axes_number (void * ip) static
Return the number of axes of the BaseHygrometer.
Parameters
[in] ip pointer to BaseHygrometer interface.
Returns
the number of axes.
Definition at line 173 of file hts221.c.
References HTS221_HYGRO_NUMBER_OF_AXES.
hygro_read_raw()
static msg_t hygro_read_raw (void * ip, int32_t axes[]) static
Retrieves raw data from the BaseHygrometer.
Note
This data is retrieved from MEMS register without any algebraical manipulation.
The axes array must be at least the same size of the BaseHygrometer axes number.
Parameters
[in] ip pointer to BaseHygrometer interface.
[out] axes a buffer which would be filled with raw data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Definition at line 195 of file hts221.c.
References HTS221_READY, and hts221I2CReadRegister().
Referenced by hygro_read_cooked().
hygro_read_cooked()
static msg_t hygro_read_cooked (void * ip, float axes[]) static
Retrieves cooked data from the BaseHygrometer.
Note
This data is manipulated according to the formula cooked = (raw * sensitivity) - bias.
Final data is expressed as rH.
The axes array must be at least the same size of the BaseHygrometer axes number.
Parameters
[in] ip pointer to BaseHygrometer interface.
[out] axes a buffer which would be filled with cooked data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Definition at line 249 of file hts221.c.
References HTS221_READY, and hygro_read_raw().
hygro_set_bias()
static msg_t hygro_set_bias (void * ip, float * bp) static
Set bias values for the BaseHygrometer.
Note
Bias must be expressed as rH.
The bias buffer must be at least the same size of the BaseHygrometer axes number.
Parameters
[in] ip pointer to BaseHygrometer interface.
[in] bp a buffer which contains biases.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Definition at line 284 of file hts221.c.
References HTS221_READY.
hygro_reset_bias()
static msg_t hygro_reset_bias (void * ip) static
Reset bias values for the BaseHygrometer.
Note
Default biases value are obtained from device datasheet when available otherwise they are considered zero.
Parameters
[in] ip pointer to BaseHygrometer interface.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Definition at line 310 of file hts221.c.
References HTS221_READY.
hygro_set_sensitivity()
static msg_t hygro_set_sensitivity (void * ip, float * sp) static
Set sensitivity values for the BaseHygrometer.
Note
Sensitivity must be expressed as rH/LSB.
The sensitivity buffer must be at least the same size of the BaseHygrometer axes number.
Parameters
[in] ip pointer to BaseHygrometer interface.
[in] sp a buffer which contains sensitivities.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Definition at line 338 of file hts221.c.
References HTS221_READY.
hygro_reset_sensitivity()
static msg_t hygro_reset_sensitivity (void * ip) static
Reset sensitivity values for the BaseHygrometer.
Note
Default sensitivities value are obtained from device datasheet.
Parameters
[in] ip pointer to BaseHygrometer interface.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Definition at line 363 of file hts221.c.
References HTS221_READY.
thermo_get_axes_number()
static size_t thermo_get_axes_number (void * ip) static
Return the number of axes of the BaseThermometer.
Parameters
[in] ip pointer to BaseThermometer interface.
Returns
the number of axes.
Definition at line 386 of file hts221.c.
References HTS221_THERMO_NUMBER_OF_AXES.
thermo_read_raw()
static msg_t thermo_read_raw (void * ip, int32_t axes[]) static
Retrieves raw data from the BaseThermometer.
Note
This data is retrieved from MEMS register without any algebraical manipulation.
The axes array must be at least the same size of the BaseThermometer axes number.
Parameters
[in] ip pointer to BaseThermometer interface.
[out] axes a buffer which would be filled with raw data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Definition at line 408 of file hts221.c.
References HTS221_READY, and hts221I2CReadRegister().
Referenced by thermo_read_cooked().
thermo_read_cooked()
static msg_t thermo_read_cooked (void * ip, float * axis) static
Retrieves cooked data from the BaseThermometer.
Note
This data is manipulated according to the formula cooked = (raw * sensitivity) - bias.
Final data is expressed as C.
The axes array must be at least the same size of the BaseThermometer axes number.
Parameters
[in] ip pointer to BaseThermometer interface.
[out] axis a buffer which would be filled with cooked data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Definition at line 462 of file hts221.c.
References HTS221_READY, and thermo_read_raw().
thermo_set_bias()
static msg_t thermo_set_bias (void * ip, float * bp) static
Set bias values for the BaseThermometer.
Note
Bias must be expressed as C.
The bias buffer must be at least the same size of the BaseThermometer axes number.
Parameters
[in] ip pointer to BaseThermometer interface.
[in] bp a buffer which contains biases.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Definition at line 494 of file hts221.c.
References HTS221_READY.
thermo_reset_bias()
static msg_t thermo_reset_bias (void * ip) static
Reset bias values for the BaseThermometer.
Note
Default biases value are obtained from device datasheet when available otherwise they are considered zero.
Parameters
[in] ip pointer to BaseThermometer interface.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Definition at line 521 of file hts221.c.
References HTS221_READY.
thermo_set_sensitivity()
static msg_t thermo_set_sensitivity (void * ip, float * sp) static
Set sensitivity values for the BaseThermometer.
Note
Sensitivity must be expressed as C/LSB.
The sensitivity buffer must be at least the same size of the BaseThermometer axes number.
Parameters
[in] ip pointer to BaseThermometer interface.
[in] sp a buffer which contains sensitivities.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Definition at line 550 of file hts221.c.
References HTS221_READY.
thermo_reset_sensitivity()
static msg_t thermo_reset_sensitivity (void * ip) static
Reset sensitivity values for the BaseThermometer.
Note
Default sensitivities value are obtained from device datasheet.
Parameters
[in] ip pointer to BaseThermometer interface.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Definition at line 576 of file hts221.c.
References HTS221_READY.
hts221ObjectInit()
void hts221ObjectInit (HTS221Driver * devp)
Initializes an instance.
Parameters
[out] devp pointer to the HTS221Driver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 622 of file hts221.c.
References HTS221Driver::vmt.
hts221Start()
void hts221Start (HTS221Driver * devp, const HTS221Config * config)
Configures and activates HTS221 Complex Driver peripheral.
Parameters
[in] devp pointer to the HTS221Driver object
[in] config pointer to the HTS221Config object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 647 of file hts221.c.
References HTS221_READY, HTS221_STOP, and hts221Calibrate().
hts221Stop()
void hts221Stop (HTS221Driver * devp)
Deactivates the HTS221 Complex Driver peripheral.
Parameters
[in] devp pointer to the HTS221Driver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 755 of file hts221.c.
References HTS221_READY, and HTS221_STOP.