ChibiOS/EX: ADXL355
ADXL355
EX » Devices » Analog Devices Devices
Detailed Description
Macros
#define adxl355AccelerometerGetAxesNumber(devp) accelerometerGetAxesNumber(&((devp)->acc_if))
Return the number of axes of the BaseAccelerometer.
#define adxl355AccelerometerReadRaw(devp, axes) accelerometerReadRaw(&((devp)->acc_if), axes)
Retrieves raw data from the BaseAccelerometer.
#define adxl355AccelerometerReadCooked(devp, axes) accelerometerReadCooked(&((devp)->acc_if), axes)
Retrieves cooked data from the BaseAccelerometer.
#define adxl355AccelerometerSetBias(devp, bp) accelerometerSetBias(&((devp)->acc_if), bp)
Set bias values for the BaseAccelerometer.
#define adxl355AccelerometerResetBias(devp) accelerometerResetBias(&((devp)->acc_if))
Reset bias values for the BaseAccelerometer.
#define adxl355AccelerometerSetSensitivity(devp, sp) accelerometerSetSensitivity(&((devp)->acc_if), sp)
Set sensitivity values for the BaseAccelerometer.
#define adxl355AccelerometerResetSensitivity(devp) accelerometerResetSensitivity(&((devp)->acc_if))
Reset sensitivity values for the BaseAccelerometer.
#define adxl355AccelerometerSetFullScale(devp, fs) (devp)->vmt->acc_set_full_scale(devp, fs)
Changes the ADXL355Driver accelerometer fullscale value.
ADXL355 data structures and types
enum adxl355_acc_fs_t { ADXL355_ACC_FS_2G = 0x01 , ADXL355_ACC_FS_4G = 0x02 , ADXL355_ACC_FS_8G = 0x03 }
ADXL355 full scale.
enum adxl355_acc_odr_t {
ADXL355_ACC_ODR_4000HZ = 0x00 , ADXL355_ACC_ODR_2000HZ = 0x01 , ADXL355_ACC_ODR_1000HZ = 0x02 , ADXL355_ACC_ODR_500HZ = 0x03 ,
ADXL355_ACC_ODR_250HZ = 0x04 , ADXL355_ACC_ODR_125HZ = 0x06 , ADXL355_ACC_ODR_62P5HZ = 0x06 , ADXL355_ACC_ODR_31P25HZ = 0x07 ,
ADXL355_ACC_ODR_15P625HZ = 0x08 , ADXL355_ACC_ODR_7P913HZ = 0x09 , ADXL355_ACC_ODR_3P906HZ = 0x0A
}
ADXL355 output data rate.
enum adxl355_acc_hp_t {
ADXL355_ACC_HP_DISABLED = 0x00 , ADXL355_ACC_HP_LEV_1 = 0x10 , ADXL355_ACC_HP_LEV_2 = 0x20 , ADXL355_ACC_HP_LEV_3 = 0x30 ,
ADXL355_ACC_HP_LEV_4 = 0x40 , ADXL355_ACC_HP_LEV_5 = 0x50 , ADXL355_ACC_HP_LEV_6 = 0x60
}
ADXL355 HP filter.
enum adxl355_state_t { ADXL355_UNINIT = 0 , ADXL355_STOP = 1 , ADXL355_READY = 2 }
Driver state machine possible states.
typedef struct ADXL355Driver ADXL355Driver
Structure representing a ADXL355 driver.
#define _adxl355_methods_alone
ADXL355 specific methods.
#define _adxl355_methods
ADXL355 specific methods with inherited ones.
#define _adxl355_data
ADXL355Driver specific data.
Version identification
#define EX_ADXL355_VERSION "1.0.0"
ADXL355 driver version string.
#define EX_ADXL355_MAJOR 1
ADXL355 driver version major number.
#define EX_ADXL355_MINOR 0
ADXL355 driver version minor number.
#define EX_ADXL355_PATCH 0
ADXL355 driver version patch number.
#define ADXL355_ACC_NUMBER_OF_AXES 3U
ADXL355 accelerometer subsystem characteristics.
ADXL355 communication interfaces related bit masks
#define ADXL355_DI_MASK 0xFF
#define ADXL355_DI(n) (1 << n)
#define ADXL355_AD_MASK 0xFE
#define ADXL355_RW (1 << 0)
#define ADXL355_AD(n) (1 << (n + 1))
ADXL355 register addresses
#define ADXL355_AD_DEVID_AD 0x00
#define ADXL355_AD_DEVID_MST 0x01
#define ADXL355_AD_PARTID 0x02
#define ADXL355_AD_REVID 0x03
#define ADXL355_AD_STATUS 0x04
#define ADXL355_AD_FIFO_ENTRIES 0x05
#define ADXL355_AD_TEMP2 0x06
#define ADXL355_AD_TEMP1 0x07
#define ADXL355_AD_XDATA3 0x08
#define ADXL355_AD_XDATA2 0x09
#define ADXL355_AD_XDATA1 0x0A
#define ADXL355_AD_YDATA3 0x0B
#define ADXL355_AD_YDATA2 0x0C
#define ADXL355_AD_YDATA1 0x0D
#define ADXL355_AD_ZDATA3 0x0E
#define ADXL355_AD_ZDATA2 0x0F
#define ADXL355_AD_ZDATA1 0x10
#define ADXL355_AD_FIFO_DATA 0x11
#define ADXL355_AD_OFFSET_X_H 0x1E
#define ADXL355_AD_OFFSET_X_L 0x1F
#define ADXL355_AD_OFFSET_Y_H 0x20
#define ADXL355_AD_OFFSET_Y_L 0x21
#define ADXL355_AD_OFFSET_Z_H 0x22
#define ADXL355_AD_OFFSET_Z_L 0x23
#define ADXL355_AD_ACT_EN 0x24
#define ADXL355_AD_ACT_THRES_L 0x25
#define ADXL355_AD_ACT_THRES_H 0x26
#define ADXL355_AD_ACT_COUNTER 0x27
#define ADXL355_AD_FILTER 0x28
#define ADXL355_AD_FIFO_SAMPLES 0x29
#define ADXL355_AD_INT_MAP 0x2A
#define ADXL355_AD_SYNC 0x2B
#define ADXL355_AD_RANGE 0x2C
#define ADXL355_AD_POWER_CTL 0x2D
#define ADXL355_AD_SELF_TEST 0x2E
#define ADXL355_AD_RESET 0x2F
ADXL355 Device Identifier
#define ADXL355_DEVID_MST 0x1D
ADXL355_FILTER register bits definitions
#define ADXL355_FILTER_MASK 0x7F
#define ADXL355_FILTER_ORD_LPF_0 (1 << 0)
#define ADXL355_FILTER_ORD_LPF_1 (1 << 1)
#define ADXL355_FILTER_ORD_LPF_2 (1 << 2)
#define ADXL355_FILTER_ORD_LPF_3 (1 << 3)
#define ADXL355_FILTER_HPF_CORNER_0 (1 << 4)
#define ADXL355_FILTER_HPF_CORNER_1 (1 << 5)
#define ADXL355_FILTER_HPF_CORNER_2 (1 << 6)
ADXL355_FIFO_SAMPLES register bits definitions
#define ADXL355_FIFO_SAMPLES_MASK 0x7F
#define ADXL355_FIFO_SAMPLES_BIT_0 (1 << 0)
#define ADXL355_FIFO_SAMPLES_BIT_1 (1 << 1)
#define ADXL355_FIFO_SAMPLES_BIT_2 (1 << 2)
#define ADXL355_FIFO_SAMPLES_BIT_3 (1 << 3)
#define ADXL355_FIFO_SAMPLES_BIT_4 (1 << 4)
#define ADXL355_FIFO_SAMPLES_BIT_5 (1 << 5)
#define ADXL355_FIFO_SAMPLES_BIT_6 (1 << 6)
ADXL355_INT_MAP register bits definitions
#define ADXL355_INT_MAP_MASK 0xFF
#define ADXL355_INT_MAP_RDY_EN1 (1 << 0)
#define ADXL355_INT_MAP_FULL_EN1 (1 << 1)
#define ADXL355_INT_MAP_OVR_EN1 (1 << 2)
#define ADXL355_INT_MAP_ACT_EN1 (1 << 3)
#define ADXL355_INT_MAP_RDY_EN2 (1 << 4)
#define ADXL355_INT_MAP_FULL_EN2 (1 << 5)
#define ADXL355_INT_MAP_OVR_EN2 (1 << 6)
#define ADXL355_INT_MAP_ACT_EN2 (1 << 7)
ADXL355_SYNC register bits definitions
#define ADXL355_SYNC_MASK 0x07
#define ADXL355_SYNC_EXT_SYNC_0 (1 << 0)
#define ADXL355_SYNC_EXT_SYNC_1 (1 << 1)
#define ADXL355_SYNC_EXT_CLK (1 << 2)
ADXL355_RANGE register bits definitions
#define ADXL355_RANGE_MASK 0xC3
#define ADXL355_RANGE_RANGE_MASK 0x03
#define ADXL355_RANGE_RANGE_1 (1 << 1)
#define ADXL355_RANGE_RANGE_1 (1 << 1)
#define ADXL355_RANGE_RANGE_0 (1 << 0)
#define ADXL355_RANGE_INT_POL (1 << 6)
#define ADXL355_RANGE_I2C_HS (1 << 7)
ADXL355_POWER_CTL register bits definitions
#define ADXL355_POWER_CTL_MASK 0x07
#define ADXL355_POWER_CTL_STANDBY (1 << 0)
#define ADXL355_POWER_CTL_TEMP_OFF (1 << 1)
#define ADXL355_POWER_CTL_DRDY_OFF (1 << 2)
ADXL355_SELT_TEST register bits definitions
#define ADXL355_SELF_TEST_MASK 0x03
#define ADXL355_SELF_TEST_ST1 (1 << 0)
#define ADXL355_SELF_TEST_ST2 (1 << 1)
Configuration options
#define ADXL355_USE_SPI TRUE
ADXL355 SPI interface switch.
#define ADXL355_SHARED_SPI FALSE
ADXL355 shared SPI switch.
#define ADXL355_USE_I2C FALSE
ADXL355 I2C interface switch.
#define ADXL355_SHARED_I2C FALSE
ADXL355 shared I2C switch.
#define ADXL355_USE_ADVANCED FALSE
ADXL355 advanced configurations switch.
#define ADXL355_COMM_BUFF_SIZE 32
ADXL355 internal communication buffer sizes.
Data Structures
struct ADXL355Config
ADXL355 configuration structure.
struct ADXL355VMT
ADXL355 virtual methods table.
struct ADXL355Driver
ADXL355 3-axis accelerometer class.
Functions
static void adxl355SPIReadRegister (ADXL355Driver *devp, uint8_t reg, size_t n, uint8_t *b)
Reads a generic register value using SPI.
static void adxl355SPIWriteRegister (ADXL355Driver *devp, uint8_t reg, size_t n, uint8_t *b)
Writes a value into a generic register using SPI.
static size_t acc_get_axes_number (void *ip)
Return the number of axes of the BaseAccelerometer.
static msg_t acc_read_raw (void *ip, int32_t axes[])
Retrieves raw data from the BaseAccelerometer.
static msg_t acc_read_cooked (void *ip, float axes[])
Retrieves cooked data from the BaseAccelerometer.
static msg_t acc_set_bias (void *ip, float *bp)
Set bias values for the BaseAccelerometer.
static msg_t acc_reset_bias (void *ip)
Reset bias values for the BaseAccelerometer.
static msg_t acc_set_sensivity (void *ip, float *sp)
Set sensitivity values for the BaseAccelerometer.
static msg_t acc_reset_sensivity (void *ip)
Reset sensitivity values for the BaseAccelerometer.
static msg_t acc_set_full_scale (ADXL355Driver *devp, adxl355_acc_fs_t fs)
Changes the ADXL355Driver accelerometer fullscale value.
void adxl355ObjectInit (ADXL355Driver *devp, uint8_t *txbp, uint8_t *rxbp)
Initializes an instance.
void adxl355Start (ADXL355Driver *devp, const ADXL355Config *config)
Configures and activates ADXL355 Complex Driver peripheral.
void adxl355Stop (ADXL355Driver *devp)
Deactivates the ADXL355 Complex Driver peripheral.
Macro Definition Documentation
EX_ADXL355_VERSION
#define EX_ADXL355_VERSION "1.0.0"
ADXL355 driver version string.
Definition at line 46 of file adxl355.h.
EX_ADXL355_MAJOR
#define EX_ADXL355_MAJOR 1
ADXL355 driver version major number.
Definition at line 51 of file adxl355.h.
EX_ADXL355_MINOR
#define EX_ADXL355_MINOR 0
ADXL355 driver version minor number.
Definition at line 56 of file adxl355.h.
EX_ADXL355_PATCH
#define EX_ADXL355_PATCH 0
ADXL355 driver version patch number.
Definition at line 61 of file adxl355.h.
ADXL355_ACC_NUMBER_OF_AXES
#define ADXL355_ACC_NUMBER_OF_AXES 3U
ADXL355 accelerometer subsystem characteristics.
Note
Sensitivity is expressed as milli-G/LSB whereas 1 milli-G = 0.00980665 m/s^2.
Bias is expressed as milli-G.
Definition at line 72 of file adxl355.h.
ADXL355_USE_SPI
#define ADXL355_USE_SPI TRUE
ADXL355 SPI interface switch.
If set to TRUE the support for SPI is included.
Note
The default is TRUE.
Definition at line 245 of file adxl355.h.
ADXL355_SHARED_SPI
#define ADXL355_SHARED_SPI FALSE
ADXL355 shared SPI switch.
If set to TRUE the device acquires SPI bus ownership on each transaction.
Note
The default is FALSE. Requires SPI_USE_MUTUAL_EXCLUSION.
Definition at line 255 of file adxl355.h.
ADXL355_USE_I2C
#define ADXL355_USE_I2C FALSE
ADXL355 I2C interface switch.
If set to TRUE the support for I2C is included.
Note
The default is FALSE.
Definition at line 264 of file adxl355.h.
ADXL355_SHARED_I2C
#define ADXL355_SHARED_I2C FALSE
ADXL355 shared I2C switch.
If set to TRUE the device acquires I2C bus ownership on each transaction.
Note
The default is FALSE. Requires I2C_USE_MUTUAL_EXCLUSION.
Definition at line 274 of file adxl355.h.
ADXL355_USE_ADVANCED
#define ADXL355_USE_ADVANCED FALSE
ADXL355 advanced configurations switch.
If set to TRUE more configurations are available.
Note
The default is FALSE.
Definition at line 283 of file adxl355.h.
ADXL355_COMM_BUFF_SIZE
#define ADXL355_COMM_BUFF_SIZE 32
ADXL355 internal communication buffer sizes.
Definition at line 290 of file adxl355.h.
_adxl355_methods_alone
#define _adxl355_methods_alone
Value:
  /* Change full scale value of ADXL355 accelerometer subsystem.*/          \
  msg_t (*acc_set_full_scale)(ADXL355Driver *devp, adxl355_acc_fs_t fs);
ADXL355 specific methods.
Definition at line 438 of file adxl355.h.
_adxl355_methods
#define _adxl355_methods
Value:
  _base_object_methods                                                      \
  _adxl355_methods_alone
ADXL355 specific methods with inherited ones.
Definition at line 446 of file adxl355.h.
_adxl355_data
#define _adxl355_data
Value:
  _base_sensor_data                                                         \
  /* Driver state.*/                                                        \
  adxl355_state_t           state;                                          \
  /* Current configuration data.*/                                          \
  const ADXL355Config       *config;                                        \
  /* Accelerometer subsystem axes number.*/                                 \
  size_t                    accaxes;                                        \
  /* Accelerometer subsystem current sensitivity.*/                         \
  float                     accsensitivity[ADXL355_ACC_NUMBER_OF_AXES];     \
  /* Accelerometer subsystem current bias .*/                               \
  float                     accbias[ADXL355_ACC_NUMBER_OF_AXES];            \
  /* Accelerometer subsystem current full scale value.*/                    \
  float                     accfullscale;                                   \
  /* Accelerometer communication tx buffer pointer.*/                       \
  uint8_t*                  commtxp;                                        \
  /* Accelerometer communication rx buffer pointer.*/                       \
  uint8_t*                  commrxp;
ADXL355Driver specific data.
Definition at line 462 of file adxl355.h.
adxl355AccelerometerGetAxesNumber
#define adxl355AccelerometerGetAxesNumber (devp) accelerometerGetAxesNumber(&((devp)->acc_if))
Return the number of axes of the BaseAccelerometer.
Parameters
[in] devp pointer to ADXL355Driver.
Returns
the number of axes.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 506 of file adxl355.h.
adxl355AccelerometerReadRaw
#define adxl355AccelerometerReadRaw (devp, axes) accelerometerReadRaw(&((devp)->acc_if), axes)
Retrieves raw data from the BaseAccelerometer.
Note
This data is retrieved from MEMS register without any algebraical manipulation.
The axes array must be at least the same size of the BaseAccelerometer axes number.
Parameters
[in] devp pointer to ADXL355Driver.
[out] axes a buffer which would be filled with raw data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 527 of file adxl355.h.
adxl355AccelerometerReadCooked
#define adxl355AccelerometerReadCooked (devp, axes) accelerometerReadCooked(&((devp)->acc_if), axes)
Retrieves cooked data from the BaseAccelerometer.
Note
This data is manipulated according to the formula cooked = (raw * sensitivity) - bias.
Final data is expressed as milli-G.
The axes array must be at least the same size of the BaseAccelerometer axes number.
Parameters
[in] devp pointer to ADXL355Driver.
[out] axes a buffer which would be filled with cooked data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 549 of file adxl355.h.
adxl355AccelerometerSetBias
#define adxl355AccelerometerSetBias (devp, bp) accelerometerSetBias(&((devp)->acc_if), bp)
Set bias values for the BaseAccelerometer.
Note
Bias must be expressed as milli-G.
The bias buffer must be at least the same size of the BaseAccelerometer axes number.
Parameters
[in] devp pointer to ADXL355Driver.
[in] bp a buffer which contains biases.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 566 of file adxl355.h.
adxl355AccelerometerResetBias
#define adxl355AccelerometerResetBias (devp) accelerometerResetBias(&((devp)->acc_if))
Reset bias values for the BaseAccelerometer.
Note
Default biases value are obtained from device datasheet when available otherwise they are considered zero.
Parameters
[in] devp pointer to ADXL355Driver.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 581 of file adxl355.h.
adxl355AccelerometerSetSensitivity
#define adxl355AccelerometerSetSensitivity (devp, sp) accelerometerSetSensitivity(&((devp)->acc_if), sp)
Set sensitivity values for the BaseAccelerometer.
Note
Sensitivity must be expressed as milli-G/LSB.
The sensitivity buffer must be at least the same size of the BaseAccelerometer axes number.
Parameters
[in] devp pointer to ADXL355Driver.
[in] sp a buffer which contains sensitivities.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 598 of file adxl355.h.
adxl355AccelerometerResetSensitivity
#define adxl355AccelerometerResetSensitivity (devp) accelerometerResetSensitivity(&((devp)->acc_if))
Reset sensitivity values for the BaseAccelerometer.
Note
Default sensitivities value are obtained from device datasheet.
Parameters
[in] devp pointer to ADXL355Driver.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET otherwise.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 613 of file adxl355.h.
adxl355AccelerometerSetFullScale
#define adxl355AccelerometerSetFullScale (devp, fs) (devp)->vmt->acc_set_full_scale(devp, fs)
Changes the ADXL355Driver accelerometer fullscale value.
Note
This function also rescale sensitivities and biases based on previous and next fullscale value.
A recalibration is highly suggested after calling this function.
Parameters
[in] devp pointer to ADXL355Driver.
[in] fs new fullscale value.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET otherwise.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 631 of file adxl355.h.
Typedef Documentation
ADXL355Driver
typedef struct ADXL355Driver ADXL355Driver
Structure representing a ADXL355 driver.
Definition at line 1 of file adxl355.h.
Enumeration Type Documentation
adxl355_acc_fs_t
enum adxl355_acc_fs_t
ADXL355 full scale.
Enumerator
ADXL355_ACC_FS_2G
Full scale 2g.
ADXL355_ACC_FS_4G
Full scale 4g.
ADXL355_ACC_FS_8G
Full scale 8g.
Definition at line 341 of file adxl355.h.
adxl355_acc_odr_t
enum adxl355_acc_odr_t
ADXL355 output data rate.
Enumerator
ADXL355_ACC_ODR_4000HZ
ODR 4000 Hz, LP cut-off ODR/4.
ADXL355_ACC_ODR_2000HZ
ODR 2000 Hz, LP cut-off ODR/4.
ADXL355_ACC_ODR_1000HZ
ODR 1000 Hz, LP cut-off ODR/4.
ADXL355_ACC_ODR_500HZ
ODR 500 Hz, LP cut-off ODR/4.
ADXL355_ACC_ODR_250HZ
ODR 250 Hz, LP cut-off ODR/4.
ADXL355_ACC_ODR_125HZ
ODR 125 Hz, LP cut-off ODR/4.
ADXL355_ACC_ODR_62P5HZ
ODR 62.5 Hz, LP cut-off ODR/4.
ADXL355_ACC_ODR_31P25HZ
ODR 31.25 Hz, LP cut-off ODR/4.
ADXL355_ACC_ODR_15P625HZ
ODR 15.625 Hz, LP cut-off ODR/4.
ADXL355_ACC_ODR_7P913HZ
ODR 7.913 Hz, LP cut-off ODR/4.
ADXL355_ACC_ODR_3P906HZ
ODR 3.906 Hz, LP cut-off ODR/4.
Definition at line 350 of file adxl355.h.
adxl355_acc_hp_t
enum adxl355_acc_hp_t
ADXL355 HP filter.
Enumerator
ADXL355_ACC_HP_DISABLED
HP disabled.
ADXL355_ACC_HP_LEV_1
HP cut-off 247 x 10^-3 x ODR.
ADXL355_ACC_HP_LEV_2
HP cut-off 62.084 x 10^-3 x ODR.
ADXL355_ACC_HP_LEV_3
HP cut-off 15.545 x 10^-3 x ODR.
ADXL355_ACC_HP_LEV_4
HP cut-off 3.892 x 10^-3 x ODR.
ADXL355_ACC_HP_LEV_5
HP cut-off 0.954 x 10^-3 x ODR.
ADXL355_ACC_HP_LEV_6
HP cut-off 0.238 x 10^-3 x ODR.
Definition at line 367 of file adxl355.h.
adxl355_state_t
enum adxl355_state_t
Driver state machine possible states.
Enumerator
ADXL355_UNINIT
Not initialized.
ADXL355_STOP
Stopped.
ADXL355_READY
Ready.
Definition at line 380 of file adxl355.h.
Function Documentation
adxl355SPIReadRegister()
static void adxl355SPIReadRegister (ADXL355Driver * devp, uint8_t reg, size_t n, uint8_t * b) static
Reads a generic register value using SPI.
Precondition
The SPI interface must be initialized and the driver started.
Parameters
[in] devp pointer to ADXL355Driver interface.
[in] reg starting register address
[in] n number of consecutive registers to read
[in] b pointer to an output buffer.
Definition at line 59 of file adxl355.c.
Referenced by acc_read_raw(), and adxl355Start().
adxl355SPIWriteRegister()
static void adxl355SPIWriteRegister (ADXL355Driver * devp, uint8_t reg, size_t n, uint8_t * b) static
Writes a value into a generic register using SPI.
Precondition
The SPI interface must be initialized and the driver started.
Parameters
[in] devp pointer to ADXL355Driver interface.
[in] reg starting register address
[in] n number of adjacent registers to write
[in] b pointer to a buffer of values.
Definition at line 83 of file adxl355.c.
Referenced by adxl355Stop().
acc_get_axes_number()
static size_t acc_get_axes_number (void * ip) static
Return the number of axes of the BaseAccelerometer.
Parameters
[in] ip pointer to BaseAccelerometer interface.
Returns
the number of axes.
Definition at line 104 of file adxl355.c.
References ADXL355_ACC_NUMBER_OF_AXES.
acc_read_raw()
static msg_t acc_read_raw (void * ip, int32_t axes[]) static
Retrieves raw data from the BaseAccelerometer.
Note
This data is retrieved from MEMS register without any algebraical manipulation.
The axes array must be at least the same size of the BaseAccelerometer axes number.
Parameters
[in] ip pointer to BaseAccelerometer interface.
[out] axes a buffer which would be filled with raw data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Definition at line 126 of file adxl355.c.
References ADXL355_ACC_NUMBER_OF_AXES, ADXL355_READY, and adxl355SPIReadRegister().
Referenced by acc_read_cooked().
acc_read_cooked()
static msg_t acc_read_cooked (void * ip, float axes[]) static
Retrieves cooked data from the BaseAccelerometer.
Note
This data is manipulated according to the formula cooked = (raw * sensitivity) - bias.
Final data is expressed as milli-G.
The axes array must be at least the same size of the BaseAccelerometer axes number.
Parameters
[in] ip pointer to BaseAccelerometer interface.
[out] axes a buffer which would be filled with cooked data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Definition at line 184 of file adxl355.c.
References acc_read_raw(), ADXL355_ACC_NUMBER_OF_AXES, and ADXL355_READY.
acc_set_bias()
static msg_t acc_set_bias (void * ip, float * bp) static
Set bias values for the BaseAccelerometer.
Note
Bias must be expressed as milli-G.
The bias buffer must be at least the same size of the BaseAccelerometer axes number.
Parameters
[in] ip pointer to BaseAccelerometer interface.
[in] bp a buffer which contains biases.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Definition at line 217 of file adxl355.c.
References ADXL355_ACC_NUMBER_OF_AXES, and ADXL355_READY.
acc_reset_bias()
static msg_t acc_reset_bias (void * ip) static
Reset bias values for the BaseAccelerometer.
Note
Default biases value are obtained from device datasheet when available otherwise they are considered zero.
Parameters
[in] ip pointer to BaseAccelerometer interface.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Definition at line 246 of file adxl355.c.
References ADXL355_ACC_NUMBER_OF_AXES, and ADXL355_READY.
acc_set_sensivity()
static msg_t acc_set_sensivity (void * ip, float * sp) static
Set sensitivity values for the BaseAccelerometer.
Note
Sensitivity must be expressed as milli-G/LSB.
The sensitivity buffer must be at least the same size of the BaseAccelerometer axes number.
Parameters
[in] ip pointer to BaseAccelerometer interface.
[in] sp a buffer which contains sensitivities.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Definition at line 276 of file adxl355.c.
References ADXL355_ACC_NUMBER_OF_AXES, and ADXL355_READY.
acc_reset_sensivity()
static msg_t acc_reset_sensivity (void * ip) static
Reset sensitivity values for the BaseAccelerometer.
Note
Default sensitivities value are obtained from device datasheet.
Parameters
[in] ip pointer to BaseAccelerometer interface.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET otherwise.
Definition at line 305 of file adxl355.c.
References ADXL355_ACC_FS_2G, ADXL355_ACC_NUMBER_OF_AXES, and ADXL355_READY.
acc_set_full_scale()
static msg_t acc_set_full_scale (ADXL355Driver * devp, adxl355_acc_fs_t fs) static
Changes the ADXL355Driver accelerometer fullscale value.
Note
This function also rescale sensitivities and biases based on previous and next fullscale value.
A recalibration is highly suggested after calling this function.
Parameters
[in] devp pointer to ADXL355Driver interface.
[in] fs new fullscale value.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET otherwise.
Definition at line 348 of file adxl355.c.
References ADXL355_ACC_FS_2G, and ADXL355_READY.
adxl355ObjectInit()
void adxl355ObjectInit (ADXL355Driver * devp, uint8_t * txbp, uint8_t * rxbp)
Initializes an instance.
The buffer should be at least large ADXL355_COMM_BUFF_SIZE.
Note
The communication buffer could be used by DMAs.
Parameters
[out] devp pointer to the ADXL355Driver object
[in] txbp pointer to a buffer used as communication tx buffer
[in] rxbp pointer to a buffer used as communication rx buffer
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 448 of file adxl355.c.
References ADXL355Driver::vmt.
adxl355Start()
void adxl355Start (ADXL355Driver * devp, const ADXL355Config * config)
Configures and activates ADXL355 Complex Driver peripheral.
Parameters
[in] devp pointer to the ADXL355Driver object
[in] config pointer to the ADXL355Config object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 469 of file adxl355.c.
References ADXL355_READY, ADXL355_STOP, and adxl355SPIReadRegister().
adxl355Stop()
void adxl355Stop (ADXL355Driver * devp)
Deactivates the ADXL355 Complex Driver peripheral.
Parameters
[in] devp pointer to the ADXL355Driver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 603 of file adxl355.c.
References ADXL355_READY, ADXL355_STOP, and adxl355SPIWriteRegister().