ChibiOS/EX: LSM303DLHC
LSM303DLHC
EX » Devices » STMicroelectronics Devices
Detailed Description
Macros
#define lsm303dlhcAccelerometerGetAxesNumber(devp) accelerometerGetAxesNumber(&((devp)->acc_if))
Return the number of axes of the BaseAccelerometer.
#define lsm303dlhcAccelerometerReadRaw(devp, axes) accelerometerReadRaw(&((devp)->acc_if), axes)
Retrieves raw data from the BaseAccelerometer.
#define lsm303dlhcAccelerometerReadCooked(devp, axes) accelerometerReadCooked(&((devp)->acc_if), axes)
Retrieves cooked data from the BaseAccelerometer.
#define lsm303dlhcAccelerometerSetBias(devp, bp) accelerometerSetBias(&((devp)->acc_if), bp)
Set bias values for the BaseAccelerometer.
#define lsm303dlhcAccelerometerResetBias(devp) accelerometerResetBias(&((devp)->acc_if))
Reset bias values for the BaseAccelerometer.
#define lsm303dlhcAccelerometerSetSensitivity(devp, sp) accelerometerSetSensitivity(&((devp)->acc_if), sp)
Set sensitivity values for the BaseAccelerometer.
#define lsm303dlhcAccelerometerResetSensitivity(devp) accelerometerResetSensitivity(&((devp)->acc_if))
Reset sensitivity values for the BaseAccelerometer.
#define lsm303dlhcAccelerometerSetFullScale(devp, fs) (devp)->vmt->acc_set_full_scale(devp, fs)
Changes the LSM303DLHCDriver accelerometer fullscale value.
#define lsm303dlhcCompassGetAxesNumber(devp) compassGetAxesNumber(&((devp)->comp_if))
Return the number of axes of the BaseCompass.
#define lsm303dlhcCompassReadRaw(devp, axes) compassReadRaw(&((devp)->comp_if), axes)
Retrieves raw data from the BaseCompass.
#define lsm303dlhcCompassReadCooked(devp, axes) compassReadCooked(&((devp)->comp_if), axes)
Retrieves cooked data from the BaseCompass.
#define lsm303dlhcCompassSetBias(devp, bp) compassSetBias(&((devp)->comp_if), bp)
Set bias values for the BaseCompass.
#define lsm303dlhcCompassResetBias(devp) compassResetBias(&((devp)->comp_if))
Reset bias values for the BaseCompass.
#define lsm303dlhcCompassSetSensitivity(devp, sp) compassSetSensitivity(&((devp)->comp_if), sp)
Set sensitivity values for the BaseCompass.
#define lsm303dlhcCompassResetSensitivity(devp) compassResetSensitivity(&((devp)->comp_if))
Reset sensitivity values for the BaseCompass.
#define lsm303dlhcCompassSetFullScale(devp, fs) (devp)->vmt->comp_set_full_scale(devp, fs)
Changes the LSM303DLHCDriver compass fullscale value.
LSM303DLHC accelerometer subsystem data structures and types.
enum lsm303dlhc_acc_fs_t { LSM303DLHC_ACC_FS_2G = 0x00 , LSM303DLHC_ACC_FS_4G = 0x10 , LSM303DLHC_ACC_FS_8G = 0x20 , LSM303DLHC_ACC_FS_16G = 0x30 }
LSM303DLHC accelerometer subsystem full scale.
enum lsm303dlhc_acc_odr_t {
LSM303DLHC_ACC_ODR_PD = 0x00 , LSM303DLHC_ACC_ODR_1Hz = 0x10 , LSM303DLHC_ACC_ODR_10Hz = 0x20 , LSM303DLHC_ACC_ODR_25Hz = 0x30 ,
LSM303DLHC_ACC_ODR_50Hz = 0x40 , LSM303DLHC_ACC_ODR_100Hz = 0x50 , LSM303DLHC_ACC_ODR_200Hz = 0x60 , LSM303DLHC_ACC_ODR_400Hz = 0x70 ,
LSM303DLHC_ACC_ODR_1620Hz = 0x80 , LSM303DLHC_ACC_ODR_1344Hz = 0x90
}
LSM303DLHC accelerometer subsystem output data rate.
enum lsm303dlhc_acc_ae_t {
LSM303DLHC_ACC_AE_DISABLED = 0x00 , LSM303DLHC_ACC_AE_X = 0x01 , LSM303DLHC_ACC_AE_Y = 0x02 , LSM303DLHC_ACC_AE_XY = 0x03 ,
LSM303DLHC_ACC_AE_Z = 0x04 , LSM303DLHC_ACC_AE_XZ = 0x05 , LSM303DLHC_ACC_AE_YZ = 0x06 , LSM303DLHC_ACC_AE_XYZ = 0x07
}
LSM303DLHC accelerometer subsystem axes enabling.
enum lsm303dlhc_acc_lp_t { LSM303DLHC_ACC_LP_DISABLED = 0x00 , LSM303DLHC_ACC_LP_ENABLED = 0x40 }
LSM303DLHC accelerometer subsystem low power mode.
enum lsm303dlhc_acc_hr_t { LSM303DLHC_ACC_HR_DISABLED = 0x00 , LSM303DLHC_ACC_HR_ENABLED = 0x08 }
LSM303DLHC accelerometer subsystem high resolution mode.
enum lsm303dlhc_acc_bdu_t { LSM303DLHC_ACC_BDU_CONT = 0x00 , LSM303DLHC_ACC_BDU_BLOCK = 0x80 }
LSM303DLHC accelerometer subsystem block data update.
enum lsm303dlhc_acc_end_t { LSM303DLHC_ACC_END_LITTLE = 0x00 , LSM303DLHC_ACC_END_BIG = 0x40 }
LSM303DLHC accelerometer endianness.
typedef struct LSM303DLHCDriver LSM303DLHCDriver
Structure representing a LSM303DLHC driver.
LSM303DLHC compass subsystem data structures and types.
enum lsm303dlhc_comp_fs_t {
LSM303DLHC_COMP_FS_1P3GA = 0x20 , LSM303DLHC_COMP_FS_1P9GA = 0x40 , LSM303DLHC_COMP_FS_2P5GA = 0x60 , LSM303DLHC_COMP_FS_4P0GA = 0x80 ,
LSM303DLHC_COMP_FS_4P7GA = 0xA0 , LSM303DLHC_COMP_FS_5P6GA = 0xC0 , LSM303DLHC_COMP_FS_8P1GA = 0xE0
}
LSM303DLHC compass subsystem full scale.
enum lsm303dlhc_comp_odr_t {
LSM303DLHC_COMP_ODR_0P75HZ = 0x00 , LSM303DLHC_COMP_ODR_1P5HZ = 0x04 , LSM303DLHC_COMP_ODR_3P0HZ = 0x08 , LSM303DLHC_COMP_ODR_7P5HZ = 0x0C ,
LSM303DLHC_COMP_ODR_15HZ = 0x10 , LSM303DLHC_COMP_ODR_30HZ = 0x14 , LSM303DLHC_COMP_ODR_75HZ = 0x18 , LSM303DLHC_COMP_ODR_220HZ = 0x1C
}
LSM303DLHC compass subsystem output data rate.
enum lsm303dlhc_comp_md_t { LSM303DLHC_COMP_MD_CONT = 0x00 , LSM303DLHC_COMP_MD_BLOCK = 0x01 , LSM303DLHC_COMP_MD_SLEEP = 0x02 }
LSM303DLHC compass subsystem working mode.
LSM303DLHC main system data structures and types.
enum lsm303dlhc_state_t { LSM303DLHC_UNINIT = 0 , LSM303DLHC_STOP = 1 , LSM303DLHC_READY = 2 }
Driver state machine possible states.
#define _lsm303dlhc_methods_alone
LSM303DLHC specific methods.
#define _lsm303dlhc_methods
LSM303DLHC specific methods with inherited ones.
#define _lsm303dlhc_data
LSM303DLHCDriver specific data.
Version identification
#define EX_LSM303DLHC_VERSION "1.1.2"
LSM303DLHC driver version string.
#define EX_LSM303DLHC_MAJOR 1
LSM303DLHC driver version major number.
#define EX_LSM303DLHC_MINOR 1
LSM303DLHC driver version minor number.
#define EX_LSM303DLHC_PATCH 2
LSM303DLHC driver version patch number.
#define LSM303DLHC_ACC_NUMBER_OF_AXES 3U
LSM303DLHC accelerometer subsystem characteristics.
#define LSM303DLHC_COMP_NUMBER_OF_AXES 3U
LSM303DLHC compass subsystem characteristics.
LSM303DLHC communication interfaces related bit masks
#define LSM303DLHC_DI_MASK 0xFF
#define LSM303DLHC_DI(n) (1 << n)
#define LSM303DLHC_AD_MASK 0x7F
#define LSM303DLHC_AD(n) (1 << n)
#define LSM303DLHC_MS (1 << 7)
LSM303DLHC register addresses
#define LSM303DLHC_AD_ACC_CTRL_REG1 0x20
#define LSM303DLHC_AD_ACC_CTRL_REG2 0x21
#define LSM303DLHC_AD_ACC_CTRL_REG3 0x22
#define LSM303DLHC_AD_ACC_CTRL_REG4 0x23
#define LSM303DLHC_AD_ACC_CTRL_REG5 0x24
#define LSM303DLHC_AD_ACC_CTRL_REG6 0x25
#define LSM303DLHC_AD_ACC_REFERENCE 0x26
#define LSM303DLHC_AD_ACC_STATUS_REG 0x27
#define LSM303DLHC_AD_ACC_OUT_X_L 0x28
#define LSM303DLHC_AD_ACC_OUT_X_H 0x29
#define LSM303DLHC_AD_ACC_OUT_Y_L 0x2A
#define LSM303DLHC_AD_ACC_OUT_Y_H 0x2B
#define LSM303DLHC_AD_ACC_OUT_Z_L 0x2C
#define LSM303DLHC_AD_ACC_OUT_Z_H 0x2D
#define LSM303DLHC_AD_ACC_FIFO_CTRL_REG 0x2E
#define LSM303DLHC_AD_ACC_FIFO_SRC_REG 0x2F
#define LSM303DLHC_AD_ACC_INT1_CFG 0x30
#define LSM303DLHC_AD_ACC_INT1_SRC 0x31
#define LSM303DLHC_AD_ACC_INT1_THS 0x32
#define LSM303DLHC_AD_ACC_INT1_DURATION 0x33
#define LSM303DLHC_AD_ACC_INT2_CFG 0x34
#define LSM303DLHC_AD_ACC_INT2_SRC 0x35
#define LSM303DLHC_AD_ACC_INT2_THS 0x36
#define LSM303DLHC_AD_ACC_INT2_DURATION 0x37
#define LSM303DLHC_AD_ACC_CLICK_CFG 0x38
#define LSM303DLHC_AD_ACC_CLICK_SRC 0x39
#define LSM303DLHC_AD_ACC_CLICK_THS 0x3A
#define LSM303DLHC_AD_ACC_TIME_LIMIT 0x3B
#define LSM303DLHC_AD_ACC_TIME_LATENCY 0x3C
#define LSM303DLHC_AD_ACC_TIME_WINDOW 0x3D
#define LSM303DLHC_AD_COMP_CRA_REG 0x00
#define LSM303DLHC_AD_COMP_CRB_REG 0x01
#define LSM303DLHC_AD_COMP_MR_REG 0x02
#define LSM303DLHC_AD_COMP_OUT_X_H 0x03
#define LSM303DLHC_AD_COMP_OUT_X_L 0x04
#define LSM303DLHC_AD_COMP_OUT_Z_H 0x05
#define LSM303DLHC_AD_COMP_OUT_Z_L 0x06
#define LSM303DLHC_AD_COMP_OUT_Y_H 0x07
#define LSM303DLHC_AD_COMP_OUT_Y_L 0x08
#define LSM303DLHC_AD_COMP_SR_REG 0x09
#define LSM303DLHC_AD_COMP_IRA_REG 0x0A
#define LSM303DLHC_AD_COMP_IRB_REG 0x0B
#define LSM303DLHC_AD_COMP_IRC_REG 0x0C
#define LSM303DLHC_AD_COMP_TEMP_OUT_H 0x31
#define LSM303DLHC_AD_COMP_TEMP_OUT_L 0x32
LSM303DLHC_CTRL_REG1_A register bits definitions
#define LSM303DLHC_CTRL_REG1_A_MASK 0xFF
#define LSM303DLHC_CTRL_REG1_A_XEN (1 << 0)
#define LSM303DLHC_CTRL_REG1_A_YEN (1 << 1)
#define LSM303DLHC_CTRL_REG1_A_ZEN (1 << 2)
#define LSM303DLHC_CTRL_REG1_A_LPEN (1 << 3)
#define LSM303DLHC_CTRL_REG1_A_ODR0 (1 << 4)
#define LSM303DLHC_CTRL_REG1_A_ODR1 (1 << 5)
#define LSM303DLHC_CTRL_REG1_A_ODR2 (1 << 6)
#define LSM303DLHC_CTRL_REG1_A_ODR3 (1 << 7)
LSM303DLHC_CTRL_REG2_A register bits definitions
#define LSM303DLHC_CTRL_REG2_A_MASK 0xFF
#define LSM303DLHC_CTRL_REG2_A_HPIS1 (1 << 0)
#define LSM303DLHC_CTRL_REG2_A_HPIS2 (1 << 1)
#define LSM303DLHC_CTRL_REG2_A_HPCLICK (1 << 2)
#define LSM303DLHC_CTRL_REG2_A_FDS (1 << 3)
#define LSM303DLHC_CTRL_REG2_A_HPCF1 (1 << 4)
#define LSM303DLHC_CTRL_REG2_A_HPCF2 (1 << 5)
#define LSM303DLHC_CTRL_REG2_A_HPM0 (1 << 6)
#define LSM303DLHC_CTRL_REG2_A_HPM1 (1 << 7)
LSM303DLHC_CTRL_REG3_A register bits definitions
#define LSM303DLHC_CTRL_REG3_A_MASK 0xFD
#define LSM303DLHC_CTRL_REG3_A_I1_OVERRUN (1 << 1)
#define LSM303DLHC_CTRL_REG3_A_I1_WTM (1 << 2)
#define LSM303DLHC_CTRL_REG3_A_I1_DRDY2 (1 << 3)
#define LSM303DLHC_CTRL_REG3_A_I1_DRDY1 (1 << 4)
#define LSM303DLHC_CTRL_REG3_A_I1_AOI2 (1 << 5)
#define LSM303DLHC_CTRL_REG3_A_I1_AOI1 (1 << 6)
#define LSM303DLHC_CTRL_REG3_A_I1_CLICK (1 << 7)
LSM303DLHC_CTRL_REG4_A register bits definitions
#define LSM303DLHC_CTRL_REG4_A_MASK 0xF9
#define LSM303DLHC_CTRL_REG4_A_SIM (1 << 0)
#define LSM303DLHC_CTRL_REG4_A_HR (1 << 3)
#define LSM303DLHC_CTRL_REG4_A_FS_MASK 0x30
#define LSM303DLHC_CTRL_REG4_A_FS0 (1 << 4)
#define LSM303DLHC_CTRL_REG4_A_FS1 (1 << 5)
#define LSM303DLHC_CTRL_REG4_A_BLE (1 << 6)
#define LSM303DLHC_CTRL_REG4_A_BDU (1 << 7)
LSM303DLHC_CTRL_REG5_A register bits definitions
#define LSM303DLHC_CTRL_REG5_A_MASK 0xCF
#define LSM303DLHC_CTRL_REG5_A_D4D_INT2 (1 << 0)
#define LSM303DLHC_CTRL_REG5_A_LIR_INT2 (1 << 1)
#define LSM303DLHC_CTRL_REG5_A_D4D_INT1 (1 << 2)
#define LSM303DLHC_CTRL_REG5_A_LIR_INT1 (1 << 3)
#define LSM303DLHC_CTRL_REG5_A_FIFO_EN (1 << 6)
#define LSM303DLHC_CTRL_REG5_A_BOOT (1 << 7)
LSM303DLHC_CTRL_REG6_A register bits definitions
#define LSM303DLHC_CTRL_REG6_A_MASK 0xFA
#define LSM303DLHC_CTRL_REG6_A_H_LACTIVE (1 << 1)
#define LSM303DLHC_CTRL_REG6_A_P2_ACT (1 << 3)
#define LSM303DLHC_CTRL_REG6_A_BOOT_I1 (1 << 4)
#define LSM303DLHC_CTRL_REG6_A_I2_INT2 (1 << 5)
#define LSM303DLHC_CTRL_REG6_A_I2_INT1 (1 << 6)
#define LSM303DLHC_CTRL_REG6_A_I2_CLICKEN (1 << 7)
LSM303DLHC_CRA_REG_M register bits definitions
#define LSM303DLHC_CRA_REG_M_MASK 0x9C
#define LSM303DLHC_CRA_REG_M_DO0 (1 << 2)
#define LSM303DLHC_CRA_REG_M_DO1 (1 << 3)
#define LSM303DLHC_CRA_REG_M_DO2 (1 << 4)
#define LSM303DLHC_CRA_REG_M_TEMP_EN (1 << 7)
LSM303DLHC_CRB_REG_M register bits definitions
#define LSM303DLHC_CRB_REG_M_MASK 0xE0
#define LSM303DLHC_CRB_REG_M_GN_MASK 0xE0
#define LSM303DLHC_CRB_REG_M_GN0 (1 << 5)
#define LSM303DLHC_CRB_REG_M_GN1 (1 << 6)
#define LSM303DLHC_CRB_REG_M_GN2 (1 << 7)
#define LSM303DLHC_MR_REG_M_MASK 0x03
#define LSM303DLHC_MR_REG_M_MD0 (1 << 0)
#define LSM303DLHC_MR_REG_M_MD1 (1 << 1)
Configuration options
#define LSM303DLHC_USE_SPI FALSE
LSM303DLHC SPI interface switch.
#define LSM303DLHC_SHARED_SPI FALSE
LSM303DLHC shared SPI switch.
#define LSM303DLHC_USE_I2C TRUE
LSM303DLHC I2C interface switch.
#define LSM303DLHC_SHARED_I2C FALSE
LSM303DLHC shared I2C switch.
#define LSM303DLHC_USE_ADVANCED FALSE
LSM303DLHC advanced configurations switch.
Data Structures
struct LSM303DLHCConfig
LSM303DLHC configuration structure.
struct LSM303DLHCVMT
LSM303DLHC virtual methods table.
struct LSM303DLHCDriver
LSM303DLHC 6-axis accelerometer/compass class.
Functions
static msg_t lsm303dlhcI2CReadRegister (I2CDriver *i2cp, lsm303dlhc_sad_t sad, uint8_t reg, uint8_t *rxbuf, size_t n)
Reads registers value using I2C.
static msg_t lsm303dlhcI2CWriteRegister (I2CDriver *i2cp, lsm303dlhc_sad_t sad, uint8_t *txbuf, size_t n)
Writes a value into a register using I2C.
static size_t acc_get_axes_number (void *ip)
Return the number of axes of the BaseAccelerometer.
static msg_t acc_read_raw (void *ip, int32_t axes[])
Retrieves raw data from the BaseAccelerometer.
static msg_t acc_read_cooked (void *ip, float axes[])
Retrieves cooked data from the BaseAccelerometer.
static msg_t acc_set_bias (void *ip, float *bp)
Set bias values for the BaseAccelerometer.
static msg_t acc_reset_bias (void *ip)
Reset bias values for the BaseAccelerometer.
static msg_t acc_set_sensivity (void *ip, float *sp)
Set sensitivity values for the BaseAccelerometer.
static msg_t acc_reset_sensivity (void *ip)
Reset sensitivity values for the BaseAccelerometer.
static msg_t acc_set_full_scale (LSM303DLHCDriver *devp, lsm303dlhc_acc_fs_t fs)
Changes the LSM303DLHCDriver accelerometer fullscale value.
static size_t comp_get_axes_number (void *ip)
Return the number of axes of the BaseCompass.
static msg_t comp_read_raw (void *ip, int32_t axes[])
Retrieves raw data from the BaseCompass.
static msg_t comp_read_cooked (void *ip, float axes[])
Retrieves cooked data from the BaseCompass.
static msg_t comp_set_bias (void *ip, float *bp)
Set bias values for the BaseCompass.
static msg_t comp_reset_bias (void *ip)
Reset bias values for the BaseCompass.
static msg_t comp_set_sensivity (void *ip, float *sp)
Set sensitivity values for the BaseCompass.
static msg_t comp_reset_sensivity (void *ip)
Reset sensitivity values for the BaseCompass.
static msg_t comp_set_full_scale (LSM303DLHCDriver *devp, lsm303dlhc_comp_fs_t fs)
Changes the LSM303DLHCDriver compass fullscale value.
void lsm303dlhcObjectInit (LSM303DLHCDriver *devp)
Initializes an instance.
void lsm303dlhcStart (LSM303DLHCDriver *devp, const LSM303DLHCConfig *config)
Configures and activates LSM303DLHC Complex Driver peripheral.
void lsm303dlhcStop (LSM303DLHCDriver *devp)
Deactivates the LSM303DLHC Complex Driver peripheral.
Enumerations
enum lsm303dlhc_sad_t { LSM303DLHC_SAD_ACC = 0x19 , LSM303DLHC_SAD_COMP = 0x1E }
Accelerometer and Compass Slave Address.
Macro Definition Documentation
EX_LSM303DLHC_VERSION
#define EX_LSM303DLHC_VERSION "1.1.2"
LSM303DLHC driver version string.
Definition at line 46 of file lsm303dlhc.h.
EX_LSM303DLHC_MAJOR
#define EX_LSM303DLHC_MAJOR 1
LSM303DLHC driver version major number.
Definition at line 51 of file lsm303dlhc.h.
EX_LSM303DLHC_MINOR
#define EX_LSM303DLHC_MINOR 1
LSM303DLHC driver version minor number.
Definition at line 56 of file lsm303dlhc.h.
EX_LSM303DLHC_PATCH
#define EX_LSM303DLHC_PATCH 2
LSM303DLHC driver version patch number.
Definition at line 61 of file lsm303dlhc.h.
LSM303DLHC_ACC_NUMBER_OF_AXES
#define LSM303DLHC_ACC_NUMBER_OF_AXES 3U
LSM303DLHC accelerometer subsystem characteristics.
Note
Sensitivity is expressed as milli-G/LSB whereas 1 milli-G = 0.00980665 m/s^2.
Bias is expressed as milli-G.
Definition at line 72 of file lsm303dlhc.h.
LSM303DLHC_COMP_NUMBER_OF_AXES
#define LSM303DLHC_COMP_NUMBER_OF_AXES 3U
LSM303DLHC compass subsystem characteristics.
Note
Sensitivity is expressed as G/LSB whereas G stands for Gauss.
Bias is expressed as G.
Definition at line 94 of file lsm303dlhc.h.
LSM303DLHC_USE_SPI
#define LSM303DLHC_USE_SPI FALSE
LSM303DLHC SPI interface switch.
If set to TRUE the support for SPI is included.
Note
The default is FALSE.
Definition at line 314 of file lsm303dlhc.h.
LSM303DLHC_SHARED_SPI
#define LSM303DLHC_SHARED_SPI FALSE
LSM303DLHC shared SPI switch.
If set to TRUE the device acquires SPI bus ownership on each transaction.
Note
The default is FALSE. Requires SPI_USE_MUTUAL_EXCLUSION.
Definition at line 324 of file lsm303dlhc.h.
LSM303DLHC_USE_I2C
#define LSM303DLHC_USE_I2C TRUE
LSM303DLHC I2C interface switch.
If set to TRUE the support for I2C is included.
Note
The default is TRUE.
Definition at line 333 of file lsm303dlhc.h.
LSM303DLHC_SHARED_I2C
#define LSM303DLHC_SHARED_I2C FALSE
LSM303DLHC shared I2C switch.
If set to TRUE the device acquires I2C bus ownership on each transaction.
Note
The default is FALSE. Requires I2C_USE_MUTUAL_EXCLUSION.
Definition at line 343 of file lsm303dlhc.h.
LSM303DLHC_USE_ADVANCED
#define LSM303DLHC_USE_ADVANCED FALSE
LSM303DLHC advanced configurations switch.
If set to TRUE more configurations are available.
Note
The default is FALSE.
Definition at line 352 of file lsm303dlhc.h.
_lsm303dlhc_methods_alone
#define _lsm303dlhc_methods_alone
Value:
  /* Change full scale value of LSM303DLHC accelerometer subsystem.*/       \
  msg_t (*acc_set_full_scale)(LSM303DLHCDriver *devp,                       \
                              lsm303dlhc_acc_fs_t fs);                      \
  /* Change full scale value of LSM303DLHC compass subsystem.*/             \
  msg_t (*comp_set_full_scale)(LSM303DLHCDriver *devp,                      \
                              lsm303dlhc_comp_fs_t fs);                     \
LSM303DLHC specific methods.
Definition at line 600 of file lsm303dlhc.h.
_lsm303dlhc_methods
#define _lsm303dlhc_methods
Value:
  _base_object_methods                                                      \
  _lsm303dlhc_methods_alone
LSM303DLHC specific methods with inherited ones.
Definition at line 611 of file lsm303dlhc.h.
_lsm303dlhc_data
#define _lsm303dlhc_data
Value:
  _base_sensor_data                                                         \
  /* Driver state.*/                                                        \
  lsm303dlhc_state_t        state;                                          \
  /* Current configuration data.*/                                          \
  const LSM303DLHCConfig    *config;                                        \
  /* Accelerometer subsystem axes number.*/                                 \
  size_t                    accaxes;                                        \
  /* Accelerometer subsystem current sensitivity.*/                         \
  float                     accsensitivity[LSM303DLHC_ACC_NUMBER_OF_AXES];  \
  /* Accelerometer subsystem current bias .*/                               \
  float                     accbias[LSM303DLHC_ACC_NUMBER_OF_AXES];         \
  /* Accelerometer subsystem current full scale value.*/                    \
  float                     accfullscale;                                   \
  /* Compass subsystem axes number.*/                                       \
  size_t                    compaxes;                                       \
  /* Compass subsystem current sensitivity.*/                               \
  float                     compsensitivity[LSM303DLHC_COMP_NUMBER_OF_AXES];\
  /* Compass subsystem current bias.*/                                      \
  float                     compbias[LSM303DLHC_COMP_NUMBER_OF_AXES];       \
  /* Compass subsystem current full scale value.*/                          \
  float                     compfullscale;
LSM303DLHCDriver specific data.
Definition at line 627 of file lsm303dlhc.h.
lsm303dlhcAccelerometerGetAxesNumber
#define lsm303dlhcAccelerometerGetAxesNumber (devp) accelerometerGetAxesNumber(&((devp)->acc_if))
Return the number of axes of the BaseAccelerometer.
Parameters
[in] devp pointer to LSM303DLHCDriver.
Returns
the number of axes.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 677 of file lsm303dlhc.h.
lsm303dlhcAccelerometerReadRaw
#define lsm303dlhcAccelerometerReadRaw (devp, axes) accelerometerReadRaw(&((devp)->acc_if), axes)
Retrieves raw data from the BaseAccelerometer.
Note
This data is retrieved from MEMS register without any algebraical manipulation.
The axes array must be at least the same size of the BaseAccelerometer axes number.
Parameters
[in] devp pointer to LSM303DLHCDriver.
[out] axes a buffer which would be filled with raw data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 698 of file lsm303dlhc.h.
lsm303dlhcAccelerometerReadCooked
#define lsm303dlhcAccelerometerReadCooked (devp, axes) accelerometerReadCooked(&((devp)->acc_if), axes)
Retrieves cooked data from the BaseAccelerometer.
Note
This data is manipulated according to the formula cooked = (raw * sensitivity) - bias.
Final data is expressed as milli-G.
The axes array must be at least the same size of the BaseAccelerometer axes number.
Parameters
[in] devp pointer to LSM303DLHCDriver.
[out] axes a buffer which would be filled with cooked data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 720 of file lsm303dlhc.h.
lsm303dlhcAccelerometerSetBias
#define lsm303dlhcAccelerometerSetBias (devp, bp) accelerometerSetBias(&((devp)->acc_if), bp)
Set bias values for the BaseAccelerometer.
Note
Bias must be expressed as milli-G.
The bias buffer must be at least the same size of the BaseAccelerometer axes number.
Parameters
[in] devp pointer to LSM303DLHCDriver.
[in] bp a buffer which contains biases.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 737 of file lsm303dlhc.h.
lsm303dlhcAccelerometerResetBias
#define lsm303dlhcAccelerometerResetBias (devp) accelerometerResetBias(&((devp)->acc_if))
Reset bias values for the BaseAccelerometer.
Note
Default biases value are obtained from device datasheet when available otherwise they are considered zero.
Parameters
[in] devp pointer to LSM303DLHCDriver.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 752 of file lsm303dlhc.h.
lsm303dlhcAccelerometerSetSensitivity
#define lsm303dlhcAccelerometerSetSensitivity (devp, sp) accelerometerSetSensitivity(&((devp)->acc_if), sp)
Set sensitivity values for the BaseAccelerometer.
Note
Sensitivity must be expressed as milli-G/LSB.
The sensitivity buffer must be at least the same size of the BaseAccelerometer axes number.
Parameters
[in] devp pointer to LSM303DLHCDriver.
[in] sp a buffer which contains sensitivities.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 769 of file lsm303dlhc.h.
lsm303dlhcAccelerometerResetSensitivity
#define lsm303dlhcAccelerometerResetSensitivity (devp) accelerometerResetSensitivity(&((devp)->acc_if))
Reset sensitivity values for the BaseAccelerometer.
Note
Default sensitivities value are obtained from device datasheet.
Parameters
[in] devp pointer to LSM303DLHCDriver.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET otherwise.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 784 of file lsm303dlhc.h.
lsm303dlhcAccelerometerSetFullScale
#define lsm303dlhcAccelerometerSetFullScale (devp, fs) (devp)->vmt->acc_set_full_scale(devp, fs)
Changes the LSM303DLHCDriver accelerometer fullscale value.
Note
This function also rescale sensitivities and biases based on previous and next fullscale value.
A recalibration is highly suggested after calling this function.
Parameters
[in] devp pointer to LSM303DLHCDriver.
[in] fs new fullscale value.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET otherwise.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 802 of file lsm303dlhc.h.
lsm303dlhcCompassGetAxesNumber
#define lsm303dlhcCompassGetAxesNumber (devp) compassGetAxesNumber(&((devp)->comp_if))
Return the number of axes of the BaseCompass.
Parameters
[in] devp pointer to LSM303DLHCDriver.
Returns
the number of axes.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 814 of file lsm303dlhc.h.
lsm303dlhcCompassReadRaw
#define lsm303dlhcCompassReadRaw (devp, axes) compassReadRaw(&((devp)->comp_if), axes)
Retrieves raw data from the BaseCompass.
Note
This data is retrieved from MEMS register without any algebraical manipulation.
The axes array must be at least the same size of the BaseCompass axes number.
Parameters
[in] devp pointer to BaseCompass interface.
[out] axes a buffer which would be filled with raw data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 835 of file lsm303dlhc.h.
lsm303dlhcCompassReadCooked
#define lsm303dlhcCompassReadCooked (devp, axes) compassReadCooked(&((devp)->comp_if), axes)
Retrieves cooked data from the BaseCompass.
Note
This data is manipulated according to the formula cooked = (raw * sensitivity) - bias.
Final data is expressed as G.
The axes array must be at least the same size of the BaseCompass axes number.
Parameters
[in] devp pointer to BaseCompass interface.
[out] axes a buffer which would be filled with cooked data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 857 of file lsm303dlhc.h.
lsm303dlhcCompassSetBias
#define lsm303dlhcCompassSetBias (devp, bp) compassSetBias(&((devp)->comp_if), bp)
Set bias values for the BaseCompass.
Note
Bias must be expressed as G.
The bias buffer must be at least the same size of the BaseCompass axes number.
Parameters
[in] devp pointer to BaseCompass interface.
[in] bp a buffer which contains biases.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 874 of file lsm303dlhc.h.
lsm303dlhcCompassResetBias
#define lsm303dlhcCompassResetBias (devp) compassResetBias(&((devp)->comp_if))
Reset bias values for the BaseCompass.
Note
Default biases value are obtained from device datasheet when available otherwise they are considered zero.
Parameters
[in] devp pointer to LSM303DLHCDriver.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 889 of file lsm303dlhc.h.
lsm303dlhcCompassSetSensitivity
#define lsm303dlhcCompassSetSensitivity (devp, sp) compassSetSensitivity(&((devp)->comp_if), sp)
Set sensitivity values for the BaseCompass.
Note
Sensitivity must be expressed as G/LSB.
The sensitivity buffer must be at least the same size of the BaseCompass axes number.
Parameters
[in] devp pointer to LSM303DLHCDriver.
[in] sp a buffer which contains sensitivities.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 906 of file lsm303dlhc.h.
lsm303dlhcCompassResetSensitivity
#define lsm303dlhcCompassResetSensitivity (devp) compassResetSensitivity(&((devp)->comp_if))
Reset sensitivity values for the BaseCompass.
Note
Default sensitivities value are obtained from device datasheet.
Parameters
[in] devp pointer to LSM303DLHCDriver.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET otherwise.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 921 of file lsm303dlhc.h.
lsm303dlhcCompassSetFullScale
#define lsm303dlhcCompassSetFullScale (devp, fs) (devp)->vmt->comp_set_full_scale(devp, fs)
Changes the LSM303DLHCDriver compass fullscale value.
Note
This function also rescale sensitivities and biases based on previous and next fullscale value.
A recalibration is highly suggested after calling this function.
Parameters
[in] devp pointer to LSM303DLHCDriver.
[in] fs new fullscale value.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET otherwise.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 939 of file lsm303dlhc.h.
Typedef Documentation
LSM303DLHCDriver
typedef struct LSM303DLHCDriver LSM303DLHCDriver
Structure representing a LSM303DLHC driver.
Definition at line 1 of file lsm303dlhc.h.
Enumeration Type Documentation
lsm303dlhc_sad_t
enum lsm303dlhc_sad_t
Accelerometer and Compass Slave Address.
Enumerator
LSM303DLHC_SAD_ACC
SAD for accelerometer.
LSM303DLHC_SAD_COMP
SAD for compass.
Definition at line 48 of file lsm303dlhc.c.
lsm303dlhc_acc_fs_t
enum lsm303dlhc_acc_fs_t
LSM303DLHC accelerometer subsystem full scale.
Enumerator
LSM303DLHC_ACC_FS_2G
Full scale 2g.
LSM303DLHC_ACC_FS_4G
Full scale 4g.
LSM303DLHC_ACC_FS_8G
Full scale 8g.
LSM303DLHC_ACC_FS_16G
Full scale 16g.
Definition at line 403 of file lsm303dlhc.h.
lsm303dlhc_acc_odr_t
enum lsm303dlhc_acc_odr_t
LSM303DLHC accelerometer subsystem output data rate.
Enumerator
LSM303DLHC_ACC_ODR_PD
Power down
LSM303DLHC_ACC_ODR_1Hz
ODR 1 Hz
LSM303DLHC_ACC_ODR_10Hz
ODR 10 Hz
LSM303DLHC_ACC_ODR_25Hz
ODR 25 Hz
LSM303DLHC_ACC_ODR_50Hz
ODR 50 Hz
LSM303DLHC_ACC_ODR_100Hz
ODR 100 Hz
LSM303DLHC_ACC_ODR_200Hz
ODR 200 Hz
LSM303DLHC_ACC_ODR_400Hz
ODR 400 Hz
LSM303DLHC_ACC_ODR_1620Hz
ODR 1620 Hz (LP only)
LSM303DLHC_ACC_ODR_1344Hz
ODR 1344 Hz or 5376 Hz in LP
Definition at line 413 of file lsm303dlhc.h.
lsm303dlhc_acc_ae_t
enum lsm303dlhc_acc_ae_t
LSM303DLHC accelerometer subsystem axes enabling.
Enumerator
LSM303DLHC_ACC_AE_DISABLED
All axes disabled.
LSM303DLHC_ACC_AE_X
Only X-axis enabled.
LSM303DLHC_ACC_AE_Y
Only Y-axis enabled.
LSM303DLHC_ACC_AE_XY
X and Y axes enabled.
LSM303DLHC_ACC_AE_Z
Only Z-axis enabled.
LSM303DLHC_ACC_AE_XZ
X and Z axes enabled.
LSM303DLHC_ACC_AE_YZ
Y and Z axes enabled.
LSM303DLHC_ACC_AE_XYZ
All axes enabled.
Definition at line 429 of file lsm303dlhc.h.
lsm303dlhc_acc_lp_t
enum lsm303dlhc_acc_lp_t
LSM303DLHC accelerometer subsystem low power mode.
Enumerator
LSM303DLHC_ACC_LP_DISABLED
Low power mode disabled.
LSM303DLHC_ACC_LP_ENABLED
Low power mode enabled.
Definition at line 443 of file lsm303dlhc.h.
lsm303dlhc_acc_hr_t
enum lsm303dlhc_acc_hr_t
LSM303DLHC accelerometer subsystem high resolution mode.
Enumerator
LSM303DLHC_ACC_HR_DISABLED
High resolution mode disabled.
LSM303DLHC_ACC_HR_ENABLED
High resolution mode enabled.
Definition at line 451 of file lsm303dlhc.h.
lsm303dlhc_acc_bdu_t
enum lsm303dlhc_acc_bdu_t
LSM303DLHC accelerometer subsystem block data update.
Enumerator
LSM303DLHC_ACC_BDU_CONT
Continuous update
LSM303DLHC_ACC_BDU_BLOCK
Update blocked
Definition at line 459 of file lsm303dlhc.h.
lsm303dlhc_acc_end_t
enum lsm303dlhc_acc_end_t
LSM303DLHC accelerometer endianness.
Enumerator
LSM303DLHC_ACC_END_LITTLE
Little Endian
LSM303DLHC_ACC_END_BIG
Big Endian
Definition at line 467 of file lsm303dlhc.h.
lsm303dlhc_comp_fs_t
enum lsm303dlhc_comp_fs_t
LSM303DLHC compass subsystem full scale.
Enumerator
LSM303DLHC_COMP_FS_1P3GA
Full scale 1.3 Gauss
LSM303DLHC_COMP_FS_1P9GA
Full scale 1.9 Gauss
LSM303DLHC_COMP_FS_2P5GA
Full scale 2.5 Gauss
LSM303DLHC_COMP_FS_4P0GA
Full scale 4.0 Gauss
LSM303DLHC_COMP_FS_4P7GA
Full scale 4.7 Gauss
LSM303DLHC_COMP_FS_5P6GA
Full scale 5.6 Gauss
LSM303DLHC_COMP_FS_8P1GA
Full scale 8.1 Gauss
Definition at line 480 of file lsm303dlhc.h.
lsm303dlhc_comp_odr_t
enum lsm303dlhc_comp_odr_t
LSM303DLHC compass subsystem output data rate.
Enumerator
LSM303DLHC_COMP_ODR_0P75HZ
ODR 0.75 Hz
LSM303DLHC_COMP_ODR_1P5HZ
ODR 1.5 Hz
LSM303DLHC_COMP_ODR_3P0HZ
ODR 3 Hz
LSM303DLHC_COMP_ODR_7P5HZ
ODR 7.5 Hz
LSM303DLHC_COMP_ODR_15HZ
ODR 15 Hz
LSM303DLHC_COMP_ODR_30HZ
ODR 30 Hz
LSM303DLHC_COMP_ODR_75HZ
ODR 75 Hz
LSM303DLHC_COMP_ODR_220HZ
ODR 220 Hz
Definition at line 493 of file lsm303dlhc.h.
lsm303dlhc_comp_md_t
enum lsm303dlhc_comp_md_t
LSM303DLHC compass subsystem working mode.
Enumerator
LSM303DLHC_COMP_MD_CONT
Continuous-Conversion Mode
LSM303DLHC_COMP_MD_BLOCK
Single-Conversion Mode
LSM303DLHC_COMP_MD_SLEEP
Sleep Mode
Definition at line 507 of file lsm303dlhc.h.
lsm303dlhc_state_t
enum lsm303dlhc_state_t
Driver state machine possible states.
Enumerator
LSM303DLHC_UNINIT
Not initialized.
LSM303DLHC_STOP
Stopped.
LSM303DLHC_READY
Ready.
Definition at line 521 of file lsm303dlhc.h.
Function Documentation
lsm303dlhcI2CReadRegister()
static msg_t lsm303dlhcI2CReadRegister (I2CDriver * i2cp, lsm303dlhc_sad_t sad, uint8_t reg, uint8_t * rxbuf, size_t n) static
Reads registers value using I2C.
Precondition
The I2C interface must be initialized and the driver started.
Note
IF_ADD_INC bit must be 1 in CTRL_REG8.
Parameters
[in] i2cp pointer to the I2C interface.
[in] sad slave address without R bit.
[in] reg first sub-register address.
[in] rxbuf receiving buffer.
[in] n size of rxbuf.
Returns
the operation status.
Definition at line 69 of file lsm303dlhc.c.
Referenced by acc_read_raw(), and comp_read_raw().
lsm303dlhcI2CWriteRegister()
static msg_t lsm303dlhcI2CWriteRegister (I2CDriver * i2cp, lsm303dlhc_sad_t sad, uint8_t * txbuf, size_t n) static
Writes a value into a register using I2C.
Precondition
The I2C interface must be initialized and the driver started.
Parameters
[in] i2cp pointer to the I2C interface.
[in] sad slave address without R bit.
[in] txbuf buffer containing sub-address value in first position and values to write.
[in] n size of txbuf less one (not considering the first element).
Returns
the operation status.
Definition at line 89 of file lsm303dlhc.c.
acc_get_axes_number()
static size_t acc_get_axes_number (void * ip) static
Return the number of axes of the BaseAccelerometer.
Parameters
[in] ip pointer to BaseAccelerometer interface.
Returns
the number of axes.
Definition at line 104 of file lsm303dlhc.c.
References LSM303DLHC_ACC_NUMBER_OF_AXES.
acc_read_raw()
static msg_t acc_read_raw (void * ip, int32_t axes[]) static
Retrieves raw data from the BaseAccelerometer.
Note
This data is retrieved from MEMS register without any algebraical manipulation.
The axes array must be at least the same size of the BaseAccelerometer axes number.
Parameters
[in] ip pointer to BaseAccelerometer interface.
[out] axes a buffer which would be filled with raw data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Definition at line 126 of file lsm303dlhc.c.
References LSM303DLHC_ACC_NUMBER_OF_AXES, LSM303DLHC_READY, LSM303DLHC_SAD_ACC, and lsm303dlhcI2CReadRegister().
Referenced by acc_read_cooked().
acc_read_cooked()
static msg_t acc_read_cooked (void * ip, float axes[]) static
Retrieves cooked data from the BaseAccelerometer.
Note
This data is manipulated according to the formula cooked = (raw * sensitivity) - bias.
Final data is expressed as milli-G.
The axes array must be at least the same size of the BaseAccelerometer axes number.
Parameters
[in] ip pointer to BaseAccelerometer interface.
[out] axes a buffer which would be filled with cooked data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Definition at line 181 of file lsm303dlhc.c.
References acc_read_raw(), LSM303DLHC_ACC_NUMBER_OF_AXES, and LSM303DLHC_READY.
acc_set_bias()
static msg_t acc_set_bias (void * ip, float * bp) static
Set bias values for the BaseAccelerometer.
Note
Bias must be expressed as milli-G.
The bias buffer must be at least the same size of the BaseAccelerometer axes number.
Parameters
[in] ip pointer to BaseAccelerometer interface.
[in] bp a buffer which contains biases.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Definition at line 214 of file lsm303dlhc.c.
References LSM303DLHC_ACC_NUMBER_OF_AXES, and LSM303DLHC_READY.
acc_reset_bias()
static msg_t acc_reset_bias (void * ip) static
Reset bias values for the BaseAccelerometer.
Note
Default biases value are obtained from device datasheet when available otherwise they are considered zero.
Parameters
[in] ip pointer to BaseAccelerometer interface.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Definition at line 243 of file lsm303dlhc.c.
References LSM303DLHC_ACC_NUMBER_OF_AXES, and LSM303DLHC_READY.
acc_set_sensivity()
static msg_t acc_set_sensivity (void * ip, float * sp) static
Set sensitivity values for the BaseAccelerometer.
Note
Sensitivity must be expressed as milli-G/LSB.
The sensitivity buffer must be at least the same size of the BaseAccelerometer axes number.
Parameters
[in] ip pointer to BaseAccelerometer interface.
[in] sp a buffer which contains sensitivities.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Definition at line 273 of file lsm303dlhc.c.
References LSM303DLHC_ACC_NUMBER_OF_AXES, and LSM303DLHC_READY.
acc_reset_sensivity()
static msg_t acc_reset_sensivity (void * ip) static
Reset sensitivity values for the BaseAccelerometer.
Note
Default sensitivities value are obtained from device datasheet.
Parameters
[in] ip pointer to BaseAccelerometer interface.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET otherwise.
Definition at line 302 of file lsm303dlhc.c.
References LSM303DLHC_ACC_FS_2G, LSM303DLHC_ACC_NUMBER_OF_AXES, and LSM303DLHC_READY.
acc_set_full_scale()
static msg_t acc_set_full_scale (LSM303DLHCDriver * devp, lsm303dlhc_acc_fs_t fs) static
Changes the LSM303DLHCDriver accelerometer fullscale value.
Note
This function also rescale sensitivities and biases based on previous and next fullscale value.
A recalibration is highly suggested after calling this function.
Parameters
[in] devp pointer to LSM303DLHCDriver interface.
[in] fs new fullscale value.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET otherwise.
Definition at line 347 of file lsm303dlhc.c.
References LSM303DLHC_ACC_FS_2G, and LSM303DLHC_READY.
comp_get_axes_number()
static size_t comp_get_axes_number (void * ip) static
Return the number of axes of the BaseCompass.
Parameters
[in] ip pointer to BaseCompass interface
Returns
the number of axes.
Definition at line 437 of file lsm303dlhc.c.
References LSM303DLHC_COMP_NUMBER_OF_AXES.
comp_read_raw()
static msg_t comp_read_raw (void * ip, int32_t axes[]) static
Retrieves raw data from the BaseCompass.
Note
This data is retrieved from MEMS register without any algebraical manipulation.
The axes array must be at least the same size of the BaseCompass axes number.
Parameters
[in] ip pointer to BaseCompass interface.
[out] axes a buffer which would be filled with raw data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Definition at line 459 of file lsm303dlhc.c.
References LSM303DLHC_COMP_NUMBER_OF_AXES, LSM303DLHC_READY, LSM303DLHC_SAD_COMP, and lsm303dlhcI2CReadRegister().
Referenced by comp_read_cooked().
comp_read_cooked()
static msg_t comp_read_cooked (void * ip, float axes[]) static
Retrieves cooked data from the BaseCompass.
Note
This data is manipulated according to the formula cooked = (raw * sensitivity) - bias.
Final data is expressed as G.
The axes array must be at least the same size of the BaseCompass axes number.
Parameters
[in] ip pointer to BaseCompass interface.
[out] axes a buffer which would be filled with cooked data.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Definition at line 513 of file lsm303dlhc.c.
References comp_read_raw(), LSM303DLHC_COMP_NUMBER_OF_AXES, and LSM303DLHC_READY.
comp_set_bias()
static msg_t comp_set_bias (void * ip, float * bp) static
Set bias values for the BaseCompass.
Note
Bias must be expressed as G.
The bias buffer must be at least the same size of the BaseCompass axes number.
Parameters
[in] ip pointer to BaseCompass interface.
[in] bp a buffer which contains biases.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Definition at line 547 of file lsm303dlhc.c.
References LSM303DLHC_COMP_NUMBER_OF_AXES, and LSM303DLHC_READY.
comp_reset_bias()
static msg_t comp_reset_bias (void * ip) static
Reset bias values for the BaseCompass.
Note
Default biases value are obtained from device datasheet when available otherwise they are considered zero.
Parameters
[in] ip pointer to BaseCompass interface.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Definition at line 576 of file lsm303dlhc.c.
References LSM303DLHC_COMP_NUMBER_OF_AXES, and LSM303DLHC_READY.
comp_set_sensivity()
static msg_t comp_set_sensivity (void * ip, float * sp) static
Set sensitivity values for the BaseCompass.
Note
Sensitivity must be expressed as G/LSB.
The sensitivity buffer must be at least the same size of the BaseCompass axes number.
Parameters
[in] ip pointer to BaseCompass interface.
[in] sp a buffer which contains sensitivities.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
Definition at line 606 of file lsm303dlhc.c.
References LSM303DLHC_COMP_NUMBER_OF_AXES, and LSM303DLHC_READY.
comp_reset_sensivity()
static msg_t comp_reset_sensivity (void * ip) static
Reset sensitivity values for the BaseCompass.
Note
Default sensitivities value are obtained from device datasheet.
Parameters
[in] ip pointer to BaseCompass interface.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET otherwise.
Definition at line 635 of file lsm303dlhc.c.
References LSM303DLHC_COMP_FS_1P3GA, LSM303DLHC_COMP_NUMBER_OF_AXES, and LSM303DLHC_READY.
comp_set_full_scale()
static msg_t comp_set_full_scale (LSM303DLHCDriver * devp, lsm303dlhc_comp_fs_t fs) static
Changes the LSM303DLHCDriver compass fullscale value.
Note
This function also rescale sensitivities and biases based on previous and next fullscale value.
A recalibration is highly suggested after calling this function.
Parameters
[in] devp pointer to LSM303DLHCDriver interface.
[in] fs new fullscale value.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET otherwise.
Definition at line 731 of file lsm303dlhc.c.
References LSM303DLHC_COMP_FS_1P3GA, and LSM303DLHC_READY.
lsm303dlhcObjectInit()
void lsm303dlhcObjectInit (LSM303DLHCDriver * devp)
Initializes an instance.
Parameters
[out] devp pointer to the LSM303DLHCDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 847 of file lsm303dlhc.c.
References LSM303DLHCDriver::vmt.
lsm303dlhcStart()
void lsm303dlhcStart (LSM303DLHCDriver * devp, const LSM303DLHCConfig * config)
Configures and activates LSM303DLHC Complex Driver peripheral.
Parameters
[in] devp pointer to the LSM303DLHCDriver object
[in] config pointer to the LSM303DLHCConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 868 of file lsm303dlhc.c.
References LSM303DLHC_READY, and LSM303DLHC_STOP.
lsm303dlhcStop()
void lsm303dlhcStop (LSM303DLHCDriver * devp)
Deactivates the LSM303DLHC Complex Driver peripheral.
Parameters
[in] devp pointer to the LSM303DLHCDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 1142 of file lsm303dlhc.c.
References LSM303DLHC_READY, and LSM303DLHC_STOP.