ChibiOS/RT: Dynamic Objects Factory
Dynamic Objects Factory
OS Library » Complex Services
Detailed Description
The object factory is a subsystem that allows to:
Register static objects by name.
Dynamically create objects and assign them a name.
Retrieve existing objects by name.
Free objects by reference.
Allocated OS objects are handled using a reference counter, only when all references have been released then the object memory is freed in a pool.
Precondition
This subsystem requires the CH_CFG_USE_MEMCORE and CH_CFG_USE_MEMPOOLS options to be set to TRUE. The option CH_CFG_USE_HEAP is also required if the support for variable length objects is enabled.
Note
Compatible with RT and NIL.
Macros
#define CH_CFG_FACTORY_MAX_NAMES_LENGTH 8
Maximum length for object names.
#define CH_CFG_FACTORY_OBJECTS_REGISTRY TRUE
Enables the registry of generic objects.
#define CH_CFG_FACTORY_GENERIC_BUFFERS TRUE
Enables factory for generic buffers.
#define CH_CFG_FACTORY_SEMAPHORES TRUE
Enables factory for semaphores.
#define CH_CFG_FACTORY_SEMAPHORES FALSE
Enables factory for semaphores.
#define CH_CFG_FACTORY_MAILBOXES TRUE
Enables factory for mailboxes.
#define CH_CFG_FACTORY_MAILBOXES FALSE
Enables factory for mailboxes.
#define CH_CFG_FACTORY_OBJ_FIFOS TRUE
Enables factory for objects FIFOs.
#define CH_CFG_FACTORY_OBJ_FIFOS TRUE
Enables factory for objects FIFOs.
#define CH_CFG_FACTORY_OBJ_FIFOS FALSE
Enables factory for objects FIFOs.
#define CH_CFG_FACTORY_PIPES TRUE
Enables factory for Pipes.
#define CH_CFG_FACTORY_PIPES FALSE
Enables factory for Pipes.
Typedefs
typedef struct ch_dyn_element dyn_element_t
Type of a dynamic object list element.
typedef struct ch_dyn_list dyn_list_t
Type of a dynamic object list.
typedef struct ch_registered_static_object registered_object_t
Type of a registered object.
typedef struct ch_dyn_object dyn_buffer_t
Type of a dynamic buffer object.
typedef struct ch_dyn_semaphore dyn_semaphore_t
Type of a dynamic semaphore.
typedef struct ch_dyn_mailbox dyn_mailbox_t
Type of a dynamic buffer object.
typedef struct ch_dyn_objects_fifo dyn_objects_fifo_t
Type of a dynamic buffer object.
typedef struct ch_dyn_pipe dyn_pipe_t
Type of a dynamic pipe object.
typedef struct ch_objects_factory objects_factory_t
Type of the factory main object.
Data Structures
struct ch_dyn_element
Type of a dynamic object list element.
struct ch_dyn_list
Type of a dynamic object list.
struct ch_registered_static_object
Type of a registered object.
struct ch_dyn_object
Type of a dynamic buffer object.
struct ch_dyn_semaphore
Type of a dynamic semaphore.
struct ch_dyn_mailbox
Type of a dynamic buffer object.
struct ch_dyn_objects_fifo
Type of a dynamic buffer object.
struct ch_dyn_pipe
Type of a dynamic pipe object.
struct ch_objects_factory
Type of the factory main object.
Functions
void __factory_init (void)
Initializes the objects factory.
registered_object_t * chFactoryRegisterObject (const char *name, void *objp)
Registers a generic object.
registered_object_t * chFactoryFindObject (const char *name)
Retrieves a registered object.
registered_object_t * chFactoryFindObjectByPointer (void *objp)
Retrieves a registered object by pointer.
void chFactoryReleaseObject (registered_object_t *rop)
Releases a registered object.
dyn_buffer_t * chFactoryCreateBuffer (const char *name, size_t size)
Creates a generic dynamic buffer object.
dyn_buffer_t * chFactoryFindBuffer (const char *name)
Retrieves a dynamic buffer object.
void chFactoryReleaseBuffer (dyn_buffer_t *dbp)
Releases a dynamic buffer object.
dyn_semaphore_t * chFactoryCreateSemaphore (const char *name, cnt_t n)
Creates a dynamic semaphore object.
dyn_semaphore_t * chFactoryFindSemaphore (const char *name)
Retrieves a dynamic semaphore object.
void chFactoryReleaseSemaphore (dyn_semaphore_t *dsp)
Releases a dynamic semaphore object.
dyn_mailbox_t * chFactoryCreateMailbox (const char *name, size_t n)
Creates a dynamic mailbox object.
dyn_mailbox_t * chFactoryFindMailbox (const char *name)
Retrieves a dynamic mailbox object.
void chFactoryReleaseMailbox (dyn_mailbox_t *dmp)
Releases a dynamic mailbox object.
dyn_objects_fifo_t * chFactoryCreateObjectsFIFO (const char *name, size_t objsize, size_t objn, unsigned objalign)
Creates a dynamic "objects FIFO" object.
dyn_objects_fifo_t * chFactoryFindObjectsFIFO (const char *name)
Retrieves a dynamic "objects FIFO" object.
void chFactoryReleaseObjectsFIFO (dyn_objects_fifo_t *dofp)
Releases a dynamic "objects FIFO" object.
dyn_pipe_t * chFactoryCreatePipe (const char *name, size_t size)
Creates a dynamic pipe object.
dyn_pipe_t * chFactoryFindPipe (const char *name)
Retrieves a dynamic pipe object.
void chFactoryReleasePipe (dyn_pipe_t *dpp)
Releases a dynamic pipe object.
static dyn_element_t * chFactoryDuplicateReference (dyn_element_t *dep)
Duplicates an object reference.
static void * chFactoryGetObject (registered_object_t *rop)
Returns the pointer to the inner registered object.
static size_t chFactoryGetBufferSize (dyn_buffer_t *dbp)
Returns the size of a generic dynamic buffer object.
static uint8_t * chFactoryGetBuffer (dyn_buffer_t *dbp)
Returns the pointer to the inner buffer.
static semaphore_t * chFactoryGetSemaphore (dyn_semaphore_t *dsp)
Returns the pointer to the inner semaphore.
static mailbox_t * chFactoryGetMailbox (dyn_mailbox_t *dmp)
Returns the pointer to the inner mailbox.
static objects_fifo_t * chFactoryGetObjectsFIFO (dyn_objects_fifo_t *dofp)
Returns the pointer to the inner objects FIFO.
static pipe_t * chFactoryGetPipe (dyn_pipe_t *dpp)
Returns the pointer to the inner pipe.
Variables
objects_factory_t ch_factory
Factory object static instance.
Macro Definition Documentation
CH_CFG_FACTORY_MAX_NAMES_LENGTH
#define CH_CFG_FACTORY_MAX_NAMES_LENGTH 8
Maximum length for object names.
If the specified length is zero then the name is stored by pointer but this could have unintended side effects.
Definition at line 47 of file chfactory.h.
CH_CFG_FACTORY_OBJECTS_REGISTRY
#define CH_CFG_FACTORY_OBJECTS_REGISTRY TRUE
Enables the registry of generic objects.
Definition at line 54 of file chfactory.h.
CH_CFG_FACTORY_GENERIC_BUFFERS
#define CH_CFG_FACTORY_GENERIC_BUFFERS TRUE
Enables factory for generic buffers.
Definition at line 61 of file chfactory.h.
CH_CFG_FACTORY_SEMAPHORES [1/2]
#define CH_CFG_FACTORY_SEMAPHORES TRUE
Enables factory for semaphores.
Definition at line 106 of file chfactory.h.
CH_CFG_FACTORY_SEMAPHORES [2/2]
#define CH_CFG_FACTORY_SEMAPHORES FALSE
Enables factory for semaphores.
Definition at line 106 of file chfactory.h.
CH_CFG_FACTORY_MAILBOXES [1/2]
#define CH_CFG_FACTORY_MAILBOXES TRUE
Enables factory for mailboxes.
Definition at line 113 of file chfactory.h.
CH_CFG_FACTORY_MAILBOXES [2/2]
#define CH_CFG_FACTORY_MAILBOXES FALSE
Enables factory for mailboxes.
Definition at line 113 of file chfactory.h.
CH_CFG_FACTORY_OBJ_FIFOS [1/3]
#define CH_CFG_FACTORY_OBJ_FIFOS TRUE
Enables factory for objects FIFOs.
Definition at line 120 of file chfactory.h.
CH_CFG_FACTORY_OBJ_FIFOS [2/3]
#define CH_CFG_FACTORY_OBJ_FIFOS TRUE
Enables factory for objects FIFOs.
Definition at line 120 of file chfactory.h.
CH_CFG_FACTORY_OBJ_FIFOS [3/3]
#define CH_CFG_FACTORY_OBJ_FIFOS FALSE
Enables factory for objects FIFOs.
Definition at line 120 of file chfactory.h.
CH_CFG_FACTORY_PIPES [1/2]
#define CH_CFG_FACTORY_PIPES TRUE
Enables factory for Pipes.
Definition at line 127 of file chfactory.h.
CH_CFG_FACTORY_PIPES [2/2]
#define CH_CFG_FACTORY_PIPES FALSE
Enables factory for Pipes.
Definition at line 127 of file chfactory.h.
Typedef Documentation
dyn_element_t
typedef struct ch_dyn_element dyn_element_t
Type of a dynamic object list element.
dyn_list_t
typedef struct ch_dyn_list dyn_list_t
Type of a dynamic object list.
registered_object_t
typedef struct ch_registered_static_object registered_object_t
Type of a registered object.
dyn_buffer_t
typedef struct ch_dyn_object dyn_buffer_t
Type of a dynamic buffer object.
dyn_semaphore_t
typedef struct ch_dyn_semaphore dyn_semaphore_t
Type of a dynamic semaphore.
dyn_mailbox_t
typedef struct ch_dyn_mailbox dyn_mailbox_t
Type of a dynamic buffer object.
dyn_objects_fifo_t
typedef struct ch_dyn_objects_fifo dyn_objects_fifo_t
Type of a dynamic buffer object.
dyn_pipe_t
typedef struct ch_dyn_pipe dyn_pipe_t
Type of a dynamic pipe object.
objects_factory_t
typedef struct ch_objects_factory objects_factory_t
Type of the factory main object.
Function Documentation
__factory_init()
void __factory_init (void)
Initializes the objects factory.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 251 of file chfactory.c.
References ch_factory, chMtxObjectInit(), chSemObjectInit(), and ch_objects_factory::mtx.
Referenced by __oslib_init().
chFactoryRegisterObject()
registered_object_t * chFactoryRegisterObject (const char * name, void * objp)
Registers a generic object.
Postcondition
A reference to the registered object is returned and the reference counter is initialized to one.
Parameters
[in] name name to be assigned to the registered object
[in] objp pointer to the object to be registered
Returns
The reference to the registered object.
Return values
NULL if the object to be registered cannot be allocated or a registered object with the same name exists.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 300 of file chfactory.c.
chFactoryFindObject()
registered_object_t * chFactoryFindObject (const char * name)
Retrieves a registered object.
Postcondition
A reference to the registered object is returned with the reference counter increased by one.
Parameters
[in] name name of the registered object
Returns
The reference to the found registered object.
Return values
NULL if a registered object with the specified name does not exist.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 332 of file chfactory.c.
chFactoryFindObjectByPointer()
registered_object_t * chFactoryFindObjectByPointer (void * objp)
Retrieves a registered object by pointer.
Postcondition
A reference to the registered object is returned with the reference counter increased by one.
Parameters
[in] objp pointer to the object to be retrieved
Returns
The reference to the found registered object.
Return values
NULL if a registered object with the specified pointer does not exist.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 357 of file chfactory.c.
References ch_factory, and ch_objects_factory::obj_list.
chFactoryReleaseObject()
void chFactoryReleaseObject (registered_object_t * rop)
Releases a registered object.
The reference counter of the registered object is decreased by one, if reaches zero then the registered object memory is freed.
Note
The object itself is not freed, it could be static, only the allocated list element is freed.
Parameters
[in] rop registered object reference
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 390 of file chfactory.c.
chFactoryCreateBuffer()
dyn_buffer_t * chFactoryCreateBuffer (const char * name, size_t size)
Creates a generic dynamic buffer object.
Postcondition
A reference to the dynamic buffer object is returned and the reference counter is initialized to one.
The dynamic buffer object is filled with zeros.
Parameters
[in] name name to be assigned to the new dynamic buffer object
[in] size payload size of the dynamic buffer object to be created
Returns
The reference to the created dynamic buffer object.
Return values
NULL if the dynamic buffer object cannot be allocated or a dynamic buffer object with the same name exists.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 418 of file chfactory.c.
chFactoryFindBuffer()
dyn_buffer_t * chFactoryFindBuffer (const char * name)
Retrieves a dynamic buffer object.
Postcondition
A reference to the dynamic buffer object is returned with the reference counter increased by one.
Parameters
[in] name name of the dynamic buffer object
Returns
The reference to the found dynamic buffer object.
Return values
NULL if a dynamic buffer object with the specified name does not exist.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 450 of file chfactory.c.
chFactoryReleaseBuffer()
void chFactoryReleaseBuffer (dyn_buffer_t * dbp)
Releases a dynamic buffer object.
The reference counter of the dynamic buffer object is decreased by one, if reaches zero then the dynamic buffer object memory is freed.
Parameters
[in] dbp dynamic buffer object reference
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 472 of file chfactory.c.
chFactoryCreateSemaphore()
dyn_semaphore_t * chFactoryCreateSemaphore (const char * name, cnt_t n)
Creates a dynamic semaphore object.
Postcondition
A reference to the dynamic semaphore object is returned and the reference counter is initialized to one.
The dynamic semaphore object is initialized and ready to use.
Parameters
[in] name name to be assigned to the new dynamic semaphore object
[in] n dynamic semaphore object counter initialization value
Returns
The reference to the created dynamic semaphore object.
Return values
NULL if the dynamic semaphore object cannot be allocated or a dynamic semaphore with the same name exists.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 498 of file chfactory.c.
chFactoryFindSemaphore()
dyn_semaphore_t * chFactoryFindSemaphore (const char * name)
Retrieves a dynamic semaphore object.
Postcondition
A reference to the dynamic semaphore object is returned with the reference counter increased by one.
Parameters
[in] name name of the dynamic semaphore object
Returns
The reference to the found dynamic semaphore object.
Return values
NULL if a dynamic semaphore object with the specified name does not exist.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 529 of file chfactory.c.
chFactoryReleaseSemaphore()
void chFactoryReleaseSemaphore (dyn_semaphore_t * dsp)
Releases a dynamic semaphore object.
The reference counter of the dynamic semaphore object is decreased by one, if reaches zero then the dynamic semaphore object memory is freed.
Parameters
[in] dsp dynamic semaphore object reference
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 551 of file chfactory.c.
chFactoryCreateMailbox()
dyn_mailbox_t * chFactoryCreateMailbox (const char * name, size_t n)
Creates a dynamic mailbox object.
Postcondition
A reference to the dynamic mailbox object is returned and the reference counter is initialized to one.
The dynamic mailbox object is initialized and ready to use.
Parameters
[in] name name to be assigned to the new dynamic mailbox object
[in] n mailbox buffer size as number of messages
Returns
The reference to the created dynamic mailbox object.
Return values
NULL if the dynamic mailbox object cannot be allocated or a dynamic mailbox object with the same name exists.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 579 of file chfactory.c.
chFactoryFindMailbox()
dyn_mailbox_t * chFactoryFindMailbox (const char * name)
Retrieves a dynamic mailbox object.
Postcondition
A reference to the dynamic mailbox object is returned with the reference counter increased by one.
Parameters
[in] name name of the dynamic mailbox object
Returns
The reference to the found dynamic mailbox object.
Return values
NULL if a dynamic mailbox object with the specified name does not exist.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 612 of file chfactory.c.
chFactoryReleaseMailbox()
void chFactoryReleaseMailbox (dyn_mailbox_t * dmp)
Releases a dynamic mailbox object.
The reference counter of the dynamic mailbox object is decreased by one, if reaches zero then the dynamic mailbox object memory is freed.
Parameters
[in] dmp dynamic mailbox object reference
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 634 of file chfactory.c.
chFactoryCreateObjectsFIFO()
dyn_objects_fifo_t * chFactoryCreateObjectsFIFO (const char * name, size_t objsize, size_t objn, unsigned objalign)
Creates a dynamic "objects FIFO" object.
Postcondition
A reference to the dynamic "objects FIFO" object is returned and the reference counter is initialized to one.
The dynamic "objects FIFO" object is initialized and ready to use.
Parameters
[in] name name to be assigned to the new dynamic "objects FIFO" object
[in] objsize size of objects
[in] objn number of objects available
[in] objalign required objects alignment
Returns
The reference to the created dynamic "objects FIFO" object.
Return values
NULL if the dynamic "objects FIFO" object cannot be allocated or a dynamic "objects FIFO" object with the same name exists.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 664 of file chfactory.c.
chFactoryFindObjectsFIFO()
dyn_objects_fifo_t * chFactoryFindObjectsFIFO (const char * name)
Retrieves a dynamic "objects FIFO" object.
Postcondition
A reference to the dynamic "objects FIFO" object is returned with the reference counter increased by one.
Parameters
[in] name name of the dynamic "objects FIFO" object
Returns
The reference to the found dynamic "objects FIFO" object.
Return values
NULL if a dynamic "objects FIFO" object with the specified name does not exist.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 712 of file chfactory.c.
chFactoryReleaseObjectsFIFO()
void chFactoryReleaseObjectsFIFO (dyn_objects_fifo_t * dofp)
Releases a dynamic "objects FIFO" object.
The reference counter of the dynamic "objects FIFO" object is decreased by one, if reaches zero then the dynamic "objects FIFO" object memory is freed.
Parameters
[in] dofp dynamic "objects FIFO" object reference
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 734 of file chfactory.c.
chFactoryCreatePipe()
dyn_pipe_t * chFactoryCreatePipe (const char * name, size_t size)
Creates a dynamic pipe object.
Postcondition
A reference to the dynamic pipe object is returned and the reference counter is initialized to one.
The dynamic pipe object is initialized and ready to use.
Parameters
[in] name name to be assigned to the new dynamic pipe object
[in] size pipe buffer size
Returns
The reference to the created dynamic pipe object.
Return values
NULL if the dynamic pipe object cannot be allocated or a dynamic pipe object with the same name exists.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 762 of file chfactory.c.
chFactoryFindPipe()
dyn_pipe_t * chFactoryFindPipe (const char * name)
Retrieves a dynamic pipe object.
Postcondition
A reference to the dynamic pipe object is returned with the reference counter increased by one.
Parameters
[in] name name of the pipe object
Returns
The reference to the found dynamic pipe object.
Return values
NULL if a dynamic pipe object with the specified name does not exist.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 795 of file chfactory.c.
chFactoryReleasePipe()
void chFactoryReleasePipe (dyn_pipe_t * dpp)
Releases a dynamic pipe object.
The reference counter of the dynamic pipe object is decreased by one, if reaches zero then the dynamic pipe object memory is freed.
Parameters
[in] dpp dynamic pipe object reference
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 817 of file chfactory.c.
chFactoryDuplicateReference()
static dyn_element_t* chFactoryDuplicateReference (dyn_element_t * dep) inline static
Duplicates an object reference.
Note
This function can be used on any kind of dynamic object.
Parameters
[in] dep pointer to the element field of the object
Returns
The duplicated object reference.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 409 of file chfactory.h.
References ch_dyn_element::refs.
chFactoryGetObject()
static void* chFactoryGetObject (registered_object_t * rop) inline static
Returns the pointer to the inner registered object.
Parameters
[in] rop registered object reference
Returns
The pointer to the registered object.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 425 of file chfactory.h.
References ch_registered_static_object::objp.
chFactoryGetBufferSize()
static size_t chFactoryGetBufferSize (dyn_buffer_t * dbp) inline static
Returns the size of a generic dynamic buffer object.
Parameters
[in] dbp dynamic buffer object reference
Returns
The size of the buffer object in bytes.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 440 of file chfactory.h.
References chHeapGetSize().
chFactoryGetBuffer()
static uint8_t* chFactoryGetBuffer (dyn_buffer_t * dbp) inline static
Returns the pointer to the inner buffer.
Parameters
[in] dbp dynamic buffer object reference
Returns
The pointer to the dynamic buffer.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 453 of file chfactory.h.
chFactoryGetSemaphore()
static semaphore_t* chFactoryGetSemaphore (dyn_semaphore_t * dsp) inline static
Returns the pointer to the inner semaphore.
Parameters
[in] dsp dynamic semaphore object reference
Returns
The pointer to the semaphore.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 468 of file chfactory.h.
References ch_dyn_semaphore::sem.
chFactoryGetMailbox()
static mailbox_t* chFactoryGetMailbox (dyn_mailbox_t * dmp) inline static
Returns the pointer to the inner mailbox.
Parameters
[in] dmp dynamic mailbox object reference
Returns
The pointer to the mailbox.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 483 of file chfactory.h.
References ch_dyn_mailbox::mbx.
chFactoryGetObjectsFIFO()
static objects_fifo_t* chFactoryGetObjectsFIFO (dyn_objects_fifo_t * dofp) inline static
Returns the pointer to the inner objects FIFO.
Parameters
[in] dofp dynamic "objects FIFO" object reference
Returns
The pointer to the objects FIFO.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 498 of file chfactory.h.
References ch_dyn_objects_fifo::fifo.
chFactoryGetPipe()
static pipe_t* chFactoryGetPipe (dyn_pipe_t * dpp) inline static
Returns the pointer to the inner pipe.
Parameters
[in] dpp dynamic pipe object reference
Returns
The pointer to the pipe.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 513 of file chfactory.h.
References ch_dyn_pipe::pipe.
Variable Documentation
ch_factory
objects_factory_t ch_factory
Factory object static instance.
Note
It is a global object because it could be accessed through a specific debugger plugin.
Definition at line 72 of file chfactory.c.
Referenced by __factory_init(), and chFactoryFindObjectByPointer().