ChibiOS/RT: Version Numbers and Identification
Version Numbers and Identification
OS Library
Detailed Description
OS Library related info.
Macros
#define __CHIBIOS_OSLIB__
ChibiOS/LIB identification macro.
#define CH_OSLIB_STABLE 1
Stable release flag.
ChibiOS/LIB version identification
#define CH_OSLIB_VERSION "1.3.0"
OS Library version string.
#define CH_OSLIB_MAJOR 1
OS Library version major number.
#define CH_OSLIB_MINOR 3
OS Library version minor number.
#define CH_OSLIB_PATCH 0
OS Library version patch number.
Functions
static void __oslib_init (void)
Initialization of all library modules.
Macro Definition Documentation
__CHIBIOS_OSLIB__
#define __CHIBIOS_OSLIB__
ChibiOS/LIB identification macro.
Definition at line 41 of file chlib.h.
CH_OSLIB_STABLE
#define CH_OSLIB_STABLE 1
Stable release flag.
Definition at line 46 of file chlib.h.
CH_OSLIB_VERSION
#define CH_OSLIB_VERSION "1.3.0"
OS Library version string.
Definition at line 55 of file chlib.h.
CH_OSLIB_MAJOR
#define CH_OSLIB_MAJOR 1
OS Library version major number.
Definition at line 60 of file chlib.h.
CH_OSLIB_MINOR
#define CH_OSLIB_MINOR 3
OS Library version minor number.
Definition at line 65 of file chlib.h.
CH_OSLIB_PATCH
#define CH_OSLIB_PATCH 0
OS Library version patch number.
Definition at line 70 of file chlib.h.
Function Documentation
__oslib_init()
static void __oslib_init (void) inline static
Initialization of all library modules.
Function Class:
Not an API, this function is for internal use only.
Definition at line 249 of file chlib.h.
References __core_init(), __factory_init(), and __heap_init().