ChibiOS/RT: Virtual Timers
Virtual Timers
RT Kernel » Base Kernel Services
Detailed Description
Time and Virtual Timers related APIs and services.
Functions
static void vt_set_alarm (systime_t now, sysinterval_t delay)
Alarm time setup.
static void vt_insert_first (virtual_timers_list_t *vtlp, virtual_timer_t *vtp, systime_t now, sysinterval_t delay)
Inserts a timer as first element in a delta list.
static void vt_enqueue (virtual_timers_list_t *vtlp, virtual_timer_t *vtp, sysinterval_t delay)
Enqueues a virtual timer in a virtual timers list.
void chVTDoSetI (virtual_timer_t *vtp, sysinterval_t delay, vtfunc_t vtfunc, void *par)
Enables a one-shot virtual timer.
void chVTDoSetContinuousI (virtual_timer_t *vtp, sysinterval_t delay, vtfunc_t vtfunc, void *par)
Enables a continuous virtual timer.
void chVTDoResetI (virtual_timer_t *vtp)
Disables a Virtual Timer.
sysinterval_t chVTGetRemainingIntervalI (virtual_timer_t *vtp)
Returns the remaining time interval before next timer trigger.
void chVTDoTickI (void)
Virtual timers ticker.
systimestamp_t chVTGetTimeStampI (void)
Generates a monotonic time stamp.
void chVTResetTimeStampI (void)
Resets and re-synchronizes the time stamps monotonic counter.
static void chVTObjectInit (virtual_timer_t *vtp)
Initializes a virtual_timer_t object.
static systime_t chVTGetSystemTimeX (void)
Current system time.
static systime_t chVTGetSystemTime (void)
Current system time.
static sysinterval_t chVTTimeElapsedSinceX (systime_t start)
Returns the elapsed time since the specified start time.
static bool chVTIsSystemTimeWithinX (systime_t start, systime_t end)
Checks if the current system time is within the specified time window.
static bool chVTIsSystemTimeWithin (systime_t start, systime_t end)
Checks if the current system time is within the specified time window.
static bool chVTGetTimersStateI (sysinterval_t *timep)
Returns the time interval until the next timer event.
static bool chVTIsArmedI (const virtual_timer_t *vtp)
Returns true if the specified timer is armed.
static bool chVTIsArmed (const virtual_timer_t *vtp)
Returns true if the specified timer is armed.
static void chVTResetI (virtual_timer_t *vtp)
Disables a Virtual Timer.
static void chVTReset (virtual_timer_t *vtp)
Disables a Virtual Timer.
static void chVTSetI (virtual_timer_t *vtp, sysinterval_t delay, vtfunc_t vtfunc, void *par)
Enables a one-shot virtual timer.
static void chVTSet (virtual_timer_t *vtp, sysinterval_t delay, vtfunc_t vtfunc, void *par)
Enables a one-shot virtual timer.
static void chVTSetContinuousI (virtual_timer_t *vtp, sysinterval_t delay, vtfunc_t vtfunc, void *par)
Enables a continuous virtual timer.
static void chVTSetContinuous (virtual_timer_t *vtp, sysinterval_t delay, vtfunc_t vtfunc, void *par)
Enables a continuous virtual timer.
static sysinterval_t chVTGetReloadIntervalX (virtual_timer_t *vtp)
Returns the current reload value.
static void chVTSetReloadIntervalX (virtual_timer_t *vtp, sysinterval_t reload)
Changes a timer reload time interval.
static systimestamp_t chVTGetTimeStamp (void)
Generates a monotonic time stamp.
static void chVTResetTimeStamp (void)
Resets and re-synchronizes the time stamps monotonic counter.
static void __vt_object_init (virtual_timers_list_t *vtlp)
Virtual Timers instance initialization.
Function Documentation
vt_set_alarm()
static void vt_set_alarm (systime_t now, sysinterval_t delay) static
Alarm time setup.
Note
An RFCU fault is registered if the system time skips past (now + delay), the deadline is skipped forward in order to compensate for the event.
Parameters
[in] now last known system time
[in] delay delay over now
Definition at line 67 of file chvt.c.
References CH_CFG_ST_TIMEDELTA, chRFCUCollectFaultsI(), chTimeAddX(), chTimeDiffX(), chVTGetSystemTimeX(), and likely.
Referenced by chVTDoResetI(), and vt_enqueue().
vt_insert_first()
static void vt_insert_first (virtual_timers_list_t * vtlp, virtual_timer_t * vtp, systime_t now, sysinterval_t delay) static
Inserts a timer as first element in a delta list.
Note
This is the special case when the delta list is initially empty.
Definition at line 129 of file chvt.c.
References CH_CFG_ST_TIMEDELTA, ch_dlist_insert_after(), chRFCUCollectFaultsI(), chTimeAddX(), chTimeDiffX(), chVTGetSystemTimeX(), ch_virtual_timer::dlist, ch_virtual_timers_list::dlist, ch_virtual_timers_list::lasttime, and likely.
Referenced by vt_enqueue().
vt_enqueue()
static void vt_enqueue (virtual_timers_list_t * vtlp, virtual_timer_t * vtp, sysinterval_t delay) static
Enqueues a virtual timer in a virtual timers list.
Definition at line 199 of file chvt.c.
References ch_dlist_insert(), ch_dlist_isempty(), chTimeDiffX(), chVTGetSystemTimeX(), ch_virtual_timer::dlist, ch_virtual_timers_list::dlist, ch_virtual_timers_list::lasttime, vt_insert_first(), and vt_set_alarm().
Referenced by chVTDoSetContinuousI(), and chVTDoSetI().
chVTDoSetI()
void chVTDoSetI (virtual_timer_t * vtp, sysinterval_t delay, vtfunc_t vtfunc, void * par)
Enables a one-shot virtual timer.
The timer is enabled and programmed to trigger after the delay specified as parameter.
Precondition
The timer must not be already armed before calling this function.
Note
The callback function is invoked from interrupt context.
Parameters
[out] vtp pointer to a virtual_timer_t structure
[in] delay the number of ticks before the operation timeouts, the special values are handled as follow:
TIME_INFINITE is allowed but interpreted as a normal time specification.
TIME_IMMEDIATE this value is not allowed.
[in] vtfunc the timer callback function. After invoking the callback the timer is disabled and the structure can be disposed or reused.
[in] par a parameter that will be passed to the callback function
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 271 of file chvt.c.
References chDbgCheck, chDbgCheckClassI(), currcore, ch_virtual_timer::func, ch_virtual_timer::par, ch_virtual_timer::reload, TIME_IMMEDIATE, and vt_enqueue().
Referenced by chSchGoSleepTimeoutS(), and chVTSetI().
chVTDoSetContinuousI()
void chVTDoSetContinuousI (virtual_timer_t * vtp, sysinterval_t delay, vtfunc_t vtfunc, void * par)
Enables a continuous virtual timer.
The timer is enabled and programmed to trigger after the delay specified as parameter.
Precondition
The timer must not be already armed before calling this function.
Note
The callback function is invoked from interrupt context.
Parameters
[out] vtp pointer to a virtual_timer_t structure
[in] delay the number of ticks before the operation timeouts, the special values are handled as follow:
TIME_INFINITE is allowed but interpreted as a normal time specification.
TIME_IMMEDIATE this value is not allowed.
[in] vtfunc the timer callback function. After invoking the callback the timer is disabled and the structure can be disposed or reused.
[in] par a parameter that will be passed to the callback function
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 309 of file chvt.c.
References chDbgCheck, chDbgCheckClassI(), currcore, ch_virtual_timer::func, ch_virtual_timer::par, ch_virtual_timer::reload, TIME_IMMEDIATE, and vt_enqueue().
Referenced by chVTSetContinuousI().
chVTDoResetI()
void chVTDoResetI (virtual_timer_t * vtp)
Disables a Virtual Timer.
Precondition
The timer must be in armed state before calling this function.
Parameters
[in] vtp pointer to a virtual_timer_t structure
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 333 of file chvt.c.
References ch_dlist_dequeue(), ch_dlist_isempty(), ch_dlist_isfirst(), ch_dlist_remove_first(), chDbgAssert, chDbgCheck, chDbgCheckClassI(), chTimeDiffX(), chVTGetSystemTimeX(), chVTIsArmedI(), currcore, ch_delta_list::delta, ch_virtual_timer::dlist, ch_virtual_timers_list::dlist, ch_virtual_timers_list::lasttime, ch_delta_list::next, and vt_set_alarm().
Referenced by chVTResetI().
chVTGetRemainingIntervalI()
sysinterval_t chVTGetRemainingIntervalI (virtual_timer_t * vtp)
Returns the remaining time interval before next timer trigger.
Note
This function can be called while the timer is active.
Parameters
[in] vtp pointer to a virtual_timer_t structure
Returns
The remaining time interval.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 419 of file chvt.c.
References chDbgAssert, chDbgCheckClassI(), chTimeDiffX(), chVTGetSystemTimeX(), currcore, ch_delta_list::delta, ch_virtual_timer::dlist, ch_virtual_timers_list::dlist, ch_virtual_timers_list::lasttime, and ch_delta_list::next.
chVTDoTickI()
void chVTDoTickI (void)
Virtual timers ticker.
Note
The system lock is released before entering the callback and re-acquired immediately after. It is callback's responsibility to acquire the lock if needed. This is done in order to reduce interrupts jitter when many timers are in use.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 459 of file chvt.c.
References ch_dlist_dequeue(), ch_dlist_insert(), ch_dlist_isempty(), ch_dlist_notempty(), chDbgAssert, chDbgCheckClassI(), chRFCUCollectFaultsI(), chSysLockFromISR(), chSysUnlockFromISR(), chTimeAddX(), chTimeDiffX(), chVTGetSystemTimeX(), currcore, ch_delta_list::delta, ch_virtual_timer::dlist, ch_virtual_timers_list::dlist, ch_virtual_timer::func, ch_virtual_timers_list::lasttime, ch_delta_list::next, ch_virtual_timer::par, ch_virtual_timer::reload, ch_virtual_timers_list::systime, and unlikely.
Referenced by chSysTimerHandlerI().
chVTGetTimeStampI()
systimestamp_t chVTGetTimeStampI (void)
Generates a monotonic time stamp.
This function generates a monotonic time stamp synchronized with the system time. The time stamp has the same resolution of system time.
Note
There is an assumption, this function must be called at least once before the system time wraps back to zero or synchronization is lost. You may use a periodic virtual timer with a very large interval in order to keep time stamps synchronized by calling this function.
Returns
The time stamp.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 621 of file chvt.c.
References chDbgAssert, chDbgCheckClassI(), chTimeDiffX(), chVTGetSystemTimeX(), currcore, ch_virtual_timers_list::laststamp, and ch_os_instance::vtlist.
Referenced by chVTGetTimeStamp().
chVTResetTimeStampI()
void chVTResetTimeStampI (void)
Resets and re-synchronizes the time stamps monotonic counter.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 652 of file chvt.c.
References chDbgCheckClassI(), chVTGetSystemTimeX(), and currcore.
Referenced by chVTResetTimeStamp().
chVTObjectInit()
static void chVTObjectInit (virtual_timer_t * vtp) inline static
Initializes a virtual_timer_t object.
Note
Initializing a timer object is not strictly required because the function chVTSetI() initializes the object too. This function is only useful if you need to perform a chVTIsArmed() check before calling chVTSetI().
Parameters
[out] vtp the virtual_timer_t structure pointer
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 104 of file chvt.h.
References ch_virtual_timer::dlist, and ch_delta_list::next.
chVTGetSystemTimeX()
static systime_t chVTGetSystemTimeX (void) inline static
Current system time.
Returns the number of system ticks since the chSysInit() invocation.
Note
The counter can reach its maximum and then restart from zero.
This function can be called from any context but its atomicity is not guaranteed on architectures whose word size is less than systime_t size.
Returns
The system time in ticks.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 122 of file chvt.h.
References currcore.
Referenced by __vt_object_init(), chThdSleepUntil(), chThdSleepUntilWindowed(), chVTDoResetI(), chVTDoTickI(), chVTGetRemainingIntervalI(), chVTGetSystemTime(), chVTGetTimersStateI(), chVTGetTimeStampI(), chVTIsSystemTimeWithinX(), chVTResetTimeStampI(), chVTTimeElapsedSinceX(), trace_next(), vt_enqueue(), vt_insert_first(), and vt_set_alarm().
chVTGetSystemTime()
static systime_t chVTGetSystemTime (void) inline static
Current system time.
Returns the number of system ticks since the chSysInit() invocation.
Note
The counter can reach its maximum and then restart from zero.
Returns
The system time in ticks.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 141 of file chvt.h.
References chSysLock(), chSysUnlock(), and chVTGetSystemTimeX().
Referenced by chVTIsSystemTimeWithin().
chVTTimeElapsedSinceX()
static sysinterval_t chVTTimeElapsedSinceX (systime_t start) inline static
Returns the elapsed time since the specified start time.
Parameters
[in] start start time
Returns
The elapsed time.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 159 of file chvt.h.
References chTimeDiffX(), and chVTGetSystemTimeX().
chVTIsSystemTimeWithinX()
static bool chVTIsSystemTimeWithinX (systime_t start, systime_t end) inline static
Checks if the current system time is within the specified time window.
Note
When start==end then the function returns always false because the time window has zero size.
Parameters
[in] start the start of the time window (inclusive)
[in] end the end of the time window (non inclusive)
Return values
true current time within the specified time window.
false current time not within the specified time window.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 177 of file chvt.h.
References chTimeIsInRangeX(), and chVTGetSystemTimeX().
chVTIsSystemTimeWithin()
static bool chVTIsSystemTimeWithin (systime_t start, systime_t end) inline static
Checks if the current system time is within the specified time window.
Note
When start==end then the function returns always false because the time window has zero size.
Parameters
[in] start the start of the time window (inclusive)
[in] end the end of the time window (non inclusive)
Return values
true current time within the specified time window.
false current time not within the specified time window.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 195 of file chvt.h.
References chTimeIsInRangeX(), and chVTGetSystemTime().
chVTGetTimersStateI()
static bool chVTGetTimersStateI (sysinterval_t * timep) inline static
Returns the time interval until the next timer event.
Note
The return value is not perfectly accurate and can report values in excess of CH_CFG_ST_TIMEDELTA ticks.
The interval returned by this function is only meaningful if more timers are not added to the list until the returned time.
Parameters
[out] timep pointer to a variable that will contain the time interval until the next timer elapses. This pointer can be NULL if the information is not required.
Returns
The time, in ticks, until next time event.
Return values
false if the timers list is empty.
true if the timers list contains at least one timer.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 216 of file chvt.h.
References CH_CFG_ST_TIMEDELTA, chDbgCheckClassI(), chTimeDiffX(), chVTGetSystemTimeX(), currcore, ch_delta_list::delta, ch_virtual_timers_list::dlist, ch_virtual_timers_list::lasttime, and ch_delta_list::next.
chVTIsArmedI()
static bool chVTIsArmedI (const virtual_timer_t * vtp) inline static
Returns true if the specified timer is armed.
Precondition
The timer must have been initialized using chVTObjectInit() or chVTDoSetI().
Parameters
[in] vtp the virtual_timer_t structure pointer
Returns
true if the timer is armed.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 248 of file chvt.h.
References chDbgCheckClassI(), ch_virtual_timer::dlist, and ch_delta_list::next.
Referenced by chVTDoResetI(), chVTIsArmed(), and chVTResetI().
chVTIsArmed()
static bool chVTIsArmed (const virtual_timer_t * vtp) inline static
Returns true if the specified timer is armed.
Precondition
The timer must have been initialized using chVTObjectInit() or chVTDoSetI().
Parameters
[in] vtp the virtual_timer_t structure pointer
Returns
true if the timer is armed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 265 of file chvt.h.
References chSysLock(), chSysUnlock(), and chVTIsArmedI().
chVTResetI()
static void chVTResetI (virtual_timer_t * vtp) inline static
Disables a Virtual Timer.
Note
The timer is first checked and disabled only if armed.
Precondition
The timer must have been initialized using chVTObjectInit() or chVTDoSetI().
Parameters
[in] vtp the virtual_timer_t structure pointer
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 285 of file chvt.h.
References chVTDoResetI(), and chVTIsArmedI().
Referenced by chVTReset(), chVTSetContinuousI(), and chVTSetI().
chVTReset()
static void chVTReset (virtual_timer_t * vtp) inline static
Disables a Virtual Timer.
Note
The timer is first checked and disabled only if armed.
Precondition
The timer must have been initialized using chVTObjectInit() or chVTDoSetI().
Parameters
[in] vtp the virtual_timer_t structure pointer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 302 of file chvt.h.
References chSysLock(), chSysUnlock(), and chVTResetI().
chVTSetI()
static void chVTSetI (virtual_timer_t * vtp, sysinterval_t delay, vtfunc_t vtfunc, void * par) inline static
Enables a one-shot virtual timer.
If the virtual timer was already enabled then it is re-enabled using the new parameters.
Precondition
The timer must have been initialized using chVTObjectInit() or chVTDoSetI().
Parameters
[in] vtp the virtual_timer_t structure pointer
[in] delay the number of ticks before the operation timeouts, the special values are handled as follow:
TIME_INFINITE is allowed but interpreted as a normal time specification.
TIME_IMMEDIATE this value is not allowed.
[in] vtfunc the timer callback function. After invoking the callback the timer is disabled and the structure can be disposed or reused.
[in] par a parameter that will be passed to the callback function
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 331 of file chvt.h.
References chVTDoSetI(), and chVTResetI().
Referenced by chVTSet().
chVTSet()
static void chVTSet (virtual_timer_t * vtp, sysinterval_t delay, vtfunc_t vtfunc, void * par) inline static
Enables a one-shot virtual timer.
If the virtual timer was already enabled then it is re-enabled using the new parameters.
Precondition
The timer must have been initialized using chVTObjectInit() or chVTDoSetI().
Parameters
[in] vtp the virtual_timer_t structure pointer
[in] delay the number of ticks before the operation timeouts, the special values are handled as follow:
TIME_INFINITE is allowed but interpreted as a normal time specification.
TIME_IMMEDIATE this value is not allowed.
[in] vtfunc the timer callback function. After invoking the callback the timer is disabled and the structure can be disposed or reused.
[in] par a parameter that will be passed to the callback function
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 360 of file chvt.h.
References chSysLock(), chSysUnlock(), and chVTSetI().
chVTSetContinuousI()
static void chVTSetContinuousI (virtual_timer_t * vtp, sysinterval_t delay, vtfunc_t vtfunc, void * par) inline static
Enables a continuous virtual timer.
If the virtual timer was already enabled then it is re-enabled using the new parameters.
Precondition
The timer must have been initialized using chVTObjectInit() or chVTDoSetI().
Parameters
[in] vtp the virtual_timer_t structure pointer
[in] delay the number of ticks before the operation timeouts, the special values are handled as follow:
TIME_INFINITE is allowed but interpreted as a normal time specification.
TIME_IMMEDIATE this value is not allowed.
[in] vtfunc the timer callback function. After invoking the callback the timer is disabled and the structure can be disposed or reused.
[in] par a parameter that will be passed to the callback function
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 390 of file chvt.h.
References chVTDoSetContinuousI(), and chVTResetI().
Referenced by chVTSetContinuous().
chVTSetContinuous()
static void chVTSetContinuous (virtual_timer_t * vtp, sysinterval_t delay, vtfunc_t vtfunc, void * par) inline static
Enables a continuous virtual timer.
If the virtual timer was already enabled then it is re-enabled using the new parameters.
Precondition
The timer must have been initialized using chVTObjectInit() or chVTDoSetI().
Parameters
[in] vtp the virtual_timer_t structure pointer
[in] delay the number of ticks before the operation timeouts, the special values are handled as follow:
TIME_INFINITE is allowed but interpreted as a normal time specification.
TIME_IMMEDIATE this value is not allowed.
[in] vtfunc the timer callback function. After invoking the callback the timer is disabled and the structure can be disposed or reused.
[in] par a parameter that will be passed to the callback function
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 419 of file chvt.h.
References chSysLock(), chSysUnlock(), and chVTSetContinuousI().
chVTGetReloadIntervalX()
static sysinterval_t chVTGetReloadIntervalX (virtual_timer_t * vtp) inline static
Returns the current reload value.
Parameters
[in] vtp the virtual_timer_t structure pointer
Returns
The reload value.
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 435 of file chvt.h.
References ch_virtual_timer::reload.
chVTSetReloadIntervalX()
static void chVTSetReloadIntervalX (virtual_timer_t * vtp, sysinterval_t reload) inline static
Changes a timer reload time interval.
Note
This function is meant to be called from a timer callback, it does nothing in any other context.
Calling this function from a one-shot timer callback turns it into a continuous timer.
Parameters
[in] vtp the virtual_timer_t structure pointer
[in] reload the new reload value, zero means no reload
Function Class:
This is an X-Class API, this function can be invoked from any context.
Definition at line 452 of file chvt.h.
References ch_virtual_timer::reload.
chVTGetTimeStamp()
static systimestamp_t chVTGetTimeStamp (void) inline static
Generates a monotonic time stamp.
This function generates a monotonic time stamp synchronized with the system time. The time stamp has the same resolution of system time.
Note
There is an assumption, this function must be called at least once before the system time wraps back to zero or synchronization is lost. You may use a periodic virtual timer with a very large interval in order to keep time stamps synchronized by calling this function.
Returns
The time stamp.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 474 of file chvt.h.
References chSysLock(), chSysUnlock(), and chVTGetTimeStampI().
chVTResetTimeStamp()
static void chVTResetTimeStamp (void) inline static
Resets and re-synchronizes the time stamps monotonic counter.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 491 of file chvt.h.
References chSysLock(), chSysUnlock(), and chVTResetTimeStampI().
__vt_object_init()
static void __vt_object_init (virtual_timers_list_t * vtlp) inline static
Virtual Timers instance initialization.
Note
Internal use only.
Parameters
[out] vtlp pointer to the virtual_timers_list_t structure
Function Class:
Not an API, this function is for internal use only.
Definition at line 509 of file chvt.h.
References ch_dlist_init(), chVTGetSystemTimeX(), ch_virtual_timers_list::dlist, ch_virtual_timers_list::laststamp, ch_virtual_timers_list::lasttime, and ch_virtual_timers_list::systime.
Referenced by chInstanceObjectInit().