ChibiOS/RT: Lists and Queues
Lists and Queues
RT Kernel » System
Detailed Description
Macros
#define __CH_QUEUE_DATA(name) {(ch_queue_t *)&name, (ch_queue_t *)&name}
Data part of a static queue object initializer.
#define CH_QUEUE_DECL(name) ch_queue_t name = __CH_QUEUE_DATA(name)
Static queue object initializer.
Typedefs
typedef struct ch_list ch_list_t
Type of a generic single link list header and element.
typedef struct ch_queue ch_queue_t
Type of a generic bidirectional linked list header and element.
typedef struct ch_priority_queue ch_priority_queue_t
Type of a generic priority-ordered bidirectional linked list header and element.
typedef struct ch_delta_list ch_delta_list_t
Type of a generic bidirectional linked delta list header and element.
Data Structures
struct ch_list
Structure representing a generic single link list header and element.
struct ch_queue
Structure representing a generic bidirectional linked list header and element.
struct ch_priority_queue
Structure representing a generic priority-ordered bidirectional linked list header and element.
struct ch_delta_list
Delta list element and header structure.
Functions
static void ch_list_init (ch_list_t *lp)
List initialization.
static bool ch_list_isempty (ch_list_t *lp)
Evaluates to true if the specified list is empty.
static bool ch_list_notempty (ch_list_t *lp)
Evaluates to true if the specified list is not empty.
static void ch_list_link (ch_list_t *lp, ch_list_t *p)
Pushes an element on top of a stack list.
static ch_list_t * ch_list_unlink (ch_list_t *lp)
Pops an element from the top of a stack list and returns it.
static void ch_queue_init (ch_queue_t *qp)
Queue initialization.
static bool ch_queue_isempty (const ch_queue_t *qp)
Evaluates to true if the specified queue is empty.
static bool ch_queue_notempty (const ch_queue_t *qp)
Evaluates to true if the specified queue is not empty.
static void ch_queue_insert (ch_queue_t *qp, ch_queue_t *p)
Inserts an element into a queue.
static ch_queue_t * ch_queue_fifo_remove (ch_queue_t *qp)
Removes the first-out element from a queue and returns it.
static ch_queue_t * ch_queue_lifo_remove (ch_queue_t *qp)
Removes the last-out element from a queue and returns it.
static ch_queue_t * ch_queue_dequeue (ch_queue_t *p)
Removes an element from a queue and returns it.
static void ch_pqueue_init (ch_priority_queue_t *pqp)
Priority queue initialization.
static ch_priority_queue_t * ch_pqueue_remove_highest (ch_priority_queue_t *pqp)
Removes the highest priority element from a priority queue and returns it.
static ch_priority_queue_t * ch_pqueue_insert_behind (ch_priority_queue_t *pqp, ch_priority_queue_t *p)
Inserts an element in the priority queue placing it behind its peers.
static ch_priority_queue_t * ch_pqueue_insert_ahead (ch_priority_queue_t *pqp, ch_priority_queue_t *p)
Inserts an element in the priority queue placing it ahead of its peers.
static void ch_dlist_init (ch_delta_list_t *dlhp)
Delta list initialization.
static bool ch_dlist_isempty (ch_delta_list_t *dlhp)
Evaluates to true if the specified delta list is empty.
static bool ch_dlist_notempty (ch_delta_list_t *dlhp)
Evaluates to true if the specified queue is not empty.
static bool ch_dlist_islast (ch_delta_list_t *dlhp, ch_delta_list_t *dlp)
Last element in the delta list check.
static bool ch_dlist_isfirst (ch_delta_list_t *dlhp, ch_delta_list_t *dlp)
Fist element in the delta list check.
static void ch_dlist_insert_after (ch_delta_list_t *dlhp, ch_delta_list_t *dlp, sysinterval_t delta)
Inserts an element after another header element.
static void ch_dlist_insert_before (ch_delta_list_t *dlhp, ch_delta_list_t *dlp, sysinterval_t delta)
Inserts an element before another header element.
static void ch_dlist_insert (ch_delta_list_t *dlhp, ch_delta_list_t *dlep, sysinterval_t delta)
Inserts an element in a delta list.
static ch_delta_list_t * ch_dlist_remove_first (ch_delta_list_t *dlhp)
Dequeues an element from the delta list.
static ch_delta_list_t * ch_dlist_dequeue (ch_delta_list_t *dlp)
Dequeues an element from the delta list.
Macro Definition Documentation
__CH_QUEUE_DATA
#define __CH_QUEUE_DATA (name) {(ch_queue_t *)&name, (ch_queue_t *)&name}
Data part of a static queue object initializer.
This macro should be used when statically initializing a queue that is part of a bigger structure.
Parameters
[in] name the name of the queue variable
Definition at line 117 of file chlists.h.
CH_QUEUE_DECL
#define CH_QUEUE_DECL (name) ch_queue_t name = __CH_QUEUE_DATA(name)
Static queue object initializer.
Statically initialized queues require no explicit initialization using queue_init().
Parameters
[in] name the name of the queue variable
Definition at line 126 of file chlists.h.
Typedef Documentation
ch_list_t
typedef struct ch_list ch_list_t
Type of a generic single link list header and element.
Definition at line 1 of file chlists.h.
ch_queue_t
typedef struct ch_queue ch_queue_t
Type of a generic bidirectional linked list header and element.
Definition at line 1 of file chlists.h.
ch_priority_queue_t
typedef struct ch_priority_queue ch_priority_queue_t
Type of a generic priority-ordered bidirectional linked list header and element.
Definition at line 1 of file chlists.h.
ch_delta_list_t
typedef struct ch_delta_list ch_delta_list_t
Type of a generic bidirectional linked delta list header and element.
Definition at line 1 of file chlists.h.
Function Documentation
ch_list_init()
static void ch_list_init (ch_list_t * lp) inline static
List initialization.
Parameters
[out] lp pointer to the list header
Function Class:
Not an API, this function is for internal use only.
Definition at line 153 of file chlists.h.
References ch_list::next.
Referenced by __thd_object_init().
ch_list_isempty()
static bool ch_list_isempty (ch_list_t * lp) inline static
Evaluates to true if the specified list is empty.
Parameters
[in] lp pointer to the list header
Returns
The status of the list.
Function Class:
Not an API, this function is for internal use only.
Definition at line 166 of file chlists.h.
References ch_list::next.
ch_list_notempty()
static bool ch_list_notempty (ch_list_t * lp) inline static
Evaluates to true if the specified list is not empty.
Parameters
[in] lp pointer to the list header
Returns
The status of the list.
Function Class:
Not an API, this function is for internal use only.
Definition at line 179 of file chlists.h.
References ch_list::next.
Referenced by chThdExitS().
ch_list_link()
static void ch_list_link (ch_list_t * lp, ch_list_t * p) inline static
Pushes an element on top of a stack list.
Parameters
[in] lp the pointer to the list header
[in] p the pointer to the element to be inserted in the list
Function Class:
Not an API, this function is for internal use only.
Definition at line 192 of file chlists.h.
References ch_list::next.
Referenced by chThdWait().
ch_list_unlink()
static ch_list_t* ch_list_unlink (ch_list_t * lp) inline static
Pops an element from the top of a stack list and returns it.
Precondition
The list must be non-empty before calling this function.
Parameters
[in] lp the pointer to the list header
Returns
The removed element pointer.
Function Class:
Not an API, this function is for internal use only.
Definition at line 207 of file chlists.h.
References ch_list::next.
Referenced by chThdExitS().
ch_queue_init()
static void ch_queue_init (ch_queue_t * qp) inline static
Queue initialization.
Parameters
[out] qp pointer to the queue header
Function Class:
Not an API, this function is for internal use only.
Definition at line 222 of file chlists.h.
References ch_queue::next, and ch_queue::prev.
Referenced by __reg_object_init(), __thd_object_init(), chCondObjectInit(), chMtxObjectInit(), chSemObjectInit(), and chThdQueueObjectInit().
ch_queue_isempty()
static bool ch_queue_isempty (const ch_queue_t * qp) inline static
Evaluates to true if the specified queue is empty.
Parameters
[in] qp pointer to the queue header
Returns
The status of the queue.
Function Class:
Not an API, this function is for internal use only.
Definition at line 236 of file chlists.h.
References ch_queue::next.
Referenced by chSemAddCounterI(), chSemResetWithMessageI(), chSemSignal(), chSemSignalI(), chSemSignalWait(), chSemWaitS(), chSemWaitTimeoutS(), and chThdQueueIsEmptyI().
ch_queue_notempty()
static bool ch_queue_notempty (const ch_queue_t * qp) inline static
Evaluates to true if the specified queue is not empty.
Parameters
[in] qp pointer to the queue header
Returns
The status of the queue.
Function Class:
Not an API, this function is for internal use only.
Definition at line 249 of file chlists.h.
References ch_queue::next.
Referenced by chCondBroadcastI(), chCondSignal(), chCondSignalI(), chMtxQueueNotEmptyS(), chSemAddCounterI(), chSemResetWithMessageI(), chSemSignal(), chSemSignalI(), chSemSignalWait(), chSemWaitS(), chSemWaitTimeoutS(), chThdDequeueAllI(), chThdDequeueNextI(), and chThdDoDequeueNextI().
ch_queue_insert()
static void ch_queue_insert (ch_queue_t * qp, ch_queue_t * p) inline static
Inserts an element into a queue.
Parameters
[in] qp the pointer to the queue header
[in] p the pointer to the element to be inserted in the queue
Function Class:
Not an API, this function is for internal use only.
Definition at line 262 of file chlists.h.
References ch_queue::next, and ch_queue::prev.
Referenced by chThdEnqueueTimeoutS().
ch_queue_fifo_remove()
static ch_queue_t* ch_queue_fifo_remove (ch_queue_t * qp) inline static
Removes the first-out element from a queue and returns it.
Note
If the queue is priority ordered then this function returns the element with the highest priority.
Parameters
[in] qp the pointer to the queue list header
Returns
The removed element pointer.
Function Class:
Not an API, this function is for internal use only.
Definition at line 280 of file chlists.h.
References ch_queue::next, and ch_queue::prev.
Referenced by chCondBroadcastI(), chCondSignal(), chCondSignalI(), chMsgPollS(), chMsgWaitS(), chMsgWaitTimeoutS(), chMtxUnlock(), chMtxUnlockAllS(), chMtxUnlockS(), chSemAddCounterI(), chSemSignal(), chSemSignalI(), chSemSignalWait(), and chThdDoDequeueNextI().
ch_queue_lifo_remove()
static ch_queue_t* ch_queue_lifo_remove (ch_queue_t * qp) inline static
Removes the last-out element from a queue and returns it.
Note
If the queue is priority ordered then this function returns the element with the lowest priority.
Parameters
[in] qp the pointer to the queue list header
Returns
The removed element pointer.
Function Class:
Not an API, this function is for internal use only.
Definition at line 299 of file chlists.h.
References ch_queue::next, and ch_queue::prev.
Referenced by chSemResetWithMessageI().
ch_queue_dequeue()
static ch_queue_t* ch_queue_dequeue (ch_queue_t * p) inline static
Removes an element from a queue and returns it.
The element is removed from the queue regardless of its relative position and regardless the used insertion method.
Parameters
[in] p the pointer to the element to be removed from the queue
Returns
The removed element pointer.
Function Class:
Not an API, this function is for internal use only.
Definition at line 318 of file chlists.h.
References ch_queue::next, and ch_queue::prev.
Referenced by chMtxLockS().
ch_pqueue_init()
static void ch_pqueue_init (ch_priority_queue_t * pqp) inline static
Priority queue initialization.
Note
The queue header priority is initialized to zero, all other elements in the queue are assumed to have priority greater than zero.
Parameters
[out] pqp pointer to the priority queue header
Function Class:
Not an API, this function is for internal use only.
Definition at line 336 of file chlists.h.
References ch_priority_queue::next, ch_priority_queue::prev, and ch_priority_queue::prio.
Referenced by chInstanceObjectInit().
ch_pqueue_remove_highest()
static ch_priority_queue_t* ch_pqueue_remove_highest (ch_priority_queue_t * pqp) inline static
Removes the highest priority element from a priority queue and returns it.
Parameters
[in] pqp the pointer to the priority queue list header
Returns
The removed element pointer.
Function Class:
Not an API, this function is for internal use only.
Definition at line 352 of file chlists.h.
References ch_priority_queue::next, and ch_priority_queue::prev.
Referenced by __sch_reschedule_ahead(), __sch_reschedule_behind(), chSchDoPreemption(), chSchGoSleepS(), and chSchSelectFirst().
ch_pqueue_insert_behind()
static ch_priority_queue_t* ch_pqueue_insert_behind (ch_priority_queue_t * pqp, ch_priority_queue_t * p) inline static
Inserts an element in the priority queue placing it behind its peers.
The element is positioned behind all elements with higher or equal priority.
Parameters
[in] pqp the pointer to the priority queue list header
[in] p the pointer to the element to be inserted in the queue
Returns
The inserted element pointer.
Function Class:
Not an API, this function is for internal use only.
Definition at line 373 of file chlists.h.
References ch_priority_queue::next, ch_priority_queue::prev, ch_priority_queue::prio, and unlikely.
Referenced by __sch_ready_behind().
ch_pqueue_insert_ahead()
static ch_priority_queue_t* ch_pqueue_insert_ahead (ch_priority_queue_t * pqp, ch_priority_queue_t * p) inline static
Inserts an element in the priority queue placing it ahead of its peers.
The element is positioned ahead of all elements with higher or equal priority.
Parameters
[in] pqp the pointer to the priority queue list header
[in] p the pointer to the element to be inserted in the queue
Returns
The inserted element pointer.
Function Class:
Not an API, this function is for internal use only.
Definition at line 402 of file chlists.h.
References ch_priority_queue::next, ch_priority_queue::prev, ch_priority_queue::prio, and unlikely.
Referenced by __sch_ready_ahead().
ch_dlist_init()
static void ch_dlist_init (ch_delta_list_t * dlhp) inline static
Delta list initialization.
Parameters
[out] dlhp pointer to the delta list header
Function Class:
Not an API, this function is for internal use only.
Definition at line 426 of file chlists.h.
References ch_delta_list::delta, ch_delta_list::next, and ch_delta_list::prev.
Referenced by __vt_object_init().
ch_dlist_isempty()
static bool ch_dlist_isempty (ch_delta_list_t * dlhp) inline static
Evaluates to true if the specified delta list is empty.
Parameters
[in] dlhp pointer to the delta list header
Returns
The status of the delta list.
Function Class:
Not an API, this function is for internal use only.
Definition at line 441 of file chlists.h.
References ch_delta_list::next.
Referenced by chVTDoResetI(), chVTDoTickI(), and vt_enqueue().
ch_dlist_notempty()
static bool ch_dlist_notempty (ch_delta_list_t * dlhp) inline static
Evaluates to true if the specified queue is not empty.
Parameters
[in] dlhp pointer to the delta list header
Returns
The status of the delta list.
Function Class:
Not an API, this function is for internal use only.
Definition at line 454 of file chlists.h.
References ch_delta_list::next.
Referenced by chVTDoTickI().
ch_dlist_islast()
static bool ch_dlist_islast (ch_delta_list_t * dlhp, ch_delta_list_t * dlp) inline static
Last element in the delta list check.
Parameters
[in] dlhp pointer to the delta list header
[in] dlp pointer to the delta list element
Function Class:
Not an API, this function is for internal use only.
Definition at line 467 of file chlists.h.
References ch_delta_list::next.
ch_dlist_isfirst()
static bool ch_dlist_isfirst (ch_delta_list_t * dlhp, ch_delta_list_t * dlp) inline static
Fist element in the delta list check.
Parameters
[in] dlhp pointer to the delta list header
[in] dlp pointer to the delta list element
Function Class:
Not an API, this function is for internal use only.
Definition at line 481 of file chlists.h.
References ch_delta_list::next.
Referenced by chVTDoResetI().
ch_dlist_insert_after()
static void ch_dlist_insert_after (ch_delta_list_t * dlhp, ch_delta_list_t * dlp, sysinterval_t delta) inline static
Inserts an element after another header element.
Parameters
[in] dlhp pointer to the delta list header element
[in] dlp element to be inserted after the header element
[in] delta delta of the element to be inserted
Function Class:
Not an API, this function is for internal use only.
Definition at line 496 of file chlists.h.
References ch_delta_list::delta, ch_delta_list::next, and ch_delta_list::prev.
Referenced by vt_insert_first().
ch_dlist_insert_before()
static void ch_dlist_insert_before (ch_delta_list_t * dlhp, ch_delta_list_t * dlp, sysinterval_t delta) inline static
Inserts an element before another header element.
Parameters
[in] dlhp pointer to the delta list header element
[in] dlp element to be inserted before the header element
[in] delta delta of the element to be inserted
Function Class:
Not an API, this function is for internal use only.
Definition at line 516 of file chlists.h.
References ch_delta_list::delta, ch_delta_list::next, and ch_delta_list::prev.
Referenced by ch_dlist_insert().
ch_dlist_insert()
static void ch_dlist_insert (ch_delta_list_t * dlhp, ch_delta_list_t * dlep, sysinterval_t delta) inline static
Inserts an element in a delta list.
Parameters
[in] dlhp pointer to the delta list header element
[in] dlep element to be inserted before the header element
[in] delta delta of the element to be inserted
Function Class:
Not an API, this function is for internal use only.
Definition at line 536 of file chlists.h.
References ch_dlist_insert_before(), chDbgAssert, ch_delta_list::delta, likely, and ch_delta_list::next.
Referenced by chVTDoTickI(), and vt_enqueue().
ch_dlist_remove_first()
static ch_delta_list_t* ch_dlist_remove_first (ch_delta_list_t * dlhp) inline static
Dequeues an element from the delta list.
Parameters
[in] dlhp pointer to the delta list header
Function Class:
Not an API, this function is for internal use only.
Definition at line 571 of file chlists.h.
References ch_delta_list::next, and ch_delta_list::prev.
Referenced by chVTDoResetI().
ch_dlist_dequeue()
static ch_delta_list_t* ch_dlist_dequeue (ch_delta_list_t * dlp) inline static
Dequeues an element from the delta list.
Parameters
[in] dlp pointer to the delta list element
Function Class:
Not an API, this function is for internal use only.
Definition at line 587 of file chlists.h.
References ch_delta_list::next, and ch_delta_list::prev.
Referenced by chVTDoResetI(), and chVTDoTickI().