ChibiOS/RT: Pipes
Pipes
OS Library » Synchronization
Detailed Description
Macros
#define __PIPE_DATA(name, buffer, size)
Data part of a static pipe initializer.
#define PIPE_DECL(name, buffer, size) pipe_t name = __PIPE_DATA(name, buffer, size)
Static pipe initializer.
Data Structures
struct pipe_t
Structure representing a pipe object.
Functions
static size_t pipe_write (pipe_t *pp, const uint8_t *bp, size_t n)
Non-blocking pipe write.
static size_t pipe_read (pipe_t *pp, uint8_t *bp, size_t n)
Non-blocking pipe read.
void chPipeObjectInit (pipe_t *pp, uint8_t *buf, size_t n)
Initializes a mailbox_t object.
void chPipeReset (pipe_t *pp)
Resets a pipe_t object.
size_t chPipeWriteTimeout (pipe_t *pp, const uint8_t *bp, size_t n, sysinterval_t timeout)
Pipe write with timeout.
size_t chPipeReadTimeout (pipe_t *pp, uint8_t *bp, size_t n, sysinterval_t timeout)
Pipe read with timeout.
static size_t chPipeGetSize (const pipe_t *pp)
Returns the pipe buffer size as number of bytes.
static size_t chPipeGetUsedCount (const pipe_t *pp)
Returns the number of used byte slots into a pipe.
static size_t chPipeGetFreeCount (const pipe_t *pp)
Returns the number of free byte slots into a pipe.
static void chPipeResume (pipe_t *pp)
Terminates the reset state.
Macro Definition Documentation
__PIPE_DATA
#define __PIPE_DATA (name, buffer, size)
Value:
  {                                   \
  (uint8_t *)(buffer),                                                      \
  (uint8_t *)(buffer) + size,                                               \
  (uint8_t *)(buffer),                                                      \
  (uint8_t *)(buffer),                                                      \
  (size_t)0,                                                                \
  false,                                                                    \
  NULL,                                                                     \
  NULL,                                                                     \
  __MUTEX_DATA(name.cmtx),                                                  \
  __MUTEX_DATA(name.wmtx),                                                  \
  __MUTEX_DATA(name.rmtx),                                                  \
}
Data part of a static pipe initializer.
This macro should be used when statically initializing a pipe that is part of a bigger structure.
Parameters
[in] name the name of the pipe variable
[in] buffer pointer to the pipe buffer array of uint8_t
[in] size number of uint8_t elements in the buffer array
Definition at line 88 of file chpipes.h.
PIPE_DECL
#define PIPE_DECL (name, buffer, size) pipe_t name = __PIPE_DATA(name, buffer, size)
Static pipe initializer.
Statically initialized pipes require no explicit initialization using chPipeObjectInit().
Parameters
[in] name the name of the pipe variable
[in] buffer pointer to the pipe buffer array of uint8_t
[in] size number of uint8_t elements in the buffer array
Definition at line 126 of file chpipes.h.
Function Documentation
pipe_write()
static size_t pipe_write (pipe_t * pp, const uint8_t * bp, size_t n) static
Non-blocking pipe write.
The function writes data from a buffer to a pipe. The operation completes when the specified amount of data has been transferred or when the pipe buffer has been filled.
Parameters
[in] pp the pointer to an initialized pipe_t object
[in] bp pointer to the data buffer
[in] n the maximum amount of data to be transferred, the value 0 is reserved
Returns
The number of bytes effectively transferred.
Function Class:
Not an API, this function is for internal use only.
Definition at line 105 of file chpipes.c.
pipe_read()
static size_t pipe_read (pipe_t * pp, uint8_t * bp, size_t n) static
Non-blocking pipe read.
The function reads data from a pipe into a buffer. The operation completes when the specified amount of data has been transferred or when the pipe buffer has been emptied.
Parameters
[in] pp the pointer to an initialized pipe_t object
[out] bp pointer to the data buffer
[in] n the maximum amount of data to be transferred, the value 0 is reserved
Returns
The number of bytes effectively transferred.
Function Class:
Not an API, this function is for internal use only.
Definition at line 156 of file chpipes.c.
chPipeObjectInit()
void chPipeObjectInit (pipe_t * pp, uint8_t * buf, size_t n)
Initializes a mailbox_t object.
Parameters
[out] pp the pointer to the pipe_t structure to be initialized
[in] buf pointer to the pipe buffer as an array of uint8_t
[in] n number of elements in the buffer array
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 207 of file chpipes.c.
References pipe_t::buffer, chDbgCheck, pipe_t::cnt, pipe_t::rdptr, pipe_t::reset, pipe_t::rtr, pipe_t::top, pipe_t::wrptr, and pipe_t::wtr.
chPipeReset()
void chPipeReset (pipe_t * pp)
Resets a pipe_t object.
All the waiting threads are resumed with status MSG_RESET and the queued data is lost.
Postcondition
The pipe is in reset state, all operations will fail and return MSG_RESET until the mailbox is enabled again using chPipeResumeX().
Parameters
[in] pp the pointer to an initialized pipe_t object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 236 of file chpipes.c.
References chDbgCheck.
chPipeWriteTimeout()
size_t chPipeWriteTimeout (pipe_t * pp, const uint8_t * bp, size_t n, sysinterval_t timeout)
Pipe write with timeout.
The function writes data from a buffer to a pipe. The operation completes when the specified amount of data has been transferred or after the specified timeout or if the pipe has been reset.
Parameters
[in] pp the pointer to an initialized pipe_t object
[in] bp pointer to the data buffer
[in] n the number of bytes to be written, the value 0 is reserved
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The number of bytes effectively transferred. A number lower than n means that a timeout occurred or the pipe went in reset state.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 278 of file chpipes.c.
References chDbgCheck, and pipe_t::reset.
chPipeReadTimeout()
size_t chPipeReadTimeout (pipe_t * pp, uint8_t * bp, size_t n, sysinterval_t timeout)
Pipe read with timeout.
The function reads data from a pipe into a buffer. The operation completes when the specified amount of data has been transferred or after the specified timeout or if the pipe has been reset.
Parameters
[in] pp the pointer to an initialized pipe_t object
[out] bp pointer to the data buffer
[in] n the number of bytes to be read, the value 0 is reserved
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The number of bytes effectively transferred. A number lower than n means that a timeout occurred or the pipe went in reset state.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 343 of file chpipes.c.
References chDbgCheck, and pipe_t::reset.
chPipeGetSize()
static size_t chPipeGetSize (const pipe_t * pp) inline static
Returns the pipe buffer size as number of bytes.
Parameters
[in] pp the pointer to an initialized pipe_t object
Returns
The size of the pipe.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 158 of file chpipes.h.
References pipe_t::buffer, and pipe_t::top.
Referenced by chPipeGetFreeCount().
chPipeGetUsedCount()
static size_t chPipeGetUsedCount (const pipe_t * pp) inline static
Returns the number of used byte slots into a pipe.
Parameters
[in] pp the pointer to an initialized pipe_t object
Returns
The number of queued bytes.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 174 of file chpipes.h.
References pipe_t::cnt.
Referenced by chPipeGetFreeCount().
chPipeGetFreeCount()
static size_t chPipeGetFreeCount (const pipe_t * pp) inline static
Returns the number of free byte slots into a pipe.
Parameters
[in] pp the pointer to an initialized pipe_t object
Returns
The number of empty byte slots.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 187 of file chpipes.h.
References chPipeGetSize(), and chPipeGetUsedCount().
chPipeResume()
static void chPipeResume (pipe_t * pp) inline static
Terminates the reset state.
Parameters
[in] pp the pointer to an initialized pipe_t object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 199 of file chpipes.h.
References pipe_t::reset.