ChibiOS/RT: Runtime Faults Collection Unit
Runtime Faults Collection Unit
RT Kernel » System
Detailed Description
Runtime Faults Collection Unit service.
Macros
#define CH_RFCU_ALL_FAULTS ((rfcu_mask_t)-1)
Mask of all faults.
Predefined Faults
#define CH_RFCU_VT_INSUFFICIENT_DELTA 1U
#define CH_RFCU_VT_SKIPPED_DEADLINE 2U
Typedefs
typedef uint32_t rfcu_mask_t
Type of a faults mask.
typedef struct ch_rfcu rfcu_t
Type of an RFCU structure.
Data Structures
struct ch_rfcu
Type of an RFCU structure.
Functions
void chRFCUCollectFaultsI (rfcu_mask_t mask)
Adds fault flags to the current mask.
rfcu_mask_t chRFCUGetAndClearFaultsI (rfcu_mask_t mask)
Returns the current faults mask clearing it.
static void __rfcu_object_init (rfcu_t *rfcup)
Runtime Faults Collection Unit initialization.
Macro Definition Documentation
CH_RFCU_ALL_FAULTS
#define CH_RFCU_ALL_FAULTS ((rfcu_mask_t)-1)
Mask of all faults.
Definition at line 46 of file chrfcu.h.
Typedef Documentation
rfcu_mask_t
typedef uint32_t rfcu_mask_t
Type of a faults mask.
Definition at line 63 of file chrfcu.h.
rfcu_t
typedef struct ch_rfcu rfcu_t
Type of an RFCU structure.
Function Documentation
chRFCUCollectFaultsI()
void chRFCUCollectFaultsI (rfcu_mask_t mask)
Adds fault flags to the current mask.
Parameters
[in] mask fault flags to be added
Definition at line 60 of file chrfcu.c.
References CH_CFG_RUNTIME_FAULTS_HOOK, currcore, ch_rfcu::mask, and ch_system::rfcu.
Referenced by chVTDoTickI(), vt_insert_first(), and vt_set_alarm().
chRFCUGetAndClearFaultsI()
rfcu_mask_t chRFCUGetAndClearFaultsI (rfcu_mask_t mask)
Returns the current faults mask clearing it.
Parameters
[in] mask mask of faults to be read and cleared
Returns
The current faults mask.
Return values
0 if no faults were collected since last call to this function.
Definition at line 79 of file chrfcu.c.
References currcore, ch_rfcu::mask, ch_os_instance::rfcu, and ch_system::rfcu.
__rfcu_object_init()
static void __rfcu_object_init (rfcu_t * rfcup) inline static
Runtime Faults Collection Unit initialization.
Note
Internal use only.
Parameters
[out] rfcup pointer to the rfcu_t structure
Function Class:
Not an API, this function is for internal use only.
Definition at line 104 of file chrfcu.h.
References ch_rfcu::mask.
Referenced by chInstanceObjectInit().